### ISSUE TITLE
Deadlocks inside Akka.Remote.TestKit

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1134]
The multi-node testkit is essential for the Akka.NET v1.1 release, and we've only just recently started running it on 100% of nightly and PR builds.

There appears to be a deadlock condition that occurs when a transition inside the `TestPlayer` or `Conductor` fails; see this build log from a recent deadlock:

http://petabridge-ci.cloudapp.net/viewLog.html?buildId=1514&buildTypeId=AkkaNet_AkkaNetPrBuild&tab=buildLog&guest=1

    [20:13:08][Step 1/1] [NODE1][7/8/2015 8:13:07 PM][DEBUG][Akka.MultiNodeTests.JoinSeedNodeMultiNode1]: Role [seed1] started with address [akka.tcp://MultiNodeClusterSpec@localhost:49876]
    [20:13:08][Step 1/1] [NODE4][7/8/2015 8:13:07 PM][DEBUG][Akka.MultiNodeTests.JoinSeedNodeMultiNode4]: Role [ordinary1] started with address [akka.tcp://MultiNodeClusterSpec@localhost:49877]
    [20:13:08][Step 1/1] [NODE4][7/8/2015 8:13:07 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: processing Event: <Akka.Remote.TestKit.ToServer
    [20:13:08][Step 1/1] [NODE4][7/8/2015 8:13:07 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: unhandled event Akka.Remote.TestKit.ToServer
    [20:13:08][Step 1/1] [NODE4][7/8/2015 8:13:07 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: transition AwaitDone, Akka.Remote.TestKit.ClientFSM+Data -> AwaitDone, Akka.Remote.TestKit.ClientFSM+Data
    [20:13:08][Step 1/1] [NODE3][7/8/2015 8:13:07 PM][DEBUG][Akka.MultiNodeTests.JoinSeedNodeMultiNode3]: Role [seed3] started with address [akka.tcp://MultiNodeClusterSpec@localhost:49879]
    [20:13:08][Step 1/1] [NODE3][7/8/2015 8:13:07 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: processing Event: <Akka.Remote.TestKit.ToServer
    [20:13:08][Step 1/1] [NODE3][7/8/2015 8:13:07 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: unhandled event Akka.Remote.TestKit.ToServer
    [20:13:08][Step 1/1] [NODE3][7/8/2015 8:13:07 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: transition AwaitDone, Akka.Remote.TestKit.ClientFSM+Data -> AwaitDone, Akka.Remote.TestKit.ClientFSM+Data
    [20:13:09][Step 1/1] [NODE2][7/8/2015 8:13:08 PM][DEBUG][Akka.MultiNodeTests.JoinSeedNodeMultiNode2]: Role [seed2] started with address [akka.tcp://MultiNodeClusterSpec@localhost:49880]
    [20:13:09][Step 1/1] [NODE2][7/8/2015 8:13:08 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: processing Event: <Akka.Remote.TestKit.ToServer
    [20:13:09][Step 1/1] [NODE2][7/8/2015 8:13:08 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: unhandled event Akka.Remote.TestKit.ToServer
    [20:13:09][Step 1/1] [NODE2][7/8/2015 8:13:08 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: transition AwaitDone, Akka.Remote.TestKit.ClientFSM+Data -> AwaitDone, Akka.Remote.TestKit.ClientFSM+Data
    [20:13:09][Step 1/1] [NODE5][7/8/2015 8:13:08 PM][DEBUG][Akka.MultiNodeTests.JoinSeedNodeMultiNode5]: Role [ordinary2] started with address [akka.tcp://MultiNodeClusterSpec@localhost:49878]
    [20:13:09][Step 1/1] [NODE5][7/8/2015 8:13:08 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: processing Event: <Akka.Remote.TestKit.ToServer
    [20:13:09][Step 1/1] [NODE5][7/8/2015 8:13:08 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: unhandled event Akka.Remote.TestKit.ToServer
    [20:13:09][Step 1/1] [NODE5][7/8/2015 8:13:08 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: transition AwaitDone, Akka.Remote.TestKit.ClientFSM+Data -> AwaitDone, Akka.Remote.TestKit.ClientFSM+Data
    [20:13:38][Step 1/1] [NODE4][7/8/2015 8:13:37 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: processing Event: <Akka.Actor.FSMBase+StateTimeout>, StateData: <Akka.Remote.TestKit.ClientFSM+Data> from state timeout
    [20:13:38][Step 1/1] [NODE4][7/8/2015 8:13:37 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: connect timeout to TestConductor
    [20:13:38][Step 1/1] [NODE4][7/8/2015 8:13:37 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: transition AwaitDone, Akka.Remote.TestKit.ClientFSM+Data -> Failed, Akka.Remote.TestKit.ClientFSM+Data
    [20:13:38][Step 1/1] [NODE4][7/8/2015 8:13:37 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: processing Event: <<Terminated>: [akka://MultiNodeClusterSpec/user/$b] - ExistenceConfirmed
    [20:13:38][Step 1/1] [NODE4][7/8/2015 8:13:37 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: unhandled event <Terminated>: [akka://MultiNodeClusterSpec/user/$b] - ExistenceConfirmed
    [20:13:38][Step 1/1] [NODE4][7/8/2015 8:13:37 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: transition Failed, Akka.Remote.TestKit.ClientFSM+Data -> Failed, Akka.Remote.TestKit.ClientFSM+Data
    [20:13:38][Step 1/1] [NODE3][7/8/2015 8:13:37 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: processing Event: <Akka.Actor.FSMBase+StateTimeout>, StateData: <Akka.Remote.TestKit.ClientFSM+Data> from state timeout
    [20:13:38][Step 1/1] [NODE3][7/8/2015 8:13:37 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: connect timeout to TestConductor
    [20:13:38][Step 1/1] [NODE3][7/8/2015 8:13:37 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: transition AwaitDone, Akka.Remote.TestKit.ClientFSM+Data -> Failed, Akka.Remote.TestKit.ClientFSM+Data
    [20:13:38][Step 1/1] [NODE3][7/8/2015 8:13:38 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: processing Event: <<Terminated>: [akka://MultiNodeClusterSpec/user/$b] - ExistenceConfirmed
    [20:13:38][Step 1/1] [NODE3][7/8/2015 8:13:38 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: unhandled event <Terminated>: [akka://MultiNodeClusterSpec/user/$b] - ExistenceConfirmed
    [20:13:38][Step 1/1] [NODE3][7/8/2015 8:13:38 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: transition Failed, Akka.Remote.TestKit.ClientFSM+Data -> Failed, Akka.Remote.TestKit.ClientFSM+Data
    [20:13:39][Step 1/1] [NODE2][7/8/2015 8:13:38 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: processing Event: <Akka.Actor.FSMBase+StateTimeout>, StateData: <Akka.Remote.TestKit.ClientFSM+Data> from state timeout
    [20:13:39][Step 1/1] [NODE2][7/8/2015 8:13:38 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: connect timeout to TestConductor
    [20:13:39][Step 1/1] [NODE2][7/8/2015 8:13:38 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: transition AwaitDone, Akka.Remote.TestKit.ClientFSM+Data -> Failed, Akka.Remote.TestKit.ClientFSM+Data
    [20:13:39][Step 1/1] [NODE2][7/8/2015 8:13:38 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: processing Event: <<Terminated>: [akka://MultiNodeClusterSpec/user/$b] - ExistenceConfirmed
    [20:13:39][Step 1/1] [NODE2][7/8/2015 8:13:38 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: unhandled event <Terminated>: [akka://MultiNodeClusterSpec/user/$b] - ExistenceConfirmed
    [20:13:39][Step 1/1] [NODE2][7/8/2015 8:13:38 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: transition Failed, Akka.Remote.TestKit.ClientFSM+Data -> Failed, Akka.Remote.TestKit.ClientFSM+Data
    [20:13:39][Step 1/1] [NODE5][7/8/2015 8:13:38 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: processing Event: <Akka.Actor.FSMBase+StateTimeout>, StateData: <Akka.Remote.TestKit.ClientFSM+Data> from state timeout
    [20:13:39][Step 1/1] [NODE5][7/8/2015 8:13:38 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: connect timeout to TestConductor
    [20:13:39][Step 1/1] [NODE5][7/8/2015 8:13:38 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: transition AwaitDone, Akka.Remote.TestKit.ClientFSM+Data -> Failed, Akka.Remote.TestKit.ClientFSM+Data
    [20:13:39][Step 1/1] [NODE5][7/8/2015 8:13:38 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: processing Event: <<Terminated>: [akka://MultiNodeClusterSpec/user/$b] - ExistenceConfirmed
    [20:13:39][Step 1/1] [NODE5][7/8/2015 8:13:38 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: unhandled event <Terminated>: [akka://MultiNodeClusterSpec/user/$b] - ExistenceConfirmed
    [20:13:39][Step 1/1] [NODE5][7/8/2015 8:13:38 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: transition Failed, Akka.Remote.TestKit.ClientFSM+Data -> Failed, Akka.Remote.TestKit.ClientFSM+Data

**Comment by Aaronontheweb** [comment]
Another set of logs from earlier today: http://petabridge-ci.cloudapp.net/viewLog.html?buildId=1524&buildTypeId=AkkaNet_AkkaNetPrBuild&tab=buildLog&guest=1

    [21:29:17][Step 1/1] [NODE4][7/8/2015 9:29:16 PM][DEBUG][Akka.MultiNodeTests.ConvergenceWithFailureDetectorPuppetMultiNode4]: Role [fourth] started with address [akka.tcp://MultiNodeClusterSpec@localhost:49991]
    [21:29:17][Step 1/1] [NODE4][7/8/2015 9:29:16 PM][DEBUG][ActorSystem(MultiNodeClusterSpec)]: entering barriers first-started
    [21:29:17][Step 1/1] [NODE4][7/8/2015 9:29:16 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: processing Event: <Akka.Remote.TestKit.ToServer
    [21:29:17][Step 1/1] [NODE4][7/8/2015 9:29:16 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: unhandled event Akka.Remote.TestKit.ToServer
    [21:29:17][Step 1/1] [NODE4][7/8/2015 9:29:16 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: transition AwaitDone, Akka.Remote.TestKit.ClientFSM+Data -> AwaitDone, Akka.Remote.TestKit.ClientFSM+Data
    [21:29:46][Step 1/1] [NODE3][7/8/2015 9:29:45 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: processing Event: <Akka.Actor.FSMBase+StateTimeout>, StateData: <Akka.Remote.TestKit.ClientFSM+Data> from state timeout
    [21:29:46][Step 1/1] [NODE3][7/8/2015 9:29:45 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: connect timeout to TestConductor
    [21:29:46][Step 1/1] [NODE3][7/8/2015 9:29:45 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: transition AwaitDone, Akka.Remote.TestKit.ClientFSM+Data -> Failed, Akka.Remote.TestKit.ClientFSM+Data
    [21:29:46][Step 1/1] [NODE3][7/8/2015 9:29:45 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: processing Event: <<Terminated>: [akka://MultiNodeClusterSpec/user/$b] - ExistenceConfirmed
    [21:29:46][Step 1/1] [NODE3][7/8/2015 9:29:45 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: unhandled event <Terminated>: [akka://MultiNodeClusterSpec/user/$b] - ExistenceConfirmed
    [21:29:46][Step 1/1] [NODE3][7/8/2015 9:29:45 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: transition Failed, Akka.Remote.TestKit.ClientFSM+Data -> Failed, Akka.Remote.TestKit.ClientFSM+Data
    [21:29:46][Step 1/1] [NODE2][7/8/2015 9:29:45 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: processing Event: <Akka.Actor.FSMBase+StateTimeout>, StateData: <Akka.Remote.TestKit.ClientFSM+Data> from state timeout
    [21:29:46][Step 1/1] [NODE2][7/8/2015 9:29:45 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: connect timeout to TestConductor
    [21:29:46][Step 1/1] [NODE2][7/8/2015 9:29:45 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: transition AwaitDone, Akka.Remote.TestKit.ClientFSM+Data -> Failed, Akka.Remote.TestKit.ClientFSM+Data
    [21:29:46][Step 1/1] [NODE2][7/8/2015 9:29:45 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: processing Event: <<Terminated>: [akka://MultiNodeClusterSpec/user/$b] - ExistenceConfirmed
    [21:29:46][Step 1/1] [NODE2][7/8/2015 9:29:45 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: unhandled event <Terminated>: [akka://MultiNodeClusterSpec/user/$b] - ExistenceConfirmed
    [21:29:46][Step 1/1] [NODE2][7/8/2015 9:29:45 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: transition Failed, Akka.Remote.TestKit.ClientFSM+Data -> Failed, Akka.Remote.TestKit.ClientFSM+Data
    [21:29:46][Step 1/1] [NODE4][7/8/2015 9:29:45 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: processing Event: <Akka.Actor.FSMBase+StateTimeout>, StateData: <Akka.Remote.TestKit.ClientFSM+Data> from state timeout
    [21:29:46][Step 1/1] [NODE4][7/8/2015 9:29:45 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: connect timeout to TestConductor
    [21:29:46][Step 1/1] [NODE4][7/8/2015 9:29:45 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: transition AwaitDone, Akka.Remote.TestKit.ClientFSM+Data -> Failed, Akka.Remote.TestKit.ClientFSM+Data
    [21:29:46][Step 1/1] [NODE4][7/8/2015 9:29:45 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: processing Event: <<Terminated>: [akka://MultiNodeClusterSpec/user/$b] - ExistenceConfirmed
    [21:29:46][Step 1/1] [NODE4][7/8/2015 9:29:45 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: unhandled event <Terminated>: [akka://MultiNodeClusterSpec/user/$b] - ExistenceConfirmed
    [21:29:46][Step 1/1] [NODE4][7/8/2015 9:29:45 PM][DEBUG][[akka://MultiNodeClusterSpec/user/TestConductorClient]]: transition Failed, Akka.Remote.TestKit.ClientFSM+Data -> Failed, Akka.Remote.TestKit.ClientFSM+Data
    [21:29:51][Step 1/1] [NODE3][9:29 PM]: SPEC FAILED: Akka.MultiNodeTests.ConvergenceWithFailureDetectorPuppetMultiNode3.ConvergenceSpecTests FAIL
    [21:29:51][Step 1/1] [NODE3][9:29 PM]: SPEC FAILED: Type: System.AggregateException
    [21:29:51][Step 1/1] [NODE3][9:29 PM]: SPEC FAILED: Type: System.Threading.Tasks.TaskCanceledException
    [21:29:51][Step 1/1] [NODE3][9:29 PM]: SPEC FAILED: Message: One or more errors occurred.
    [21:29:51][Step 1/1] [NODE3][9:29 PM]: SPEC FAILED: Message: A task was canceled.
    [21:29:51][Step 1/1] [NODE3][9:29 PM]: SPEC FAILED: StackTrace:at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
    [21:29:51][Step 1/1] [NODE3][9:29 PM]: SPEC FAILED: StackTrace: 
    [21:29:51][Step 1/1] [NODE1][7/8/2015 9:29:50 PM][DEBUG][Akka.Remote.TestKit.ConductorHandler]: disconnect from 127.0.0.1:49994
    [21:29:51][Step 1/1] [NODE1][7/8/2015 9:29:50 PM][DEBUG][[akka://MultiNodeClusterSpec/user/controller/127.0.0.1:49994:49994-server3]]: processing Event: <Akka.Remote.TestKit.Controller+ClientDisconnected: RoleName()>, StateData: <> from unknown
    [21:29:51][Step 1/1] [NODE1][7/8/2015 9:29:50 PM][DEBUG][Akka.Remote.TestKit.ConductorHandler]: disconnect from 127.0.0.1:49994
    [21:29:51][Step 1/1] [NODE1][7/8/2015 9:29:50 PM][DEBUG][[akka://MultiNodeClusterSpec/user/controller/127.0.0.1:49994:49994-server3]]: transition Ready,  -> Ready, 
    [21:29:51][Step 1/1] [NODE1][7/8/2015 9:29:50 PM][DEBUG][[akka://MultiNodeClusterSpec/user/controller/barriers]]: processing Event: <Akka.Remote.TestKit.Controller+ClientDisconnected: RoleName(third)>, StateData: <Akka.Remote.TestKit.BarrierCoordinator+Data> from [akka://MultiNodeClusterSpec/user/controller/127.0.0.1:49994:49994-server3]
    [21:29:51][Step 1/1] [NODE1][7/8/2015 9:29:50 PM][DEBUG][[akka://MultiNodeClusterSpec/user/controller/barriers]]: transition Idle, Akka.Remote.TestKit.BarrierCoordinator+Data -> Idle, Akka.Remote.TestKit.BarrierCoordinator+Data
    [21:29:51][Step 1/1] [NODE2][9:29 PM]: SPEC FAILED: Akka.MultiNodeTests.ConvergenceWithFailureDetectorPuppetMultiNode2.ConvergenceSpecTests FAIL
    [21:29:51][Step 1/1] [NODE2][9:29 PM]: SPEC FAILED: Type: System.AggregateException
    [21:29:51][Step 1/1] [NODE2][9:29 PM]: SPEC FAILED: Type: System.Threading.Tasks.TaskCanceledException
    [21:29:51][Step 1/1] [NODE2][9:29 PM]: SPEC FAILED: Message: One or more errors occurred.
    [21:29:51][Step 1/1] [NODE2][9:29 PM]: SPEC FAILED: Message: A task was canceled.
    [21:29:51][Step 1/1] [NODE2][9:29 PM]: SPEC FAILED: StackTrace:at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
    [21:29:51][Step 1/1] [NODE2][9:29 PM]: SPEC FAILED: StackTrace: 
    [21:29:51][Step 1/1] [NODE1][7/8/2015 9:29:50 PM][DEBUG][Akka.Remote.TestKit.ConductorHandler]: disconnect from 127.0.0.1:49995
    [21:29:51][Step 1/1] [NODE1][7/8/2015 9:29:50 PM][DEBUG][[akka://MultiNodeClusterSpec/user/controller/127.0.0.1:49995:49995-server4]]: processing Event: <Akka.Remote.TestKit.Controller+ClientDisconnected: RoleName()>, StateData: <> from unknown
    [21:29:51][Step 1/1] [NODE1][7/8/2015 9:29:50 PM][DEBUG][[akka://MultiNodeClusterSpec/user/controller/127.0.0.1:49995:49995-server4]]: transition Ready,  -> Ready, 
    [21:29:51][Step 1/1] [NODE1][7/8/2015 9:29:50 PM][DEBUG][[akka://MultiNodeClusterSpec/user/controller/barriers]]: processing Event: <Akka.Remote.TestKit.Controller+ClientDisconnected: RoleName(second)>, StateData: <Akka.Remote.TestKit.BarrierCoordinator+Data> from [akka://MultiNodeClusterSpec/user/controller/127.0.0.1:49995:49995-server4]
    [21:29:51][Step 1/1] [NODE1][7/8/2015 9:29:50 PM][DEBUG][[akka://MultiNodeClusterSpec/user/controller/barriers]]: transition Idle, Akka.Remote.TestKit.BarrierCoordinator+Data -> Idle, Akka.Remote.TestKit.BarrierCoordinator+Data
    [21:29:51][Step 1/1] [NODE1][7/8/2015 9:29:50 PM][DEBUG][Akka.Remote.TestKit.ConductorHandler]: disconnect from 127.0.0.1:49995
    [21:29:51][Step 1/1] [NODE4][9:29 PM]: SPEC FAILED: Akka.MultiNodeTests.ConvergenceWithFailureDetectorPuppetMultiNode4.ConvergenceSpecTests FAIL
    [21:29:51][Step 1/1] [NODE4][9:29 PM]: SPEC FAILED: Type: System.AggregateException
    [21:29:51][Step 1/1] [NODE4][9:29 PM]: SPEC FAILED: Type: System.Threading.Tasks.TaskCanceledException
    [21:29:51][Step 1/1] [NODE4][9:29 PM]: SPEC FAILED: Message: One or more errors occurred.
    [21:29:51][Step 1/1] [NODE4][9:29 PM]: SPEC FAILED: Message: A task was canceled.
    [21:29:51][Step 1/1] [NODE4][9:29 PM]: SPEC FAILED: StackTrace:at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
    [21:29:51][Step 1/1] [NODE4][9:29 PM]: SPEC FAILED: StackTrace: 
    [21:29:51][Step 1/1] [NODE1][7/8/2015 9:29:50 PM][DEBUG][Akka.Remote.TestKit.ConductorHandler]: disconnect from 127.0.0.1:49993
    [21:29:51][Step 1/1] [NODE1][7/8/2015 9:29:50 PM][DEBUG][[akka://MultiNodeClusterSpec/user/controller/127.0.0.1:49993:49993-server2]]: processing Event: <Akka.Remote.TestKit.Controller+ClientDisconnected: RoleName()>, StateData: <> from unknown
    [21:29:51][Step 1/1] [NODE1][7/8/2015 9:29:50 PM][DEBUG][[akka://MultiNodeClusterSpec/user/controller/127.0.0.1:49993:49993-server2]]: transition Ready,  -> Ready, 
    [21:29:51][Step 1/1] [NODE1][7/8/2015 9:29:50 PM][DEBUG][Akka.Remote.TestKit.ConductorHandler]: disconnect from 127.0.0.1:49993
    [21:29:51][Step 1/1] [NODE1][7/8/2015 9:29:50 PM][DEBUG][[akka://MultiNodeClusterSpec/user/controller/barriers]]: processing Event: <Akka.Remote.TestKit.Controller+ClientDisconnected: RoleName(fourth)>, StateData: <Akka.Remote.TestKit.BarrierCoordinator+Data> from [akka://MultiNodeClusterSpec/user/controller/127.0.0.1:49993:49993-server2]
    [21:29:51][Step 1/1] [NODE1][7/8/2015 9:29:50 PM][DEBUG][[akka://MultiNodeClusterSpec/user/controller/barriers]]: transition Idle, Akka.Remote.TestKit.BarrierCoordinator+Data -> Idle, Akka.Remote.TestKit.BarrierCoordinator+Data

**Comment by Aaronontheweb** [comment]
Resolved by https://github.com/akkadotnet/akka.net/pull/1777
