### ISSUE TITLE
InvalidActorNameException upon actor restart

### ISSUE THREAD

**Issue by raymens** [akkadotnet/akka.net#1290]
A while back we noticed some processes weren't being executed anymore in our application. Upon some investigation we noticed that several actors had crashed, which happens from time to time, but this time the actors couldn't be restarted due to a `InvalidActorNameException`.

This has happened once within a few months. I'm not sure if this is an akka.net issue or a bad implementation on our side. But anyway, just to be sure I thought I'd post it here. The names of several systems have been altered and this is one of several actors that crashes. They all produced similar/same log outputs as this one.

All the actors crashes due to a bad HTTP request to some service. Actors crashes. Couldn't be restarted so those particular processes stopped. All the other processes kept running just fine.

```
2015-08-28 07:12:54.826 +00:00 [Error] "Unknown Http Error: BadGateway"
System.Exception: Unknown Http Error: BadGateway (`SomeApplication/user/Mother/UpdateAddresses` crashes)

2015-08-28 07:12:55.154 +00:00 [Error] "Error while creating actor instance of type Akka.FSharp.Actors+FunActor`2[System.Object,System.Object] with 1 args: (SomeApplication.Actors.Addresses+updateActor@136)"
[akka://SomeApplication/user/Mother/UpdateAddresses]: Akka.Actor.PostRestartException: Exception post restart (System.Exception) ---> System.Exception: Error while creating actor instance of type Akka.FSharp.Actors+FunActor`2[System.Object,System.Object] with 1 args: (SomeApplication.Actors.Addresses+updateActor@136) ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Akka.Actor.InvalidActorNameException: Actor name "UpdateAddresses" is not unique!
   at Akka.Actor.Internal.NormalChildrenContainer.Reserve(String name)
   at Akka.Actor.ActorCell.<>c__DisplayClass53.<ReserveChild>b__52(IChildrenContainer c)
   at Akka.Util.Internal.InterlockedSpin.Swap[T](T& reference, Func`2 updater)
   at Akka.Actor.ActorCell.ReserveChild(String name)
   at Akka.Actor.ActorCell.MakeChild(Props props, String name, Boolean async, Boolean systemService)
   at Akka.Actor.ActorCell.ActorOf(Props props, String name, Boolean isAsync, Boolean isSystemService)
   at Akka.Actor.ActorCell.ActorOf(Props props, String name)
   at SomeApplication.Actors.Addresses.Actor.updateApiActor[a,b](Actor`1 mailbox) in C:\SomeFolder\AddressesActor.fs:line 33
   at SomeApplication.Actors.Addresses.updateActor@136.Invoke(Actor`1 mailbox) in C:\SomeFolder\AddressesActor.fs:line 136
   at Akka.FSharp.Actors.FunActor`2..ctor(FSharpFunc`2 actor)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Akka.Actor.Props.ActivatorProducer.Produce()
   at Akka.Actor.Props.NewActor()
   --- End of inner exception stack trace ---
   at Akka.Actor.Props.NewActor()
   at Akka.Actor.ActorCell.CreateNewActorInstance()
   at Akka.Actor.ActorCell.<>c__DisplayClass48.<NewActor>b__47()
   at Akka.Actor.ActorCell.UseThreadContext(Action action)
   at Akka.Actor.ActorCell.NewActor()
   at Akka.Actor.ActorCell.FinishRecreate(Exception cause, ActorBase failedActor)
   --- End of inner exception stack trace ---
2015-08-28 07:12:55.185 +00:00 [Error] "Object reference not set to an instance of an object."
System.NullReferenceException: Object reference not set to an instance of an object.
   at Akka.Event.DeadLetterListener.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
2015-08-28 07:12:55.201 +00:00 [Error] "Object reference not set to an instance of an object."
System.NullReferenceException: Object reference not set to an instance of an object.
   at Akka.Event.DeadLetterListener.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
```

**Comment by rogeralsing** [comment]
We need some way to reproduce this.

This specific line in the stacktrace looks suspicious to me:

```
2015-08-28 07:12:55.185 +00:00 [Error] "Object reference not set to an instance of an object."
System.NullReferenceException: Object reference not set to an instance of an object.
```

Was `null` passed as a message somewhere?

**Comment by raymens** [comment]
That's probably the F# `unit` we send to some actors. Like the implementation in #1285. These actors are called using the scheduler.

**Comment by Danthar** [comment]
Whats the status on this issue?
