### ISSUE TITLE
Akka.Fsharp Newtonsoft System.TypeLoadException

### ISSUE THREAD

**Issue by halcwb** [akkadotnet/akka.net#1331]
Using a clean install (via nuget) of Akka.Fsharp, an exception is thrown with the following code:

	#load "Scripts/load-project.fsx"

	open Akka.FSharp

	let system = System.create "akka" (Configuration.load())

resulting in:

	Binding session to 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\Blend\Newtonsoft.Json.dll'...
	System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: Could not load type 'Newtonsoft.Json.Converters.DiscriminatedUnionConverter' from assembly 'Newtonsoft.Json, Version=4.5.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'.
	   at Akka.Serialization.NewtonSoftJsonSerializer..ctor(ExtendedActorSystem system)
	   --- End of inner exception stack trace ---
	   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
	   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
	   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
	   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
	   at System.Activator.CreateInstance(Type type, Object[] args)
	   at Akka.Serialization.Serialization..ctor(ExtendedActorSystem system)
	   at Akka.Actor.Internal.ActorSystemImpl..ctor(String name, Config config)
	   at Akka.FSharp.System.create(String name, Config config)
	   at <StartupCode$FSI_0005>.$FSI_0005.main@() in C:\Users\hal\Dropbox\Development\Lab\Akka\Akka\Script1.fsx:line 5
	Stopped due to error

**Comment by Horusiath** [comment]
For some reason, you've loaded Newtonsoft.Json package in version 4.5, while the current one used by Akka.NET is >=7.0.

**Comment by halcwb** [comment]
I have the right package installed in the project file, only the wrong Newtonsoft dll is used:

Binding session to 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\Blend\Newtonsoft.Json.dll'.

So, that's the problem. Any ideas how to avoid binding to the wrong assembly?

**Comment by Horusiath** [comment]
You can add following snipped to configuration/runtime/assemblyBinding section:

```xml
<dependentAssembly>
  <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="7.01" />
</dependentAssembly>
```
where 7.0.1 is an actually installed version of Newtonsoft.Json.

**Comment by halcwb** [comment]
Thanks!
