### ISSUE TITLE
Akka.IO TcpConnectionListener Racy Spec

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1431]
From http://petabridge-ci.cloudapp.net/viewLog.html?buildId=2720&tab=buildResultsDiv&buildTypeId=AkkaNet_AkkaNetPrBuild&guest=1

 TcpListenerSpec.A_TCP_Listner_must_continue_to_accept_connections_after_a_previous_accept	
 
First failure:  	1429	#1498	No changes	17 Nov 15 22:11
Failed: Timeout 00:00:03 while waiting for a message of type Akka.IO.SelectionHandler+WorkerForCommand 
Expected: True
Actual:   False
   at Akka.TestKit.TestKitBase.InternalExpectMsgEnvelope[T](Nullable`1 timeout, Action`2 assert, String hint, Boolean shouldLog) in d:\BuildAgent\work\49b164d63843fb4\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 193
   at Akka.TestKit.TestKitBase.InternalExpectMsgEnvelope[T](Nullable`1 timeout, Action`1 msgAssert, Action`1 senderAssert, String hint) in d:\BuildAgent\work\49b164d63843fb4\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 179
   at Akka.Tests.IO.TcpListenerSpec.TestSetup.ExpectWorkerForCommand() in d:\BuildAgent\work\49b164d63843fb4\src\core\Akka.Tests\IO\TcpListenerSpec.cs:line 240
   at Akka.Tests.IO.TcpListenerSpec.<A_TCP_Listner_must_continue_to_accept_connections_after_a_previous_accept>b__a(TestSetup x) in d:\BuildAgent\work\49b164d63843fb4\src\core\Akka.Tests\IO\TcpListenerSpec.cs:line 84
   at Akka.Tests.IO.TcpListenerSpec.TestSetup.Run(Action`1 test) in d:\BuildAgent\work\49b164d63843fb4\src\core\Akka.Tests\IO\TcpListenerSpec.cs:line 208

**Comment by Silv3rcircl3** [comment]
Isn't racy anymore
