### ISSUE TITLE
Akka.Persistence.Sqlite spec failure SqliteJournalQuerySpec.Journal_queried_on_Manifest_returns_events_with_particular_manifest	

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1436]
Failed: Timeout 00:00:03 while waiting for a message of type Akka.Persistence.WriteMessagesSuccessful 
Expected: True
Actual:   False
   at Akka.TestKit.Xunit2.XunitAssertions.Fail(String format, Object[] args) in D:\BuildAgent\work\49b164d63843fb4\src\contrib\testkits\Akka.TestKit.Xunit2\XunitAssertions.cs:line 22
   at Akka.TestKit.TestKitBase.InternalExpectMsgEnvelope[T](Nullable`1 timeout, Action`2 assert, String hint, Boolean shouldLog) in D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 196
   at Akka.TestKit.TestKitBase.InternalExpectMsgEnvelope[T](Nullable`1 timeout, Action`1 msgAssert, Action`1 senderAssert, String hint) in D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 179
   at Akka.TestKit.TestKitBase.InternalExpectMsg[T](Nullable`1 timeout, Action`1 msgAssert, String hint) in D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 154
   at Akka.TestKit.TestKitBase.ExpectMsg[T](Nullable`1 duration, String hint) in D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 29
   at Akka.Persistence.Sql.Common.TestKit.SqlJournalQuerySpec.WriteEvents() in D:\BuildAgent\work\49b164d63843fb4\src\contrib\persistence\Akka.Persistence.Sql.Common.TestKit\SqlJournalQuerySpec.cs:line 123
   at Akka.Persistence.Sqlite.Tests.SqliteJournalQuerySpec..ctor(ITestOutputHelper output) in D:\BuildAgent\work\49b164d63843fb4\src\contrib\persistence\Akka.Persistence.Sqlite.Tests\SqliteJournalQuerySpec.cs:line 16

See http://petabridge-ci.cloudapp.net/viewLog.html?buildId=2738&tab=buildResultsDiv&buildTypeId=AkkaNet_AkkaNetPrBuild&guest=1

**Comment by Horusiath** [comment]
Closing, as this seems to be no longer an issue (atm of 1.0.5).
