### ISSUE TITLE
Akka.Persistence Spec failure   MemoryEndToEndAdapterSpec.EventAdapters_in_end_to_end_scenarios_should_allow_using_an_adapter_when_write_was_performed_without_an_adapter	

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1437]
Akka.Actor.InvalidActorNameException : Actor name "p2" is not unique!
   at Akka.Actor.Internal.NormalChildrenContainer.Reserve(String name) in D:\BuildAgent\work\49b164d63843fb4\src\core\Akka\Actor\ChildrenContainer\Internal\NormalChildrenContainer.cs:line 50
   at Akka.Util.Internal.InterlockedSpin.Swap[T](T& reference, Func`2 updater) in D:\BuildAgent\work\49b164d63843fb4\src\core\Akka\Util\Internal\InterlockedSpin.cs:line 32
   at Akka.Actor.ActorCell.ReserveChild(String name) in D:\BuildAgent\work\49b164d63843fb4\src\core\Akka\Actor\ActorCell.Children.cs:line 135
   at Akka.Actor.ActorCell.MakeChild(Props props, String name, Boolean async, Boolean systemService) in D:\BuildAgent\work\49b164d63843fb4\src\core\Akka\Actor\ActorCell.Children.cs:line 355
   at Akka.Actor.ActorCell.ActorOf(Props props, String name) in D:\BuildAgent\work\49b164d63843fb4\src\core\Akka\Actor\ActorCell.Children.cs:line 61
   at Akka.Persistence.Tests.EndToEndEventAdapterSpec.<>c__DisplayClass22_0.<EventAdapters_in_end_to_end_scenarios_should_allow_using_an_adapter_when_write_was_performed_without_an_adapter>b__0(ActorSystem system) in D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.Persistence.Tests\EndToEndEventAdapterSpec.cs:line 370
   at Akka.Persistence.Tests.EndToEndEventAdapterSpec.WithActorSystem[T](String name, Config config, Func`2 block) in D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.Persistence.Tests\EndToEndEventAdapterSpec.cs:line 315
   at Akka.Persistence.Tests.EndToEndEventAdapterSpec.EventAdapters_in_end_to_end_scenarios_should_allow_using_an_adapter_when_write_was_performed_without_an_adapter() in D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.Persistence.Tests\EndToEndEventAdapterSpec.cs:line 379

http://petabridge-ci.cloudapp.net/viewLog.html?buildId=2735&tab=buildResultsDiv&buildTypeId=AkkaNet_AkkaNetPrBuild&guest=1

**Comment by Horusiath** [comment]
Closing, as this seems to be no longer an issue (atm of v1.0.5).
