### ISSUE TITLE
Akka.IO Spec Failure  TcpListenerSpec.A_TCP_Listner_must_drop_an_incoming_connection_if_it_cannot_be_registered_with_a_selector	

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1438]
Failed: Timeout 00:00:03 while waiting for a message of type Akka.IO.SelectionHandler+WorkerForCommand 
Expected: True
Actual:   False
   at Akka.TestKit.Xunit2.XunitAssertions.Fail(String format, Object[] args) in D:\BuildAgent\work\49b164d63843fb4\src\contrib\testkits\Akka.TestKit.Xunit2\XunitAssertions.cs:line 22
   at Akka.TestKit.TestKitBase.InternalExpectMsgEnvelope[T](Nullable`1 timeout, Action`2 assert, String hint, Boolean shouldLog) in D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 196
   at Akka.TestKit.TestKitBase.InternalExpectMsgEnvelope[T](Nullable`1 timeout, Action`1 msgAssert, Action`1 senderAssert, String hint) in D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 179
   at Akka.TestKit.TestKitBase.InternalExpectMsg[T](Nullable`1 timeout, Action`1 msgAssert, String hint) in D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 154
   at Akka.TestKit.TestKitBase.ExpectMsg[T](Nullable`1 duration, String hint) in D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 29
   at Akka.Tests.IO.TcpListenerSpec.TestSetup.ExpectWorkerForCommand() in D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.Tests\IO\TcpListenerSpec.cs:line 240
   at Akka.Tests.IO.TcpListenerSpec.<A_TCP_Listner_must_drop_an_incoming_connection_if_it_cannot_be_registered_with_a_selector>b__7_0(TestSetup x) in D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.Tests\IO\TcpListenerSpec.cs:line 159
   at Akka.Tests.IO.TcpListenerSpec.TestSetup.Run(Action`1 test) in D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.Tests\IO\TcpListenerSpec.cs:line 209

http://petabridge-ci.cloudapp.net/viewLog.html?buildId=2747&tab=buildResultsDiv&buildTypeId=AkkaNet_AkkaNetPrBuild&guest=1

**Comment by Silv3rcircl3** [comment]
Spec is passing
