### ISSUE TITLE
Receivers list cleared when actor is created using Dependency Injection

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#1468]
Given custom base actor A in example shape:

```csharp
class A : ReceiveActor 
{
    protected A()
    {
        Receive<X>(x => { /* do smth */ })
    }
}
```

And inheriting actor B:

```csharp
class B: A
{
    public B() : base() { /* all receivers are inherited from A */ }
}
```

When we'll try to build actor `B` using dependency injection (confirmed on Castle Windsor), we may hit infinite restart loop inside an actor caused by `NullReferenceException` in actor's `AroundReceive` method:

> Object reference not set to an instance of an object.
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)

- Reason for that is that list of receivers (*_matchHandlerBuilders*) defined inside `A` was cleared for some reason once B has been created. Probable source of an issue in DI actor producer and the way it invokes `IInitializableActor.Init` method used by `ReceiveActor`. 
- Another problem we need to address, is the infinite restart loop of a `ReceiveActor` which has no receive behaviors defined.

**Comment by alexpantyukhin** [comment]
I will fix it.

**Comment by annayafi** [comment]
I just found your issue, I think mine is highly related: https://github.com/akkadotnet/akka.net/issues/3039
