### ISSUE TITLE
Race condition with Akka.Remote.Tests.Multinode.RemoteRoundRobinSpec

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1628]
This is the reason why the MNTR fails regularly - this spec. Now we have the information to determine why

```
Running specs for Akka.Remote.Tests.MultiNode.dll [D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.Remote.Tests.MultiNode\bin\Release\Akka.Remote.Tests.MultiNode.dll]
[WARNING][1/8/2016 1:39:19 AM][Thread 0009][[akka://RemoteRoundRobinMultiNode4/user/TestConductorClient]] unhandled event <Terminated>: [akka://RemoteRoundRobinMultiNode4/user/$b] - ExistenceConfirmed=True in state Connected

[Node4][FAIL] Akka.Remote.Tests.MultiNode.RemoteRoundRobinMultiNode4.RemoteRoundRobinSpecs
[Node4][FAIL-EXCEPTION] Type: Xunit.Sdk.EqualException
--> [Node4][FAIL-EXCEPTION] Message: Assert.Equal() Failure
Expected: 8
Actual:   10
--> [Node4][FAIL-EXCEPTION] StackTrace:    at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in c:\TeamCity\buildAgent\work\74856245f07a90f0\src\xunit.assert\Asserts\EqualityAsserts.cs:line 35
   at Akka.Remote.Tests.MultiNode.RemoteRoundRobinSpec.<>c__DisplayClass8_0.<ARemoteRoundRobinMustBeLocallyInstantiatedOnARemoteNodeAndBeAbleToCommunicateThroughItsRemoteActorRef>b__4(Int32 x) in D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.Remote.Tests.MultiNode\RemoteRoundRobinSpec.cs:line 171
   at Akka.Util.Internal.Extensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action) in D:\BuildAgent\work\49b164d63843fb4\src\core\Akka\Util\Internal\Extensions.cs:line 101
   at Akka.Remote.Tests.MultiNode.RemoteRoundRobinSpec.<ARemoteRoundRobinMustBeLocallyInstantiatedOnARemoteNodeAndBeAbleToCommunicateThroughItsRemoteActorRef>b__8_1() in D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.Remote.Tests.MultiNode\RemoteRoundRobinSpec.cs:line 171
   at Akka.Remote.TestKit.MultiNodeSpec.RunOn(Action thunk, RoleName[] nodes) in D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.Remote.TestKit\MultiNodeSpec.cs:line 500
   at Akka.Remote.Tests.MultiNode.RemoteRoundRobinSpec.ARemoteRoundRobinMustBeLocallyInstantiatedOnARemoteNodeAndBeAbleToCommunicateThroughItsRemoteActorRef() in D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.Remote.Tests.MultiNode\RemoteRoundRobinSpec.cs:line 177
   at Akka.Remote.Tests.MultiNode.RemoteRoundRobinSpec.RemoteRoundRobinSpecs() in D:\BuildAgent\work\49b164d63843fb4\src\core\Akka.Remote.Tests.MultiNode\RemoteRoundRobinSpec.cs:line 120

[WARNING][1/8/2016 1:39:24 AM][Thread 0009][LocalActorRefProvider(akka://NoteTestRunner-3)] akka://NoteTestRunner-3/temp trying to remove non-child c
```

**Comment by Aaronontheweb** [comment]
Here's the assertion that fails: https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Remote.Tests.MultiNode/RemoteRoundRobinSpec.cs#L275
