### ISSUE TITLE
Racy Spec: SqliteJournalQuerySpec.Journal_queried_on_Manifest_returns_events_with_particular_manifest	

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1750]
Fails pretty often.

https://github.com/akkadotnet/akka.net/blob/dev/src/contrib/persistence/Akka.Persistence.Sqlite.Tests/SqliteJournalQuerySpec.cs#L13

```
Failed: Timeout 00:00:03 while waiting for a message of type Akka.Persistence.WriteMessagesSuccessful 
Expected: True
Actual:   False
   at Akka.TestKit.Xunit2.XunitAssertions.Fail(String format, Object[] args) in D:\BuildAgent\work\d26c9d7f36545acd\src\contrib\testkits\Akka.TestKit.Xunit2\XunitAssertions.cs:line 22
   at Akka.TestKit.TestKitBase.InternalExpectMsgEnvelope[T](Nullable`1 timeout, Action`2 assert, String hint, Boolean shouldLog) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 196
   at Akka.TestKit.TestKitBase.InternalExpectMsgEnvelope[T](Nullable`1 timeout, Action`1 msgAssert, Action`1 senderAssert, String hint) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 179
   at Akka.TestKit.TestKitBase.InternalExpectMsg[T](Nullable`1 timeout, Action`1 msgAssert, String hint) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 154
   at Akka.TestKit.TestKitBase.ExpectMsg[T](Nullable`1 duration, String hint) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 29
   at Akka.Persistence.Sql.Common.TestKit.SqlJournalQuerySpec.WriteEvents() in D:\BuildAgent\work\d26c9d7f36545acd\src\contrib\persistence\Akka.Persistence.Sql.Common.TestKit\SqlJournalQuerySpec.cs:line 124
   at Akka.Persistence.Sqlite.Tests.SqliteJournalQuerySpec..ctor(ITestOutputHelper output) in D:\BuildAgent\work\d26c9d7f36545acd\src\contrib\persistence\Akka.Persistence.Sqlite.Tests\SqliteJournalQuerySpec.cs:line 23
```

http://petabridge-ci.cloudapp.net/viewLog.html?buildId=6873&tab=buildResultsDiv&buildTypeId=AkkaNet_AkkaNetWindowsUnitTests&guest=1

**Comment by cconstantin** [comment]
@Aaronontheweb I'll look into it.

**Comment by alexvaluyskiy** [comment]
Maybe we should change here Context to context in order to fix this bug?

Akka.Persistence.Sql.Common.SqlJournal
```C#
public override Task ReplayMessagesAsync(IActorContext context, string persistenceId, long fromSequenceNr, long toSequenceNr, long max, Action<IPersistentRepresentation> recoveryCallback)
{
    return DbEngine.ReplayMessagesAsync(persistenceId, fromSequenceNr, toSequenceNr, max, Context.Sender, recoveryCallback);
}
```

**Comment by Aaronontheweb** [comment]
Yep, that might be it

**Comment by cconstantin** [comment]
good catch @alexvaluyskiy. Would you mind sending a PR?

**Comment by alexvaluyskiy** [comment]
@cconstantin, done

**Comment by Aaronontheweb** [comment]
I'd wait until a few new PRs have crept in with this commit included and see if the test no longer fails intermittently, then close the issue.

**Comment by Aaronontheweb** [comment]
Yep, failure is still happening - this is with #1760 merged in:

http://petabridge-ci.cloudapp.net/viewLog.html?buildId=7319&tab=buildResultsDiv&buildTypeId=AkkaNet_AkkaNetWindowsUnitTests&guest=1

**Comment by cconstantin** [comment]
@Aaronontheweb the failure is in the setup of the test, it's got nothing to do with this particular test. It may just be that this test is always run first. As for why the setup fails, I'm not sure.

@Horusiath any thoughts on what can cause the Sqlite journal to initialize slowly? Any chance the shared cache is the reason? As far as I can tell there's a different db set up for each test, so shared cache should have no impact.

**Comment by alexvaluyskiy** [comment]
Not an issue, since we have remote plain old Sql Query

**Comment by alexvaluyskiy** [comment]
@Aaronontheweb @heynickc could we remove this test from the muted tests on TeamCity?
