### ISSUE TITLE
Racy Spec: SnapshotDirectoryFailureSpec.LocalSnapshotStore_configured_with_a_failing_directory_name_should_throw_an_exception_at_startup

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1751]
```
System.IO.DirectoryNotFoundException : Could not find a part of the path 'D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.Persistence.Tests\bin\Release\target\inUseSnapshotPath'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.FileInfo.Create()
   at Akka.Persistence.Tests.SnapshotDirectoryFailureSpec.AtStartup() in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.Persistence.Tests\SnapshotDirectoryFailureSpec.cs:line 61
   at Akka.TestKit.AkkaSpec..ctor(Config config, ITestOutputHelper output) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.Tests.Shared.Internals\AkkaSpec.cs:line 52
   at Akka.Persistence.Tests.PersistenceSpec..ctor(Config config, ITestOutputHelper output) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.Persistence.Tests\PersistenceSpec.cs:line 56
```

Relatively new failure - might be related to some of the changes we've made to Akka.Persistence cc @cconstantin @Horusiath

**Comment by Aaronontheweb** [comment]
Related build: http://petabridge-ci.cloudapp.net/viewLog.html?buildId=6854&buildTypeId=AkkaNet_AkkaNetWindowsUnitTests&guest=1

**Comment by cconstantin** [comment]
@Aaronontheweb yes, it's a new test. I'll look into it.

**Comment by alexvaluyskiy** [comment]
It fails again
