### ISSUE TITLE
Streams: returning `unit` from Map causes ArgumentNullException

### ISSUE THREAD

**Issue by vasily-kirichenko** [akkadotnet/akka.net#1923]
Everything is OK:
```fsharp
Source
    .From([1..10])
    .Map(fun x -> printfn "%d" x; 1) // pay attention we return `1` here 
    .RunForeach((fun _ -> ()), materializer)
```
Raises exception:
```fsharp
Source
    .From([1..10])
    .Map(fun x -> printfn "%d" x; ()) // we return `unit` here
    .RunForeach((fun _ -> ()), materializer)
```
Also raises exception:
```fsharp
Source
    .From([1..10])
    .Map(fun x -> printfn "%d" x) // we return `unit` here as well
    .RunForeach((fun _ -> ()), materializer)
```
```
1         // the first element
val it : Task =
  System.Threading.Tasks.Task`1[System.Reactive.Streams.Unit]
    {AsyncState = null;
     CreationOptions = None;
     Exception = System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Element must not be null, rule 2.13
Parameter name: element
   at Akka.Streams.Stage.GraphStageLogic.Push[T](Outlet outlet, T element) in D:\github\akka.net\src\core\Akka.Streams\Stage\GraphStage.cs:line 904
   at Akka.Streams.Stage.PushPullGraphLogic`2.Push(TOut element) in D:\github\akka.net\src\core\Akka.Streams\Stage\AbstractStage.cs:line 59
   at Akka.Streams.Implementation.Fusing.Map`2.OnPush(TIn element, IContext`1 context) in D:\github\akka.net\src\core\Akka.Streams\Implementation\Fusing\Ops.cs:line 32
   at Akka.Streams.Stage.AbstractStage`6.OnPush(TIn element, IContext context) in D:\github\akka.net\src\core\Akka.Streams\Stage\AbstractStage.cs:line 386
   at Akka.Streams.Stage.PushPullGraphLogic`2.<.ctor>b__2_0() in D:\github\akka.net\src\core\Akka.Streams\Stage\AbstractStage.cs:line 26
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentNullException: Element must not be null, rule 2.13
Parameter name: element
   at Akka.Streams.Stage.GraphStageLogic.Push[T](Outlet outlet, T element) in D:\github\akka.net\src\core\Akka.Streams\Stage\GraphStage.cs:line 904
   at Akka.Streams.Stage.PushPullGraphLogic`2.Push(TOut element) in D:\github\akka.net\src\core\Akka.Streams\Stage\AbstractStage.cs:line 59
   at Akka.Streams.Implementation.Fusing.Map`2.OnPush(TIn element, IContext`1 context) in D:\github\akka.net\src\core\Akka.Streams\Implementation\Fusing\Ops.cs:line 32
   at Akka.Streams.Stage.AbstractStage`6.OnPush(TIn element, IContext context) in D:\github\akka.net\src\core\Akka.Streams\Stage\AbstractStage.cs:line 386
   at Akka.Streams.Stage.PushPullGraphLogic`2.<.ctor>b__2_0() in D:\github\akka.net\src\core\Akka.Streams\Stage\AbstractStage.cs:line 26<---
;
     Id = 109;
     IsCanceled = false;
     IsCompleted = true;
     IsFaulted = true;
     Status = Faulted;}
> 
```
The same problem arises if we return `null` from `Map` like this `.Map(fun x -> printfn "%d" x; null)`. 
It may be not a problem, just don't return `null`s and `unit`s, but all side effecting functions in F# return `unit`, so `.Map(fun x -> printfn "%d" x)`, which looks completely OK, will throw as well, which is far from intuitive behavior.

**Comment by Horusiath** [comment]
This works as intended. If you'll read the error message, passing nullish value between stages is explicit violation of of 2.13 rule of the Reactive Streams specification.

**Comment by vasily-kirichenko** [comment]
I'm curious if it crashes on `.Map(x => Console.WriteLine(x))` in C#, it returns `void` whereas F# returns `()`, which is represented as `null` at runtime.

**Comment by Horusiath** [comment]
Map on C# void return type will result with compilation error.

**Comment by vasily-kirichenko** [comment]
One more inconvenience: 
```fsharp
.Map(fun x -> if x < 0 then Some (x + 10) else None)
```
`None` is also represented as `null` at runtime, so the code raises NRE as well.

**Comment by vasily-kirichenko** [comment]
OK, let's consider this as well knows F#-related issue.
