### ISSUE TITLE
Port Akka.Cluster MultiNodeSpec: NodeChurnSpec

### ISSUE THREAD

**Issue by alexvaluyskiy** [akkadotnet/akka.net#2008]
https://github.com/akka/akka/blob/master/akka-cluster/src/multi-jvm/scala/akka/cluster/NodeChurnSpec.scala

**Comment by alexvaluyskiy** [comment]
Started here
https://github.com/alexvaluyskiy/akka.net/commit/b97e38358bc8983dc59cecad3171ace0339884c0

It works only on the first round, when the nodes are leaving. On the second round the spec is fails, when the nodes are downing

**Comment by Aaronontheweb** [comment]
Think it might be related to either of these?

https://github.com/akkadotnet/akka.net/pull/2090
https://github.com/akkadotnet/akka.net/pull/2091

#2090 fixed some definite bugs in the `EndpointManager` (proven by the `ActorsLeakSpec`) but it looks like that may have exposed some issues in the Clustering system itself... Haven't had a chance to look into it; still waiting on the build server to give me the reports on some of the failed tests as I write this.

**Comment by alexvaluyskiy** [comment]
This fails on the newest code, right here
https://github.com/alexvaluyskiy/akka.net/commit/b97e38358bc8983dc59cecad3171ace0339884c0#diff-135840efba0277572572f184c1ba7107R142

```
[Node3][FAIL] Akka.Cluster.Tests.MultiNode.NodeChurnMultiNode3.NodeChurnSpecs
[Node3][FAIL-EXCEPTION] Type: Xunit.Sdk.EqualException
--> [Node3][FAIL-EXCEPTION] Message: Assert.Equal() Failure
Expected: 3
Actual:   18
--> [Node3][FAIL-EXCEPTION] StackTrace:    at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in c:\TeamCity\buildAgent\work\74856245f07a90f0\src\xunit.assert\Asserts\EqualityAsserts.cs:line 35
   at Akka.Cluster.Tests.MultiNode.MultiNodeClusterSpec.<>c__DisplayClass26_0.<AwaitMembersUp>b__3() in C:\Projects\akka.net\src\core\Akka.Cluster.TestKit\MultiNodeClusterSpec.cs:line 367
   at Akka.TestKit.TestKitBase.AwaitAssert(Action assertion, Nullable`1 duration, Nullable`1 interval) in C:\Projects\akka.net\src\core\Akka.TestKit\TestKitBase_AwaitAssert.cs:line 48
   at Akka.Cluster.Tests.MultiNode.MultiNodeClusterSpec.<>c__DisplayClass26_0.<AwaitMembersUp>b__0() in C:\Projects\akka.net\src\core\Akka.Cluster.TestKit\MultiNodeClusterSpec.cs:line 367
   at Akka.TestKit.TestKitBase.<>c__DisplayClass116_0.<Within>b__0() in C:\Projects\akka.net\src\core\Akka.TestKit\TestKitBase_Within.cs:line 38
   at Akka.TestKit.TestKitBase.Within[T](TimeSpan min, TimeSpan max, Func`1 function, String hint) in C:\Projects\akka.net\src\core\Akka.TestKit\TestKitBase_Within.cs:line 79
   at Akka.TestKit.TestKitBase.Within(TimeSpan min, TimeSpan max, Action action, String hint) in C:\Projects\akka.net\src\core\Akka.TestKit\TestKitBase_Within.cs:line 38
   at Akka.TestKit.TestKitBase.Within(TimeSpan max, Action action) in C:\Projects\akka.net\src\core\Akka.TestKit\TestKitBase_Within.cs:line 26
   at Akka.Cluster.Tests.MultiNode.MultiNodeClusterSpec.AwaitMembersUp(Int32 numbersOfMembers, ImmutableHashSet`1 canNotBePartOfMemberRing, Nullable`1 timeout) in C:\Projects\akka.net\src\core\Akka.Cluster.TestKit\MultiNodeClusterSpec.cs:line 359
   at Akka.Cluster.Tests.MultiNode.NodeChurnSpec.AwaitRemoved(ImmutableList`1 additionaSystems) in C:\Projects\akka.net\src\core\Akka.Cluster.Tests.MultiNode\NodeChurnSpec.cs:line 176
   at Akka.Cluster.Tests.MultiNode.NodeChurnSpec.Cluster_with_short_lived_members_must_join_and_remove_transient_nodes_without_growing_gossip_payload() in C:\Projects\akka.net\src\core\Akka.Cluster.Tests.MultiNode\NodeChurnSpec.cs:line 143
   at Akka.Cluster.Tests.MultiNode.NodeChurnSpec.NodeChurnSpecs() in C:\Projects\akka.net\src\core\Akka.Cluster.Tests.MultiNode\NodeChurnSpec.cs:line 92
```

The spec expects that the all downed node will remove from the Roles, but they don't
