### ISSUE TITLE
Port Akka.Cluster MultiNodeSpec: TransitionSpec

### ISSUE THREAD

**Issue by alexvaluyskiy** [akkadotnet/akka.net#2014]
https://github.com/akka/akka/blob/master/akka-cluster/src/multi-jvm/scala/akka/cluster/TransitionSpec.scala

**Comment by alexvaluyskiy** [comment]
Started here https://github.com/alexvaluyskiy/akka.net/commit/c41d2f69dccd8737bb51de03c7db47ae826850da
Seems to be, that transitions is not working so fast, as it should be. If I put Thread.Sleep between all transitions, this spec will pass

**Comment by alexvaluyskiy** [comment]
This spec have already been implemented here https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Cluster.Tests.MultiNode/TransitionSpec.cs
It just not works

**Comment by alexvaluyskiy** [comment]
```
[Node1][FAIL] Akka.Cluster.Tests.MultiNode.TransitionMultiNode1.TransitionSpecs
[Node1][FAIL-EXCEPTION] Type: FluentAssertions.Execution.AssertionFailedException
--> [Node1][FAIL-EXCEPTION] Message: Expected collection {akka.tcp://MultiNodeClusterSpec@localhost:50216} to be equivalent to {akka.tcp://MultiNodeClusterSpec@localhost:50216, akka.tcp://MultiNodeClusterSpec@localhost:50215}, but it misses {akka.tcp://MultiNodeClusterSpec@localhost:50215}.
--> [Node1][FAIL-EXCEPTION] StackTrace:    at FluentAssertions.Execution.FallbackTestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\Shared\Execution\FallbackTestFramework.cs:line 21
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 42
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Collections.CollectionAssertions`2.BeEquivalentTo[T](IEnumerable`1 expected, String because, Object[] reasonArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Collections\CollectionAssertions.cs:line 369
   at Akka.Cluster.Tests.MultiNode.TransitionSpec.AwaitMembers(Address[] addresses) in C:\Projects\akka.net\src\core\Akka.Cluster.Tests.MultiNode\TransitionSpec.cs:line 106
   at Akka.Cluster.Tests.MultiNode.TransitionSpec.<A_Cluster_must_perform_correct_transitions_when_second_joining_first>b__18_1() in C:\Projects\akka.net\src\core\Akka.Cluster.Tests.MultiNode\TransitionSpec.cs:line 195
   at Akka.Remote.TestKit.MultiNodeSpec.RunOn(Action thunk, RoleName[] nodes) in C:\Projects\akka.net\src\core\Akka.Remote.TestKit\MultiNodeSpec.cs:line 503
   at Akka.Cluster.Tests.MultiNode.TransitionSpec.A_Cluster_must_perform_correct_transitions_when_second_joining_first() in C:\Projects\akka.net\src\core\Akka.Cluster.Tests.MultiNode\TransitionSpec.cs:line 192
   at Akka.Cluster.Tests.MultiNode.TransitionSpec.TransitionSpecs() in C:\Projects\akka.net\src\core\Akka.Cluster.Tests.MultiNode\TransitionSpec.cs:line 163
```

**Comment by Aaronontheweb** [comment]
Looking into this now

**Comment by Aaronontheweb** [comment]
Also moving to 1.2 - same reason. Need to investigate some equality comparison issues with `RoleName` and how it's used specifically in this spec.

**Comment by Aaronontheweb** [comment]
I've resumed work on this per 1.2.1

**Comment by Aaronontheweb** [comment]
Found the issue with this spec - passes when the `First` role has the lowest port number (making it the leader;) fails when it doesn't. Need to adjust the `Leader` method accordingly inside the spec. So it's a bug with the spec itself.
