### ISSUE TITLE
Racy spec: AkkaProtocolStressTest.AkkaProtocolTransport_must_guarantee_at_most_once_delivery_and_message_ordering_despite_packet_loss	

### ISSUE THREAD

**Issue by alexvaluyskiy** [akkadotnet/akka.net#2036]
Failed: Timeout 00:01:00 while waiting for a message of type System.Tuple`2[System.Int32,System.Int32] 
Expected: True
Actual:   False
   at Akka.TestKit.Xunit2.XunitAssertions.Fail(String format, Object[] args) in D:\BuildAgent\work\d26c9d7f36545acd\src\contrib\testkits\Akka.TestKit.Xunit2\XunitAssertions.cs:line 22
   at Akka.TestKit.TestKitBase.InternalExpectMsgEnvelope[T](Nullable`1 timeout, Action`2 assert, String hint, Boolean shouldLog) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 196
   at Akka.TestKit.TestKitBase.InternalExpectMsgEnvelope[T](Nullable`1 timeout, Action`1 msgAssert, Action`1 senderAssert, String hint) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 179
   at Akka.TestKit.TestKitBase.InternalExpectMsg[T](Nullable`1 timeout, Action`1 msgAssert, String hint) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 154
   at Akka.TestKit.TestKitBase.ExpectMsg[T](Nullable`1 duration, String hint) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 29
   at Akka.Remote.Tests.Transport.AkkaProtocolStressTest.AkkaProtocolTransport_must_guarantee_at_most_once_delivery_and_message_ordering_despite_packet_loss() in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.Remote.Tests\Transport\AkkaProtocolStressTest.cs:line 199

**Comment by Aaronontheweb** [comment]
Yeah, @JeffCyr and I both suspect that it's an issue with the `FailureInjectorTransportAdapter`.

**Comment by Aaronontheweb** [comment]
Fails locally for me every now and then too.
