### ISSUE TITLE
Racy MultiNodeSpec: RestartFirstSeedNodeSpecs

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#2045]
http://petabridge-ci.cloudapp.net/viewLog.html?buildId=11407&buildTypeId=AkkaNet_AkkaNetWindowsMultiNodeTests&tab=artifacts#!a2z9s3fds32,bojvyhxihmxb&guest=1

```
[Node1][FAIL] Akka.Cluster.Tests.MultiNode.RestartFirstSeedNodeNode1.RestartFirstSeedNodeSpecs
[Node1][FAIL-EXCEPTION] Type: Xunit.Sdk.XunitException
--> [Node1][FAIL-EXCEPTION] Message: Expected value to be 3, but found 2.
--> [Node1][FAIL-EXCEPTION] StackTrace:    at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\Shared\Execution\LateBoundTestFramework.cs:line 26
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 42
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Numeric.NumericAssertions`1.Be(T expected, String because, Object[] reasonArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Numeric\NumericAssertions.cs:line 44
   at Akka.Cluster.Tests.MultiNode.RestartFirstSeedNodeSpec.<Cluster_seed_nodes__must_be_able_to_restart_first_seed_node_and_join_other_seed_nodes>b__8_4() in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.Cluster.Tests.MultiNode\RestartFirstSeedNodeSpec.cs:line 106
   at Akka.TestKit.TestKitBase.AwaitAssert(Action assertion, Nullable`1 duration, Nullable`1 interval) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.TestKit\TestKitBase_AwaitAssert.cs:line 48
   at Akka.Cluster.Tests.MultiNode.RestartFirstSeedNodeSpec.<Cluster_seed_nodes__must_be_able_to_restart_first_seed_node_and_join_other_seed_nodes>b__8_3() in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.Cluster.Tests.MultiNode\RestartFirstSeedNodeSpec.cs:line 104
   at Akka.Remote.TestKit.MultiNodeSpec.RunOn(Action thunk, RoleName[] nodes) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.Remote.TestKit\MultiNodeSpec.cs:line 501
   at Akka.Cluster.Tests.MultiNode.RestartFirstSeedNodeSpec.<Cluster_seed_nodes__must_be_able_to_restart_first_seed_node_and_join_other_seed_nodes>b__8_0() in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.Cluster.Tests.MultiNode\RestartFirstSeedNodeSpec.cs:line 101
   at Akka.TestKit.TestKitBase.<>c__DisplayClass116_0.<Within>b__0() in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.TestKit\TestKitBase_Within.cs:line 38
   at Akka.TestKit.TestKitBase.Within[T](TimeSpan min, TimeSpan max, Func`1 function, String hint) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.TestKit\TestKitBase_Within.cs:line 79
   at Akka.TestKit.TestKitBase.Within(TimeSpan min, TimeSpan max, Action action, String hint) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.TestKit\TestKitBase_Within.cs:line 38
   at Akka.TestKit.TestKitBase.Within(TimeSpan max, Action action) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.TestKit\TestKitBase_Within.cs:line 26
   at Akka.Cluster.Tests.MultiNode.RestartFirstSeedNodeSpec.Cluster_seed_nodes__must_be_able_to_restart_first_seed_node_and_join_other_seed_nodes() in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.Cluster.Tests.MultiNode\RestartFirstSeedNodeSpec.cs:line 78
   at Akka.Cluster.Tests.MultiNode.RestartFirstSeedNodeSpec.RestartFirstSeedNodeSpecs() in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.Cluster.Tests.MultiNode\RestartFirstSeedNodeSpec.cs:line 73
```

**Comment by alexvaluyskiy** [comment]
It has failed just one time. I think it is not racy spec

**Comment by Aaronontheweb** [comment]
@alexvaluyskiy just wanted to log it right away in the event that there's an issue with the code under test. If it failed because of a random timeout in the test conductor (which does happen) then it's nothing to worry about.

**Comment by Aaronontheweb** [comment]
Not a racy spec.
