### ISSUE TITLE
Akka.Remote TypeLoadException for RouterConfiguration

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#2136]
Installed some of the Akka.NET 1.1 nightly builds into WebCrawler and had the following exception on startup (this code runs fine in Akka.NET 1.0.8):

![image](https://cloud.githubusercontent.com/assets/326939/16597714/38e97836-42af-11e6-958f-de8e26fc338d.png)

```
System.TypeLoadException was unhandled by user code
  HResult=-2146233054
  Message=Derived method 'NewRoutee' in type 'Akka.Remote.Routing.RemoteRouterConfig' from assembly 'Akka.Remote, Version=1.0.9.237, Culture=neutral, PublicKeyToken=null' cannot reduce access.
  Source=Akka.Remote
  TypeName=Akka.Remote.Routing.RemoteRouterConfig
  StackTrace:
       at Akka.Remote.RemoteDeployer.CheckRemoteRouterConfig(Deploy deploy)
       at Akka.Remote.RemoteDeployer.ParseConfig(String key, Config config)
       at Akka.Actor.Deployer.<>c__DisplayClass3_0.<.ctor>b__1(KeyValuePair`2 x)
       at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
       at Akka.Actor.Deployer..ctor(Settings settings)
       at Akka.Remote.RemoteDeployer..ctor(Settings settings)
       at Akka.Remote.RemoteActorRefProvider..ctor(String systemName, Settings settings, EventStream eventStream)
       at Akka.Cluster.ClusterActorRefProvider..ctor(String systemName, Settings settings, EventStream eventStream)
  InnerException: 
```

![image](https://cloud.githubusercontent.com/assets/326939/16597759/69617cf2-42af-11e6-8ea8-7175a39bf966.png)

Relevant HOCON - fails on `tasker`:

```
akka {
    actor {
        provider = "Akka.Cluster.ClusterActorRefProvider, Akka.Cluster"
        deployment {
            /tasker {
                router = consistent-hashing-group
                routees.paths = ["/user/api"]
                virtual-nodes-factor = 8
                cluster {
                        enabled = on
                        max-nr-of-instances-per-node = 2
                        allow-local-routees = off
                        use-role = tracker
                }
            }                
        }
    }
    
    remote {
        log-remote-lifecycle-events = DEBUG
        
        helios.tcp {
            transport-class = "Akka.Remote.Transport.Helios.HeliosTcpTransport, Akka.Remote"
            applied-adapters = []
            transport-protocol = tcp
            #will be populated with a dynamic host-name at runtime if left uncommented
            #public-hostname = "POPULATE STATIC IP HERE"
            hostname = "127.0.0.1"
            port = 16666
        }
    }            

    cluster {
        #will inject this node as a self-seed node at run-time
        seed-nodes = ["akka.tcp://webcrawler@127.0.0.1:4053"] #manually populate other seed nodes here, i.e. "akka.tcp://lighthouse@127.0.0.1:4053", "akka.tcp://lighthouse@127.0.0.1:4044"
        roles = [web]
    }
}
```

**Comment by Aaronontheweb** [comment]
Nevermind! This was caused by not properly rebuilding the solution after installing the NuGet packages. Works as expected after a rebuild.
