### ISSUE TITLE
NullReferenceException thrown during remote message routing if address conflict

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#2151]
Definitely a bug; investigating the reproduction steps now.

NRE gets thrown here:
```
   at Akka.Actor.ActorPath.get_ElementsWithUid()
   at Akka.Remote.RemoteActorRefProvider.ResolveActorRefWithLocalAddress(String path, Address localAddress)
   at Akka.Remote.Transport.AkkaPduProtobuffCodec.DecodeMessage(ByteString raw, RemoteActorRefProvider provider, Address localAddress)
   at Akka.Remote.EndpointReader.TryDecodeMessageAndAck(ByteString pdu)
```

Appears to occur during an address mismatch; i.e. one node bound to `127.0.0.1`, other is trying to contact `localhost`. Resolves to same physical address, but different logical addresses.

**Comment by Aaronontheweb** [comment]
Think I figured it out:

```csharp
/// <summary>
        /// INTERNAL API.
        /// 
        /// Called in deserialization of incoming remote messages where the correct local address is known.
        /// </summary>
        internal IInternalActorRef ResolveActorRefWithLocalAddress(string path, Address localAddress)
        {
            ActorPath actorPath;
            if (ActorPath.TryParse(path, out actorPath))
            {
                //the actor's local address was already included in the ActorPath
                if (HasAddress(actorPath.Address))
                {
                    // HACK: needed to make ActorSelections work
                    if (actorPath.ToStringWithoutAddress().Equals("/"))
                        return RootGuardian;
                    return _local.ResolveActorRef(RootGuardian, actorPath.ElementsWithUid);
                }
                    
                return new RemoteActorRef(Transport, localAddress, new RootActorPath(actorPath.Address) / actorPath.ElementsWithUid, ActorRefs.Nobody, Props.None, Deploy.None);
            }
            _log.Debug("resolve of unknown path [{0}] failed", path);
            return InternalDeadLetters;
        }
```

We're not enforcing the correct behavior if `HasAddress` is false.
