### ISSUE TITLE
Racy spec: TailChoppingSpec.Tail_chopping_group_router_must_throw_exception_if_no_result_will_arrive_within_the_given_time

### ISSUE THREAD

**Issue by alexvaluyskiy** [akkadotnet/akka.net#2231]
It fails with message

```
Failed: Expected a message of type Akka.Actor.Status+Failure, but received {ack} (type System.String) instead  from [akka://RuntimeType-120/deadLetters]
Expected: True
Actual:   False
   at Akka.TestKit.Xunit2.XunitAssertions.Fail(String format, Object[] args) in D:\BuildAgent\work\d26c9d7f36545acd\src\contrib\testkits\Akka.TestKit.Xunit2\XunitAssertions.cs:line 22
   at Akka.TestKit.TestKitBase.InternalExpectMsgEnvelope[T](Nullable`1 timeout, Action`2 assert, String hint, Boolean shouldLog) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 206
   at Akka.TestKit.TestKitBase.InternalExpectMsgEnvelope[T](Nullable`1 timeout, Action`1 msgAssert, Action`1 senderAssert, String hint) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 182
   at Akka.TestKit.TestKitBase.InternalExpectMsg[T](Nullable`1 timeout, Action`1 msgAssert, String hint) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 157
   at Akka.TestKit.TestKitBase.ExpectMsg[T](Nullable`1 duration, String hint) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 29
   at Akka.Tests.Routing.TailChoppingSpec.Tail_chopping_group_router_must_throw_exception_if_no_result_will_arrive_within_the_given_time() in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.Tests\Routing\TailChoppingSpec.cs:line 138
```

**Comment by marcpiechura** [comment]
fixed in #2721
