### ISSUE TITLE
NullReferenceException when trying to configure sharding

### ISSUE THREAD

**Issue by jpierson** [akkadotnet/akka.net#2235]
I'm working on a prototype based on the example code shown in the documentation for [cluster sharding](http://getakka.net/docs/clustering/cluster-sharding) but I'm running into a NullReferenceException when making a call to `ClusterSharding.Get(mySystem)`. I'm assuming there is something I'm missing in my configuration but the exception here really isn't pointing me in a clear direction.

```
System.NullReferenceException occurred
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Akka.Cluster
  StackTrace:
       at Akka.Cluster.ClusterSettings..ctor(Config config, String systemName)
       at Akka.Cluster.Cluster..ctor(ActorSystemImpl system)
       at Akka.Cluster.ClusterExtension.CreateExtension(ExtendedActorSystem system)
       at Akka.Actor.ExtensionIdProvider`1.Akka.Actor.IExtensionId.CreateExtension(ExtendedActorSystem system)
       at Akka.Actor.Internal.ActorSystemImpl.<>c__DisplayClass55_0.<RegisterExtension>b__1()
       at System.Lazy`1.CreateValue()
       at System.Lazy`1.LazyInitValue()
       at System.Lazy`1.get_Value()
       at Akka.Actor.Internal.ActorSystemImpl.TryGetExtension(Type extensionType, Object& extension)
       at Akka.Actor.Internal.ActorSystemImpl.GetExtension(IExtensionId extensionId)
       at Akka.Actor.ExtensionIdProvider`1.Get(ActorSystem system)
       at Akka.Actor.ExtensionIdProvider`1.Akka.Actor.IExtensionId.Get(ActorSystem system)
       at Akka.Actor.Internal.ActorSystemImpl.RegisterExtension(IExtensionId extension)
       at Akka.Actor.ActorSystemWithExtensions.WithExtension[T,TI](ActorSystem system)
       at Akka.Cluster.Sharding.ClusterSharding..ctor(ExtendedActorSystem system)
       at Akka.Cluster.Sharding.ClusterShardingExtensionProvider.CreateExtension(ExtendedActorSystem system)
       at Akka.Actor.ExtensionIdProvider`1.Akka.Actor.IExtensionId.CreateExtension(ExtendedActorSystem system)
       at Akka.Actor.Internal.ActorSystemImpl.<>c__DisplayClass55_0.<RegisterExtension>b__1()
       at System.Lazy`1.CreateValue()
       at System.Lazy`1.LazyInitValue()
       at System.Lazy`1.get_Value()
       at Akka.Actor.Internal.ActorSystemImpl.TryGetExtension(Type extensionType, Object& extension)
       at Akka.Actor.Internal.ActorSystemImpl.GetExtension(IExtensionId extensionId)
       at Akka.Actor.ExtensionIdProvider`1.Get(ActorSystem system)
       at Akka.Actor.ExtensionIdProvider`1.Akka.Actor.IExtensionId.Get(ActorSystem system)
       at Akka.Actor.Internal.ActorSystemImpl.RegisterExtension(IExtensionId extension)
       at Akka.Actor.ActorSystemWithExtensions.WithExtension[T,TI](ActorSystem system)
       at Akka.Cluster.Sharding.ClusterSharding.Get(ActorSystem system)
       at Experiments.EventRouterActor.ConfigureSharding() in C:\MyFolder\Myfile.cs:line 88
  InnerException: 
```

**Comment by jpierson** [comment]
After poking around I realized that I had copied my hocon config into the wrong project's App.config. After correcting that I found that I'm getting the same exception in the same place but with a different stack trace.

```
System.NullReferenceException occurred
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Akka.Cluster.Tools
  StackTrace:
       at Akka.Cluster.Tools.Singleton.ClusterSingletonManagerSettings.Create(Config config)
       at Akka.Cluster.Sharding.ClusterShardingSettings.Create(Config config, Config singletonConfig)
       at Akka.Cluster.Sharding.ClusterShardingSettings.Create(ActorSystem system)
       at Akka.Cluster.Sharding.ClusterSharding..ctor(ExtendedActorSystem system)
       at Akka.Cluster.Sharding.ClusterShardingExtensionProvider.CreateExtension(ExtendedActorSystem system)
       at Akka.Actor.ExtensionIdProvider`1.Akka.Actor.IExtensionId.CreateExtension(ExtendedActorSystem system)
       at Akka.Actor.Internal.ActorSystemImpl.<>c__DisplayClass55_0.<RegisterExtension>b__1()
       at System.Lazy`1.CreateValue()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Lazy`1.get_Value()
       at Akka.Actor.Internal.ActorSystemImpl.TryGetExtension[T](T& extension)
       at Akka.Actor.Internal.ActorSystemImpl.GetExtension[T]()
       at Akka.Actor.ActorSystemWithExtensions.WithExtension[T,TI](ActorSystem system)
       at Akka.Cluster.Sharding.ClusterSharding.Get(ActorSystem system)
       at Experiments.EventRouterActor.ConfigureSharding() in C:\Users\jeff\source\365POS-Sync\365POS_Kiosk_Sync\KioskDistributorNode\EventRouterActor.cs:line 88
  InnerException: 

```

**Comment by alexvaluyskiy** [comment]
please provide your source code

**Comment by jpierson** [comment]
@alexvaluyskiy: I pushed a sample app I can reproduce this issue to https://github.com/jpierson/x-akka-sharding

**Comment by jpierson** [comment]
Based on the [code here](https://github.com/akkadotnet/akka.net/blob/a9e02659d5e73c226630c7034281e811a1cca21f/src/contrib/cluster/Akka.Cluster.Tools/Singleton/ClusterSingletonManagerSettings.cs#L28-L35) I don't see anything other than the `config` parameter possibly being a null reference which would cause a NullReferenceException directly from the `ClusterSingletonManagerSettings` constructor.

**Comment by jpierson** [comment]
Ok, now that I had more context to search for I found https://github.com/akkadotnet/akka.net/issues/1660 which appears to be a duplicate. I haven't traced where this code has been merged into yet to determine whether it is in the version of the packages I'm referencing.

**Comment by alexvaluyskiy** [comment]
Yes, try to use DefaultConfig as a fallback. Or just copy all standard sharding config to your config

**Comment by jpierson** [comment]
@alexvaluyskiy, I haven't tried working around this by setting the config directly but I did update `Akka.Cluster.Sharding` and `Akka.Cluster.Tools` from _1.0.6_ to _1.1.1.28-beta_ and I don't seem to be getting the error anymore. I'm not sure if using these pre-release packages will give me grief in terms of compatibility with other packages or whether they will be out of beta any time soon (appears from roadmap sept at the earliest).

With the above mentioned changes I'm still unable to get my [sharding example](https://github.com/jpierson/x-akka-sharding) working as expected due to [some other issues](https://github.com/jpierson/x-akka-sharding/issues/2) but the immediate problem mentioned here seems to be resolved for now.

**Comment by Silv3rcircl3** [comment]
@jpierson so we can close this one?

**Comment by jpierson** [comment]
I suppose so, I would re recommend that more inflation on the intended use of lighthouse be added to a readme in that repo. It's not clear whether it is intended to be customized or not in order to use.
