### ISSUE TITLE
A node using cluster sharding appears to require Lighthouse also to reference Akka.Cluster.Sharding packages

### ISSUE THREAD

**Issue by jpierson** [akkadotnet/akka.net#2238]
While working out a small test app for learning Akka Cluster Sharding I ran into an unexpected issue where after updating my main cluster node project to reference 1.1.1.28 beta NuGet packages to work around #2235 that I then started to see errors such as the ones below in the Lighthouse log. From the details it appeared to me that Lighthouse was expecting to also resolve the assembly references to `Akka.Cluster.Sharding` even though I didn't expect it to do anything more than just the cluster seed responsibility. Is this expected design that lighthouse or a similar seed node would have to be customized according to the cluster or is it possible that this is just a rough part in the current design or even something that I have wrong in my configuration?

Please find the sample app source code demonstrating the issue [here](https://github.com/jpierson/x-akka-sharding/tree/c63b66c7accd471de5f9f0e4186b6220779d39fe) and https://github.com/jpierson/x-akka-sharding/issues/2 for more details on the error and how I worked around it for now.

```
Akka.Remote.EndpointWriter: AssociationError [akka.tcp://test@127.0.0.1:4053] <- akka.tcp://test@0.0.0.0:42647: Error [Could not load file or assembly 'Akka.Cluster.Sharding, Version=1.1.1.28, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.] [   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at Wire.ValueSerializers.ObjectSerializer.<>c.<GetTypeFromManifestName>b__16_0(Byte[] b)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Wire.ValueSerializers.ObjectSerializer.GetTypeFromManifestName(Stream stream, DeserializerSession session)
   at Wire.Serializer.GetDeserializerByManifest(Stream stream, DeserializerSession session)
   at Wire.Serializer.Deserialize[T](Stream stream)
   at Akka.Serialization.WireSerializer.FromBinary(Byte[] bytes, Type type)
   at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
   at Akka.Remote.Serialization.MessageContainerSerializer.FromBinary(Byte[] bytes, Type type)
   at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
   at Akka.Remote.MessageSerializer.Deserialize(ActorSystem system, SerializedMessage messageProtocol)
   at Akka.Remote.DefaultMessageDispatcher.Dispatch(IInternalActorRef recipient, Address recipientAddress, SerializedMessage message, IActorRef senderOption)
   at Akka.Remote.EndpointReader.<Reading>b__11_1(InboundPayload inbound)
   at lambda_method(Closure , Object , Action`1 , Action`1 , Action`1 )
   at Akka.Tools.MatchHandler.PartialHandlerArgumentsCapture`4.Handle(T value)
   at Akka.Actor.ReceiveActor.ExecutePartialMessageHandler(Object message, PartialAction`1 partialAction)
   at Akka.Actor.ReceiveActor.OnReceive(Object message)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)]
Akka.Remote.ReliableDeliverySupervisor: Association with remote system akka.tcp://test@0.0.0.0:42647 has failed; address is now gated for 5000 ms. Reason is: [System.IO.FileNotFoundException: Could not load file or assembly 'Akka.Cluster.Sharding, Version=1.1.1.28, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'Akka.Cluster.Sharding, Version=1.1.1.28, Culture=neutral, PublicKeyToken=null'
   at Akka.Remote.EndpointWriter.PublishAndThrow(Exception reason, LogLevel level)
   at Akka.Remote.EndpointWriter.<SupervisorStrategy>b__20_0(Exception ex)
   at Akka.Actor.LocalOnlyDecider.Decide(Exception cause)
   at Akka.Actor.OneForOneStrategy.Handle(IActorRef child, Exception x)
   at Akka.Actor.SupervisorStrategy.HandleFailure(ActorCell actorCell, Exception cause, ChildRestartStats failedChildStats, IReadOnlyCollection`1 allChildren)
   at Akka.Actor.ActorCell.HandleFailed(Failed f)
   at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState)
--- End of stack trace from previous location where exception was thrown ---
   at Akka.Actor.ActorCell.HandleFailed(Failed f)
   at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState)

=== Pre-bind state information ===
LOG: DisplayName = Akka.Cluster.Sharding, Version=1.1.1.28, Culture=neutral, PublicKeyToken=null
 (Fully-specified)
LOG: Appbase = file:///C:/Users/jeff/source/x-akka-sharding/Lighthouse/bin/Debug/
LOG: Initial PrivatePath = NULL
Calling assembly : Wire, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\jeff\source\x-akka-sharding\Lighthouse\bin\Debug\Lighthouse.vshost.exe.Config
LOG: Using host configuration file:
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: Attempting download of new URL file:///C:/Users/jeff/source/x-akka-sharding/Lighthouse/bin/Debug/Akka.Cluster.Sharding.DLL.
LOG: Attempting download of new URL file:///C:/Users/jeff/source/x-akka-sharding/Lighthouse/bin/Debug/Akka.Cluster.Sharding/Akka.Cluster.Sharding.DLL.
LOG: Attempting download of new URL file:///C:/Users/jeff/source/x-akka-sharding/Lighthouse/bin/Debug/Akka.Cluster.Sharding.EXE.
LOG: Attempting download of new URL file:///C:/Users/jeff/source/x-akka-sharding/Lighthouse/bin/Debug/Akka.Cluster.Sharding/Akka.Cluster.Sharding.EXE.
]
```

**Comment by alexvaluyskiy** [comment]
Sharding is not working without Wire at the moment. Try it first http://getakka.net/docs/Serialization#how-to-setup-wire-as-default-serializer

**Comment by alexvaluyskiy** [comment]
PR for the default serializer is coming https://github.com/akkadotnet/akka.net/pull/2236

**Comment by jpierson** [comment]
I have [Lighthouse](https://github.com/jpierson/x-akka-sharding/blob/ee7f2c1ca07e1fb9b4a057b444badd64396abaf7/Lighthouse/App.config#L19-L24) and my [sharding node](https://github.com/jpierson/x-akka-sharding/blob/ee7f2c1ca07e1fb9b4a057b444badd64396abaf7/x-akka-sharding/App.config#L29-L34) both configured for using Wire already as the serializer.

**Comment by jpierson** [comment]
It looks like this issue may have been caused by the fact that I missed adding a role to the sharding section of my hocon config. My guess from looking at things is that Lighthouse, being part of the cluster, was being chosen to host the ShardCoordinator singleton because no specific role was being provided. 

```
    sharding {
      role = sharding
    }
```

**Comment by ismaelhamed** [comment]
@jpierson You got it right. As stated in the documentation:

> The ShardRegion actor is started on each node in the cluster, or group of nodes tagged with a specific role. 

So, you MUST make sure the Lighthouse nodes are excluded from this group by specifying a role in your sharding.

**Comment by amichel** [comment]
I have same issue when running Sharding Proxy with LightHouse. The nodes themselves work correctly.
