### ISSUE TITLE
Wire serialization fails on messages containing byte

### ISSUE THREAD

**Issue by florisch** [akkadotnet/akka.net#2239]
The serialization of a message containing a byte with wire fails on a strange cast. Using json or replacing the byte by an ushort the serialization works.

StackTrace
```
System.ArgumentException : Object of type 'System.Int64' cannot be converted to type 'System.DateTime'.
at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
at System.Reflection.RtFieldInfo.InternalSetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture, StackCrawlMark& stackMark)
at System.Reflection.RtFieldInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture)
at System.Reflection.FieldInfo.SetValue(Object obj, Object value)
at Wire.CodeGenerator.<>c__DisplayClass4_0.<GenerateFieldInfoDeserializer>b__1(Stream stream, Object o, DeserializerSession session)
at Wire.CodeGenerator.<>c__DisplayClass1_0.<MakeReader>b__0(Stream stream, DeserializerSession session)
at Wire.ValueSerializers.ObjectSerializer.ReadValue(Stream stream, DeserializerSession session)
at Wire.Serializer.Deserialize[T](Stream stream)
at Akka.Serialization.WireSerializer.FromBinary(Byte[] bytes, Type type)
at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
at Akka.Actor.ActorCell.SendMessage(IActorRef sender, Object message)
at Akka.Actor.RepointableActorRef.TellInternal(Object message, IActorRef sender)
at Akka.Actor.ActorRefBase.Tell(Object message, IActorRef sender)
at Akka.Actor.ActorRefImplicitSenderExtensions.Tell(IActorRef receiver, Object message)
```

Some code to reproduce the issue

With Messages: 
```
	public class ByteMessage
	{
		public DateTime UtcTime { get; }
		public long LongValue { get; }
		public byte ByteValue { get; }
		
		public ByteMessage(DateTime utcTime, byte byteValue, long longValue)
		{
			UtcTime = utcTime;
			ByteValue = byteValue;
			LongValue = longValue;
		}

		public override bool Equals(object obj)
		{
			var msg = obj as ByteMessage;
			return msg != null && Equals(msg);
		}

		public bool Equals(ByteMessage other)
		{
			return UtcTime.Equals(other.UtcTime) && LongValue.Equals(other.LongValue) && ByteValue.Equals(other.ByteValue);
		}
	}

	public class UshortMessage
	{
		public DateTime UtcTime { get; }
		public long LongValue { get; }
		public ushort ByteValue { get; }

		public UshortMessage(DateTime utcTime, byte byteValue, long longValue)
		{
			UtcTime = utcTime;
			ByteValue = byteValue;
			LongValue = longValue;
		}

		public override bool Equals(object obj)
		{
			var msg = obj as UshortMessage;
			return msg != null && Equals(msg);
		}

		public bool Equals(UshortMessage other)
		{
			return UtcTime.Equals(other.UtcTime) && LongValue.Equals(other.LongValue) && ByteValue.Equals(other.ByteValue);
		}
	}
```

And the tests:
```
[TestFixture]
	class TestWithWire : TestKit
	{
		public TestWithWire() : base(WireConfig)
		{
		}

		public static Config WireConfig => ConfigurationFactory.ParseString(@"
			akka {
				actor{
					serializers { wire = ""Akka.Serialization.WireSerializer, Akka.Serialization.Wire"" }
					serialization-bindings { ""System.Object"" = wire }
					serialize-messages = on
				}
			}");

		[Test]
		public void TestByteMessage()
		{
			var date = DateTime.Now;
			var message = new ByteMessage(date, 15, 2345);
			TestActor.Tell(message);
			ExpectMsg<ByteMessage>(received => received.Equals(message));
		}

		[Test]
		public void TestUshortMessage()
		{
			var date = DateTime.Now;
			var message = new UshortMessage(date, 15, 2345);
			TestActor.Tell(message);
			ExpectMsg<UshortMessage>(received => received.Equals(message));
		}
	}

	[TestFixture]
	class TestWithJson : TestKit
	{
		public TestWithJson() : base(JsonConfig)
		{
		}

		public static Config JsonConfig => ConfigurationFactory.ParseString(@"
			akka {
				actor{
					serializers { json = ""Akka.Serialization.NewtonSoftJsonSerializer"" }
					serialization-bindings { ""System.Object"" = json }
					serialize-messages = on
				}
			}");

		[Test]
		public void TestByteMessage()
		{
			var date = DateTime.Now;
			var message = new ByteMessage(date, 15, 2345);
			TestActor.Tell(message);
			ExpectMsg<ByteMessage>(received => received.Equals(message));
		}

		[Test]
		public void TestUshortMessage()
		{
			var date = DateTime.Now;
			var message = new UshortMessage(date, 15, 2345);
			TestActor.Tell(message);
			ExpectMsg<UshortMessage>(received => received.Equals(message));
		}
	}
```

TestWithWire.TestByteMessage fail with the mentioned stacktrace

**Comment by rogeralsing** [comment]
Byte serialization in Wire have been fixed recently.
I've added a (passing) test for your bug report here https://github.com/akkadotnet/Wire/blob/dev/Wire.Tests/Bugs.cs#L38

Stay tuned for updated nugets.

**Comment by florisch** [comment]
Ok cool, waiting for this update.

Thanks

**Comment by Danthar** [comment]
Since this issue is fixed. Closing it.
