### ISSUE TITLE
Serialization issues drop network / cluster connectivity

### ISSUE THREAD

**Issue by kantora** [akkadotnet/akka.net#2278]
Suppose that second question from https://github.com/akkadotnet/akka.net/issues/2271 worths to be moved to separate discussion.

Sometimes nodes can send each other incorrect messages. For example, nodes contain two incompatible versions of the same message or message itself is not serializable. So we get serialization error in `Endpoint` on Read/Write operation. As for now it often leads to overall network errors, disassociations, and e.t.c. Also, I noticed that normal working node can be removed from the cluster as unreachable only because other nodes could not serialize messages addressed to it. And final - errors itself are not clear. It is very hard to diagnose the erroneous message to fix it.

Maybe serialization process should be wrapped into try/catch to distinguish such errors from network ones? And they should be reported to log with some more data? (sender/receiver addresses and message type, if available along with serialization exception). 

Also - is it right, that such messages lead to cluster member invalidation?

**Comment by kantora** [comment]
As I see - `SerializationException` is caught on write, but `Wire` throws quite another type of exceptions...
For example `RuntimeBinderException` and `InvalidCastException`...

**Comment by Aaronontheweb** [comment]
@kantora @rogeralsing in this case the Akka.NET serializer implementation for Wire should probably be throwing the correct type exception. Probably should just bundle the native Wire ones as inner exceptions to a `SerializationException`.

**Comment by kantora** [comment]
@Aaronontheweb Maybe  it will be better idea to wrap the serialization call and catch any exception there (and wrap it into a `SerializationException` in case it not already wrapped)? I think that requirement to serialization plugin to throw only serialization exceptions is not obvious and hard to be tested (I just can't imagine a test that verifies that only `SerializationException` is thrown).

Also what about serialization exceptions on the receiver side? Should we catch them also?

**Comment by Horusiath** [comment]
@Aaronontheweb @rogeralsing I think that @kantora touched a serious thing to discuss - at the present moment any serialization errors will cause nodes to disassociate and there is no way for user to prevent/react on that fact. 

I think, that this should be somewhat configurable, as various behaviors could apply here:

1. Current default have some points - if message is not serializable, this is clearly breaking a contract between nodes. To prevent further corruption they would dissassociate from each other.
2. However maybe programmers would like to react on that behavior i.e. 
  - Have some actor system component (configurable from HOCON), that will be notified on failure. I think this have most sense.
 -  Send something like `SerializationFailure(byte[])` to message receiver instead. Only idea, I think this would be too cumbersome for setting up (as potentially every actor with remote communication should be able to handle it).
 - Log error, send `SerializationFailure(byte[])` to dead letters and pretend that nothing had happened. Wrong behavior IMHO.

**Comment by kantora** [comment]
> Current default have some points - if message is not serializable, this is clearly breaking a contract between nodes. To prevent further corruption they would dissassociate from each other.

In cluster context, it leads to serious problems. The case - we have a nice working cluster. Then some new node with new code appears and brings serialization errors. As dissassociate happens, the node is removed from the cluster (and it may be any node, not the new one, most probably it will be working nodes without errors).

>However maybe programmers would like to react on that behavior i.e.
IMHO, as far as I know if a message cannot be delivered it goes to the DeadLeters. Honestly - I like the idea of actor sending undeliverable message receives some notification, but I don't see a difference between network serialization problem or any other cause. And, suppose, it will violate the Akka JVM design.

P.S. don't forget that serialization issues can be on the receiver side too...

**Comment by Horusiath** [comment]
> In cluster context, it leads to serious problems. The case - we have a nice working cluster. Then some new node with new code appears and brings serialization errors. As dissassociate happens, the node is removed from the cluster (and it may be any node, not the new one, most probably it will be working nodes without errors).

@kantora if it's nice working cluster, then serialization erros won't occur. Problems with serialization points out that something wrong has happen not by the fault of the cluster runtime, but because nodes that have been deployed are incompatible - as they cannot serialize all messages they're exchanging i.e. as result of some new messages are not serializable or refer to data in unknown assemblies. 

It's more compile-time error - if you have message that will throw error upon deserialization, it will throw it every time, it's send. It's not an accident but a constant failure. So by default the safest option is to tear down node that notified the problems.

**Comment by kantora** [comment]
@Horusiath cluster is supposed to be updated. And it can be (for example) some version incompatibility. And, IMHO, introducing error in one part of it should not break all others.

**Comment by kantora** [comment]
> if you have message that will throw error upon deserialization, it will throw it every time, it's send. It's not an accident but a constant failure. So by default the safest option is to tear down node that notified the problems

Exactly. But now other nodes tered down (as problem node can't send them messages and consider them to be unreachable).

**Comment by vladkosarev** [comment]
We had the same issue using remoting. Took a while to track down since serialization errors were swallowed. All we saw were disconnects on Akka server. Would be good to have a nicer way of dealing with serialization issues.

**Comment by kostrse** [comment]
Maybe just always kick offending sender out of cluster in case of message serialization errors?
In this case cluster would be self-healing instead of self-destroying.

How does JVM Akka address this problem?

**Comment by kostrse** [comment]
Silently ignoring non-deserializable messages is not enough.
Not all messages will be causing serialization errors. Receivers will be receiving only some percent of them, thus getting distorted information/state without any clue about the problem.

**Comment by kantora** [comment]
> Maybe just always kick offending sender out of cluster in case of message serialization errors?
In this case cluster would be self-healing instead of self-destroying.

As for me - this is the very good point. 
As I see there can be two possible cause of the problem.

1. The message cannot be serialized due to some inner problem. This means that node contains malfunctional code and it will be better to remove this node from working cluster in order to protect cluster and other working nodes (this node, not the one the message was addressed to).

2. Code incompatibility or configuration incompatibility. This can lead to deserialization issues. For example, the new node has an updated code with message class that has some property with changed type (damn junior programmers, this can be only caught by code review), or serializer was updated without backward compatibility or just serialization configuration was changed. This problem is much more complex as it is hard to decide what node contains error. This is very hard to test in the development environment, so only code-contracts and detailed code review can work. Suppose that it will be a good idea to place some large warning into the `Akka.Remote`/`Akka.Cluster` documentation.
As for cluster work strategy, maybe it will be right to disassociate just the younger node.

**Comment by Horusiath** [comment]
> The message cannot be serialized due to some inner problem. This means that node contains malfunctional code and it will be better to remove this node from working cluster in order to protect cluster and other working nodes (this node, not the one the message was addressed to).

Most of the time on production, serialization errors will occur in cases, when nodes are upgraded - new nodes have new message types unknown to previous versions. 

In case of downing the sender, upgrading the cluster without shutting it down would be close to impossible, as any newer node could be potentially downed before the whole cluster will be converted (we assume that programmers know what they're doing). 

Currently nodes become unreachable, not downed, which could be potentially used to implement correct downing strategy (using `IDowningProvider` API) to decide which nodes in the cluster should go down in case of unreachability.

**Comment by kantora** [comment]
Ouch... Sorry, missed that point.
Nevertheless, if node can't serialize its own method - we can be sure that node is broken and, possibly, should be removed from cluster and maintainers should receive all possible easy readable log notifications.

So the question is the deserialization issues. I agree that most time this will be caused by normal upgrade procedure. Also now I am not sure that even move node to the unreachable state is a good option. And, as I've read from code, `IDowningProvider` doesn't have an access to the reason of the node unreachability. Still thinking of it.

**Comment by kantora** [comment]
I would like to propose to continue this discussion.
As @Aaronontheweb wrote in https://github.com/akkadotnet/akka.net/issues/2364
> A serialization issue is a severe enough one where I'd consider blowing up the cluster to be the correct behavior. Fail fast.

But as @Horusiath said - serialization issues are normal during cluster upgrade procedure. So it will be a disaster if trying to upgrade cluster node by node (without overall downtime) and suddenly get it falling apart as nodes randomly dissociate from each other with serialization issues.

And finally - serialization issues now is very hard to debug. Log messages give absolutely no info to check, No message type and no sender. Only sender and receiver node addresses. 

For example, I am trying to find the cause of such message (that brings nodes down) and currently stuck as I don't know where to seek.
```
	AssociationError [akka.tcp://ClusterKit@172.18.0.14:44382] <- akka.tcp://ClusterKit@172.18.0.16:45742: Error [Non-negative number required.
Parameter name: count] [  at System.IO.MemoryStream.Read (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x0004d] in <94fd79a3b7144c54b4cb162b50fc7761>:0 
  at Wire.Extensions.StreamEx.ReadString (System.IO.Stream stream, Wire.DeserializerSession session) [0x0002c] in <bfe82252b0f34e35a30383a0ee0d294a>:0 
  at Wire.ValueSerializers.StringSerializer.ReadValueImpl (System.IO.Stream stream, Wire.DeserializerSession session) [0x00000] in <bfe82252b0f34e35a30383a0ee0d294a>:0 
  at Wire.ValueSerializers.StringSerializer.ReadValue (System.IO.Stream stream, Wire.DeserializerSession session) [0x00000] in <bfe82252b0f34e35a30383a0ee0d294a>:0 
  at Wire.Extensions.StreamEx.ReadObject (System.IO.Stream stream, Wire.DeserializerSession session) [0x0000d] in <bfe82252b0f34e35a30383a0ee0d294a>:0 
  at (wrapper dynamic-method) System.Object:lambda_method (System.Runtime.CompilerServices.Closure,System.IO.Stream,Wire.DeserializerSession)
  at Wire.ValueSerializers.ObjectSerializer.ReadValue (System.IO.Stream stream, Wire.DeserializerSession session) [0x00000] in <bfe82252b0f34e35a30383a0ee0d294a>:0 
  at Wire.Extensions.StreamEx.ReadObject (System.IO.Stream stream, Wire.DeserializerSession session) [0x0000d] in <bfe82252b0f34e35a30383a0ee0d294a>:0 
  at Wire.SerializerFactories.EnumerableSerializerFactory+<>c__DisplayClass3_0.<BuildSerializer>b__1 (System.IO.Stream stream, Wire.DeserializerSession session) [0x00042] in <bfe82252b0f34e35a30383a0ee0d294a>:0 
  at Wire.ValueSerializers.ObjectSerializer.ReadValue (System.IO.Stream stream, Wire.DeserializerSession session) [0x00000] in <bfe82252b0f34e35a30383a0ee0d294a>:0 
  at Wire.Extensions.StreamEx.ReadObject (System.IO.Stream stream, Wire.DeserializerSession session) [0x0000d] in <bfe82252b0f34e35a30383a0ee0d294a>:0 
  at (wrapper dynamic-method) System.Object:lambda_method (System.Runtime.CompilerServices.Closure,System.IO.Stream,Wire.DeserializerSession)
  at Wire.ValueSerializers.ObjectSerializer.ReadValue (System.IO.Stream stream, Wire.DeserializerSession session) [0x00000] in <bfe82252b0f34e35a30383a0ee0d294a>:0 
  at Wire.Extensions.StreamEx.ReadObject (System.IO.Stream stream, Wire.DeserializerSession session) [0x0000d] in <bfe82252b0f34e35a30383a0ee0d294a>:0 
  at (wrapper dynamic-method) System.Object:lambda_method (System.Runtime.CompilerServices.Closure,System.IO.Stream,Wire.DeserializerSession)
  at Wire.ValueSerializers.ObjectSerializer.ReadValue (System.IO.Stream stream, Wire.DeserializerSession session) [0x00000] in <bfe82252b0f34e35a30383a0ee0d294a>:0 
  at Wire.Serializer.Deserialize[T] (System.IO.Stream stream) [0x0000f] in <bfe82252b0f34e35a30383a0ee0d294a>:0 
  at Akka.Serialization.WireSerializer.FromBinary (System.Byte[] bytes, System.Type type) [0x00007] in <f1d7550354534998b829b28215812f33>:0 
  at Akka.Serialization.Serialization.Deserialize (System.Byte[] bytes, System.Int32 serializerId, System.String manifest) [0x0004e] in <3037f0ad8de04f218afd844cce059dfe>:0 
  at Akka.Remote.MessageSerializer.Deserialize (Akka.Actor.ActorSystem system, SerializedMessage messageProtocol) [0x0002d] in <c1c7e715068742578977370643bbf78f>:0 
  at Akka.Remote.DefaultMessageDispatcher.Dispatch (Akka.Actor.IInternalActorRef recipient, Akka.Actor.Address recipientAddress, SerializedMessage message, Akka.Actor.IActorRef senderOption) [0x00000] in <c1c7e715068742578977370643bbf78f>:0 
  at Akka.Remote.EndpointReader.<Reading>b__11_1 (Akka.Remote.Transport.InboundPayload inbound) [0x000ec] in <c1c7e715068742578977370643bbf78f>:0 
  at (wrapper dynamic-method) System.Object:lambda_method (System.Runtime.CompilerServices.Closure,object,System.Action`1<Akka.Remote.Transport.Disassociated>,System.Action`1<Akka.Remote.Transport.InboundPayload>,System.Action`1<Akka.Remote.EndpointWriter/StopReading>)
  at Akka.Tools.MatchHandler.PartialHandlerArgumentsCapture`4[T,T1,T2,T3].Handle (T value) [0x00000] in <3037f0ad8de04f218afd844cce059dfe>:0 
  at Akka.Actor.ReceiveActor.ExecutePartialMessageHandler (System.Object message, Akka.Tools.MatchHandler.PartialAction`1[T] partialAction) [0x00000] in <3037f0ad8de04f218afd844cce059dfe>:0 
  at Akka.Actor.ReceiveActor.OnReceive (System.Object message) [0x00000] in <3037f0ad8de04f218afd844cce059dfe>:0 
  at Akka.Actor.UntypedActor.Receive (System.Object message) [0x00000] in <3037f0ad8de04f218afd844cce059dfe>:0 
  at Akka.Actor.ActorBase.AroundReceive (Akka.Actor.Receive receive, System.Object message) [0x00000] in <3037f0ad8de04f218afd844cce059dfe>:0 
  at Akka.Actor.ActorCell.ReceiveMessage (System.Object message) [0x00011] in <3037f0ad8de04f218afd844cce059dfe>:0 
  at Akka.Actor.ActorCell.Invoke (Akka.Actor.Envelope envelope) [0x00057] in <3037f0ad8de04f218afd844cce059dfe>:0 ]
```

**Comment by zbynek001** [comment]
Same error now breaks cluster when sharding is used during upgrade to 1.3.3, because of introducing ddata there. It takes down the whole cluster. Even if the sharding is not using ddata at all!
So basically we're now stuck, because we can't deploy this to a production clusters.
There needs to be a better way how to handle this during cluster upgrade.


```
2018-01-26 09:19:53.335 +00:00 [Error] "AssociationError [akka.tcp://engine@10.0.0.4:30003] <- akka.tcp://engine@10.0.0.8:30004: Error [Cannot find serializer with id [12]. The most probable reason is that the configuration entry 'akka.actor.serializers' is not in sync between the two systems.] [   at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
   at Akka.Remote.Serialization.MessageContainerSerializer.FromBinary(Byte[] bytes, Type type)
   at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
   at Akka.Remote.DefaultMessageDispatcher.Dispatch(IInternalActorRef recipient, Address recipientAddress, Payload message, IActorRef senderOption)
   at Akka.Remote.EndpointReader.<Reading>b__11_1(InboundPayload inbound)
   at lambda_method(Closure , Object , Action`1 , Action`1 , Action`1 )
   at Akka.Tools.MatchHandler.PartialHandlerArgumentsCapture`4.Handle(T value)
   at Akka.Actor.ReceiveActor.ExecutePartialMessageHandler(Object message, PartialAction`1 partialAction)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)]"
```

**Comment by Horusiath** [comment]
@zbynek001 ddata shouldn't be even initialized when not used. I need to look at it.

**Comment by zbynek001** [comment]
@Horusiath might it be this line?
https://github.com/akkadotnet/akka.net/blob/e607088d00e60b318897da3f01b8982666a5f6cc/src/contrib/cluster/Akka.Cluster.Sharding/ClusterShardingGuardian.cs#L225

**Comment by Horusiath** [comment]
@zbynek001 I've created an issue #3297 for that - I've missed the necessary change. The case will occur when building shard region proxies, otherwise it should work as designed. Also this issue is general to Akka.Cluster.Sharding - other libraries should be work without problems.

**Comment by Aaronontheweb** [comment]
We should port https://github.com/akka/akka/pull/1269 so serialization issues don't blow up Akka.Remote

**Comment by Aaronontheweb** [comment]
Serialization exceptions no longer cause any type of disassociation in Akka.Remote.
