### ISSUE TITLE
MNTR: Unannounced node disconnects

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#2296]
Been a big increase in MNTR failures lately as we've expanded the test suite, looking into it there appears to be a possible fault with the MNTR Runner itself:

<summary>
Cause: Akka.Remote.TestKit.BarrierCoordinator+ClientLostException: unannounced disconnect of RoleName(fourth) - Akka.Cluster.Tests.ConvergenceSpec
<details>
[DEBUG][9/6/2016 9:52:50 PM][Thread 0035][Akka.Remote.TestKit.MsgDecoder] Decoded Akka.Remote.TestKit.EnterBarrier
[DEBUG][9/6/2016 9:52:50 PM][Thread 0018][akka://MultiNodeClusterSpec/user/controller] received handled message Akka.Remote.TestKit.Controller+ClientDisconnected: RoleName(fourth)
[DEBUG][9/6/2016 9:52:50 PM][Thread 0018][[akka://MultiNodeClusterSpec/user/controller/barriers#1509742045]] processing Event: <Akka.Remote.TestKit.Controller+ClientDisconnected: RoleName(fourth)>, StateData: <Akka.Remote.TestKit.BarrierCoordinator+Data> from [akka://MultiNodeClusterSpec/user/controller/%5B%3A%3A1%5D%3A52005%3A52005-server3#1539168185]
[DEBUG][9/6/2016 9:52:50 PM][Thread 0035][Akka.Remote.TestKit.ConductorHandler] message from [::1]:52008: Akka.Remote.TestKit.EnterBarrier
[DEBUG][9/6/2016 9:52:50 PM][Thread 0018][[akka://MultiNodeClusterSpec/user/controller/%5B%3A%3A1%5D%3A52008%3A52008-server4#8676766]] processing Event: <Akka.Remote.TestKit.EnterBarrier>, StateData: <> from [akka://MultiNodeClusterSpec/deadLetters]
[DEBUG][9/6/2016 9:52:50 PM][Thread 0018][[akka://MultiNodeClusterSpec/user/controller/%5B%3A%3A1%5D%3A52008%3A52008-server4#8676766]] transition Ready,  -> Ready, 
[DEBUG][9/6/2016 9:52:50 PM][Thread 0027][[akka://MultiNodeClusterSpec/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FMultiNodeClusterSpec%40localhost%3A52006-2/endpointWriter#1470763997]] received local message [RemoteMessage: ActorSelectionMessage - Message: Akka.Cluster.GossipStatus - WildCartFanOut: False - Elements: system/cluster/core/daemon to [akka://MultiNodeClusterSpec/]<+akka://MultiNodeClusterSpec/ from [akka.tcp://MultiNodeClusterSpec@localhost:52006/system/cluster/core/daemon#1303362951]]
[ERROR][9/6/2016 9:52:50 PM][Thread 0020][akka://MultiNodeClusterSpec/user/controller/barriers] unannounced disconnect of RoleName(fourth)
Cause: Akka.Remote.TestKit.BarrierCoordinator+ClientLostException: unannounced disconnect of RoleName(fourth)
   at Akka.Remote.TestKit.BarrierCoordinator.<>c__DisplayClass14_0.<InitFSM>b__3(ClientDisconnected disconnected) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.Remote.TestKit\BarrierCoordinator.cs:line 422
   at Akka.Case.With[TMessage](Action`1 action) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka\PatternMatch.cs:line 94
   at Akka.Remote.TestKit.BarrierCoordinator.<InitFSM>b__14_0(Event`1 event) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.Remote.TestKit\BarrierCoordinator.cs:line 403
   at Akka.Actor.FSM`2.<>c__DisplayClass52_0.<OrElse>b__0(Event`1 event) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka\Actor\FSM.cs:line 755
   at Akka.Actor.FSM`2.ProcessEvent(Event`1 fsmEvent, Object source) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka\Actor\FSM.cs:line 857
   at Akka.Actor.FSM`2.ProcessMsg(Object any, Object source) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka\Actor\FSM.cs:line 838
   at Akka.Actor.FSM`2.<Receive>b__53_7(Object msg) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka\Actor\FSM.cs:line 829
   at Akka.Case.Default(Action`1 action) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka\PatternMatch.cs:line 112
   at Akka.Actor.FSM`2.Receive(Object message) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka\Actor\FSM.cs:line 773
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka\Actor\ActorBase.cs:line 154
   at Akka.Actor.ActorCell.ReceiveMessage(Object message) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka\Actor\ActorCell.DefaultMessages.cs:line 168
   at Akka.Actor.ActorCell.Invoke(Envelope envelope) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka\Actor\ActorCell.DefaultMessages.cs:line 77
</details>
</summary>

[Build log](http://petabridge-ci.cloudapp.net/viewLog.html?buildId=15614&buildTypeId=AkkaNet_AkkaNetWindowsMultiNodeTests&tab=buildLog&guest=1#_focus=18833)

**Comment by Aaronontheweb** [comment]
Looking at the logs for Node4 separately, it seems to be a more innocent explaination:

<summary>
[Node4][FAIL-EXCEPTION] Message: Unable to cast object of type 'Failure' to type 'Akka.Actor.Address'
<details>
[Node4][FAIL] Akka.Cluster.Tests.MultiNode.ConvergenceWithAccrualFailureDetectorMultiNode4.ConvergenceSpecTests
[Node4][FAIL-EXCEPTION] Type: System.AggregateException
[Node4][FAIL-EXCEPTION] Type: System.InvalidCastException
--> [Node4][FAIL-EXCEPTION] Message: One or more errors occurred.
--> [Node4][FAIL-EXCEPTION] Message: Unable to cast object of type 'Failure' to type 'Akka.Actor.Address'.
--> [Node4][FAIL-EXCEPTION] StackTrace:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Akka.Remote.TestKit.MultiNodeSpec.Node(RoleName role) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.Remote.TestKit\MultiNodeSpec.cs:line 532
   at Akka.Cluster.TestKit.MultiNodeClusterSpec.GetAddress(RoleName role) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.Cluster.TestKit\MultiNodeClusterSpec.cs:line 224
   at Akka.Cluster.Tests.MultiNode.ConvergenceSpec.<A_cluster_of_3_members_must_not_move_a_new_joining_node_to_up_while_there_is_no_convergence>b__6_0() in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.Cluster.Tests.MultiNode\ConvergenceSpec.cs:line 167
   at Akka.Remote.TestKit.MultiNodeSpec.RunOn(Action thunk, RoleName[] nodes) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.Remote.TestKit\MultiNodeSpec.cs:line 503
   at Akka.Cluster.Tests.MultiNode.ConvergenceSpec.A_cluster_of_3_members_must_not_move_a_new_joining_node_to_up_while_there_is_no_convergence() in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.Cluster.Tests.MultiNode\ConvergenceSpec.cs:line 167
   at Akka.Cluster.Tests.MultiNode.ConvergenceSpec.ConvergenceSpecTests() in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.Cluster.Tests.MultiNode\ConvergenceSpec.cs:line 127
--> [Node4][FAIL-EXCEPTION] StackTrace:    at Akka.Util.Internal.TaskExtensions.<>c__DisplayClass0_0`2.<CastTask>b__0(Task`1 _) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka\Util\Internal\TaskExtensions.cs:line 32
</details>
</summary>

Occurs when a timeout occurs when attempting to locate another role's address.
