### ISSUE TITLE
Error after upgrading my project to use Json.NET 9.0.1

### ISSUE THREAD

**Issue by jpierson** [akkadotnet/akka.net#2309]
After upgrading a set of projects that use Akka.NET to Json.NET 9.0.1 we started seeing the following errors on some machines that are running the application.

It appears that this exception is resulting from a simple call to `Akka.Actor.ActorSystem.Create` however we are configuring Akka through hocon to use the Wire serializer.

Akka assembly versions:
- Akka 1.0.8.24
- Akka.Remote 1.0.8.24
- Akka.Serialization.Wire 1.0.0.0

```
System.AggregateException: One or more errors occurred. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
--- End of inner exception stack trace ---
at Akka.Serialization.NewtonSoftJsonSerializer..ctor(ExtendedActorSystem system)
--- End of inner exception stack trace ---
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
at System.Activator.CreateInstance(Type type, Object[] args)
at Akka.Serialization.Serialization..ctor(ExtendedActorSystem system)
at Akka.Actor.Internal.ActorSystemImpl..ctor(String name, Config config)
at Akka.Actor.ActorSystem.Create(String name)
at Fabricom.Fabricom.SetupAkkaListener() in C:\mypath\Fabricom.cs:line 73
at Fabricom.Fabricom..ctor(FabricomSettings settings) in C:\mypath\Fabricom.cs:line 68
at Fabricom_Sync.Program.<Configure>d__8.MoveNext() in C:\mypath_Sync\Program.cs:line 114
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at Fabricom_Sync.Program.<>c__DisplayClass7_0.<<Main>b__2>d.MoveNext() in C:\mypath_Sync\Program.cs:line 58
--- End of inner exception stack trace ---
at Settings.CommandLineUX.<Run>d__0`3.MoveNext() in CC:\mypath\CommandLineUX.cs:line 117
---> (Inner Exception #0) System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
--- End of inner exception stack trace ---
at Akka.Serialization.NewtonSoftJsonSerializer..ctor(ExtendedActorSystem system)
--- End of inner exception stack trace ---
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
at System.Activator.CreateInstance(Type type, Object[] args)
at Akka.Serialization.Serialization..ctor(ExtendedActorSystem system)
at Akka.Actor.Internal.ActorSystemImpl..ctor(String name, Config config)
at Akka.Actor.ActorSystem.Create(String name)
at Fabricom.Fabricom.SetupAkkaListener() in C:\mypath\Fabricom.cs:line 73
at Fabricom.Fabricom..ctor(FabricomSettings settings) in C:\mypath\Fabricom.cs:line 68
at Fabricom_Sync.Program.<Configure>d__8.MoveNext() in C:\mypath_Sync\Program.cs:line 114
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at Fabricom_Sync.Program.<>c__DisplayClass7_0.<<Main>b__2>d.MoveNext() in C:\mypath\Program.cs:line 58<---
```

**Comment by Danthar** [comment]
It appears that the old version of newtonsoft.json is still being referenced somewhere. I expect it to be in usercode. But it could very well be somewhere in the framework. I noticed the PR to update this dependency might have some problems.

However you can probably quick-fix this by adding an assembly redirect in your config file(s).

     //something like this.
     <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="<tokencodehere>" />
        <bindingRedirect oldVersion="0.0.0.0-9.0.0.0" newVersion="9.0.0.0" />
      </dependentAssembly>

**Comment by marcpiechura** [comment]
Don’t think this is still an issue, so closing this one.
