### ISSUE TITLE
Remote actor system: connection timed out (version 1.1.1 or higher)

### ISSUE THREAD

**Issue by leonelcm** [akkadotnet/akka.net#2325]
Hi,

I am having issues connecting to a remote actor in my development machine. It seems that this issue might be related with firewall as I don't have the same issue in the servers. I can successfully send messages to remote users in my machine using Akka.net version 1.1.0, but with version 1.1.1 and 1.1.2 I get timed outs errors. I looked at the release notes for 1.1.1 and I can see some DNS enhancements as part of these release. Could you please let me know what kind of changes could cause the issues with my machines firewall?
Please see the configuration that I am using below:

```
  <![CDATA[

    akka {
      loglevel = Info

      actor {
        provider = "Akka.Remote.RemoteActorRefProvider, Akka.Remote"
        debug {
          receive = on
          autoreceive = on
          lifecycle = on
          event-stream = on
          unhandled = on
        }
      }

      remote {
        helios.tcp {
          transport-class = "Akka.Remote.Transport.Helios.HeliosTcpTransport, Akka.Remote"
          transport-protocol = tcp
          port = 8091
            hostname = 127.0.0.1
          public-hostname = "localhost"
          dns-use-ipv6 = false
          enforce-ip-family = false
        }
      }
    }      

  ]]>
```

Error:
[WARNING][26/09/2016 16:13:40][Thread 0010][[akka://MovieStreamingActorSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FMovieStreamingActorSystem%40localhost%3A8091-1/endpointWriter#1237905416]] AssociationError [akka.tcp://MovieStreamingActorSystem@127.0.0.1:62559] -> akka.tcp:
//MovieStreamingActorSystem@localhost:8091: Error [Invalid address: akka.tcp://MovieStreamingActorSystem@localhost:8091] []
[WARNING][26/09/2016 16:13:40][Thread 0012][remoting] Tried to associate with unreachable remote address [akka.tcp://MovieStreamingActorSystem@localhost:8091]. Address is now gated for 5000 ms, all messages to this address will be delivered to dead letters. Reason: [Invalid address: akka.tcp://Movie
StreamingActorSystem@localhost:8091] Caused by: [Akka.Remote.Transport.InvalidAssociationException: Association failure ---> Helios.Exceptions.HeliosConnectionException: failed as a result of System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors o
ccurred. ---> System.AggregateException: One or more errors occurred. ---> Helios.Channels.ConnectTimeoutException: connection timed out: 127.0.0.1:8091
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Helios.Channels.Bootstrap.ClientBootstrap.<DoResolveAndConnect>d__15.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Akka.Remote.Transport.Helios.HeliosTcpTransport.<>c.<AssociateInternal>b__1_0(Task`1 tr)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> Helios.Channels.ConnectTimeoutException: connection timed out: 127.0.0.1:8091
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Helios.Channels.Bootstrap.ClientBootstrap.<DoResolveAndConnect>d__15.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Akka.Remote.Transport.Helios.HeliosTcpTransport.<>c.<AssociateInternal>b__1_0(Task`1 tr)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> Helios.Channels.ConnectTimeoutException: connection timed out: 127.0.0.1:8091
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Helios.Channels.Bootstrap.ClientBootstrap.<DoResolveAndConnect>d__15.MoveNext()
---> (Inner Exception #0) Helios.Channels.ConnectTimeoutException: connection timed out: 127.0.0.1:8091<---
<---
<---
 ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> Helios.Channels.ConnectTimeoutException: connection timed out: 127.0.0.1:8091
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Helios.Channels.Bootstrap.ClientBootstrap.<DoResolveAndConnect>d__15.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Akka.Remote.Transport.Helios.HeliosTcpTransport.<>c.<AssociateInternal>b__1_0(Task`1 tr)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Akka.Remote.Transport.Helios.HeliosTcpTransport.<>c.<AssociateInternal>b__1_1(Task`1 r)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Remote.Transport.Helios.HeliosTransport.<Associate>d__27.MoveNext()
   --- End of inner exception stack trace ---]
[ERROR][26/09/2016 16:13:40][Thread 0012][akka://MovieStreamingActorSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FMovieStreamingActorSystem%40localhost%3A8091-1] Invalid address: akka.tcp://MovieStreamingActorSystem@localhost:8091
Cause: Akka.Remote.InvalidAssociation: Invalid address: akka.tcp://MovieStreamingActorSystem@localhost:8091 ---> Akka.Remote.Transport.InvalidAssociationException: Association failure ---> Helios.Exceptions.HeliosConnectionException: failed as a result of System.AggregateException: One or more error
s occurred. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> Helios.Channels.ConnectTimeoutException: connection timed out: 127.0.0.1:8091
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Helios.Channels.Bootstrap.ClientBootstrap.<DoResolveAndConnect>d__15.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Akka.Remote.Transport.Helios.HeliosTcpTransport.<>c.<AssociateInternal>b__1_0(Task`1 tr)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> Helios.Channels.ConnectTimeoutException: connection timed out: 127.0.0.1:8091
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Helios.Channels.Bootstrap.ClientBootstrap.<DoResolveAndConnect>d__15.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Akka.Remote.Transport.Helios.HeliosTcpTransport.<>c.<AssociateInternal>b__1_0(Task`1 tr)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> Helios.Channels.ConnectTimeoutException: connection timed out: 127.0.0.1:8091
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Helios.Channels.Bootstrap.ClientBootstrap.<DoResolveAndConnect>d__15.MoveNext()
---> (Inner Exception #0) Helios.Channels.ConnectTimeoutException: connection timed out: 127.0.0.1:8091<---
<---
<---
 ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> Helios.Channels.ConnectTimeoutException: connection timed out: 127.0.0.1:8091
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Helios.Channels.Bootstrap.ClientBootstrap.<DoResolveAndConnect>d__15.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Akka.Remote.Transport.Helios.HeliosTcpTransport.<>c.<AssociateInternal>b__1_0(Task`1 tr)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Akka.Remote.Transport.Helios.HeliosTcpTransport.<>c.<AssociateInternal>b__1_1(Task`1 r)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Remote.Transport.Helios.HeliosTransport.<Associate>d__27.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Akka.Remote.EndpointWriter.PublishAndThrow(Exception reason, LogLevel level)
   at Akka.Remote.EndpointWriter.<Initializing>b__24_1(Failure failure)
   at lambda_method(Closure , Object , Action`1 , Action`1 , Action`1 )
   at Akka.Tools.MatchHandler.PartialHandlerArgumentsCapture`4.Handle(T value)
   at Akka.Actor.ReceiveActor.ExecutePartialMessageHandler(Object message, PartialAction`1 partialAction)
   at Akka.Actor.ReceiveActor.OnReceive(Object message)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
--- End of stack trace from previous location where exception was thrown ---
   at Akka.Actor.ActorCell.HandleFailed(Failed f)
   at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState)
[INFO][26/09/2016 16:13:40][Thread 0004][akka://MovieStreamingActorSystem/deadLetters] Message Heartbeat from akka://MovieStreamingActorSystem/system/remote-watcher to akka://MovieStreamingActorSystem/deadLetters was not delivered. 1 dead letters encountered.
[INFO][26/09/2016 16:13:40][Thread 0004][akka://MovieStreamingActorSystem/deadLetters] Message Heartbeat from akka://MovieStreamingActorSystem/system/remote-watcher to akka://MovieStreamingActorSystem/deadLetters was not delivered. 2 dead letters encountered.
[INFO][26/09/2016 16:13:40][Thread 0004][akka://MovieStreamingActorSystem/deadLetters] Message Heartbeat from akka://MovieStreamingActorSystem/system/remote-watcher to akka://MovieStreamingActorSystem/deadLetters was not delivered. 3 dead letters encountered.
[INFO][26/09/2016 16:13:40][Thread 0004][akka://MovieStreamingActorSystem/deadLetters] Message Heartbeat from akka://MovieStreamingActorSystem/system/remote-watcher to akka://MovieStreamingActorSystem/deadLetters was not delivered. 4 dead letters encountered.
[INFO][26/09/2016 16:13:40][Thread 0004][akka://MovieStreamingActorSystem/deadLetters] Message Heartbeat from akka://MovieStreamingActorSystem/system/remote-watcher to akka://MovieStreamingActorSystem/deadLetters was not delivered. 5 dead letters encountered.
[INFO][26/09/2016 16:13:40][Thread 0004][akka://MovieStreamingActorSystem/deadLetters] Message Heartbeat from akka://MovieStreamingActorSystem/system/remote-watcher to akka://MovieStreamingActorSystem/deadLetters was not delivered. 6 dead letters encountered.
[INFO][26/09/2016 16:13:40][Thread 0004][akka://MovieStreamingActorSystem/deadLetters] Message Heartbeat from akka://MovieStreamingActorSystem/system/remote-watcher to akka://MovieStreamingActorSystem/deadLetters was not delivered. 7 dead letters encountered.
[INFO][26/09/2016 16:13:40][Thread 0004][akka://MovieStreamingActorSystem/deadLetters] Message Heartbeat from akka://MovieStreamingActorSystem/system/remote-watcher to akka://MovieStreamingActorSystem/deadLetters was not delivered. 8 dead letters encountered.
[INFO][26/09/2016 16:13:40][Thread 0004][akka://MovieStreamingActorSystem/deadLetters] Message Heartbeat from akka://MovieStreamingActorSystem/system/remote-watcher to akka://MovieStreamingActorSystem/deadLetters was not delivered. 9 dead letters encountered.

**Comment by Aaronontheweb** [comment]
Is the system running on `localhost:8091` also using 1.1.1 or 1.1.2? Sounds like the issue is that your development environment either has a firewall issue or an IPV6 / dual-mode issue.

**Comment by leonelcm** [comment]
With both systems in 1.1.0 it works, with both systems 1.1.1 or 1.1.2 I get timed outs. I still get timed outs If I disable the IPV6 (dns-use-ipv6 = false). Any suggestions?

**Comment by leonelcm** [comment]
I forgot to mention that the first time I execute the code with version 1.1.1 or 1.1.2 I don't have any issues, in the following executions the port somehow is not accessible. I disabled IPV6 (dns-use-ipv6 = false) so, besides the IPv6 changes, were any other changes in version 1.1.1 that could cause this issue? I am assuming that the issue is caused by Mcafee firewall, but I would like to understand what are the differences between version 1.1.0 and 1.1.1 that causes this behaviour.

Thanks

**Comment by Silv3rcircl3** [comment]
Closing due to inactivity and where now on 1.3, feel free to reopen if neccassary.
