### ISSUE TITLE
InvalidCast exception when associating between 1.1.1 and 1.1.2

### ISSUE THREAD

**Issue by melcloud** [akkadotnet/akka.net#2328]
Environment: Windows 8.1
Version: 1.1.1 and 1.1.2
Wire Version: 1.1.1 -> 0.0.6, 1.1.2 -> 0.0.8

When trying to associate akka.net 1.1.1 and 1.1.2, `InvalidCastException` is thrown from wire serialiser.

Detail:

``` csharp
2016-09-28 08:01:28.206 +10:00 [Error] Error caught channel ["[::ffff:127.0.0.1]:6000"->"[::ffff:127.0.0.1]:54941"](Id="ChannelId(-526309920)")
System.Net.Sockets.SocketException (0x80004005): The I/O operation has been aborted because of either a thread exit or an application request
   at Helios.Channels.Sockets.SocketChannelAsyncOperation.Validate()
   at Helios.Channels.Sockets.AbstractSocketByteChannel.SocketByteChannelUnsafe.FinishRead(SocketChannelAsyncOperation operation)
2016-09-28 08:01:38.205 +10:00 [Error] "AssociationError [akka.tcp://mondo@localhost:6000] <- akka.tcp://mondo@localhost:5001: Error [Specified cast is not valid.] [   at lambda_method(Closure , Stream , DeserializerSession )
   at Wire.ValueSerializers.ObjectSerializer.ReadValue(Stream stream, DeserializerSession session)
   at Wire.Serializer.Deserialize[T](Stream stream)
   at Akka.Serialization.WireSerializer.FromBinary(Byte[] bytes, Type type)
   at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
   at Akka.Remote.Serialization.MessageContainerSerializer.FromBinary(Byte[] bytes, Type type)
   at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
   at Akka.Remote.MessageSerializer.Deserialize(ActorSystem system, SerializedMessage messageProtocol)
   at Akka.Remote.DefaultMessageDispatcher.Dispatch(IInternalActorRef recipient, Address recipientAddress, SerializedMessage message, IActorRef senderOption)
   at Akka.Remote.EndpointReader.<Reading>b__11_1(InboundPayload inbound)
   at lambda_method(Closure , Object , Action`1 , Action`1 , Action`1 )
   at Akka.Tools.MatchHandler.PartialHandlerArgumentsCapture`4.Handle(T value)
   at Akka.Actor.ReceiveActor.ExecutePartialMessageHandler(Object message, PartialAction`1 partialAction)
   at Akka.Actor.ReceiveActor.OnReceive(Object message)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)]"
2016-09-28 08:01:38.227 +10:00 [Error] "Specified cast is not valid."
System.InvalidCastException: Specified cast is not valid.
   at Akka.Remote.EndpointWriter.PublishAndThrow(Exception reason, LogLevel level)
   at Akka.Remote.EndpointWriter.<SupervisorStrategy>b__20_0(Exception ex)
   at Akka.Actor.LocalOnlyDecider.Decide(Exception cause)
   at Akka.Actor.OneForOneStrategy.Handle(IActorRef child, Exception x)
   at Akka.Actor.SupervisorStrategy.HandleFailure(ActorCell actorCell, IActorRef child, Exception cause, ChildRestartStats stats, IReadOnlyCollection`1 children)
   at Akka.Actor.ActorCell.HandleFailed(Failed f)
   at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState)
```

**Comment by alexvaluyskiy** [comment]
Wire/Hyperion packages are in a beta status and don't support a wire compatibility between two versions.
