### ISSUE TITLE
Unable to find a constructor to use for type Akka.Cluster.Member.

### ISSUE THREAD

**Issue by kvarv** [akkadotnet/akka.net#2344]
Hi, I'm trying out Akka.Cluster 1.1.2 and keep getting this error when a node have joined the cluster. 

```
[INFO][20.10.2016 09:31:09][Thread 0006][[akka://ClusterSystem/system/cluster/core/daemon#1957519997]] Node [akka.tcp://ClusterSystem@localhost:21652] is JOINING, roles []
[INFO][20.10.2016 09:31:09][Thread 0003][[akka://ClusterSystem/system/cluster/core/daemon#1957519997]] Leader is moving node [akka.tcp://ClusterSystem@localhost:21652] to [Up]
[ERROR][20.10.2016 09:31:09][Thread 0009][[akka://ClusterSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FClusterSystem%40localhost%3A21652-1/endpointWriter#194879391]] AssociationError [akka.tcp://ClusterSystem@localhost:2553] <- akka.tcp://ClusterSystem@localhost:21652: Error [Unable to find a constructor to use for type Akka.Cluster.Member. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'Member.UniqueAddress', line 1, position 144.] [   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
```

This results in the following error in the follower:

```
[ERROR][20.10.2016 09:31:09][Thread 0011][akka://ClusterSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FClusterSystem%40localhost%3A2553-1/endpointWriter] Disassociated
Cause: Akka.Remote.EndpointDisassociatedException: Disassociated
   at Akka.Remote.EndpointWriter.PublishAndThrow(Exception reason, LogLevel level)
   at Akka.Remote.EndpointWriter.Unhandled(Object message)
   at Akka.Actor.ReceiveActor.ExecutePartialMessageHandler(Object message, PartialAction`1 partialAction)
   at Akka.Actor.ReceiveActor.<>c__DisplayClass11_0.<Become>b__0(Object m)
   at Akka.Actor.ActorCell.<>c__DisplayClass114_0.<Akka.Actor.IUntypedActorContext.Become>b__0(Object m)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.ReceivedTerminated(Terminated t)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
```

Any help is appreciated!

**Comment by kvarv** [comment]
Seems to be working with Wire serialization.

> Starting from Akka.NET v1.5, default Newtonsoft.Json serializer will be replaced in the favor of Wire. **At the present moment, wire is required by some of the newer plugins (like Akka.Cluster.Tools)**. 

So I guess it's expected behaviour...
