### ISSUE TITLE
Error"Collection was modified after the enumerator was instantiated" in Akka.IO.SimpleDnsCache

### ISSUE THREAD

**Issue by alvarezdaniel** [akkadotnet/akka.net#2345]
I'm using Akka.IO for a service that connects to a TCP Socket server.

For that purpose, inside an actor, I use Tcp() extension to connect sending a Tcp.Connect message, passing in it the remote address as a DnsEndpoint. In that endpoint I'm configuring the address and port to connect to.

It connects and starts to communicate with the other system with no problems.

Now, while it is communicating, randomly I'm getting this error;

System.InvalidOperationException: Collection was modified after the enumerator was instantiated.
   at System.Collections.Generic.SortedSet`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Akka.IO.SimpleDnsCache.Cache.Cleanup()
   at Akka.IO.SimpleDnsCache.CleanUp()
   at Akka.IO.SimpleDnsManager.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)

I get this error several times, whiout affecting the communication (It only logs the error)

After closing the connection gracefully, and trying to connect again, sometimes I'm getting this another error, with no possibility to connect again if I don't restart the service that hosts the actor system.

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: capacity
   at System.Collections.Generic.Dictionary`2..ctor(Int32 capacity, IEqualityComparer`1 comparer)
   at System.Collections.Generic.Dictionary`2..ctor(IDictionary`2 dictionary, IEqualityComparer`1 comparer)
   at Akka.IO.SimpleDnsCache.Cache.Put(Resolved answer, Int64 ttl)
   at Akka.IO.SimpleDnsCache.Put(Resolved r, Int64 ttl)
   at Akka.IO.InetAddressDnsResolver.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)

I explored Akka.IO namespace, and saw a timer that refreshes a DNS cache.

**Comment by yoPCix** [comment]
I experienced the same issue. However I could not fix the code myself quickly enough so I created a workaround instead. I resolve IP address myself and pass IPEndPoint to Tcp.Connect message. Works fine.
I hope somebody fixes this properly.

**Comment by Aaronontheweb** [comment]
@IgorFedchenko correct me if I'm wrong, but you found this bug and fixed it not too long ago, no?

**Comment by IgorFedchenko** [comment]
@Aaronontheweb Fixed something similar - I will take a closer look

**Comment by IgorFedchenko** [comment]
Yep, exactly this issue: https://github.com/akkadotnet/akka.net/issues/4020 - at least for the first exception described

**Comment by IgorFedchenko** [comment]
Yep, exactly this issue: https://github.com/akkadotnet/akka.net/issues/4020 - at least for the first exception described

**Comment by Aaronontheweb** [comment]
closed via #4081
