### ISSUE TITLE
ClusterShardingSettings.WithRole doesn't work as expected

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#2355]
Demonstration code:

```csharp
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using Akka.Actor;
using Akka.Cluster;
using Akka.Cluster.Sharding;
using Akka.Configuration;
using Akka.Configuration.Hocon;

namespace ShardingThatWorks
{
    class Program
    {
        private static Config _builtInConfig;

        static void Main(string[] args)
        {
            var ports = new[] { "2551", "2552", "0", "0" };
            var teamMembers = new[]
            {"SomePerson1" , "SomePerson2"};
            _builtInConfig = ((AkkaConfigurationSection)ConfigurationManager.GetSection("akka")).AkkaConfig;
           
            LaunchAiTeam("2551");
            LaunchAiTeam("2552");
            LaunchBarTender("0", teamMembers);
            LaunchAiTeam("0");

            Console.ReadLine();
        }

        private static void LaunchBarTender(string port, IList<string> patrons)
        {
            var heliosConfig = ConfigurationFactory.ParseString("akka.remote.helios.tcp.port=" + port);
            var roleConfig = ConfigurationFactory.ParseString("akka.cluster.roles = [bartender]");
            var finalConfig = heliosConfig.WithFallback(roleConfig).WithFallback(_builtInConfig);

            var sys = ActorSystem.Create("ai-corporate-retreat", finalConfig);
            var cluster = Cluster.Get(sys);
            cluster.RegisterOnMemberUp(() =>
            {
                var sharding = ClusterSharding.Get(sys);
                var shardRegion = sharding.Start(
                       typeName: "aiTeamMember",
                       entityProps: Props.Create(() => new AiTeamMember()),
                       settings: ClusterShardingSettings.Create(sys).WithRole(cluster.State.Members.Where(x => x.Address.Equals(cluster.State.Leader)).Select(x => x.Roles.First()).First()),
                       messageExtractor: new DrinkExtractor(10));

                sys.ActorOf(Props.Create(() => new BarTender(patrons, shardRegion)));
            });
        }

        private static void LaunchAiTeam(string port)
        {
            var heliosConfig = ConfigurationFactory.ParseString("akka.remote.helios.tcp.port=" + port);
            var roleConfig = ConfigurationFactory.ParseString("akka.cluster.roles = [aiteam]");
            var finalConfig = heliosConfig.WithFallback(roleConfig).WithFallback(_builtInConfig);

            var sys = ActorSystem.Create("ai-corporate-retreat", finalConfig);
        }
    }
}

```

This code prevents the cluster sharding region from even starting before at least 1 node of role "aiteam" type is started, and yet the cluster shard region throws the following exception upon startup:

```
[ERROR][10/26/2016 5:59:39 PM][Thread 0056][[akka://ai-corporate-retreat/system/cluster/$a#269996623]] [Up] callback failed with [This cluster member [akka.tcp://ai-corporate-retreat@127.0.0.1:37423] doesn't have the role [aiteam]]
Cause: Akka.Pattern.IllegalStateException: This cluster member [akka.tcp://ai-corporate-retreat@127.0.0.1:37423] doesn't have the role [aiteam]
   at Akka.Cluster.Sharding.ClusterSharding.RequireClusterRole(String role)
   at Akka.Cluster.Sharding.ClusterSharding.Start(String typeName, Props entityProps, ClusterShardingSettings settings, IdExtractor idExtractor, ShardResolver shardResolver, IShardAllocationStrategy allocationStrategy, Object handOffStopMessage)
   at Akka.Cluster.Sharding.ClusterSharding.Start(String typeName, Props entityProps, ClusterShardingSettings settings, IMessageExtractor messageExtractor, IShardAllocationStrategy allocationStrategy, Object handOffMessage)
   at Akka.Cluster.Sharding.ClusterSharding.Start(String typeName, Props entityProps, ClusterShardingSettings settings, IMessageExtractor messageExtractor)
   at ShardingThatWorks.Program.<>c__DisplayClass2_0.<LaunchBarTender>b__0() in C:\Repositories\petabridge\sharding-demo\ShardingThatWorks\ShardingThatWorks\Program.cs:line 46
   at Akka.Cluster.OnMemberStatusChangedListener.Done()
```

The node that's trying to utilize cluster sharding shouldn't have to be the same role as the shard entities themselves, right? So shouldn't this check be to ensure that at least 1 node of this type is available somewhere in the cluster? Or is the issue that sharding has to have been started in one of those nodes?

**Comment by Aaronontheweb** [comment]
Might not be a bug, but definitely needs clarification

**Comment by Aaronontheweb** [comment]
Not a bug. Looks like the shard region has to be started on each individual node capable of running that shard?

**Comment by Horusiath** [comment]
@Aaronontheweb sharding region serves as a container for shared actors. It must be started on every single node capable of running that shard. Cluster sharding role can be used to filter a subset of nodes, that are allowed to carry shards of that type, otherwise it will assume, that all of them are capable to do so.

If you want to communicate with shards of some type from cluster nodes that are not going to host those shards themselves, you may want to initialize `ShardRegionProxy` instead of shard region. 

Both shard regions and proxies have buffering capability - so they won't discard incoming messages in case when there are no recipients, instead they will buffer them and retransmit once the destination shards will be discovered.

**Comment by Aaronontheweb** [comment]
Yeah, I figured that out later - wasn't clear to me that shards needed to be started on each node capable of hosting one, but it makes sense now. No worries. We can close this.
