### ISSUE TITLE
Bug [racy spec]: FlowSelectAsyncSpec.A_Flow_with_SelectAsync_must_not_run_more_futures_than_configured

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#2357]
Full logs:
http://petabridge-ci.cloudapp.net/viewLog.html?buildId=16846&tab=buildResultsDiv&buildTypeId=AkkaNet_AkkaNetWindowsUnitTests&guest=1

```
Expected value to be 10000, but found 9998.
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Numeric.NumericAssertions`1.Be(T expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Numeric\NumericAssertions.cs:line 49
   at Akka.Streams.Tests.Dsl.FlowSelectAsyncSpec.<A_Flow_with_SelectAsync_must_not_run_more_futures_than_configured>b__16_0() in D:\work\d26c9d7f36545acd\src\core\Akka.Streams.Tests\Dsl\FlowSelectAsyncSpec.cs:line 348
   at Akka.Streams.TestKit.Tests.Utils.<>c__DisplayClass3_0.<AssertAllStagesStopped>b__0() in D:\work\d26c9d7f36545acd\src\core\Akka.Streams.TestKit.Tests\Utils.cs:line 30
   at Akka.Streams.TestKit.Tests.Utils.AssertAllStagesStopped[T](AkkaSpec spec, Func`1 block, IMaterializer materializer) in D:\work\d26c9d7f36545acd\src\core\Akka.Streams.TestKit.Tests\Utils.cs:line 43
```

**Comment by Aaronontheweb** [comment]
Can confirm that this is a bug, using historical data from TeamCity: http://petabridge-ci.cloudapp.net/project.html?projectId=AkkaNet&tab=testDetails&testNameId=6459777096029023508&guest=1#analysis

cc @Silv3rcircl3

**Comment by CodingPythonMan** [comment]
Noticed this one’s still open — mind if I take a look and try to fix it?

**Comment by Aaronontheweb** [comment]
Go right ahead

**Comment by CodingPythonMan** [comment]
I've reviewed the test A_Flow_with_SelectAsync_must_not_run_more_futures_than_configured() and I'm currently looking into the failure — specifically, the "Expected value to be 10000, but found 9998" error.

While investigating, I came across [this old TeamCity link](http://petabridge-ci.cloudapp.net/project.html?projectId=AkkaNet&tab=testDetails&testNameId=6459777096029023508&guest=1#analysis), but the page is no longer accessible.
Do you happen to remember what kind of information was in that page?

**Comment by CodingPythonMan** [comment]
I tested the original version of `A_Flow_with_SelectAsync_must_not_run_more_futures_than_configured` on GitHub Actions CI  
using a custom workflow that ran the test **10 times in a loop via `dotnet test`**.

Each run consistently failed with the following error message:

Expected task to complete within 3s.

`
test:
  runs-on: windows-latest
  steps:
    - name: Run specific test
      run: |
        for ($i = 1; $i -le 10; $i++) {
          Write-Host "🔁 Run #$i"
          dotnet test src/core/Akka.Streams.Tests/Akka.Streams.Tests.csproj --filter "FullyQualifiedName~A_Flow_with_SelectAsync_must_not_run_more_futures_than_configured" --logger trx
        }
`

**Comment by CodingPythonMan** [comment]
I tested the original version of `A_Flow_with_SelectAsync_must_not_run_more_futures_than_configured` on GitHub Actions CI  
using a custom workflow that ran the test **10 times in a loop via `dotnet test`**.

Each run consistently failed with the following error message:

Expected task to complete within 3s.

![Image](https://github.com/user-attachments/assets/82f20299-0ba6-402d-8c75-5fd883274a1e)

You can view the CI workflow I used [here](https://github.com/CodingPythonMan/akka.net/blob/dev/.github/workflows/ci.yml).

This doesn’t seem like a flaky test — it just doesn’t work reliably in CI at all.

**Comment by Aaronontheweb** [comment]
@CodingPythonMan yeah we replaced TeamCity with Azure DevOps probably 5-6 years ago, so that page is long-gone.

I think the issue with that spec is probably a design issue with the test itself - many of our Akka.Streams tests all suffer from the sin of being "over-fitted" to execution time (i.e. make sure this thing that's supposed to take 3 seconds takes exactly 3 seconds, which is dumb because scheduling can't be that precise on preemptive operating systems)

**Comment by Aaronontheweb** [comment]
This is the right place to look for racy test failure data going forward - the reports on CI/CD pipeline pass rates. You can drill down to see data about which tests have the highest flip rate https://dev.azure.com/dotnet/Akka.NET/_build?definitionId=84&_a=summary&view=ms.vss-pipelineanalytics-web.new-build-definition-pipeline-analytics-view-cardmetrics

**Comment by CodingPythonMan** [comment]
Thanks! I’ll observe the PR validation and see how it behaves in CI.

**Comment by CodingPythonMan** [comment]
This test is currently skipped in CI via [LocalFact], but I've rewritten it to remove the timing-based flakiness while keeping its original purpose. Would you be open to converting it to [Fact] if it passes reliably?

**Comment by Aaronontheweb** [comment]
100% we would! @CodingPythonMan
