### ISSUE TITLE
Sending messages through a Load balancer: Error while decoding incoming Akka PDU

### ISSUE THREAD

**Issue by leonelcm** [akkadotnet/akka.net#2363]
Hi,

Is it possible to send messages to a remote actor through a Load Balancer? 
I tried the following scenarios:

- Send a message to a remote actor by using the remote server IP address - Server1 -> Server2 - Message was successfully sent and received

- Send a message to a remote actor through a LB - Server1 -> LB -> Server2 - The message is received in Server2, but the following exceptions are generated:

Server2:
"AssociationError [akka.tcp://NodeSystem@Server2:8005] <- akka.tcp://PING@Server1:2110: Error [Error while decoding incoming Akka PDU] [   at Akka.Remote.EndpointReader.TryDecodeMessageAndAck(ByteString pdu)
   at Akka.Remote.EndpointReader.<Reading>b__11_1(InboundPayload inbound)
   at lambda_method(Closure , Object , Action`1 , Action`1 , Action`1 )
   at Akka.Tools.MatchHandler.PartialHandlerArgumentsCapture`4.Handle(T value)
   at Akka.Actor.ReceiveActor.ExecutePartialMessageHandler(Object message, PartialAction`1 partialAction)
   at Akka.Actor.ReceiveActor.OnReceive(Object message)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)]"

Server1:
[akka://PING/system/endpointManager/reliableEndpointWriter-akka.tcp%3a%2f%2fNodeSystem%40Server2%3a8005-1] Invalid address: akka.tcp://NodeSystem@Server2:8005
Cause: Akka.Remote.InvalidAssociation: Invalid address: akka.tcp://NodeSystem@Server2:8005 ---> Akka.Remote.Transport.InvalidAssociationException: Association failure ---> Helios.Exceptions.HeliosConnectionException: failed as a result of System.AggregateException: One or more errors occurred.
 ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> Helios.Channels.ConnectException: LogError connecting to Server2:8005 ---> System.Net.Sockets.SocketException: No connection could be made because the target machine
actively refused it
   at Helios.Channels.Sockets.SocketChannelAsyncOperation.Validate()
   at Helios.Channels.Sockets.TcpSocketChannel.DoFinishConnect(SocketChannelAsyncOperation operation)
   at Helios.Channels.Sockets.AbstractSocketChannel.AbstractSocketUnsafe.FinishConnect(SocketChannelAsyncOperation operation)

Is this second scenario not supported by Akka.net? Or could it be that the message is being corrupted?

I am using the version 1.1.0.

Thank you very much

**Comment by Danthar** [comment]
There is nothing in Akka that would prevent you from using an LoadBalancer. However considering that in Akka you setup direct connections to other actorsystems, and that that relation is 1on1. I fail to see the value in using an loadbalancer.
I mean, its not like you can use a loadbalancer appliance to actually loadbalance messages in akka. Conceptually it does not work like that. Note that Akka.net has build in loadbalancing (across machines) capabilities in the form of clustered routers and cluster-sharding.

Besides that it seems like the message is being corrupted somehow. Which would mean your loadbalancer is not transparent (?). In other words the bytestream is being changed somehow while in transit.

**Comment by nikobiker12** [comment]
Hello, I get the same problem using dotnet core on Linux but I don't use Load balancer... only 4 AWS reources... 

@leonelcm did you manage to solve it ?
@Danthar How can I investigate ? Log mode ?  hocon configuration ?

Thx for your help ?

@Dan
