### ISSUE TITLE
PublishSubscribe.DistributedPubSubRestartMultiNode fails

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#2390]
Probably related to https://github.com/akkadotnet/akka.net/issues/2312

This spec fails racily with the following issue on Node 1:

<summary>
[Node1][FAIL-EXCEPTION] Type: Xunit.Sdk.TrueException
--> [Node1][FAIL-EXCEPTION] Message: Failed: Timeout 00:00:01 while waiting for a message of type Akka.Actor.ActorIdentity 
Expected: True
Actual:   False
<details>
[Node1][FAIL] Akka.Cluster.Tools.Tests.MultiNode.PublishSubscribe.DistributedPubSubRestartMultiNode1.DistributedPubSubRestartSpecs
[Node1][FAIL-EXCEPTION] Type: Xunit.Sdk.TrueException
--> [Node1][FAIL-EXCEPTION] Message: Failed: Timeout 00:00:01 while waiting for a message of type Akka.Actor.ActorIdentity 
Expected: True
Actual:   False
--> [Node1][FAIL-EXCEPTION] StackTrace:    at Xunit.Assert.True(Nullable`1 condition, String userMessage) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\BooleanAsserts.cs:line 90
   at Akka.TestKit.Xunit2.XunitAssertions.Fail(String format, Object[] args) in D:\work\d26c9d7f36545acd\src\contrib\testkits\Akka.TestKit.Xunit2\XunitAssertions.cs:line 21
   at Akka.TestKit.TestKitBase.InternalExpectMsgEnvelope[T](Nullable`1 timeout, Action`2 assert, String hint, Boolean shouldLog) in D:\work\d26c9d7f36545acd\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 196
   at Akka.TestKit.TestKitBase.InternalExpectMsgEnvelope[T](Nullable`1 timeout, Action`1 msgAssert, Action`1 senderAssert, String hint) in D:\work\d26c9d7f36545acd\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 182
   at Akka.TestKit.TestKitBase.InternalExpectMsg[T](Nullable`1 timeout, Action`1 msgAssert, String hint) in D:\work\d26c9d7f36545acd\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 157
   at Akka.TestKit.TestKitBase.ExpectMsg[T](Nullable`1 duration, String hint) in D:\work\d26c9d7f36545acd\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 29
   at Akka.Cluster.Tools.Tests.MultiNode.PublishSubscribe.DistributedPubSubRestartSpec.<>c__DisplayClass5_0.<A_Cluster_with_DistributedPubSub_must_handle_restart_of_nodes_with_same_address>b__5() in D:\work\d26c9d7f36545acd\src\contrib\cluster\Akka.Cluster.Tools.Tests.MultiNode\PublishSubscribe\DistributedPubSubRestartSpec.cs:line 130
   at Akka.TestKit.TestKitBase.AwaitAssert(Action assertion, Nullable`1 duration, Nullable`1 interval) in D:\work\d26c9d7f36545acd\src\core\Akka.TestKit\TestKitBase_AwaitAssert.cs:line 48
   at Akka.Cluster.Tools.Tests.MultiNode.PublishSubscribe.DistributedPubSubRestartSpec.<>c__DisplayClass5_0.<A_Cluster_with_DistributedPubSub_must_handle_restart_of_nodes_with_same_address>b__4() in D:\work\d26c9d7f36545acd\src\contrib\cluster\Akka.Cluster.Tools.Tests.MultiNode\PublishSubscribe\DistributedPubSubRestartSpec.cs:line 127
   at Akka.TestKit.TestKitBase.<>c__DisplayClass116_0.<Within>b__0() in D:\work\d26c9d7f36545acd\src\core\Akka.TestKit\TestKitBase_Within.cs:line 38
   at Akka.TestKit.TestKitBase.Within[T](TimeSpan min, TimeSpan max, Func`1 function, String hint, Nullable`1 epsilonValue) in D:\work\d26c9d7f36545acd\src\core\Akka.TestKit\TestKitBase_Within.cs:line 79
   at Akka.TestKit.TestKitBase.Within(TimeSpan min, TimeSpan max, Action action, String hint, Nullable`1 epsilonValue) in D:\work\d26c9d7f36545acd\src\core\Akka.TestKit\TestKitBase_Within.cs:line 38
   at Akka.TestKit.TestKitBase.Within(TimeSpan max, Action action, Nullable`1 epsilonValue) in D:\work\d26c9d7f36545acd\src\core\Akka.TestKit\TestKitBase_Within.cs:line 26
   at Akka.Cluster.Tools.Tests.MultiNode.PublishSubscribe.DistributedPubSubRestartSpec.<A_Cluster_with_DistributedPubSub_must_handle_restart_of_nodes_with_same_address>b__5_3() in D:\work\d26c9d7f36545acd\src\contrib\cluster\Akka.Cluster.Tools.Tests.MultiNode\PublishSubscribe\DistributedPubSubRestartSpec.cs:line 125
   at Akka.Remote.TestKit.MultiNodeSpec.RunOn(Action thunk, RoleName[] nodes) in D:\work\d26c9d7f36545acd\src\core\Akka.Remote.TestKit\MultiNodeSpec.cs:line 503
   at Akka.Cluster.Tools.Tests.MultiNode.PublishSubscribe.DistributedPubSubRestartSpec.<A_Cluster_with_DistributedPubSub_must_handle_restart_of_nodes_with_same_address>b__5_0() in D:\work\d26c9d7f36545acd\src\contrib\cluster\Akka.Cluster.Tools.Tests.MultiNode\PublishSubscribe\DistributedPubSubRestartSpec.cs:line 117
   at Akka.TestKit.TestKitBase.<>c__DisplayClass116_0.<Within>b__0() in D:\work\d26c9d7f36545acd\src\core\Akka.TestKit\TestKitBase_Within.cs:line 38
   at Akka.TestKit.TestKitBase.Within[T](TimeSpan min, TimeSpan max, Func`1 function, String hint, Nullable`1 epsilonValue) in D:\work\d26c9d7f36545acd\src\core\Akka.TestKit\TestKitBase_Within.cs:line 79
   at Akka.TestKit.TestKitBase.Within(TimeSpan min, TimeSpan max, Action action, String hint, Nullable`1 epsilonValue) in D:\work\d26c9d7f36545acd\src\core\Akka.TestKit\TestKitBase_Within.cs:line 38
   at Akka.TestKit.TestKitBase.Within(TimeSpan max, Action action, Nullable`1 epsilonValue) in D:\work\d26c9d7f36545acd\src\core\Akka.TestKit\TestKitBase_Within.cs:line 26
   at Akka.Cluster.Tools.Tests.MultiNode.PublishSubscribe.DistributedPubSubRestartSpec.A_Cluster_with_DistributedPubSub_must_handle_restart_of_nodes_with_same_address() in D:\work\d26c9d7f36545acd\src\contrib\cluster\Akka.Cluster.Tools.Tests.MultiNode\PublishSubscribe\DistributedPubSubRestartSpec.cs:line 90
   at Akka.Cluster.Tools.Tests.MultiNode.PublishSubscribe.DistributedPubSubRestartSpec.DistributedPubSubRestartSpecs() in D:\work\d26c9d7f36545acd\src\contrib\cluster\Akka.Cluster.Tools.Tests.MultiNode\PublishSubscribe\DistributedPubSubRestartSpec.cs:line 74
</details>
</summary>

Full stack trace in the details. Attached individual logs for all 3 nodes.

[node1.txt](https://github.com/akkadotnet/akka.net/files/622460/node1.txt)
[node2.txt](https://github.com/akkadotnet/akka.net/files/622461/node2.txt)
[node3.txt](https://github.com/akkadotnet/akka.net/files/622462/node3.txt)

**Comment by alexvaluyskiy** [comment]
@Aaronontheweb Have you seen this spec as failed again?
