### ISSUE TITLE
Unhandled Helios Exceptions

### ISSUE THREAD

**Issue by michaelsg** [akkadotnet/akka.net#2392]
I have a task exception handler (``TaskScheduler.UnobservedTaskException``) which is reporting a recurring exception in Helios. I'm pretty sure this is the cause of some of my recent frustrations with disappearing messages during moments of intense message sending. 

Please consider adding a handler to catch and report these errors so that they can be diagnosed and fixed.

```
[]System.AggregateException
One or more errors occurred.
No stacktrace.
----------------------------------------
[Helios]System.Net.Sockets.SocketException
An invalid argument was supplied
   at Helios.Channels.Sockets.SocketChannelAsyncOperation.Validate()
   at Helios.Channels.Sockets.AbstractSocketChannel.AbstractSocketUnsafe.FinishWrite(SocketChannelAsyncOperation operation)
   at Helios.Channels.Sockets.AbstractSocketByteChannel.IncompleteWrite(Boolean scheduleAsync, SocketChannelAsyncOperation operation)
   at Helios.Channels.Sockets.TcpSocketChannel.DoWrite(ChannelOutboundBuffer input)
   at Helios.Channels.AbstractChannel.AbstractUnsafe.Flush0()
```

**Comment by Aaronontheweb** [comment]
@michaelsg thanks, we'll take a look at that.

**Comment by Silv3rcircl3** [comment]
Closing, Helios is replaced by DotNetty and is no longer under active development.
