### ISSUE TITLE
Akka.Cluster.Sharding / Akka.Persistence Race Condition for high volume snapshots

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#2437]
Received a bug report from a user via email, copied below.
----

We are currently having a random error when PersistentShard/Coordinator actors generates a Snapshot. This occurs when a big amount of events are inserted in a short period of time.

```
Failed to SaveSnapshot given metadata [SnapshotMetadata<pid: /sharding/imageShard/99, seqNr: 1999, timestamp: 0001-01-01>] due to: [System.NotSupportedException: There is no active ActorContext, this is most likely due to use of async operations from within this actor.
   at Akka.Actor.ActorBase.get_Context()
   at Akka.Persistence.Sql.Common.Snapshot.SqlSnapshotStore.ToSnapshotEntry(SnapshotMetadata metadata, Object snapshot)
   at Akka.Persistence.Sql.Common.Snapshot.SqlSnapshotStore.<SaveAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Util.Internal.AtomicState.<CallThrough>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Akka.Util.Internal.AtomicState.<CallThrough>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Pattern.Closed.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Pattern.CircuitBreaker.<WithCircuitBreaker>d__33.MoveNext(): There is no active ActorContext, this is most likely due to use of async operations from within this actor.]
 ```
Despite this error the system continues working ok, and the next snapshot is generated fine.  This is shown sporadically on the system. 

The snapshot-after value is set as default (1000) and the shard distribution is up to 100 different shards on the cluster.

**Work-around**
The only work-around we found is to, on the actor that uses snapshooting, create the Snapshot Actor in the Constructor Method call, like this.
 
            var nothing = (this.SnapshotStore != null) ? this.SnapshotStore.Path : null;
            nothing = (this.Journal != null) ? this.Journal.Path : null;

**Comment by Aaronontheweb** [comment]
cc @Horusiath

**Comment by Horusiath** [comment]
This is really interesting as `ToSnapshotEntry` method mentioned in the stack trace is not used on any of the current paths - neither of /dev nor or /master branches. Also there's no similar method in SQL Server plugin.

First possible solution that comes to my mind: try to upgrade dependency on SQL plugin (it's probably outdated).

**Comment by Aaronontheweb** [comment]
Haven't heard any more about this, and we've made a ton of work to the guts of Akka.Cluster.Sharding and Akka.Persistence since. Marking this as closed.
