### ISSUE TITLE
Random Mono test failure: Akka.Configuration.ConfigurationException : Logger [Akka.Event.DefaultLogger] specified in config cannot be loaded

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#2610]
Seen this come up on many different tests lately:

```
Akka.Configuration.ConfigurationException : Logger [Akka.Event.DefaultLogger] specified in config cannot be loaded: System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00014] in <dca3b561b8ad4f9fb10141d81b39ff45>:0 
  at System.Threading.Tasks.Task`1[TResult].GetResultCore (System.Boolean waitCompletionNotification) [0x00034] in <dca3b561b8ad4f9fb10141d81b39ff45>:0 
  at System.Threading.Tasks.Task`1[TResult].get_Result () [0x0000b] in <dca3b561b8ad4f9fb10141d81b39ff45>:0 
  at Akka.Event.LoggingBus.AddLogger (Akka.Actor.Internal.ActorSystemImpl system, System.Type loggerType, Akka.Event.LogLevel logLevel, System.String loggingBusName, System.TimeSpan timeout) [0x00042] in <2f7572f625f74ec0b489853bc1ea74e6>:0 
  at Akka.Event.LoggingBus.StartDefaultLoggers (Akka.Actor.Internal.ActorSystemImpl system) [0x000a5] in <2f7572f625f74ec0b489853bc1ea74e6>:0 
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

---- System.AggregateException : One or more errors occurred.
-------- System.Threading.Tasks.TaskCanceledException : A task was canceled.
  at Akka.Event.LoggingBus.StartDefaultLoggers (Akka.Actor.Internal.ActorSystemImpl system) [0x000cd] in <2f7572f625f74ec0b489853bc1ea74e6>:0 
  at Akka.Actor.LocalActorRefProvider.Init (Akka.Actor.Internal.ActorSystemImpl system) [0x000e1] in <2f7572f625f74ec0b489853bc1ea74e6>:0 
  at Akka.Remote.RemoteActorRefProvider.Init (Akka.Actor.Internal.ActorSystemImpl system) [0x00007] in <2654ac264e46416e8c3ec42cce0f6b6e>:0 
  at Akka.Cluster.ClusterActorRefProvider.Init (Akka.Actor.Internal.ActorSystemImpl system) [0x00000] in <e9f53706bfb14547883192c10e490710>:0 
  at Akka.Actor.Internal.ActorSystemImpl.Start () [0x00012] in <2f7572f625f74ec0b489853bc1ea74e6>:0 
----- Inner Stack Trace -----
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00014] in <dca3b561b8ad4f9fb10141d81b39ff45>:0 
  at System.Threading.Tasks.Task`1[TResult].GetResultCore (System.Boolean waitCompletionNotification) [0x00034] in <dca3b561b8ad4f9fb10141d81b39ff45>:0 
  at System.Threading.Tasks.Task`1[TResult].get_Result () [0x0000b] in <dca3b561b8ad4f9fb10141d81b39ff45>:0 
  at Akka.Event.LoggingBus.AddLogger (Akka.Actor.Internal.ActorSystemImpl system, System.Type loggerType, Akka.Event.LogLevel logLevel, System.String loggingBusName, System.TimeSpan timeout) [0x00042] in <2f7572f625f74ec0b489853bc1ea74e6>:0 
  at Akka.Event.LoggingBus.StartDefaultLoggers (Akka.Actor.Internal.ActorSystemImpl system) [0x000a5] in <2f7572f625f74ec0b489853bc1ea74e6>:0 
----- Inner Stack Trace -----
```

**Comment by dpavsrtrl** [comment]
I believe this has to do with the number of minimum worker threads in threadpool. You ran out of on-demand workers, and management algorithm kicked in.

ThreadPool.SetMinThreads

**Comment by baburajc** [comment]
I'm also getting an Akka.Configuration.ConfigurationException while creating an actor system with Akka.Actor.ActorSystem.Create() method call.
I did some investigation and found that, by default timeout value of logger-startup-timeout  is 5 seconds and we can increase the timeout value by adding following section in app.config.
  ```
<configSections>
    <section name="akka" type="Akka.Configuration.Hocon.AkkaConfigurationSection, Akka" />
  </configSections>
  <akka>
    <hocon>
      <![CDATA[
          akka {
            loglevel = WARNING
            logger-startup-timeout = 30s
          }
      ]]>
    </hocon>
  </akka>
```

I added the same in my app.config, now we are getting the same Akka.Configuration.ConfigurationException after 30 seconds intermittently.

Could you guys get me the root cause of this Akka.Configuration.ConfigurationException?

Below This is the log snapshot of exception.

> Akka.Configuration.ConfigurationException: Logger [Akka.Event.DefaultLogger] specified in config cannot be loaded: System.AggregateException: One or more errors occurred. ---> Akka.Actor.AskTimeoutException: Timeout after 00:00:30 seconds
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Akka.Actor.Futures.<Ask>d__9.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Akka.Actor.Futures.<Ask>d__5`1.MoveNext()
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
>    at Akka.Event.LoggingBus.AddLogger(ActorSystemImpl system, Type loggerType, LogLevel logLevel, String loggingBusName, TimeSpan timeout)
>    at Akka.Event.LoggingBus.StartDefaultLoggers(ActorSystemImpl system)
> ---> (Inner Exception #0) Akka.Actor.AskTimeoutException: Timeout after 00:00:30 seconds
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Akka.Actor.Futures.<Ask>d__9.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Akka.Actor.Futures.<Ask>d__5`1.MoveNext()<---
> ---> System.AggregateException: One or more errors occurred. ---> Akka.Actor.AskTimeoutException: Timeout after 00:00:30 seconds
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Akka.Actor.Futures.<Ask>d__9.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Akka.Actor.Futures.<Ask>d__5`1.MoveNext()
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
>    at Akka.Event.LoggingBus.AddLogger(ActorSystemImpl system, Type loggerType, LogLevel logLevel, String loggingBusName, TimeSpan timeout)
>    at Akka.Event.LoggingBus.StartDefaultLoggers(ActorSystemImpl system)
>    --- End of inner exception stack trace ---
>    at Akka.Event.LoggingBus.StartDefaultLoggers(ActorSystemImpl system)
>    at Akka.Actor.Internal.ActorSystemImpl.Start()
>    at Akka.Actor.ActorSystem.Create(String name)
>    at SchedulerFSM.SchedulerFSMManager.Initialize(IDataProvider dataProvider)
>    at Schedular.ProcessEngine.ProcessEngine.InitializeEngine()
>    at SorterScheduler.Scheduler.SchedulerBuilder.Initialize(IToolController toolController)
>    at SorterScheduler.Scheduler.Scheduler.DoInitialize(IToolController toolController)
>
