### ISSUE TITLE
NullReferenceExcpetion in Akka.Testkit on shutdown

### ISSUE THREAD

**Issue by Silv3rcircl3** [akkadotnet/akka.net#2797]
System.NullReferenceException : Object reference not set to an instance of an object
  at Akka.TestKit.TestKitBase.Shutdown (Akka.Actor.ActorSystem system, System.Nullable`1[T] duration, System.Boolean verifySystemShutdown) [0x0004b] in <3fe3b26ec99f49c4a9d40c8de61f848e>:0 
  at Akka.TestKit.TestKitBase.Shutdown (System.Nullable`1[T] duration, System.Boolean verifySystemShutdown) [0x0000d] in <3fe3b26ec99f49c4a9d40c8de61f848e>:0 
  at Akka.TestKit.Xunit2.TestKit.AfterAll () [0x00001] in <2a1c9050fdd048988126e78aa6e5a477>:0 
  at Akka.TestKit.AkkaSpec.AfterAll () [0x00008] in <924feb85ae93402cb2d6dd77cc062c1e>:0 
  at Akka.TestKit.Xunit2.TestKit.Dispose (System.Boolean disposing) [0x00012] in <2a1c9050fdd048988126e78aa6e5a477>:0 
  at Akka.TestKit.Xunit2.TestKit.Dispose () [0x00001] in <2a1c9050fdd048988126e78aa6e5a477>:0 
  at ReflectionAbstractionExtensions.DisposeTestClass (Xunit.Abstractions.ITest test, System.Object testClass, Xunit.Sdk.IMessageBus messageBus, Xunit.Sdk.ExecutionTimer timer, System.Threading.CancellationTokenSource cancellationTokenSource) [0x00021] in <7127fda305884c609142d1a99f7edf3f>:0

**Comment by Aaronontheweb** [comment]
ty @Silv3rcircl3

**Comment by Aaronontheweb** [comment]
After some investigation, this issue is the same one as this one that occurs in the Mono test suite - an example from the latest false-positive failure on the Akka.IO rework PR: https://github.com/akkadotnet/akka.net/pull/2683

```
Akka.Configuration.ConfigurationException : Logger [Akka.TestKit.TestEventListener, Akka.TestKit] specified in config cannot be loaded: System.InvalidOperationException: Cannot create child while terminating or terminated
   at Akka.Actor.ActorCell.MakeChild(Props props, String name, Boolean async, Boolean systemService) in /checkout/src/core/Akka/Actor/ActorCell.Children.cs:line 441
   at Akka.Actor.ActorCell.AttachChild(Props props, Boolean isSystemService, String name) in /checkout/src/core/Akka/Actor/ActorCell.Children.cs:line 54
   at Akka.Actor.Internal.ActorSystemImpl.SystemActorOf(Props props, String name) in /checkout/src/core/Akka/Actor/Internal/ActorSystemImpl.cs:line 142
   at Akka.Event.LoggingBus.AddLogger(ActorSystemImpl system, Type loggerType, LogLevel logLevel, String loggingBusName, TimeSpan timeout) in /checkout/src/core/Akka/Event/LoggingBus.cs:line 169
   at Akka.Event.LoggingBus.StartDefaultLoggers(ActorSystemImpl system) in /checkout/src/core/Akka/Event/LoggingBus.cs:line 112
---- System.InvalidOperationException : Cannot create child while terminating or terminated
   at Akka.Event.LoggingBus.StartDefaultLoggers(ActorSystemImpl system) in /checkout/src/core/Akka/Event/LoggingBus.cs:line 116
   at Akka.Actor.LocalActorRefProvider.Init(ActorSystemImpl system) in /checkout/src/core/Akka/Actor/ActorRefProvider.cs:line 373
   at Akka.Actor.Internal.ActorSystemImpl.Start() in /checkout/src/core/Akka/Actor/Internal/ActorSystemImpl.cs:line 215
   at Akka.Actor.ActorSystem.CreateAndStartSystem(String name, Config withFallback) in /checkout/src/core/Akka/Actor/ActorSystem.cs:line 118
   at Akka.Actor.ActorSystem.Create(String name, Config config) in /checkout/src/core/Akka/Actor/ActorSystem.cs:line 100
   at Akka.TestKit.TestKitBase.InitializeTest(ActorSystem system, Config config, String actorSystemName, String testActorName) in /checkout/src/core/Akka.TestKit/TestKitBase.cs:line 115
   at Akka.TestKit.TestKitBase..ctor(ITestKitAssertions assertions, ActorSystem system, Config config, String actorSystemName, String testActorName) in /checkout/src/core/Akka.TestKit/TestKitBase.cs:line 98
   at Akka.TestKit.TestKitBase..ctor(ITestKitAssertions assertions, Config config, String actorSystemName, String testActorName) in /checkout/src/core/Akka.TestKit/TestKitBase.cs:line 88
   at Akka.TestKit.Xunit2.TestKit..ctor(Config config, String actorSystemName, ITestOutputHelper output) in /checkout/src/contrib/testkits/Akka.TestKit.Xunit2/TestKit.cs:line 55
   at Akka.TestKit.AkkaSpec..ctor(ITestOutputHelper output, Config config) in /checkout/src/core/Akka.Tests.Shared.Internals/AkkaSpec.cs:line 61
   at Akka.Streams.Tests.Dsl.FlowWatchTerminationSpec..ctor(ITestOutputHelper helper) in /checkout/src/core/Akka.Streams.Tests/Dsl/FlowWatchTerminationSpec.cs:line 24
----- Inner Stack Trace -----
   at Akka.Actor.ActorCell.MakeChild(Props props, String name, Boolean async, Boolean systemService) in /checkout/src/core/Akka/Actor/ActorCell.Children.cs:line 441
   at Akka.Actor.ActorCell.AttachChild(Props props, Boolean isSystemService, String name) in /checkout/src/core/Akka/Actor/ActorCell.Children.cs:line 54
   at Akka.Actor.Internal.ActorSystemImpl.SystemActorOf(Props props, String name) in /checkout/src/core/Akka/Actor/Internal/ActorSystemImpl.cs:line 142
   at Akka.Event.LoggingBus.AddLogger(ActorSystemImpl system, Type loggerType, LogLevel logLevel, String loggingBusName, TimeSpan timeout) in /checkout/src/core/Akka/Event/LoggingBus.cs:line 169
   at Akka.Event.LoggingBus.StartDefaultLoggers(ActorSystemImpl system) in /checkout/src/core/Akka/Event/LoggingBus.cs:line 112
```

Looks like the test suite is bailing out at the start of the test and the `ActorSystem` for the spec hasn't even been created yet, hence the NRE. All of the other parts of that method are null-checked. 

This exception can happen if we fail when creating the `ActorSystem` here: https://github.com/akkadotnet/akka.net/blob/v1.3/src/core/Akka.TestKit/TestKitBase.cs#L115

Something is failing during the process of creating the `ActorSystem` on Mono, hence why this is an issue. I wonder if XUnit is doing something in the background that interferes with this.

IMHO, we need to finish https://github.com/akkadotnet/akka.net/pull/2771 so we can observe this without the .NET Core noise.

**Comment by Aaronontheweb** [comment]
Ahh, turns out the root cause to this issue was a few lines above in the logfile...

```
[ERROR][06/25/2017 20:50:51][Thread 0175][LocalActorRefProvider(akka://AkkaSpec)] guardian [akka://AkkaSpec/] failed, shutting down!
[20:50:50]	[docker] Cause: System.NullReferenceException: Object reference not set to an instance of an object.
[20:50:50]	[docker]    at Akka.Actor.ActorPath.FillElements(ActorPath actorPath) in /checkout/src/core/Akka/Actor/ActorPath.cs:line 207
[20:50:50]	[docker]    at Akka.Actor.ActorPath.<>c.<.cctor>b__56_0(ActorPath actorPath) in /checkout/src/core/Akka/Actor/ActorPath.cs:line 156
[20:50:50]	[docker]    at Akka.Util.FastLazy`2.get_Value() in /checkout/src/core/Akka/Util/FastLazy.cs:line 149
[20:50:50]	[docker]    at Akka.Actor.ActorPath.get_Elements() in /checkout/src/core/Akka/Actor/ActorPath.cs:line 255
[20:50:50]	[docker]    at Akka.Actor.ActorPath.Equals(ActorPath other) in /checkout/src/core/Akka/Actor/ActorPath.cs:line 306
[20:50:50]	[docker]    at Akka.Actor.ActorRefBase.Equals(IActorRef other) in /checkout/src/core/Akka/Actor/ActorRef.cs:line 331
[20:50:50]	[docker]    at Akka.Actor.ActorCell.AddWatcher(IActorRef watchee, IActorRef watcher) in /checkout/src/core/Akka/Actor/ActorCell.DeathWatch.cs:line 193
[20:50:50]	[docker]    at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState) in /checkout/src/core/Akka/Actor/ActorCell.DefaultMessages.cs:line 262
```

I'll take a look at the `ActorPath` class then.

**Comment by Aaronontheweb** [comment]
Yeah, looks like the way the `ActorPath` is being evaluated with `FastLazy` might not be compiled on Mono in a manner that makes it thread-safe; never seen this issue occur on Windows... But we'll have to create a fix for it.

**Comment by Aaronontheweb** [comment]
@Silv3rcircl3 these are the same issue: https://github.com/akkadotnet/akka.net/issues/2829

**Comment by Aaronontheweb** [comment]
Actually no, similar symptoms but different causes.

**Comment by Aaronontheweb** [comment]
So having done some more work looking into this issue, it shows up in a variety of ways:

```
System.InvalidOperationException : Cannot create child while terminating or terminated
   at Akka.Actor.ActorCell.MakeChild(Props props, String name, Boolean async, Boolean systemService) in /checkout/src/core/Akka/Actor/ActorCell.Children.cs:line 441
   at Akka.Actor.ActorCell.AttachChild(Props props, Boolean isSystemService, String name) in /checkout/src/core/Akka/Actor/ActorCell.Children.cs:line 54
   at Akka.Actor.Internal.ActorSystemImpl.SystemActorOf(Props props, String name) in /checkout/src/core/Akka/Actor/Internal/ActorSystemImpl.cs:line 142
   at Akka.TestKit.TestKitBase.CreateTestActor(ActorSystem system, String name) in /checkout/src/core/Akka.TestKit/TestKitBase.cs:line 449
   at Akka.TestKit.TestKitBase.InitializeTest(ActorSystem system, Config config, String actorSystemName, String testActorName) in /checkout/src/core/Akka.TestKit/TestKitBase.cs:line 135
   at Akka.TestKit.TestKitBase..ctor(ITestKitAssertions assertions, ActorSystem system, Config config, String actorSystemName, String testActorName) in /checkout/src/core/Akka.TestKit/TestKitBase.cs:line 98
   at Akka.TestKit.TestKitBase..ctor(ITestKitAssertions assertions, ActorSystem system, String testActorName) in /checkout/src/core/Akka.TestKit/TestKitBase.cs:line 72
   at Akka.TestKit.TestProbe..ctor(ActorSystem system, ITestKitAssertions assertions, String testProbeName) in /checkout/src/core/Akka.TestKit/TestProbe.cs:line 30
   at Akka.TestKit.TestKitBase.CreateTestProbe(ActorSystem system, String name) in /checkout/src/core/Akka.TestKit/TestKitBase.cs:line 472
   at Akka.TestKit.TestKitBase.CreateTestProbe(String name) in /checkout/src/core/Akka.TestKit/TestKitBase.cs:line 461
   at Akka.Streams.TestKit.TestSubscriber.ManualProbe`1..ctor(TestKitBase testKit) in /checkout/src/core/Akka.Streams.TestKit/TestSubscriber.cs:line 80
   at Akka.Streams.TestKit.TestSubscriber.CreateManualSubscriberProbe[T](TestKitBase testKit) in /checkout/src/core/Akka.Streams.TestKit/TestSubscriber.cs:line 515
   at Akka.Streams.Tests.Dsl.FlowZipWithSpec.A_ZipWith_for_Flow_must_work_in_the_happy_case() in /checkout/src/core/Akka.Streams.Tests/Dsl/FlowZipWithSpec.cs:line 38
```

I think what's happening, in essence, is that the ActorSystem is being shutdown before a test has a chance to actually start and it appears to be racy. I suspect there's something in the initialization code that causes this issue to occur in the `v1.3` branch on Mono.

**Comment by Aaronontheweb** [comment]
Now we're getting somewhere...

```
[09:47:21]	[docker] [ERROR][07/17/2017 09:47:21][Thread 0623][akka://RemotingSpec-105/system/log-test] There is no currently active test.
[09:47:21]	[docker] Cause: System.InvalidOperationException: There is no currently active test.
[09:47:21]	[docker]   at Xunit.Sdk.TestOutputHelper.GuardInitialized () [0x00008] in <7127fda305884c609142d1a99f7edf3f>:0 
[09:47:21]	[docker]   at Xunit.Sdk.TestOutputHelper.QueueTestOutput (System.String output) [0x00019] in <7127fda305884c609142d1a99f7edf3f>:0 
[09:47:21]	[docker]   at Xunit.Sdk.TestOutputHelper.WriteLine (System.String message) [0x00017] in <7127fda305884c609142d1a99f7edf3f>:0 
[09:47:21]	[docker]   at Akka.TestKit.Xunit2.Internals.TestOutputLogger+<>c__DisplayClass0_0.<.ctor>b__2 (Akka.Event.Warning e) [0x0000c] in <c39c51a0c4ec47f4926c55cc502785d4>:0 
```

XUnit beta version we're using under .NET Core / Linux is half the problem. The `ITestOutputHelper` itself blows up because the actor system code starts before, as far as XUnit knows, the test has actually started.... Going to keep digging, but I think this is part of the problem.

**Comment by Aaronontheweb** [comment]
Resovled via https://github.com/akkadotnet/akka.net/pull/2876
