### ISSUE TITLE
Incremental tests - TeamCity agent Git environment issues

### ISSUE THREAD

**Issue by heynickc** [akkadotnet/akka.net#2834]
Can't utilize FAKE's Git namespace at the moment on our TeamCity build agents:
Docker:
```
[19:27:35][docker] Searching for incremental tests to run in Unit test mode...
[19:27:35][docker] git merge-base --fork-point v1.3
[19:27:35][docker] ﻿git log --oneline -1
[19:27:35][docker] ﻿﻿﻿Running build failed.
[19:27:35][docker] Error:
[19:27:35][docker] System.Exception: git log --oneline failed: error: object directory /etc/buildAgent/system/git/git-63A8AB84.git/objects does not exist; check .git/objects/info/alternates.
[19:27:35][docker] fatal: bad object HEAD
```
Windows:
```
[20:16:46][RunTests] Searching for incremental tests to run in Unit test mode...
[20:16:46][RunTests] C:\Program Files\Git\cmd\git.exe merge-base --fork-point v1.3
[20:16:47][RunTests] Running build failed.
[20:16:47][RunTests] Error:
[20:16:47][RunTests] System.Exception: Could not run "git merge-base --fork-point v1.3".
[20:16:47][RunTests] Error: 
[20:16:47][RunTests] fatal: Not a git repository (or any of the parent directories): .git
```

**Comment by heynickc** [comment]
Windows error working directory is set to `__SOURCE_DIRECTORY__` which is the root directory and should contain `.git` folder so could be that the git folder isn't accessible or getting cleaned up.  The Linux error I'm unsure of the root cause, but may be related (file permissions maybe)

**Comment by heynickc** [comment]
`.git` folders are not accessible by default when TeamCity clones the repo

**Comment by heynickc** [comment]
changing the VCS Checkout Mode to "Always checkout on Agent" per these docs, as they are supposed to bring the `.git` folder into the source directory: https://confluence.jetbrains.com/display/TCD10/VCS+Checkout+Mode

**Comment by heynickc** [comment]
The above issue will be resolved with changing the setting below:

![checkout_on_agent](https://user-images.githubusercontent.com/1671359/27887051-b5cb36ec-61ac-11e7-871f-227f0d0d3273.png)

However, the next issue is that TeamCity doesn't check out any branches other than the feature branch of the PR.  It needs the default branch `v1.3` so need to add this.  Here's the error:

```
[21:44:49][RunTests] C:\Program Files\Git\cmd\git.exe merge-base --fork-point v1.3
[21:44:49][RunTests] Running build failed.
[21:44:49][RunTests] Error:
[21:44:49][RunTests] System.Exception: Could not run "git merge-base --fork-point v1.3".
[21:44:49][RunTests] Error: 
[21:44:49][RunTests] fatal: No such ref: 'v1.3'
[21:44:49][RunTests]    at Fake.Git.CommandHelper.runSimpleGitCommand@94-2.Invoke(String message) in C:\code\fake\src\app\FakeLib\Git\CommandHelper.fs:line 94
[21:44:49][RunTests]    at Fake.Git.CommandHelper.runSimpleGitCommand(String repositoryDir, String command) in C:\code\fake\src\app\FakeLib\Git\CommandHelper.fs:line 94
[21:44:49][RunTests]    at FSI_0005.BuildIncremental.IncrementalTests.getUpdatedFiles()
[21:44:49][RunTests]    at FSI_0005.BuildIncremental.IncrementalTests.getIncrementalTestProjects2(TestMode testMode)
[21:44:49][RunTests]    at FSI_0005.Build.clo@88-7.Invoke(Unit _arg1)
[21:44:49][RunTests]    at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626
```

**Comment by heynickc** [comment]
#2837 resolves issue with branch v1.3 not being available on TeamCity build agent

**Comment by heynickc** [comment]
Incremental testing works now on Windows, but still having issues on Linux:

```
[21:01:28][docker] Searching for incremental tests to run in Unit test mode...
[21:01:28][docker] git branch
[21:01:28][docker] ﻿git merge-base --fork-point v1.3
[21:01:28][docker] ﻿git log --oneline -1
[21:01:28][docker] ﻿﻿﻿﻿﻿Running build failed.
[21:01:28][docker] Error:
[21:01:28][docker] System.Exception: git log --oneline failed: error: object directory /etc/buildAgent/system/git/git-63A8AB84.git/objects does not exist; check .git/objects/info/alternates.
[21:01:28][docker] fatal: bad object HEAD
```

**Comment by heynickc** [comment]
Resolved via a TeamCity configuration change

**Comment by imrekb** [comment]
How did you fix "bad object HEAD" via a TeamCity configuration?

**Comment by jebbench** [comment]
I found I had to turn off the "Use mirrors" advanced option under "Edit VCS settings" in TeamCity to avoid "HEAD is not an object" errors.

![image](https://user-images.githubusercontent.com/1029732/41284481-4f3747da-6e31-11e8-8d47-f6f8c22cd398.png)

**Comment by tomasz-sodzawiczny** [comment]
Leaving a comment here as this issue pops up high in Google when searching for this problem:

The issue with 
```
object directory /etc/buildAgent/system/git/git-63A8AB84.git/objects does not exist; check .git/objects/info/alternates
```
occurs when _"Use mirrors"_ option is on (default, recommended for performance) and a `git` command is run inside a docker container and doesn't have access to the `/etc/buildAgent/...` directory.

### How to fix?

Mount the logged dir`/etc/buildAgent/system/git/git-63A8AB84.git` (or any parent dir) as a volume of the docker container, e.g.:
```
-v /etc/buildAgent:/etc/buildAgent
```
The path may differ depending on your TeamCity version / configuration, make sure to mount correct directory. The path on container must match the path on agent.

### Why is it happening?

TeamCity _"Use mirrors"_ option uses git alternates mechanism.

The build directory doesn't contain the full repository checkout, but it has a `.git/objects/info/alternates` file which contains a path to full clone (in above example `/etc/buildAgent/system/git/git-63A8AB84.git`).

If the path in question is not accessible (e.g. not exposed to the docker container) the git repo is not functional.

**Comment by pmolodo** [comment]
@tomasz-sodzawiczny - Sorry to necro an old thread, but was wondering if you knew of a way to query what the `buildAgent/system` directory is instead of hardcoding it.

On your system, it was apparently at `/etc/buildAgent/system`, while on some of my runners it's `/buildAgent/system`, and on others it's `/home/ubuntu/teamcity/system`.  Is there an environment variable or similar, perhaps?
