### ISSUE TITLE
Random package restore failures

### ISSUE THREAD

**Issue by heynickc** [akkadotnet/akka.net#2864]
`dotnet restore` is failing randomly on the TeamCity server:

```
[20:36:20][RestorePackages] Target: RestorePackages
[20:36:20][RestorePackages] Starting Target: RestorePackages (==> Clean, Clean, Clean)
[20:36:20][RestorePackages] Task: DotNet.Restore 
[20:36:20][RestorePackages] dotnet "restore" "./src/Akka.sln" 
[20:36:25][RestorePackages]   Restoring packages for D:\work\edbce350daf6a08d\src\benchmark\PingPong\PingPong.csproj...
[20:36:25][RestorePackages]   Restoring packages for D:\work\edbce350daf6a08d\src\benchmark\PersistenceBenchmark\PersistenceBenchmark.csproj...
[20:36:26][RestorePackages] D:\work\edbce350daf6a08d\.dotnet\sdk\1.0.4\NuGet.targets(97,5): error : Unable to load package 'System.Threading.Timer'. [D:\work\edbce350daf6a08d\src\Akka.sln]
[20:37:38][RestorePackages] Running build failed.
[20:37:38][RestorePackages] Error:
[20:37:38][RestorePackages] System.Exception: Restore failed on "restore" "./src/Akka.sln" 
[20:37:38][RestorePackages]    at Fake.DotNetCli.Restore@146-3.Invoke(String message) in C:\code\fake\src\app\FakeLib\DotNetCLIHelper.fs:line 146
[20:37:38][RestorePackages]    at Fake.DotNetCli.Restore(FSharpFunc`2 setRestoreParams) in C:\code\fake\src\app\FakeLib\DotNetCLIHelper.fs:line 146
[20:37:38][RestorePackages]    at FSI_0005.Build.clo@49-3.Invoke(Unit _arg2) in D:\work\edbce350daf6a08d\build.fsx:line 52
[20:37:38][RestorePackages]    at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626
```
Not associated with any infrastructure changes and running the build again seems to resolve.  Possible solution is to upgrade NuGet.config to use the NuGet v3 feed instead of the v2 feed as suggested on NuGet.org: `NuGet feed v3 (VS 2015 and later / NuGet v3.x and above): https://api.nuget.org/v3/index.json`

**Comment by heynickc** [comment]
Closed by #2865
