### ISSUE TITLE
Disabled Akka.MultiNodeTestRunner.Shared.Tests/MultiNodeTestRunnerDiscovery/DiscoverySpec.cs

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#2881]
Ran into an issue with `DiscoverySpec` suddenly failing on .NET 4.5.2 with an `AppDomain` serialization exception that appears to be internal to XUnit:

```
System.InvalidCastException : Unable to cast transparent proxy to type 'Xunit.DiaSessionWrapperHelper'.
   at Akka.MultiNodeTestRunner.Shared.Tests.MultiNodeTestRunnerDiscovery.DiscoverySpec.DiscoverSpecs() in D:\work\edbce350daf6a08d\src\core\Akka.MultiNodeTestRunner.Shared.Tests\MultiNodeTestRunnerDiscovery\DiscoverySpec.cs:line 49
   at Akka.MultiNodeTestRunner.Shared.Tests.MultiNodeTestRunnerDiscovery.DiscoverySpec.No_abstract_classes() in D:\work\edbce350daf6a08d\src\core\Akka.MultiNodeTestRunner.Shared.Tests\MultiNodeTestRunnerDiscovery\DiscoverySpec.cs:line 20
```

The cause appears to be running a second `XunitFrontController` inside another XUnit session.

This is using XUnit 2.3-beta2-*

**Comment by Aaronontheweb** [comment]
Resolved by #2883
