### ISSUE TITLE
MNTR .NET Core test flakiness

### ISSUE THREAD

**Issue by heynickc** [akkadotnet/akka.net#2938]
Seeing some flakiness with MNTR specs being run by the new .NET Core version of MultiNodeTestRunner on the build server step: "Akka.NET Windows MultiNode Tests (.NET Core)".

Example tests that are failing:

```
Starting test AttemptSysMsgRedelivery
[19:11:27][Step 2/2] Akka.Remote.Tests.MultiNode.AttemptSysMsgRedeliverySpec.AttemptSysMsgRedelivery (30s)
[19:11:27]
[Akka.Remote.Tests.MultiNode.AttemptSysMsgRedeliverySpec.AttemptSysMsgRedelivery] [Test Output]
Started node 1 : first on pid 11956
Started node 2 : second on pid 12152
Started node 3 : third on pid 10060
[19:11:27][MultiNodeTestsNetCore] [INFO][8/7/2017 7:11:27 PM][Thread 0020][[akka://TestRunnerLogging/user/TcpLogger#769398449]] Node connected on [akka://TestRunnerLogging/system/IO-TCP/$a/$1#2010136783]
[19:11:28][MultiNodeTestsNetCore] [INFO][8/7/2017 7:11:27 PM][Thread 0029][[akka://TestRunnerLogging/user/TcpLogger#769398449]] Node connected on [akka://TestRunnerLogging/system/IO-TCP/$a/$2#689479577]
[19:11:28][MultiNodeTestsNetCore] [INFO][8/7/2017 7:11:27 PM][Thread 0029][[akka://TestRunnerLogging/user/TcpLogger#769398449]] Node connected on [akka://TestRunnerLogging/system/IO-TCP/$a/$3#320140629]
[19:11:47][MultiNodeTestsNetCore] [INFO][8/7/2017 7:11:46 PM][Thread 0007][[akka://TestRunnerLogging/user/TcpLogger#769398449]] Node disconnected on [akka://TestRunnerLogging/system/IO-TCP/$a/$3#320140629]
[19:11:47][MultiNodeTestsNetCore] 
[19:11:47][Akka.Remote.Tests.MultiNode.AttemptSysMsgRedeliverySpec.AttemptSysMsgRedelivery] [NODE2:second][8/7/2017]: SPEC FAILED: Akka.Remote.Tests.MultiNode.AttemptSysMsgRedeliverySpec.AttemptSysMsgRedelivery
 FAIL
[19:11:47][MultiNodeTestsNetCore] [INFO][8/7/2017 7:11:47 PM][Thread 0046][[akka://TestRunnerLogging/user/TcpLogger#769398449]] Node disconnected on [akka://TestRunnerLogging/system/IO-TCP/$a/$2#689479577]
[19:11:47][MultiNodeTestsNetCore] 
[19:11:47][Akka.Remote.Tests.MultiNode.AttemptSysMsgRedeliverySpec.AttemptSysMsgRedelivery] [NODE3:third][8/7/2017]: SPEC FAILED: Akka.Remote.Tests.MultiNode.AttemptSysMsgRedeliverySpec.AttemptSysMsgRedelivery
 FAIL
[19:11:55][Akka.Remote.Tests.MultiNode.AttemptSysMsgRedeliverySpec.AttemptSysMsgRedelivery] [NODE1:first][8/7/2017]: SPEC FAILED: Akka.Remote.Tests.MultiNode.AttemptSysMsgRedeliverySpec.AttemptSysMsgRedelivery
 FAIL
[19:11:55][MultiNodeTestsNetCore] Unknown message:   at Akka.TestKit.Xunit2.XunitAssertions.Fail(String format, Object[] args) in D:\work\edbce350daf6a08d\src\contrib\testkits\Akka.TestKit.Xunit2\XunitAssertions.cs:line 27
[19:11:55][MultiNodeTestsNetCore]    at Akka.TestKit.TestKitBase.InternalExpectMsgEnvelope[T](Nullable`1 timeout, Act
[19:11:55][Akka.Remote.Tests.MultiNode.AttemptSysMsgRedeliverySpec.AttemptSysMsgRedelivery] [NODE1:first][8/7/2017]: SPEC FAILED: StackTrace:    at Xunit.Assert.True(Nullable`1 condition, String userMessage) in C:\projects\xunit\src\xunit.assert\Asserts\BooleanAsserts.cs:line 95
[19:11:55][MultiNodeTestsNetCore] Unknown message: ion`2 assert, String hint, Boolean shouldLog) in D:\work\edbce350daf6a08d\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 238
[19:11:55][MultiNodeTestsNetCore]    at Akka.TestKit.TestKitBase.InternalExpectMsgEnvelope[T](Nullable`1 timeout, Action`1 msgAssert, Action`1 senderAssert, Strin
[19:11:55][MultiNodeTestsNetCore] Unknown message: g hint) in D:\work\edbce350daf6a08d\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 224
[19:11:55][MultiNodeTestsNetCore]    at Akka.TestKit.TestKitBase.InternalExpectMsg[T](Nullable`1 timeout, Action`1 msgAssert, String hint) in D:\work\edbce350daf6a08d\src\core\Akka.TestKit\TestKitBase
[19:11:55][MultiNodeTestsNetCore] Unknown message: _Expect.cs:line 199
[19:11:55][MultiNodeTestsNetCore]    at Akka.TestKit.TestKitBase.ExpectMsg[T](Nullable`1 duration, String hint) in D:\work\edbce350daf6a08d\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 36
[19:11:55][MultiNodeTestsNetCore]    at Akka.Remote.Tests.MultiNode.AttemptSysMsgRedeliverySpec.RedeliverSyste
[19:11:55][MultiNodeTestsNetCore] Unknown message: mMessageAfterInactivity() in D:\work\edbce350daf6a08d\src\core\Akka.Remote.Tests.MultiNode\AttemptSysMsgRedeliverySpec.cs:line 76
[19:11:55][MultiNodeTestsNetCore] 
[19:11:55][MultiNodeTestsNetCore] [INFO][8/7/2017 7:11:54 PM][Thread 0004][[akka://TestRunnerLogging/user/TcpLogger#769398449]] Node disconnected on [akka://TestRunnerLogging/system/IO-TCP/$a/$1#2010136783]
[19:11:55][MultiNodeTestsNetCore] 
[19:11:55]
[Akka.Remote.Tests.MultiNode.AttemptSysMsgRedeliverySpec.AttemptSysMsgRedelivery] [Test Output]
Waiting 3 seconds for all messages from all processes to be collected.
[19:11:58][MultiNodeTestsNetCore] Complete
```

```
[Akka.Cluster.Tools.Tests.MultiNode] Akka.Cluster.Tools.Tests.MultiNode.Singleton.ClusterSingletonManagerLeaveSpec.ClusterSingletonManagerLeaveSpecs (27s)
[19:24:09]
[Akka.Cluster.Tools.Tests.MultiNode.Singleton.ClusterSingletonManagerLeaveSpec.ClusterSingletonManagerLeaveSpecs] [Test Output]
Started node 1 : first on pid 4368
Started node 2 : second on pid 1400
Started node 3 : third on pid 3984
[19:24:10][MultiNodeTestsNetCore] [INFO][8/7/2017 7:24:10 PM][Thread 0059][[akka://TestRunnerLogging/user/TcpLogger#1602536459]] Node connected on [akka://TestRunnerLogging/system/IO-TCP/$a/$z#1636593008]
[19:24:10][MultiNodeTestsNetCore] [INFO][8/7/2017 7:24:10 PM][Thread 0059][[akka://TestRunnerLogging/user/TcpLogger#1602536459]] Node connected on [akka://TestRunnerLogging/system/IO-TCP/$a/$A#1711429103]
[19:24:10][MultiNodeTestsNetCore] [INFO][8/7/2017 7:24:10 PM][Thread 0059][[akka://TestRunnerLogging/user/TcpLogger#1602536459]] Node connected on [akka://TestRunnerLogging/system/IO-TCP/$a/$B#1469780052]
[19:24:26][MultiNodeTestsNetCore] [INFO][8/7/2017 7:24:26 PM][Thread 0058][[akka://TestRunnerLogging/user/TcpLogger#1602536459]] Node disconnected on [akka://TestRunnerLogging/system/IO-TCP/$a/$A#1711429103]
[19:24:26][MultiNodeTestsNetCore] 
[19:24:26][Akka.Cluster.Tools.Tests.MultiNode.Singleton.ClusterSingletonManagerLeaveSpec.ClusterSingletonManagerLeaveSpecs] [NODE2:second][8/7/2017]: SPEC FAILED: Akka.Cluster.Tools.Tests.MultiNode.Singleton.ClusterSingletonManagerLeaveSpec.ClusterSingletonManagerLeaveSpecs
 FAIL
[19:24:26]
[Akka.Cluster.Tools.Tests.MultiNode.Singleton.ClusterSingletonManagerLeaveSpec.ClusterSingletonManagerLeaveSpecs] [Test Output]
[NODE3:third][8/7/2017]: SPEC PASSED: Akka.Cluster.Tools.Tests.MultiNode.Singleton.ClusterSingletonManagerLeaveSpec.ClusterSingletonManagerLeaveSpecs PASS
[19:24:27][MultiNodeTestsNetCore] [INFO][8/7/2017 7:24:26 PM][Thread 0059][[akka://TestRunnerLogging/user/TcpLogger#1602536459]] Node disconnected on [akka://TestRunnerLogging/system/IO-TCP/$a/$B#1469780052]
[19:24:27][MultiNodeTestsNetCore] 
[19:24:33]
[Akka.Cluster.Tools.Tests.MultiNode.Singleton.ClusterSingletonManagerLeaveSpec.ClusterSingletonManagerLeaveSpecs] [Test Output]
[NODE1:first][8/7/2017]: SPEC PASSED: Akka.Cluster.Tools.Tests.MultiNode.Singleton.ClusterSingletonManagerLeaveSpec.ClusterSingletonManagerLeaveSpecs PASS
[19:24:33][MultiNodeTestsNetCore] [INFO][8/7/2017 7:24:33 PM][Thread 0056][[akka://TestRunnerLogging/user/TcpLogger#1602536459]] Node disconnected on [akka://TestRunnerLogging/system/IO-TCP/$a/$z#1636593008]
[19:24:33][MultiNodeTestsNetCore] 
[19:24:33]
[Akka.Cluster.Tools.Tests.MultiNode.Singleton.ClusterSingletonManagerLeaveSpec.ClusterSingletonManagerLeaveSpecs] [Test Output]
[NODE1:first][8/7/2017]: SPEC PASSED: Akka.Cluster.Tools.Tests.MultiNode.Singleton.ClusterSingletonManagerLeaveSpec passed.
[NODE3:third][8/7/2017]: SPEC PASSED: Akka.Cluster.Tools.Tests.MultiNode.Singleton.ClusterSingletonManagerLeaveSpec passed.
Waiting 3 seconds for all messages from all processes to be collected.
```

**Comment by heynickc** [comment]
`ClusterSingletonManagerLeaveSpec.ClusterSingletonManagerLeaveSpecs` seems to be more frequent than any others

**Comment by heynickc** [comment]
cc @Arkatufus if you have any thoughts

**Comment by Arkatufus** [comment]
I think this could be a timeout issue, on a passing spec, the second node received the MemberRemoved message, on a failed test, the MemberRemoved message was sent to the dead letter mailbox.
Maybe we could add a 3 seconds timeout on each ExpectMsg function call and see if this helps with the flakiness?

**Comment by Arkatufus** [comment]
made #2940 to test this out

**Comment by heynickc** [comment]
thanks @Arkatufus!
