### ISSUE TITLE
Cluster.Sharding MultiNode specs do not pass on .NET Core

### ISSUE THREAD

**Issue by heynickc** [akkadotnet/akka.net#2948]
Re #2937 "Cluster.Sharding.Tests.MultiNode targeting .NET Core" no specs are passing.  From the output:

```
Starting test ClusterSharding_specs
[RUNNER][8/9/2017 11:17:19 PM][INFO][Akka.MultiNodeTestRunner]: Starting test ClusterSharding_specs
[RUNNER][8/9/2017]: Beginning spec Akka.Cluster.Sharding.Tests.ClusterShardingSpecRecoveryAll.ClusterSharding_specs on 7 nodes
[RUNNER][8/9/2017 11:17:19 PM][INFO][Akka.MultiNodeTestRunner]: Started node 1 : controller on pid 5980
[RUNNER][8/9/2017 11:17:19 PM][INFO][Akka.MultiNodeTestRunner]: Started node 2 : first on pid 28860
[RUNNER][8/9/2017 11:17:19 PM][INFO][Akka.MultiNodeTestRunner]: Started node 3 : second on pid 24396
[RUNNER][8/9/2017 11:17:19 PM][INFO][Akka.MultiNodeTestRunner]: Started node 4 : third on pid 20676
[RUNNER][8/9/2017 11:17:19 PM][INFO][Akka.MultiNodeTestRunner]: Started node 5 : fourth on pid 30840
[RUNNER][8/9/2017 11:17:19 PM][INFO][Akka.MultiNodeTestRunner]: Started node 6 : fifth on pid 28724
[RUNNER][8/9/2017 11:17:19 PM][INFO][Akka.MultiNodeTestRunner]: Started node 7 : sixth on pid 1668
[INFO][8/9/2017 11:17:20 PM][Thread 0003][[akka://TestRunnerLogging/user/TcpLogger#690705933]] Node connected on [akka://TestRunnerLogging/system/IO-TCP/$a/$a#1649302420]
[INFO][8/9/2017 11:17:20 PM][Thread 0003][[akka://TestRunnerLogging/user/TcpLogger#690705933]] Node connected on [akka://TestRunnerLogging/system/IO-TCP/$a/$b#623543386]
[INFO][8/9/2017 11:17:20 PM][Thread 0003][[akka://TestRunnerLogging/user/TcpLogger#690705933]] Node connected on [akka://TestRunnerLogging/system/IO-TCP/$a/$c#1136163732]
[INFO][8/9/2017 11:17:20 PM][Thread 0003][[akka://TestRunnerLogging/user/TcpLogger#690705933]] Node connected on [akka://TestRunnerLogging/system/IO-TCP/$a/$d#392924570]
[INFO][8/9/2017 11:17:20 PM][Thread 0009][[akka://TestRunnerLogging/user/TcpLogger#690705933]] Node connected on [akka://TestRunnerLogging/system/IO-TCP/$a/$e#576096355]
[INFO][8/9/2017 11:17:20 PM][Thread 0009][[akka://TestRunnerLogging/user/TcpLogger#690705933]] Node connected on [akka://TestRunnerLogging/system/IO-TCP/$a/$f#99260668]
[INFO][8/9/2017 11:17:20 PM][Thread 0009][[akka://TestRunnerLogging/user/TcpLogger#690705933]] Node connected on [akka://TestRunnerLogging/system/IO-TCP/$a/$g#8578484]
Unknown message: e.RecoverySuccess, but received {ReplayMessagesFailure<cause: System.TimeoutException: The operation has timed out.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAnd
 FAIL2:first][8/9/2017]: SPEC FAILED: Akka.Cluster.Sharding.Tests.ClusterShardingSpecRecoveryAll.ClusterSharding_specs
[INFO][8/9/2017 11:17:37 PM][Thread 0008][[akka://TestRunnerLogging/user/TcpLogger#690705933]] Node disconnected on [akka://TestRunnerLogging/system/IO-TCP/$a/$e#576096355]

[INFO][8/9/2017 11:17:37 PM][Thread 0014][[akka://TestRunnerLogging/user/TcpLogger#690705933]] Node disconnected on [akka://TestRunnerLogging/system/IO-TCP/$a/$f#99260668]

 FAIL1:controller][8/9/2017]: SPEC FAILED: Akka.Cluster.Sharding.Tests.ClusterShardingSpecRecoveryAll.ClusterSharding_specs
[NODE1:controller][8/9/2017]: SPEC FAILED: Type: System.Threading.Tasks.TaskCanceledException
[NODE1:controller][8/9/2017]: SPEC FAILED: Message: One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (A task was canceled.))) (One or more errors occur
ed. (A task was canceled.))
[NODE1:controller][8/9/2017]: SPEC FAILED: Message: One or more errors occurred. (One or more errors occurred. (A task was canceled.))
[NODE1:controller][8/9/2017]: SPEC FAILED: Message: One or more errors occurred. (A task was canceled.)
[NODE1:controller][8/9/2017]: SPEC FAILED: StackTrace:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
Unknown message: nToken)
   at Akka.Cluster.Sharding.Tests.ClusterShardingSpec.<ClusterSharding_should_failover_shards_on_crashed_node>b__21_3() in C:\Users\nickc\Documents\Projects\akka.net\src\contrib\cluster\Akka.
luster.Sharding.Tests.MultiNode\ClusterShardingSpec.cs:
Unknown message: line 623
   at Akka.Remote.TestKit.MultiNodeSpec.RunOn(Action thunk, RoleName[] nodes) in C:\Users\nickc\Documents\Projects\akka.net\src\core\Akka.Remote.TestKit\MultiNodeSpec.cs:line 507
   at Akka.Cluster.Sharding.Tests.ClusterShardingSpec.<ClusterShar
Unknown message: ding_should_failover_shards_on_crashed_node>b__21_0() in C:\Users\nickc\Documents\Projects\akka.net\src\contrib\cluster\Akka.Cluster.Sharding.Tests.MultiNode\ClusterShardingS
ec.cs:line 624
   at Akka.TestKit.TestKitBase.<>c__DisplayClass139_0.<Within>b__
Unknown message: 0() in C:\Users\nickc\Documents\Projects\akka.net\src\core\Akka.TestKit\TestKitBase_Within.cs:line 48
   at Akka.TestKit.TestKitBase.Within[T](TimeSpan min, TimeSpan max, Func`1 function, String hint, Nullable`1 epsilonValue) in C:\Users\nickc\Documents\P
Unknown message: rojects\akka.net\src\core\Akka.TestKit\TestKitBase_Within.cs:line 101
   at Akka.TestKit.TestKitBase.Within(TimeSpan min, TimeSpan max, Action action, String hint, Nullable`1 epsilonValue) in C:\Users\nickc\Documents\Projects\akka.net\src\core\Akka.TestKi
Unknown message: t\TestKitBase_Within.cs:line 48
   at Akka.TestKit.TestKitBase.Within(TimeSpan max, Action action, Nullable`1 epsilonValue) in C:\Users\nickc\Documents\Projects\akka.net\src\core\Akka.TestKit\TestKitBase_Within.cs:line 31
   at Akka.Cluster.Sharding.Test
Unknown message: s.ClusterShardingSpec.ClusterSharding_should_failover_shards_on_crashed_node() in C:\Users\nickc\Documents\Projects\akka.net\src\contrib\cluster\Akka.Cluster.Sharding.Tests.M
ltiNode\ClusterShardingSpec.cs:line 654
   at Akka.Cluster.Sharding.Tests.Cluste
Unknown message: ask.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Akka.Remote.TestKit.TestConductor.<>c.<Exit>b__10_0(Task`1 t) in C:\Users\nickc\Documents\Projects\a
[NODE1:controller][8/9/2017]: SPEC FAILED: StackTrace:    at System.Threading.Tasks.T
[NODE1:controller][8/9/2017]: SPEC FAILED: StackTrace:
Unknown message: roller][FAIL-EXCEPTION] StackTrace:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Akka.Remote.TestKit.MultiNodeSpec.
Unknown message: <MultiNodeSpecAfterAll>b__39_1() in C:\Users\nickc\Documents\Projects\akka.net\src\core\Akka.Remote.TestKit\MultiNodeSpec.cs:line 439
   at Akka.TestKit.TestKitBase.InternalAwaitCondition(Func`1 conditionIsFulfilled, TimeSpan max, Nullable`1 interval, Act
Unknown message: ion`2 fail, ILoggingAdapter logger) in C:\Users\nickc\Documents\Projects\akka.net\src\core\Akka.TestKit\TestKitBase_AwaitConditions.cs:line 220
   at Akka.TestKit.TestKitBase.AwaitCondition(Func`1 conditionIsFulfilled) in C:\Users\nickc\Documents\Projects
Unknown message: \akka.net\src\core\Akka.TestKit\TestKitBase_AwaitConditions.cs:line 38
   at Akka.Remote.TestKit.MultiNodeSpec.<MultiNodeSpecAfterAll>b__39_0() in C:\Users\nickc\Documents\Projects\akka.net\src\core\Akka.Remote.TestKit\MultiNodeSpec.cs:line 439
   at Akk
Unknown message: a.TestKit.TestKitBase.<>c__DisplayClass139_0.<Within>b__0() in C:\Users\nickc\Documents\Projects\akka.net\src\core\Akka.TestKit\TestKitBase_Within.cs:line 48
   at Akka.TestKit.TestKitBase.Within[T](TimeSpan min, TimeSpan max, Func`1 function, String hint
Unknown message: , Nullable`1 epsilonValue) in C:\Users\nickc\Documents\Projects\akka.net\src\core\Akka.TestKit\TestKitBase_Within.cs:line 101
   at Akka.TestKit.TestKitBase.Within(TimeSpan min, TimeSpan max, Action action, String hint, Nullable`1 epsilonValue) in C:\User
Unknown message: s\nickc\Documents\Projects\akka.net\src\core\Akka.TestKit\TestKitBase_Within.cs:line 48
   at Akka.TestKit.TestKitBase.Within(TimeSpan max, Action action, Nullable`1 epsilonValue) in C:\Users\nickc\Documents\Projects\akka.net\src\core\Akka.TestKit\TestKit
Unknown message: Base_Within.cs:line 31
   at Akka.Remote.TestKit.MultiNodeSpec.MultiNodeSpecAfterAll() in C:\Users\nickc\Documents\Projects\akka.net\src\core\Akka.Remote.TestKit\MultiNodeSpec.cs:line 438
   at Akka.Remote.TestKit.MultiNodeSpec.Dispose(Boolean disposing)
Unknown message:  in C:\Users\nickc\Documents\Projects\akka.net\src\core\Akka.Remote.TestKit\MultiNodeSpec.cs:line 681
   at Akka.Remote.TestKit.MultiNodeSpec.Dispose() in C:\Users\nickc\Documents\Projects\akka.net\src\core\Akka.Remote.TestKit\MultiNodeSpec.cs:line 657

Unknown message:   at Xunit.Sdk.ExecutionTimer.Aggregate(Action action) in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 31
   at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, Execution
Unknown message: Timer timer, CancellationTokenSource cancellationTokenSource) in C:\projects\xunit\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs:line 76
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass47_0.<RunAsync>b__1() in C:\projects\xunit\src\xuni
[NODE1:controller][8/9/2017]: SPEC FAILED: StackTrace:
[INFO][8/9/2017 11:17:47 PM][Thread 0034][[akka://TestRunnerLogging/user/TcpLogger#690705933]] Node disconnected on [akka://TestRunnerLogging/system/IO-TCP/$a/$d#392924570]

 FAIL7:sixth][8/9/2017]: SPEC FAILED: Akka.Cluster.Sharding.Tests.ClusterShardingSpecRecoveryAll.ClusterSharding_specs
[NODE7:sixth][8/9/2017]: SPEC FAILED: StackTrace:    at Akka.Remote.TestKit.TestConductor.Enter(TimeSpan timeout, ImmutableList`1 names) in C:\Users\nickc\Documents\Projects\akka.net\src\core
Akka.Remote.TestKit\Player.cs:line 144
Unknown message: MultiNodeSpec.EnterBarrier(String[] name) in C:\Users\nickc\Documents\Projects\akka.net\src\core\Akka.Remote.TestKit\MultiNodeSpec.cs:line 524
   at Akka.TestKit.TestKitBase.<>c__DisplayClass139_0.<Within>b__0() in C:\Users\nickc\Documents\Projects\akka.n
Unknown message: et\src\core\Akka.TestKit\TestKitBase_Within.cs:line 48
   at Akka.TestKit.TestKitBase.Within[T](TimeSpan min, TimeSpan max, Func`1 function, String hint, Nullable`1 epsilonValue) in C:\Users\nickc\Documents\Projects\akka.net\src\core\Akka.TestKit
TestKitB
Unknown message: ase_Within.cs:line 101
   at Akka.TestKit.TestKitBase.Within(TimeSpan min, TimeSpan max, Action action, String hint, Nullable`1 epsilonValue) in C:\Users\nickc\Documents\Projects\akka.net\src\core\Akka.TestKit\Test
itBase_Within.cs:line 48
   at Akka.Tes
Unknown message: tKit.TestKitBase.Within(TimeSpan max, Action action, Nullable`1 epsilonValue) in C:\Users\nickc\Documents\Projects\akka.net\src\core\Akka.TestKit\TestKitBase_Within.cs:line 3
   at Akka.Cluster.Sharding.Tests.ClusterShardingSpec.ClusterSharding_should_su
Unknown message: pport_proxy_only_mode() in C:\Users\nickc\Documents\Projects\akka.net\src\contrib\cluster\Akka.Cluster.Sharding.Tests.MultiNode\ClusterShardingSpec.cs:line 609
   at Akka.Cluster.Sharding.Tests.ClusterShardingSpec.ClusterSharding_specs() in C:\Users\nickc
Unknown message: \Documents\Projects\akka.net\src\contrib\cluster\Akka.Cluster.Sharding.Tests.MultiNode\ClusterShardingSpec.cs:line 432

[INFO][8/9/2017 11:17:52 PM][Thread 0026][[akka://TestRunnerLogging/user/TcpLogger#690705933]] Node disconnected on [akka://TestRunnerLogging/system/IO-TCP/$a/$g#8578484]

 FAIL4:third][8/9/2017]: SPEC FAILED: Akka.Cluster.Sharding.Tests.ClusterShardingSpecRecoveryAll.ClusterSharding_specs
Unknown message: it.MultiNodeSpec.EnterBarrier(String[] name) in C:\Users\nickc\Documents\Projects\akka.net\src\core\Akka.Remote.TestKit\MultiNodeSpec.cs:line 524
   at Akka.Cluster.Sharding.Tests.ClusterShardingSpec.<ClusterSharding_should_failover_shards_on_crashed_node
[NODE4:third][8/9/2017]: SPEC FAILED: StackTrace:    at Akka.Remote.TestKit.TestConductor.Enter(TimeSpan timeout, ImmutableList`1 names) in C:\Users\nickc\Documents\Projects\akka.net\src\core
Akka.Remote.TestKit\Player.cs:line 144
Unknown message: >b__21_0() in C:\Users\nickc\Documents\Projects\akka.net\src\contrib\cluster\Akka.Cluster.Sharding.Tests.MultiNode\ClusterShardingSpec.cs:line 620
   at Akka.TestKit.TestKitBase.<>c__DisplayClass139_0.<Within>b__0() in C:\Users\nickc\Documents\Projects\ak
Unknown message: ka.net\src\core\Akka.TestKit\TestKitBase_Within.cs:line 48
   at Akka.TestKit.TestKitBase.Within[T](TimeSpan min, TimeSpan max, Func`1 function, String hint, Nullable`1 epsilonValue) in C:\Users\nickc\Documents\Projects\akka.net\src\core\Akka.TestKit
Test
Unknown message: KitBase_Within.cs:line 101
   at Akka.TestKit.TestKitBase.Within(TimeSpan min, TimeSpan max, Action action, String hint, Nullable`1 epsilonValue) in C:\Users\nickc\Documents\Projects\akka.net\src\core\Akka.TestKit\Test
itBase_Within.cs:line 48
   at Akka
 FAIL5:fourth][8/9/2017]: SPEC FAILED: Akka.Cluster.Sharding.Tests.ClusterShardingSpecRecoveryAll.ClusterSharding_specs
```

**Comment by heynickc** [comment]
```
Cause: System.Runtime.Serialization.SerializationException: Serializer not found for type ReplayMessages
   at Akka.Serialization.Serialization.FindSerializerForType(Type objectType) in C:\Users\nickc\Documents\Projects\akka.net\src\core\Akka\Serialization\Serialization.cs:line 255
   at Akka.Remote.MessageSerializer.Serialize(ActorSystem system, Address address, Object message) in C:\Users\nickc\Documents\Projects\akka.net\src\core\Akka.Remote\MessageSerializer.cs:line 46
   at Akka.Remote.EndpointWriter.SerializeMessage(Object msg) in C:\Users\nickc\Documents\Projects\akka.net\src\core\Akka.Remote\Endpoint.cs:line 1327
   at Akka.Remote.EndpointWriter.WriteSend(Send send) in C:\Users\nickc\Documents\Projects\akka.net\src\core\Akka.Remote\Endpoint.cs:line 1438
```

**Comment by heynickc** [comment]
```
Running specs for Akka.Cluster.Sharding.Tests.MultiNode.dll [C:\Users\nickc\Documents\Projects\akka.net\src\contrib\cluster\Akka.Cluster.Sharding.Tests.MultiNode\bin\Release\netcoreapp1.1\Akka.Cluster.Sharding.Tests.MultiNode.dll]
[WARNING][8/9/2017 11:17:30 PM][Thread 0018][ActorSystem(ClusterShardingSpec)] The type name for serializer 'hyperion' did not resolve to an actual Type: 'Akka.Serialization.HyperionSerializer, Akka.Serialization.Hyperion'
[WARNING][8/9/2017 11:17:30 PM][Thread 0018][ActorSystem(ClusterShardingSpec)] Serialization binding to non existing serializer: 'hyperion'
```
