### ISSUE TITLE
Could not load type 'Nessos.FsPickler.BinarySerializer' from assembly 'FsPickler, Version=3.3.0.0

### ISSUE THREAD

**Issue by vasily-kirichenko** [akkadotnet/akka.net#2977]
```fsharp
#r "../../packages/freshfspickler/FsPickler/lib/net45/FsPickler.dll"
#r "../../packages/Akka/lib/net45/Akka.dll"
#r "../../packages/Akka.FSharp/lib/net45/Akka.FSharp.dll"

open Akka.Actor
open Akka.Configuration
open Akka.FSharp

let system = System.create "system" (Configuration.defaultConfig())
```

```
--> Referenced '../../packages/freshfspickler/FsPickler/lib/net45/FsPickler.dll'
--> Referenced '../../packages/Akka/lib/net45/Akka.dll'
--> Referenced ../../packages/Akka.FSharp/lib/net45/Akka.FSharp.dll'

Binding session to '../../packages/Akka/lib/net45/Akka.dll'...
Binding session to '../../packages/freshfspickler/FsPickler/lib/net45/FsPickler.dll'...
[WARNING][14-Aug-17 10:24:53][Thread 0001][ActorSystem(system)] NewtonSoftJsonSerializer has been detected as a default serializer. It will be obsoleted in Akka.NET starting from version 1.5 in the favor of Hyperion (for more info visit: http://getakka.net/docs/Serialization#how-to-setup-hyperion-as-default-serializer ). If you want to suppress this message set HOCON `akka.suppress-json-serializer-warning` config flag to on.
> System.TypeLoadException: Could not load type 'Nessos.FsPickler.BinarySerializer' from assembly 'FsPickler, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null'.
   at Akka.FSharp.Serialization.ExprSerializer..ctor(ExtendedActorSystem system)
   at Akka.FSharp.Serialization.exprSerializationSupport(ActorSystem system)
   at Akka.FSharp.System.create(String name, Config config)
   at <StartupCode$FSI_0005>.$FSI_0005.main@() in Script1.fsx:line 10
Stopped due to error
```

**Comment by Horusiath** [comment]
It looks like there's a mismatch between **FsPickler** version referenced in your project and the one expected by akka. You may need to download the 3.3 version explicitly.

**Comment by vasily-kirichenko** [comment]
I added a special paket group just to get the fresh FsPickler, it's definitely 3.3.0.0:

![image](https://user-images.githubusercontent.com/873919/29268831-47139b62-80f7-11e7-8fc0-84c49426f217.png)

**Comment by vasily-kirichenko** [comment]
Just tried 3.2.0.0 - the same error.

**Comment by alexvaluyskiy** [comment]
@vasily-kirichenko Which version of Akka and Akka.FSharp do you use?

**Comment by vasily-kirichenko** [comment]
```
Akka (1.3)
      Newtonsoft.Json (>= 9.0.1)
      System.Collections.Immutable (>= 1.3.1)
Akka.FSharp (1.2)
      Akka (>= 1.2)
      FsPickler (>= 1.2.21)
      FSPowerPack.Core.Community (>= 3.0)
      FSPowerPack.Linq.Community (>= 3.0)
```

**Comment by vasily-kirichenko** [comment]
Maybe it wants FsPickler 1.2?

**Comment by alexvaluyskiy** [comment]
Try Akka.Fsharp 1.2.3

**Comment by vasily-kirichenko** [comment]
FsPickler was pinned to 3.1 in paket.dependencies, hence the error. Solved. Thanks, guys!
