### ISSUE TITLE
Akka.Persistence does not work if actor state is represented with F# types

### ISSUE THREAD

**Issue by vasily-kirichenko** [akkadotnet/akka.net#3007]
(literally translated from http://getakka.net/articles/persistence/event-sourcing.html)

```fsharp
#r @"..\packages\Newtonsoft.Json.9.0.1\lib\net45\Newtonsoft.Json.dll"
#r @"..\packages\Akka.1.3.0\lib\net45\Akka.dll"
#r @"..\packages\Akka.Persistence.1.3.0\lib\net45\Akka.Persistence.dll"

open Akka.Actor
open Akka.Routing
open Akka.Event
open Akka.Persistence
open System

type Cmd = { Data: string }
type Evt = { Data: string }

type ExampleState =
    { Events: string list }
    member this.Updated (evt: Evt) = { this with Events = evt.Data :: this.Events }
    member this.Size = this.Events.Length

type PersistentActor() =
    inherit UntypedPersistentActor()

    let context = PersistentActor.Context
    let mutable state = { Events = [] }
    let updateState (evt: Evt) = state <- state.Updated evt
    let numEvents() = state.Size

    override __.OnRecover (message: obj) =
        match message with
        | :? Evt as evt ->
            updateState evt
        | :? SnapshotOffer as snapshot when (snapshot.Snapshot :? ExampleState) ->
            state <- snapshot.Snapshot :?> ExampleState
        | _ -> ()

    override this.OnCommand (message: obj) =
        match message with
        | :? Cmd as cmd ->
            this.Persist({ Evt.Data = sprintf "%s-%d" cmd.Data (numEvents()) }, Action<_> updateState)
            this.Persist(
                { Evt.Data = sprintf "%s-%d" cmd.Data (numEvents() + 1) },
                fun evt ->
                    updateState evt
                    context.System.EventStream.Publish evt
                )
        | :? string as s when s = "snap" ->
            this.SaveSnapshot state
        | :? string as s when s = "print" ->
            printfn "%A" (List.rev state.Events)
        | _ -> ()

    override __.PersistenceId = "sample-id-1"

let system = ActorSystem.Create "system"
let a = system.ActorOf(Props.Create<PersistentActor>())
a.Tell { Cmd.Data = "foo" }
a.Tell "print"
```
1. Execute the above script in FSI
2. Restart FSI
3. Execute the script again.
4. Result:
```
[ERROR][18-Aug-17 12:54:33][Thread 0006][[akka://system/user/$a#1466814050]] Persistence failure when replaying events for persistenceId [sample-id-1]. Last known sequence number [0]
Cause: Newtonsoft.Json.JsonSerializationException: Error resolving type specified in JSON 'FSI_0014+ExampleState, FSI-ASSEMBLY'. Path 'Data.$type', line 1, position 142. ---> Newtonsoft.Json.JsonSerializationException: Could not find type 'FSI_0014+ExampleState' in assembly 'FSI-ASSEMBLY, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeFromTypeNameKey(TypeNameKey typeNameKey)
   at Newtonsoft.Json.Utilities.ThreadSafeStore`2.AddValue(TKey key)
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.BindToType(String assemblyName, String typeName)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, String qualifiedTypeName)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, String qualifiedTypeName)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object& newValue, String& id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Akka.Serialization.NewtonSoftJsonSerializer.SurrogateConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Akka.Serialization.NewtonSoftJsonSerializer.FromBinary(Byte[] bytes, Type type)
   at Akka.Persistence.Snapshot.LocalSnapshotStore.Deserialize(Stream stream)
   at Akka.Persistence.Snapshot.LocalSnapshotStore.<>c__DisplayClass15_0.<Load>b__0(Stream stream)
   at Akka.Persistence.Snapshot.LocalSnapshotStore.WithStream[T](Stream stream, Func`2 p)
   at Akka.Persistence.Snapshot.LocalSnapshotStore.Load(ImmutableArray`1 metadata)
   at Akka.Persistence.Snapshot.LocalSnapshotStore.<>c__DisplayClass28_0`1.<RunWithStreamDispatcher>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Util.Internal.AtomicState.<CallThrough>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Akka.Util.Internal.AtomicState.<CallThrough>d__7`1.MoveNext()
```

**Comment by Horusiath** [comment]
This looks more like an issue of the serializer itself - specifically a Newtonsoft.Json not being able to discover types from dynamic assemblies (like the ones produced by the FSI).

**Comment by vasily-kirichenko** [comment]
I see. Thanks.
