### ISSUE TITLE
ClusterSharding.Get(ActorSystem system) fails with TestKit ActorSystem

### ISSUE THREAD

**Issue by goodisontoffee** [akkadotnet/akka.net#3051]
.net framework v4.6.1
Akka.Net v1.3.0
Akka.Cluster.Sharding v1.3.0-beta50
Akka.TestKit v1.3.0

Executing on Windows

TestKit is being created with this HOCON - via constructor on TestKit that accepts a Config object.

akka {
  loglevel = INFO
  actor {
    serialize-creators = off
    serialize-messages = on
    serializers {
      hyperion = "Akka.Serialization.HyperionSerializer, Akka.Serialization.Hyperion"
    }
    serialization-bindings {
      "System.Object" = hyperion
    }
    serialization-settings {
      hyperion {
        version-tolerance = true
      }
    }
  }
  persistence {
    snapshot-store {
      plugin = "akka.persistence.no-snapshot-store"
    }
  }
}

When the call to ClusterSharding.Get(ActorSystem system) is performed a NullReferenceException is thrown with the following call stack.

System.NullReferenceException : Object reference not set to an instance of an object.
   at Akka.Cluster.ClusterSettings..ctor(Config config, String systemName)
   at Akka.Cluster.Cluster..ctor(ActorSystemImpl system)
   at Akka.Cluster.ClusterExtension.CreateExtension(ExtendedActorSystem system)
   at Akka.Actor.ExtensionIdProvider`1.Akka.Actor.IExtensionId.CreateExtension(ExtendedActorSystem system)
   at Akka.Actor.Internal.ActorSystemImpl.<>c__DisplayClass56_0.<RegisterExtension>b__1()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Akka.Actor.Internal.ActorSystemImpl.TryGetExtension(Type extensionType, Object& extension)
   at Akka.Actor.Internal.ActorSystemImpl.GetExtension(IExtensionId extensionId)
   at Akka.Actor.ExtensionIdProvider`1.Get(ActorSystem system)
   at Akka.Actor.ExtensionIdProvider`1.Akka.Actor.IExtensionId.Get(ActorSystem system)
   at Akka.Actor.Internal.ActorSystemImpl.RegisterExtension(IExtensionId extension)
   at Akka.Actor.ActorSystemWithExtensions.WithExtension[T,TI](ActorSystem system)
   at Akka.Cluster.Sharding.ClusterSharding..ctor(ExtendedActorSystem system)
   at Akka.Cluster.Sharding.ClusterShardingExtensionProvider.CreateExtension(ExtendedActorSystem system)
   at Akka.Actor.ExtensionIdProvider`1.Akka.Actor.IExtensionId.CreateExtension(ExtendedActorSystem system)
   at Akka.Actor.Internal.ActorSystemImpl.<>c__DisplayClass56_0.<RegisterExtension>b__1()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Akka.Actor.Internal.ActorSystemImpl.TryGetExtension(Type extensionType, Object& extension)
   at Akka.Actor.Internal.ActorSystemImpl.GetExtension(IExtensionId extensionId)
   at Akka.Actor.ExtensionIdProvider`1.Get(ActorSystem system)
   at Akka.Actor.ExtensionIdProvider`1.Akka.Actor.IExtensionId.Get(ActorSystem system)
   at Akka.Actor.Internal.ActorSystemImpl.RegisterExtension(IExtensionId extension)
   at Akka.Actor.ActorSystemWithExtensions.WithExtension[T,TI](ActorSystem system)
   at Akka.Cluster.Sharding.ClusterSharding.Get(ActorSystem system)

**Comment by Horusiath** [comment]
Have you used `ClusterSharding.DefaultConfig()` as a configuration fallback?

**Comment by goodisontoffee** [comment]
I just tried it, and receive the same issue, but thanks for the suggestion.

**Comment by goodisontoffee** [comment]
I've removed the fallback and updated my config to use the cluster actor ref provider and this seems to have cleaned up a lot of the issues.

    provider = "Akka.Cluster.ClusterActorRefProvider, Akka.Cluster"

A nicer error message might be handy but it's a step forward.
