### ISSUE TITLE
Hyperion serializer is incompatable with "serialize-creators" option for XUnit2 TestKit

### ISSUE THREAD

**Issue by andreyleskov** [akkadotnet/akka.net#3065]
Hi all, 
 I'm trying to improve my tests by enabling serialize-creators options in Debug mode. 
 But it seems Hyperion serializer cases an error on Xunit2.TestKit creation. 
 Platform:  Net 4.6.1
 packages: { 
 akka : 1.3.0
 akka.testkit : 1.1.3
 akka.testKit.xunit2: 1.1.3
}
Can be reproduced by [gist code](https://gist.github.com/andreyleskov/6e2decce26e6e2b95864c122422a4dca)

**Comment by Aaronontheweb** [comment]
Want to give it a try with newer versions of the TestKit? And what error message do you get back?

**Comment by andreyleskov** [comment]
Sorry for missing error, here it is: 
`Hyperion.ValueSerializers.UnsupportedTypeException
Ambiguous match found.
   at Hyperion.ValueSerializers.UnsupportedTypeSerializer.WriteManifest(Stream stream, SerializerSession session)
   at Hyperion.Extensions.StreamEx.WriteObject(Stream stream, Object value, Type valueType, ValueSerializer valueSerializer, Boolean preserveObjectReferences, SerializerSession session)
   at lambda_method(Closure , Stream , Object , SerializerSession )
   at Akka.Serialization.HyperionSerializer.ToBinary(Object obj)
   at Akka.Actor.ActorCell.MakeChild(Props props, String name, Boolean async, Boolean systemService)
   at Akka.Actor.ActorCell.AttachChild(Props props, Boolean isSystemService, String name)
   at Akka.TestKit.TestKitBase.InitializeTest(ActorSystem system, Config config, String actorSystemName, String testActorName)
   at Akka.TestKit.Xunit2.TestKit..ctor(String config, ITestOutputHelper output)
   at GridDomain.Tests.Unit.DependencyInjection.HyperionTest2..ctor() in HyperionTest.cs:line 23
`

**Comment by andreyleskov** [comment]
It seems working ok with "Akka.TestKit.Xunit2" version="1.3.0-beta420" 
Thank you for suggestion )
