### ISSUE TITLE
System.Net.Sockets.SocketException during coordinated shutdown CLR termination hook

### ISSUE THREAD

**Issue by gengle** [akkadotnet/akka.net#3208]
I sporadically receive the following exception when node (role=client) disconnects from cluster.

`[08:45:33` INF] Starting coordinated shutdown from CLR termination hook.
[08:45:33 INF] Shutting down remote daemon.
[08:45:33 INF] Remote daemon shut down; proceeding with flushing remote transports.
[08:45:33 ERR] Error caught channel [[::ffff:10.29.37.77]:7999->[::ffff:10.29.37.77]:8007](Id=4d86546a)
System.Net.Sockets.SocketException (0x80004005): An established connection was aborted by the software in your host machine
   at DotNetty.Transport.Channels.Sockets.TcpSocketChannel.DoReadBytes(IByteBuffer byteBuf)
   at DotNetty.Transport.Channels.Sockets.AbstractSocketByteChannel.SocketByteChannelUnsafe.FinishRead(SocketChannelAsyncOperation operation)
[08:45:33 INF] Remoting shut down.
`

The following packages are used on net461
`
<PackageReference Include="Akka" Version="1.3.1" />
<PackageReference Include="Akka.Cluster" Version="1.3.1" />
<PackageReference Include="Akka.DI.AutoFac" Version="1.3.0" />
<PackageReference Include="Akka.Logger.Serilog" Version="1.3.0" />
<PackageReference Include="Akka.Remote" Version="1.3.1" />
<PackageReference Include="Akka.Serialization.Hyperion" Version="1.3.1-beta52" />
`

This error occurs randomly but I have noticed the frequency increase when spawn multiple instances node are spawned on the same machine (with same IP and dynamic port#)

I'll update this issue once I've isolated a consistent pattern we can reproduce.

**Comment by Aaronontheweb** [comment]
@gengle not sure if this is worth fixing, but it appears to be an issue when we terminate DotNetty and a particular connection doesn't get a chance to shut down before the timeout threshold and we abort it (we force the shutdown to occur one way or another.) We can look into it but it's usually harmless.

**Comment by maxcherednik** [comment]
the shutdown is not graceful then :) (the fan of clear log here)

**Comment by gengle** [comment]
@Aaronontheweb thanks for the feedback.  In this situation, the node is a client tool which quickly connects and disconnects from the cluster.  Maybe I should consider using ClusterClient instead in this situation.

**Comment by maxcherednik** [comment]
hey @Aaronontheweb, shall I have a look the remoting part for a graceful shutdown?
