### ISSUE TITLE
It's impossible to process a stream of F# `Option`s with Akka Streams

### ISSUE THREAD

**Issue by vasily-kirichenko** [akkadotnet/akka.net#3223]
```fsharp
    use system = ActorSystem.Create("test")
    let mat = system.Materializer()
    
    let xs =
        [ Some 1; Some 2; None
          Some 3; Some 4; None
          Some 5; None ]
    
    Source.From(xs)
        .SplitAfter(fun x -> x.IsNone)
        .Where(fun x -> x.IsSome)
        .Aggregate([], fun r x -> x.Value :: r)
        .To(Sink.ForEach(fun x -> printfn "%A" x))
        .Run(mat)
        |> ignore
```
```
[ERROR][22-Dec-17 19:53:25][Thread 0005][[akka://test/user/StreamSupervisor-0/Flow-0-0-unknown-operation#865289471]] Error in stage [StatefulSelectMany]: Element must not be null, rule 2.13
Parameter name: element
Cause: System.ArgumentNullException: Element must not be null, rule 2.13
Parameter name: element
   at Akka.Streams.Stage.GraphStageLogic.Push[T](Outlet outlet, T element)
   at Akka.Streams.Implementation.Fusing.StatefulSelectMany`2.Logic.PushPull()
   at Akka.Streams.Implementation.Fusing.GraphInterpreter.ProcessEvent(Connection connection)
   at Akka.Streams.Implementation.Fusing.GraphInterpreter.Execute(Int32 eventLimit)
```
That's because `Option.None` is represented as `null` at runtime.

**Comment by Aaronontheweb** [comment]
cc @Horusiath

**Comment by marcpiechura** [comment]
@vasily-kirichenko as the error messages says null elements are not allowed since they violate rule 2.13 of the RS spec, see also https://github.com/reactive-streams/reactive-streams-jvm/issues/204

**Comment by Horusiath** [comment]
F# compiler optimizes `None` cases as nulls, which stands against Reactive Streams specification. There's not much we can do here.

**Comment by vasily-kirichenko** [comment]
Thanks.
