### ISSUE TITLE
Marking node(s) as UNREACHABLE

### ISSUE THREAD

**Issue by gengle** [akkadotnet/akka.net#3228]
### Version
- 1.3.1
- build: net461, net45

## Environment
- Production
- Single server, Windows Server 2018
- node; lighthouse always connected at port 4053
- node; engine always connected at random port
- node; client which connects when needed at random port

# Scenario
Other than normal gossip message, everything looks good 

`2017-12-27 00:15:50.878 -05:00 DBG [6340:****HOST\****ACCT] Cluster Node ["akka.tcp://..:59643"] - Receiving gossip from ["UniqueAddress: (akka.tcp://...:4053, 1805878683)"]`

6 hours later, I receive an address gated message
```
 2017-12-27 06:10:35.057 -05:00 WRN [6340:****HOST\****ACCT] Association with remote system "akka.tcp://****@****host:4053" has failed; address is now gated for 5000 ms. Reason is: ["Akka.Remote.EndpointDisassociatedException: Disassociated
    at Akka.Remote.EndpointWriter.PublishAndThrow(Exception reason, LogLevel level, Boolean needToThrow)
    at Akka.Actor.ReceiveActor.ExecutePartialMessageHandler(Object message, PartialAction`1 partialAction)
    at Akka.Actor.ActorCell.<>c__DisplayClass106_0.<Akka.Actor.IUntypedActorContext.Become>b__0(Object m)
    at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
    at Akka.Actor.ActorCell.ReceiveMessage(Object message)
    at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
    at Akka.Actor.ActorCell.Invoke(Envelope envelope)
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at Akka.Actor.ActorCell.HandleFailed(Failed f)
    at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState)"]
```

I then get these errors flooding the log file

```
2017-12-27 06:10:46.576 -05:00 INF [6340:****HOST\****ACCT] Leader can currently not perform its duties, reachability status: ["Reachability([akka.tcp://****@****host:59643 -> UniqueAddress: (akka.tcp://****@****host:4053, 1805878683): Unreachable [Unreachable] (18)])"], member status: ["$akka.tcp://****@****host:4053 $Up seen=$False, $akka.tcp://****@****host:59643 $Up seen=$True"]
2017-12-27 06:10:46.592 -05:00 WRN [6340:****HOST\****ACCT] Tried to associate with unreachable remote address ["akka.tcp://****@****host:4053"]. Address is now gated for 5000 ms, all messages to this address will be delivered to dead letters. Reason: ["The remote system has quarantined this system. No further associations to the remote system are possible until this system is restarted."]
```

## What's known
- as stated above, all nodes are on same machine
- only lighthouse and engine were active at the time
- these logs are from the Engine node
- lighthouse had no issues
- system has been in monitored production since October with moderate usage

## Resolution
- manually restarted both Lighthouse and Engine nodes

# Questions

- Assuming all communication is on single node; what would cause this type of unreachable remote address error?
- How can I prevent this type of error and force a node restart or termination  (instead of generating tons of log entries)

**Comment by Horusiath** [comment]
Disassociation happens when the connection between two actor systems breaks for some reason (the easiest way to trigger it from user-code is to pass a message that cannot be deserialized by one of the communicating parties or simply by hard kill of the process). Usually if it happens, the actual error reason can be found on another machine, so it's hard to say what's wrong based solely on your log.

By default actor systems will try to reconnect every 5sec. One of the ways to avoiding flooding and to stabilize the cluster is to down the corrupted node (effectively kicking it from the cluster after some period of inactivity). You can set up `akka.cluster.auto-down-unreachable-after = 10s` which will automatically down the nodes that haven't reconnected for 10 seconds. Keep in mind that this can be dangerous in some situations (on rare occasions it may cause your cluster to split in two).
