### ISSUE TITLE
Akka.DistributedData package should depend on Google.Protobuf

### ISSUE THREAD

**Issue by vasily-kirichenko** [akkadotnet/akka.net#3248]
```
[ERROR][05-Jan-18 09:38:39][Thread 0012][remoting] Could not load file or assembly 'Google.Protobuf, Version=3.3.0.0, PublicKeyToken=a7d26565bac4d604' or one of its dependencies. The locate
d assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Cause: System.IO.FileLoadException: Could not load file or assembly 'Google.Protobuf, Version=3.3.0.0, PublicKeyToken=a7d26565bac4d604' or one of its dependencies. The located assembly's ma
nifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Google.Protobuf, Version=3.3.0.0, PublicKeyToken=a7d26565bac4d604'
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean l
oadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTy
peFromPartialName)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at Hyperion.Extensions.TypeEx.<>c.<GetTypeFromManifestName>b__26_0(ByteArrayKey b)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Hyperion.Extensions.TypeEx.GetTypeFromManifestName(Stream stream, DeserializerSession session)
   at Hyperion.Extensions.TypeEx.GetTypeFromManifestVersion(Stream stream, DeserializerSession session)
   at Hyperion.Serializer.GetDeserializerByManifest(Stream stream, DeserializerSession session)
   at lambda_method(Closure , Stream , DeserializerSession )
   at Akka.DistributedData.Serialization.ReplicatorMessageSerializer.FromBinary(Byte[] bytes, Type type)
   at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
   at Akka.Remote.Serialization.MessageContainerSerializer.FromBinary(Byte[] bytes, Type type)
   at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
   at Akka.Remote.DefaultMessageDispatcher.Dispatch(IInternalActorRef recipient, Address recipientAddress, Payload message, IActorRef senderOption)
   at Akka.Remote.EndpointReader.<Reading>b__11_1(InboundPayload inbound)
   at lambda_method(Closure , Object , Action`1 , Action`1 , Action`1 )
   at Akka.Tools.MatchHandler.PartialHandlerArgumentsCapture`4.Handle(T value)
   at Akka.Actor.ReceiveActor.ExecutePartialMessageHandler(Object message, PartialAction`1 partialAction)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Akka.Actor.ActorCell.HandleFailed(Failed f)
   at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Akka.Actor.ActorCell.HandleFailed(Failed f)
   at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

**Comment by vasily-kirichenko** [comment]
Updating Google.Protobuf to version 3.5.1 has solved the problem. No idea how.

**Comment by Aaronontheweb** [comment]
@Horusiath we should get to the bottom of this before 1.3.3 ships.

**Comment by Horusiath** [comment]
It's very strange, the error message point to Google.Protobuf while the serializer used by DData is Hyperion - essentially Hyperion tried to serialize some type, which seems to has dependency to protobuf. @vasily-kirichenko could you give more info about data types you're using?

**Comment by vasily-kirichenko** [comment]
This is all the code:

```fsharp
let cluster = Cluster.Get system
let ddata = DistributedData.Get system
let key = PNCounterDictionaryKey "test"

async {
    for n in 1..10_000_000 do
        let counterKey = string (n % 10)
        
        ddata.Replicator.Tell(
            Dsl.Update(
                key, 
                PNCounterDictionary.Empty, 
                Consistency.writeLocal, 
                fun existing -> existing.Increment(cluster, counterKey)))
        
        //do! ddata.AsyncUpdate(key, PNCounterDictionary.Empty.Increment(cluster, counterKey), Consistency.writeLocal)  
        do! Async.Sleep 50
} 
|> Async.RunSynchronously
```
