### ISSUE TITLE
UnhandledMessageForwarder crashes and restarted every time the app is starting

### ISSUE THREAD

**Issue by vasily-kirichenko** [akkadotnet/akka.net#3267]
```
...
[DEBUG][01/12/2018 07:45:23][Thread 0007][akka://host-states-system/user/app-restarter] Started (Akkling.Actors+FunActor`1[System.Object])
[ERROR][01/12/2018 07:45:23][Thread 0009][akka://host-states-system/system/UnhandledMessageForwarder] Object reference not set to an instance of an object.
Cause: System.NullReferenceException: Object reference not set to an instance of an object.
   at Akka.Event.LoggingBus.UnhandledMessageForwarder.ToDebug(UnhandledMessage message)
   at Akka.Event.LoggingBus.UnhandledMessageForwarder.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[DEBUG][01/12/2018 07:45:23][Thread 0007][akka://host-states-system/system/UnhandledMessageForwarder] Restarting
[DEBUG][01/12/2018 07:45:23][Thread 0007][akka://host-states-system/system/UnhandledMessageForwarder] Restarted (Akka.Event.LoggingBus+UnhandledMessageForwarder)
```

**Comment by marcpiechura** [comment]
@vasily-kirichenko is this still an issue?

**Comment by vasily-kirichenko** [comment]
@marcpiechura yes :)

**Comment by Aaronontheweb** [comment]
Same issue reported by @object in Gitter today. Reproduction sample: https://github.com/pmbanka/akkling-lifecycle-repro

I'm on the case.

**Comment by Aaronontheweb** [comment]
Only occurs when the following setting is active:

```
akka.actor.debug.unhandled = on
```
```

**Comment by Aaronontheweb** [comment]
Issue is that we don't treat `ActorRefs.NoSender` / `null` properly when we're printing out debug messages for `UnhandledMessage` - I'm going to apply the same fixes we use for `DeadLetter` logging to this.
