### ISSUE TITLE
tcp-reuse-addr = off-for-windows prevents actorsystem from starting

### ISSUE THREAD

**Issue by nvivo** [akkadotnet/akka.net#3293]
[Remote.conf states](https://github.com/akkadotnet/akka.net/blob/e607088d00e60b318897da3f01b8982666a5f6cc/src/core/Akka.Remote/Configuration/Remote.conf#L460-L465) `off-for-windows` as one of the possible values for tcp-reuse-addr, but 1.3.3 fails to start when used:

```
 System.NotSupportedException: Unknown boolean format: off-for-windows
   at Akka.Configuration.Hocon.HoconValue.GetBoolean()
   at Akka.Remote.Transport.DotNetty.DotNettyTransportSettings.Create(Config config)
   at Akka.Remote.Transport.DotNetty.DotNettyTransport..ctor(ActorSystem system, Config config)
```

**Comment by Horusiath** [comment]
@nvivo error message suggests that configuration value for `off-for-windows` is not a valid HOCON boolean.

**Comment by maxcherednik** [comment]
#2477

**Comment by nvivo** [comment]
@Horusiath Yes, I saw that. I'm currently setting this up manually during my hocon generation. The point is that from the documentation, this shouldn't be parsed as boolean. I'm guessing this worked with helios, but but was lost during the transition to dotnetty.
