### ISSUE TITLE
synchronized-dispatcher in child actor

### ISSUE THREAD

**Issue by leo12chandu** [akkadotnet/akka.net#3305]
When creating a new issue, please make sure the following information is part of your issue description. (if applicable). Thank You!

- Which Akka.Net version you are using
1.3.3
- On which platform you are using Akka.Net
Windows with VS2017
- A list of steps to reproduce the issue. Or an gist or github repo which can be easily used to reproduce your case.
using synchronized-dispatcher in child actor leads to "SynchronizationContext may not be used as a TaskScheduler" exception.
I have 4 actors. Coordinator actor the parent that sends messages to Schema actor which gets routed using Pool router. This Schema actor inturn creates aggregator actor on demand. I am trying to run aggregator under a single thread by using synchronized-dispatcher like below. No UI. This is because MSDTC transactionScope needs to be disposed in the same thread where it was created and aggregator creates the actual transactionscope.

var aggregatorActor = Context.ActorOf(Props.Create(() => new ggregatorActor()).WithDispatcher("akka.actor.synchronized-dispatcher"));

It throws the following error
[ERROR][1/30/2018 7:32:49 PM][Thread 0020][akka://errorcheck/user/coordinator/sc
hemarouter] Configuration problem while creating [akka://errorcheck/user/coordin
ator/schemarouter/c6/$a] with dispatcher [akka.actor.synchronized-dispatcher] an
d mailbox []
Cause: Akka.Configuration.ConfigurationException: Configuration problem while cr
eating [akka://errorcheck/user/coordinator/schemarouter/c6/$a] with dispatcher [
akka.actor.synchronized-dispatcher] and mailbox [] ---> System.InvalidOperationE
xception: The current SynchronizationContext may not be used as a TaskScheduler.

   at System.Threading.Tasks.SynchronizationContextTaskScheduler..ctor()
   at Akka.Dispatch.CurrentSynchronizationContextExecutorServiceFactory.Produce(
String id)
   at Akka.Dispatch.Dispatcher.LazyExecutorServiceDelegate.<>c__DisplayClass3_0.
<.ctor>b__0()
   at Akka.Util.FastLazy`1.get_Value()
   at Akka.Dispatch.Dispatcher.ExecuteTask(IRunnable run)
   at Akka.Dispatch.CurrentSynchronizationContextDispatcherConfigurator.Dispatch
er()
   at Akka.Dispatch.Dispatchers.Lookup(String dispatcherName)
   at Akka.Actor.LocalActorRefProvider.ActorOf(ActorSystemImpl system, Props pro
ps, IInternalActorRef supervisor, ActorPath path, Boolean systemService, Deploy
deploy, Boolean lookupDeploy, Boolean async)
   --- End of inner exception stack trace ---
   at Akka.Actor.LocalActorRefProvider.ActorOf(ActorSystemImpl system, Props pro
ps, IInternalActorRef supervisor, ActorPath path, Boolean systemService, Deploy
deploy, Boolean lookupDeploy, Boolean async)
   at Akka.Remote.RemoteActorRefProvider.ActorOf(ActorSystemImpl system, Props p
rops, IInternalActorRef supervisor, ActorPath path, Boolean systemService, Deplo
y deploy, Boolean lookupDeploy, Boolean async)
   at Akka.Actor.ActorCell.MakeChild(Props props, String name, Boolean async, Bo
olean systemService)
   at Akka.Actor.ActorCell.ActorOf(Props props, String name, Boolean isAsync, Bo
olean isSystemService)
   at Akka.Actor.ActorCell.ActorOf(Props props, String name)
   at SPGMI.ErrorChecks.Actors.ErrorCheckSchemaActor.<GetObjectErrorCheckSchema>
b__6_0(RunErrorCheck runErrorCheck) in C:\Users\chandram\source\repos\SPGMI.Erro
rChecks\SPGMI.ErrorChecks\Actors\ErrorCheckSchemaActor.cs:line 63
   at lambda_method(Closure , Object , Action`1 )
   at Akka.Tools.MatchHandler.PartialHandlerArgumentsCapture`2.Handle(T value)
   at Akka.Actor.ReceiveActor.ExecutePartialMessageHandler(Object message, Parti
alAction`1 partialAction)
   at Akka.Actor.ReceiveActor.OnReceive(Object message)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
--- End of stack trace from previous location where exception was thrown ---
   at Akka.Actor.ActorCell.HandleFailed(Failed f)
   at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messag
es, Int32 currentState)

**Comment by Aaronontheweb** [comment]
@leo12chandu in this instance, a `SynchronizedDispatcher` probably isn't the right tool for the job since it binds to the synchronziation context of thread that called `ActorOf`.

Try a `PinnedDispatcher` instead - this will guarantee that the actor runs on its own dedicated, exclusive thread. That should help.

**Comment by leo12chandu** [comment]
That is awesome. It worked!! Thank You!
