### ISSUE TITLE
Akka.FSharp System.create trows an exception when akka.extensions is populated in HOCON 

### ISSUE THREAD

**Issue by mjelev** [akkadotnet/akka.net#3404]
- In Akka.FSharp 1.3.6
- When you try to start an actor system, System.create throws the following exception: 

> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Akka.FSharp.Serialization.exprSerializationSupport(ActorSystem system)
   at Akka.FSharp.System.create(String name, Config config)
   at <StartupCode$FSI_0042>.$FSI_0042.main@() in 

Here is the script to reproduce: 

let configWithExtension = Configuration.parse """akka {
                extensions = ["Akka.Cluster.Tools.PublishSubscribe.DistributedPubSubExtensionProvider,Akka.Cluster.Tools"]
                actor {              
                    provider = cluster
                }
              }"""
let system = System.create  "mySystem" configWithExtension

**Comment by AaronEshbach** [comment]
Pull Request #3407 adds a unit test that reproduces this issue.

**Comment by chrisjhoare** [comment]
If you don't need remote deployment of serialized f# actors you can use the regular ActorSystem.Create to get around this.
