### ISSUE TITLE
Incompatibility with DotNetty 0.4.7

### ISSUE THREAD

**Issue by vasily-kirichenko** [akkadotnet/akka.net#3409]
```
13:31:11 FATAL [DomainUnhandled, 1] Domain unhandled exception of type AggregateException occured (System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.MissingMethodException: Method not found: 'Void DotNetty.Buffers.UnpooledByteBufferAllocator..ctor()'.
   at Akka.Remote.Transport.DotNetty.DotNettyTransport.ServerFactory()
   at Akka.Remote.Transport.DotNetty.DotNettyTransport.<NewServer>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Remote.Transport.DotNetty.DotNettyTransport.<Listen>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Akka.Remote.Transport.DotNetty.DotNettyTransport.<Listen>d__21.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Akka.Remote.Transport.AbstractTransportAdapter.<>c__DisplayClass11_0.<<Listen>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Akka.Remote.EndpointManager.<>c__DisplayClass48_1.<get_Listens>b__4(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Akka.Remote.EndpointManager.<>c.<get_Listens>b__48_5(Task`1 transportResults)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Akka.Remote.Remoting.Start()
   at Akka.Remote.RemoteActorRefProvider.Init(ActorSystemImpl system)
   at Akka.Cluster.ClusterActorRefProvider.Init(ActorSystemImpl system)
   at Akka.Actor.Internal.ActorSystemImpl.Start()
   at Akka.Actor.ActorSystem.Create(String name, Config config)
```

**Comment by vasily-kirichenko** [comment]
This is having Akka 1.3.6 package. It claims it's compatible with DotNetty 0.4.6+, but it's clearly not the case. It should depends on 0.4.6, strictly.

**Comment by vasily-kirichenko** [comment]
Yes, pinning DotNetty to 0.4.6 has solved the problem. 
I think it's a major bug and it should be fixed ASAP.

**Comment by vasily-kirichenko** [comment]
![image](https://user-images.githubusercontent.com/873919/39047482-aee78b8a-44a2-11e8-98f6-827036bc44a1.png)
