### ISSUE TITLE
JSonconverter can't deserialize Akka.Actor.Status.Failure

### ISSUE THREAD

**Issue by AndreSteenbergen** [akkadotnet/akka.net#3490]
Akka 1.3.8
.Net Core 2.0

Create an object of type Akka.Actor.Status.Failure and serialize using JsonConverter. It will trhrow an exception about JObject not being to cast to JValue

This is probably caused by the Exception.

**Comment by Aaronontheweb** [comment]
@AndreSteenbergen any idea what the underlying exception was?

**Comment by AndreSteenbergen** [comment]
In my case it was Task.Cancelled Exception

**Comment by Aaronontheweb** [comment]
Ok, that shouldn't be the end of the world. This should be easy enough to reproduce. Happened over an Akka.Remote connection between two .NET Core 2.0 nodes?

**Comment by AndreSteenbergen** [comment]
Yes, in a webcrawler project modified from the examples

**Comment by AndreSteenbergen** [comment]
Bug report is faulted, the deserialization gives errors, I don't know which part is at fault.

**Comment by Zetanova** [comment]
I have currently a related problem with RemoteDeploy

An agent is remote deployed and make some work with Akka.Streams.
It throws an System.InvalidOperationException inside SelectAsync(1, ...) of the stream
The exception is handled with the default supervisor strategy and send back to the Deployer. 

The deployer throws on receive.
```
[06:40:43 ERR] AssociationError [akka.tcp://system@controller-01.cluster:2552] <- akka.tcp://system@worker-01.cluster:2552: Error [Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'Newtonsoft.Json.Linq.JValue'.] [   at Akka.Remote.EndpointReader.<Reading>b__11_1(InboundPayload inbound)
   at lambda_method(Closure , Object , Action`1 , Action`1 , Action`1 )
   at Akka.Actor.ReceiveActor.ExecutePartialMessageHandler(Object message, PartialAction`1 partialAction)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)]

[06:40:43 ERR] Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'Newtonsoft.Json.Linq.JValue'.
System.InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'Newtonsoft.Json.Linq.JValue'.
   at Akka.Remote.EndpointReader.<Reading>b__11_1(InboundPayload inbound)
   at lambda_method(Closure , Object , Action`1 , Action`1 , Action`1 )
   at Akka.Actor.ReceiveActor.ExecutePartialMessageHandler(Object message, PartialAction`1 partialAction)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
--- End of stack trace from previous location where exception was thrown ---
   at Akka.Actor.ActorCell.HandleFailed(Failed f)
   at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState)
```

**Comment by Zetanova** [comment]
I made a separate topic #3903 on problem

its not realy a problem with the json serializer.
If NodeA RemoteDeployes to NodeB work.
NobeB can use unknown assemblies to NodeA
like SQL-Client, EventStore-Client ...

**Comment by Aaronontheweb** [comment]
Real issue here is #3903 - serialization of exceptions in Akka.Remote payloads. Going to address the issue there.
