### ISSUE TITLE
Akka.Persistence.MemorySnapshotStore: System.InvalidOperation exception

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#3526]
Version: Akka.NET v1.3.8

Error should be relatively easy to find:

```
'18-06-21 08:36:52: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.OrderedEnumerable`1.TryGetFirst(Boolean& found)
   at System.Linq.OrderedEnumerable`1.TryGetElementAt(Int32 index, Boolean& found)
   at System.Linq.OrderedPartition`1.TryGetFirst(Boolean& found)
   at System.Linq.Enumerable.SelectIPartitionIterator`2.TryGetFirst(Boolean& found)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at Akka.Persistence.Snapshot.MemorySnapshotStore.<>c__DisplayClass5_0.<LoadAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Comment by Aaronontheweb** [comment]
Found the issue and fixed it here: https://github.com/akkadotnet/akka.net/pull/3527
