### ISSUE TITLE
Restarting not supported for connection actors

### ISSUE THREAD

**Issue by erikzhang** [akkadotnet/akka.net#3543]
```
[ERROR][07/06/2018 20:25:27][Thread 0004][akka://NeoSystem/system/IO-TCP/$h] Restarting not supported for connection actors.
Cause: [akka://NeoSystem/system/IO-TCP/$h#236330216]: Akka.Actor.PostRestartException: Exception post restart (System.Net.Sockets.SocketException) ---> Akka.Pattern.IllegalStateException: Restarting not supported for connection actors.
   at Akka.IO.TcpConnection.PostRestart(Exception reason)
   at Akka.Actor.ActorCell.UseThreadContext(Action action)
   at Akka.Actor.ActorCell.FinishRecreate(Exception cause, ActorBase failedActor)
   --- End of inner exception stack trace ---
```

**Comment by Horusiath** [comment]
@erikzhang would you care to actually elaborate on your problem?

**Comment by erikzhang** [comment]
I'm using the TCP Driver described in documentation. http://getakka.net/articles/networking/io.html
But sometimes the error log shown above appears on the console.
It seems that the system is attempting to restart the TCP connection actor. But this is supposed to be unexpected, isn't it?

**Comment by vncoelho** [comment]
I found you here, @erikzhang....aehauehauea

@Horusiath, It is also described here #3648, I did not see this one before opening. Sorry if it is kind of duplicated.
There are some additional descriptions there.
