### ISSUE TITLE
Only one usage of each socket address is normally permitted

### ISSUE THREAD

**Issue by jalchr** [akkadotnet/akka.net#3546]
This is still an issue #2626

Sometimes, the asp.net application gets hanged in a 'restart loop', until manually killing the process with following log:
```
2018-07-10 21:01:26,536 [15] INFO  Archive.Api.Startup - ASP.NET application starting ...
2018-07-10 21:01:29,833 [61] INFO  Akka.Event.DummyClassForStringSources - Starting remoting
2018-07-10 21:01:30,020 [61] ERROR Akka.Remote.Transport.DotNetty.TcpTransport - Failed to bind to 0.0.0.0:16666; shutting down DotNetty transport.
System.Net.Sockets.SocketException (0x80004005): Only one usage of each socket address (protocol/network address/port) is normally permitted
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at DotNetty.Transport.Channels.Sockets.TcpServerSocketChannel.DoBind(EndPoint localAddress)
   at DotNetty.Transport.Channels.AbstractChannel.AbstractUnsafe.BindAsync(EndPoint localAddress)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DotNetty.Transport.Bootstrapping.AbstractBootstrap`2.<DoBindAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Remote.Transport.DotNetty.DotNettyTransport.<NewServer>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Remote.Transport.DotNetty.DotNettyTransport.<Listen>d__21.MoveNext()
2018-07-10 21:01:30,036 [47] ERROR Akka.Event.DummyClassForStringSources - Remoting error: [Startup failed] []
2018-07-10 21:01:30,052 [61] INFO  Akka.Remote.RemoteActorRefProvider+RemotingTerminator - Shutting down remote daemon.
2018-07-10 21:01:30,052 [61] INFO  Akka.Remote.RemoteActorRefProvider+RemotingTerminator - Remote daemon shut down; proceeding with flushing remote transports.
2018-07-10 21:01:30,067 [71] INFO  Akka.Event.DummyClassForStringSources - Remoting shut down
2018-07-10 21:01:30,067 [47] ERROR Akka.Event.DummyClassForStringSources - Remoting system has been terminated abruptly. Attempting to shut down transports
2018-07-10 21:01:30,067 [47] INFO  Akka.Remote.RemoteActorRefProvider+RemotingTerminator - Remoting shut down.
```
Any suggested work around to avoid this ?

This is using latest v1.3.8

**Comment by Horusiath** [comment]
How are you assigning ports for your actor systems? Are they dynamically assigned?

**Comment by jalchr** [comment]
No ... in the configuration I have the port 16,666 assigned to it. 
Good to mention that "Disable overlapped recycling" is set to true, but somehow another instance is created before the previous one gets completely disposed !

**Comment by jalchr** [comment]
@Horusiath Isn't there a retry mechanism when binding to a port ? 
The application should not throw when starting and waiting for the port to become available

**Comment by sebaim** [comment]
Hi jalchr, did you found any solution?
