### ISSUE TITLE
Handling skipped ordering number in eventjournal

### ISSUE THREAD

**Issue by eaba** [akkadotnet/akka.net#3556]
- AKKA.Net 1.3.8, Akka.Persistence.SqlServer 1.3.7, Akka.Persistence 1.3.7
- Aspnet Core Windows Service

If I started and stopped the Windows Service a few times, I see that the Message gets to the Actor but never get persisted and the event is never called. Looking at the the EventJournal table, I see something in this line:
`1,2,3,4,5,109,110,111` with the ordering column
 once this happens the actor seems to be `deadlocked`, restarting the service does not fix it, it only get fixed when the service is stopped and the tables are deleted and thereby creating it anew!

```
                Command<DMessage>(message =>
                {
                    Persist(message, m =>
                    {
                        Handle(m);
                    });
                    if (LastSequenceNr % SnapshotInterval == 0 && LastSequenceNr != 0)
                    {
                        var snapshot = GetDeliverySnapshot();
                        SaveSnapshot(snapshot);
                    }
                });
```

Note that am using MassTransit to consume message off of azure service bus queue and then handle the message over to the coordinating PersistentActor

**Comment by Horusiath** [comment]
@eaba persistence actors will try to recover from events stored in the journal (and from snapshots). For that all events in journal are expected to have a monotonically increasing (always by 1) sequence number. 

This is very important for consistency of actor's state - if actor finds that after event with sequence nr. `x`, the next one have seqNr `x+2` (meaning `x+1` is missing), this means that event journal is corrupted and needs a human intervention. Actor will stop itself immediatelly. This is actually a desired behavior: if actor would try to replay from corrupted journal, it means its own state is also corrupted and it cannot be allowed to live. Otherwise it could propagate more decision changes based on invalid state: *imagine makind a decision about giving someone a credit based on account balance situation where not all withdrawal/deposits where known*.

Event journal can remove events prior to some sequence number it told so explictily, but it will never leave holes with some events before and after. To be honest your issue looks like someone removed a window of events directly from the journal table.

**Comment by eaba** [comment]
The sequence number is correct in my own case......the missing ordering number indicates a failure in trying to persist the message since ordering number is auto-incremented by the database

I think this failure in persisting the message is what is causing the issue......I cant see much detail in the log.
I see something like this also: 1,2,3,4,5,6,1000,1009,1010....look at the big difference but the SeqNr is not affected it remains: 1,2,3,4,5,6,7,8,9

**Comment by eaba** [comment]
```
Ordering             PersistenceId                                                                                                                                                                                                                                                   SequenceNr           Timestamp            IsDeleted Manifest                                                                                                                                                                                                                                                         Payload                                                                                                                                                                                                                                                          Tags                                                                                                 SerializerId
-------------------- --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- -------------------- -------------------- --------- ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- ---------------------------------------------------------------------------------------------------- ------------
1                    Distributor                                                                                                                                                                                                                                   1                    0                    0                                                                                                                                                                                                                                                                          0x7B22246964223A2231222C222474797065223A2276322E4D6573736167652E42757365732E44746F2C2076322E4D6573736167652E4275736573222C225061796C6F6164223A7B22246964223A2232222C222474797065223A2253797374656D2E436F6C6C656374696F6E732E496D6D757461626C652E496D6D757461626C                                                                                                      1
2                    Distributor                                                                                                                                                                                                                                   2                    0                    0                                                                                                                                                                                                                                                                          0x7B22246964223A2231222C222474797065223A2276322E4D6573736167652E42757365732E44746F2C2076322E4D6573736167652E4275736573222C225061796C6F6164223A7B22246964223A2232222C222474797065223A2253797374656D2E436F6C6C656374696F6E732E496D6D757461626C652E496D6D757461626C                                                                                                      1
3                    Distributor                                                                                                                                                                                                                                   3                    0                    0                                                                                                                                                                                                                                                                          0x7B22246964223A2231222C222474797065223A2276322E4D6573736167652E42757365732E44746F2C2076322E4D6573736167652E4275736573222C225061796C6F6164223A7B22246964223A2232222C222474797065223A2253797374656D2E436F6C6C656374696F6E732E496D6D757461626C652E496D6D757461626C                                                                                                      1
4                    Distributor                                                                                                                                                                                                                                   4                    0                    0                                                                                                                                                                                                                                                                          0x7B22246964223A2231222C222474797065223A2276322E4D6573736167652E42757365732E44746F2C2076322E4D6573736167652E4275736573222C225061796C6F6164223A7B22246964223A2232222C222474797065223A2253797374656D2E436F6C6C656374696F6E732E496D6D757461626C652E496D6D757461626C                                                                                                      1
10003                Distributor                                                                                                                                                                                                                                   5                    0                    0                                                                                                                                                                                                                                                                          0x7B22246964223A2231222C222474797065223A2276322E4D6573736167652E42757365732E44746F2C2076322E4D6573736167652E4275736573222C225061796C6F6164223A7B22246964223A2232222C222474797065223A2253797374656D2E436F6C6C656374696F6E732E496D6D757461626C652E496D6D757461626C                                                                                                      1
10004                Distributor                                                                                                                                                                                                                                   6                    0                    0                                                                                                                                                                                                                                                                          0x7B22246964223A2231222C222474797065223A2276322E4D6573736167652E42757365732E44746F2C2076322E4D6573736167652E4275736573222C225061796C6F6164223A7B22246964223A2232222C222474797065223A2253797374656D2E436F6C6C656374696F6E732E496D6D757461626C652E496D6D757461626C                                                                                                      1
10005                Distributor                                                                                                                                                                                                                                   7                    0                    0                                                                                                                                                                                                                                                                          0x7B22246964223A2231222C222474797065223A2276322E4D6573736167652E42757365732E44746F2C2076322E4D6573736167652E4275736573222C225061796C6F6164223A7B22246964223A2232222C222474797065223A2253797374656D2E436F6C6C656374696F6E732E496D6D757461626C652E496D6D757461626C                                                                                                      1

(7 rows affected)
```
Just experienced same right now and as always, Actor stops processing messages.....

**Comment by eaba** [comment]
Without dropping tables, the Actor has started processes messages after some minutes but prior messages are lost.
Considering am consuming message from Azure Service Bus, is there a way for one to check the state of an Actor before messaging it?

**Comment by eaba** [comment]
> unless your actor i.e. fails to change its state after persisted event on during replay
I will go with that line.
How can I log better details? Below is how I do logging currently:
`: AtLeastOnceDeliveryReceiveActor, ILogReceive
`loggers = ["Akka.Logger.NLog.NLogLogger, Akka.Logger.NLog"]

**Comment by Horusiath** [comment]
The most basic logging setting is `akka.loglevel = DEBUG` (it's INFO by default). Nonetheless if actor fails due to any exception, it should be logged on ERROR level.

**Comment by eaba** [comment]
Okay, I will be closing this issue....there are many sides to the story, as I have discovered: when the system becomes sluggish(slow in opening applications) this happens.

**Comment by eaba** [comment]
After a long while I came to find out that the is was due to this:
```
Newtonsoft.Json.JsonSerializationException: Cannot preserve reference to readonly dictionary, or dictionary created from a non-default constructor: System.Collections.Immutable.ImmutableDictionary`2[System.String,System.String]. Path 'Message.Message.Payload.Request', line 1, position 735.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Akka.Serialization.NewtonSoftJsonSerializer.SurrogateConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Akka.Serialization.NewtonSoftJsonSerializer.FromBinary(Byte[] bytes, Type type)
   at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
   at Akka.Persistence.Serialization.PersistenceMessageSerializer.GetAtLeastOnceDeliverySnapshot(Byte[] bytes)
   at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
   at Akka.Persistence.Sql.Common.Snapshot.AbstractQueryExecutor.GetSnapshot(DbDataReader reader)
   at Akka.Persistence.Sql.Common.Snapshot.AbstractQueryExecutor.ReadSnapshot(DbDataReader reader)
   at Akka.Persistence.Sql.Common.Snapshot.AbstractQueryExecutor.<SelectSnapshotAsync>d_
```
This caused the Actors to shutdown! It is recommended that default Serializer should not be used for akka.persistence
