### ISSUE TITLE
An asynchronous socket operation is already in progress using this SocketAsyncEventArgs instance.

### ISSUE THREAD

**Issue by erikzhang** [akkadotnet/akka.net#3572]
I'm using the TCP Driver described in documentation. http://getakka.net/articles/networking/io.html

But sometimes the following error log shown on the console:

```
[ERROR][2018/8/22 0:46:04][Thread 0115][akka://NeoSystem/system/IO-TCP/$a/$gTg] An asynchronous socket operation is already in progress using this SocketAsyncEventArgs instance.
Cause: System.InvalidOperationException: An asynchronous socket operation is already in progress using this SocketAsyncEventArgs instance.
   at System.Net.Sockets.SocketAsyncEventArgs.StartOperationCommon(Socket socket)
   at System.Net.Sockets.Socket.ReceiveAsync(SocketAsyncEventArgs e)
   at Akka.IO.TcpConnection.ReceiveAsync()
   at Akka.IO.TcpConnection.DoRead(ConnectionInfo info, IActorRef closeCommander)
   at Akka.IO.TcpConnection.<>c__DisplayClass22_0.<Connected>b__0(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
```

**Comment by Horusiath** [comment]
@erikzhang could you provide any more information? Maybe scenario, which reproduces an issue?

**Comment by erikzhang** [comment]
This is hard to reproduce. However, the program may work for a few days and may crush due to this problem.

**Comment by erikzhang** [comment]
It appears again.

```
[ERROR][2018/12/16 20:53:04][Thread 0108][akka://NeoSystem/system/IO-TCP/$a/$C3D] An asynchronous socket operation is already in progress using this SocketAsyncEventArgs instance.
Cause: System.InvalidOperationException: An asynchronous socket operation is already in progress using this SocketAsyncEventArgs instance.
   at System.Net.Sockets.SocketAsyncEventArgs.StartOperationCommon(Socket socket)
   at System.Net.Sockets.Socket.ReceiveAsync(SocketAsyncEventArgs e)
   at Akka.IO.TcpConnection.ReceiveAsync()
   at Akka.IO.TcpConnection.DoRead(ConnectionInfo info, IActorRef closeCommander)
   at Akka.IO.TcpConnection.<>c__DisplayClass22_0.<Connected>b__0(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
```

**Comment by Aaronontheweb** [comment]
Issue has been resolved via https://github.com/akkadotnet/akka.net/pull/4140

Will be part of v1.4.0 and possibly 1.3.18.
