### ISSUE TITLE
DistributedPubSub error on remote noteds/cluster

### ISSUE THREAD

**Issue by hectorcaban** [akkadotnet/akka.net#3585]
I am using Akka.Cluster.Tools, Version=1.3.9.0
any time I put this line 
 var mediator = DistributedPubSub.Get(SystemActors.ActorSystem).Mediator; 

I start getting this error

2018-09-02 01:20:25.174 -05:00 [Warning] Association with remote system "akka.tcp://LifecycleOneProxy@0.0.0.0:49735" has failed; address is now gated for 5000 ms. Reason is: ["Akka.Remote.EndpointDisassociatedException: Disassociated
   at Akka.Remote.EndpointWriter.PublishAndThrow(Exception reason, LogLevel level, Boolean needToThrow)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
--- End of stack trace from previous location where exception was thrown ---
   at Akka.Actor.ActorCell.HandleFailed(Failed f)

**Comment by Horusiath** [comment]
This error message that at least two of your actor systems have dissassociated and can no longer communicate with each other. My guess would be that you haven't set a DistributedPubSub serializers configuration on all of the nodes.

**Comment by hectorcaban** [comment]
I was just about to do that. I will let you know.. Thanks !

**Comment by hectorcaban** [comment]
Fixed.. Thanks !
