### ISSUE TITLE
HttpClient raises random.occasional IO:Exceptions in ContinueWith block

### ISSUE THREAD

**Issue by acds** [akkadotnet/akka.net#3661]
Akka.net 1.3.10 .Net Core 2.1 AspNetCore 2.1.1

Have actors raising HttpClient requests on a 3rd party API. Results are JSON that are sent as messages to the Actor.

Model is based 100% on the Petabridge  Image Downloader examples.

These exception are 100% Radom.

````
_httpClient.GetAsync(url)
    .ContinueWith(httpRequest =>
        {
           var response = httpRequest.Result; // <-- IO.Exception occurs here 

            if (response.StatusCode == HttpStatusCode.OK)
            {
                var contentStream = response.Content.ReadAsStreamAsync();
                try
                {
                    contentStream.Wait(TimeSpan.FromSeconds(1));
                    return new MyResponse(response.StatusCode, contentStream.Result);
                }
                catch //timeout exceptions!
                {
                    return new MyResponse(HttpStatusCode.PartialContent);
                }
            }

            return new MyResponse(response.StatusCode);
        }, TaskContinuationOptions.AttachedToParent & TaskContinuationOptions.ExecuteSynchronously
    ).PipeTo(Self);
````
I also notice that I get the same issues when make HttpClient requests data outbound to other API's following the same model and using (on a different HttpClient):
````
_httpClient.PostAsJsonAsync(uri, outJsonObject).ContinueWith(httpRequest =>
{
    var response = httpRequest.Result; // <-- IO.Exception occurs here

}, TaskContinuationOptions.AttachedToParent & TaskContinuationOptions.ExecuteSynchronously);

````

**Comment by Aaronontheweb** [comment]
What are the exceptions exactly?

**Comment by acds** [comment]
there are three inbound:

1:
````
System.AggregateException: One or more errors occurred. (An error occurred while sending the request.) ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: The server returned an invalid or unrecognized response.
at at System.Net.Http.HttpConnection.FillAsync()
at at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
at at System.Threading.Tasks.ValueTask`1.get_Result()
at at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
--- End of inner exception stack trace ---
at at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
at at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
at at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
--- End of inner exception stack trace ---
at at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
at at System.Threading.Tasks.Task`1.get_Result()
at FlightDataSource.Actors.AirportActor.<>c.<loaddata>b__13_3(Task`1 httpRequest) in /Users/spscs/Projects/ProcessThis/flightdatasource/Actors/AirportActor.cs:102
at at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
at at System.Threading.Tasks.Task.<>c.<.cctor>b__278_1(Object obj)
at at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
````
2:
````
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> 
System.IO.IOException: The server returned an invalid or unrecognized response.
at at System.Net.Http.HttpConnection.FillAsync()
at at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
at at System.Threading.Tasks.ValueTask`1.get_Result()
at at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
--- End of inner exception stack trace ---
at at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
at at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
at at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
````

3:
````
System.IO.IOException: The server returned an invalid or unrecognized response.
at at System.Net.Http.HttpConnection.FillAsync()
at at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
at at System.Threading.Tasks.ValueTask`1.get_Result()
at at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
````

and three outbound ones:
1:
````
System.AggregateException: One or more errors occurred. (An error occurred while sending the request.) ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: The server returned an invalid or unrecognized response.
  at at System.Net.Http.HttpConnection.FillAsync()
  at at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
  at at System.Threading.Tasks.ValueTask`1.get_Result()
  at at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
  --- End of inner exception stack trace ---
  at at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
  at at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
  at at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  at at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
  --- End of inner exception stack trace ---
  at at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
  at at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
  at at System.Threading.Tasks.Task`1.get_Result()
  at FlightDataSource.Actors.PipelineHookActor.<>c.<Active>b__9_10(Task`1 httpRequest) in /Users/spscs/Projects/ProcessThis/flightdatasource/Actors/PipelineHookActor.cs:160
  at at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
  at at System.Threading.Tasks.Task.<>c.<.cctor>b__278_1(Object obj)
  at at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
````
2:
````
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: The server returned an invalid or unrecognized response.
  at at System.Net.Http.HttpConnection.FillAsync()
  at at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
  at at System.Threading.Tasks.ValueTask`1.get_Result()
  at at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
  --- End of inner exception stack trace ---
  at at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
  at at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
  at at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  at at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
````

3:
````
System.IO.IOException: The server returned an invalid or unrecognized response.
  at at System.Net.Http.HttpConnection.FillAsync()
  at at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
  at at System.Threading.Tasks.ValueTask`1.get_Result()
  at at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
````

**Comment by Aaronontheweb** [comment]
So these are basic HTTP errors - nothing to do with Actors

**Comment by acds** [comment]
I'm guessing given a little research there since I'm running hit sin the context of a .AspNetCore API sever I need to use a combination of the [IHttpClientFactory](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.1) service (in startup.cs) if I can work out how to make that Akka.net compatible, 

Possibly also use of [Microsoft.AspNet.WebApi.Client](https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Client/) albeit there seem to be some fun to jump though to get this to work in .Net Core with the possibly need for [Microsoft.AspNetCore.Mvc.WebApiCompatShim](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.WebApiCompatShim/)

**Comment by acds** [comment]
I switched over to use HttpClientFactory...and still get issues. This is brand new to .Net Core 2.1 and apparently v robust, so I'm ginseng there are some interesting interaction going on with the async stuff ...?

**Comment by acds** [comment]
Suspect this is Akka.Net unrelated and was due to a macOS environment running out sockets.

Per Microsoft one is supposed to increase the number of [available sockets](https://docs.microsoft.com/en-us/dotnet/core/macos-prerequisites?tabs=netcore2x#increase-the-maximum-open-file-limit-net-core-versions-before-net-core-sdk-202) per Microsoft Recommendations.
