### ISSUE TITLE
ClusteredPoolRouter, No actor producer specified

### ISSUE THREAD

**Issue by Lyynx92** [akkadotnet/akka.net#3687]
Attempting to create a clustered round robin pool to fan out remote workers, running into an issue whenever the deployment is attempted I get this error.

```
[ERROR][12/21/18 1:55:40 AM][Thread 0006][akka://testing/user/Deploy/DummyPool] Error while creating actor instance of type Akka.Actor.ActorBase with 0 args: ()
Cause: [akka.tcp://testing@localhost:4053/remote/akka.tcp/testing@localhost:35427/user/Deploy/DummyPool/c1#911197206]: Akka.Actor.ActorInitializationException: Exception during creation ---> System.TypeLoadException: Error while creating actor instance of type Akka.Actor.ActorBase with 0 args: () ---> System.InvalidOperationException: No actor producer specified!
   at Akka.Actor.Props.DefaultProducer.Produce()
   at Akka.Actor.Props.NewActor()
   --- End of inner exception stack trace ---
   at Akka.Actor.Props.NewActor()
   at Akka.Actor.ActorCell.CreateNewActorInstance()
   at Akka.Actor.ActorCell.<>c__DisplayClass109_0.<NewActor>b__0()
   at Akka.Actor.ActorCell.UseThreadContext(Action action)
   at Akka.Actor.ActorCell.NewActor()
   at Akka.Actor.ActorCell.Create(Exception failure)
   --- End of inner exception stack trace ---
   at Akka.Actor.ActorCell.HandleFailed(Failed f)
   at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState)
```

I've tried both a Hocon configured cluster aware pool router as well as in code. 

```c#
            var router = Context.ActorOf(
                Props.Create(() => new Worker())
                    .WithRouter(new ClusterRouterPool(new RoundRobinPool(1),
                    new ClusterRouterPoolSettings(4, 2, false, "runner"))));
```

```
akka 
{
    actor.provider = cluster
    actor.deployment {

        "/Deploy/router" {
            router = round-robin-pool
            nr-of-instances = 10
                cluster 
                {
                    enabled = on
                    max-nr-of-instances-per-node = 2
                    allow-local-routees = off
                    use-role = runner
                }
        }
    }
      
    remote 
    {
        dot-netty.tcp 
        {
            port = 0
            hostname = localhost
        }
    }
    
    cluster 
    {
        seed-nodes = ["akka.tcp://testing@localhost:4053"]
        roles =["Deploy"]
    }
}

```

I've reproduced this on three bare bones dotnet-core 2.1 Console applications (1 seed, 1 deployer and 1 target), all running Akka.Cluster 1.3.11. I've been digging around but found no reference other than in the Props class as it seems to keep using the DefaultProducer when remoting the actors instead of the ActivatorProducer.

**Comment by raskolnikoov** [comment]
I have the same problem. Any updates on this?

**Comment by marsop** [comment]
I had the same problem, the solution for me was referencing the (shared) project where my actor was defined from both the project where I was creating the router as well as the project where the actor was supposed to be deployed.

**Comment by Aaronontheweb** [comment]
Ah ok, this was an actor serialization issue due to the actor not being defined on the node being deployed. Thanks for clarifying.
