### ISSUE TITLE
Routees serialization issue

### ISSUE THREAD

**Issue by AndreSteenbergen** [akkadotnet/akka.net#3733]
In a cluster on Akka 1.3.11 I have remotely deployed some actors. Right now I need to know the number routees from one of the routees. But when I call the following code:

```
Console.WriteLine("A");
routeesCount = Context.Parent.Ask<Routees>(new GetRoutees()).Result.Members.Count();
Console.WriteLine(routeesCount);
```

I do get the A written on screen, but right after that message I get the following JsonDeserialization Error:
```
A
[ERROR][3/8/19 9:33:07 PM][Thread 0008][[akka://system/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2Fsystem%4010.0.0.31%3A10160-3/endpointWriter#1275743299]] AssociationError [akka.tcp://system@10.0.0.21:10170] <- akka.tcp://system@10.0.0.31:10160: Error [Value cannot be null.
Parameter name: source] [   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at lambda_method(Closure , Object[] )
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Akka.Serialization.NewtonSoftJsonSerializer.FromBinary(Byte[] bytes, Type type)
   at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
   at Akka.Remote.DefaultMessageDispatcher.Dispatch(IInternalActorRef recipient, Address recipientAddress, Payload message, IActorRef senderOption)
   at Akka.Remote.EndpointReader.<Reading>b__11_1(InboundPayload inbound)
   at lambda_method(Closure , Object , Action`1 , Action`1 , Action`1 )
   at Akka.Actor.ReceiveActor.ExecutePartialMessageHandler(Object message, PartialAction`1 partialAction)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)]
Cause: Unknown
```

**Comment by Aaronontheweb** [comment]
hi @AndreSteenbergen - thanks for reporting this - we'll look into reproducing it ASAP.
