### ISSUE TITLE
SqlJournal WriteMessagesAsync occasionally throws 'Collection was modified; enumeration...' InvalidOperationException

### ISSUE THREAD

**Issue by ptjhuang** [akkadotnet/akka.net#3822]
- Akka.Net 1.3.13
- Windows .NET Core 2.2

```
Failed to persist event type [MyEventType] with sequence number [1] for persistenceId ["d7e146218641473490f6a7e50fe4b9be"].
Cause: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at Akka.Persistence.Sql.Common.Journal.SqlJournal.NotifyTagChange(String tag)
   at Akka.Persistence.Sql.Common.Journal.SqlJournal.WriteMessagesAsync(IEnumerable`1 messages)
   at Akka.Util.Internal.AtomicState.CallThrough[T](Func`1 task)
   at Akka.Util.Internal.AtomicState.CallThrough[T](Func`1 task)
```

This is an intermittent error, most of the time it works.  It would appear the HashSet used in line 453, is simultaneously modified by multiple threads, perhaps unintentially.

Should it be changed to an `ImmutableSet`?

**Comment by Horusiath** [comment]
@ptjhuang if this is really the case, then yes, you're right. It definitely should be an immutable collection.
