### ISSUE TITLE
Akka.Cluster.Sharding GetShardRegionStats serialization issue

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#3830]
Version: Akka.NET v1.4.0 current `dev` branch

Error occurs when attempting to send a  `GetClusterShardingStats` message from a non-coordinator `ShardRegion` to the `PersistentShardRegion` coordinator, in this case via the [Petabridge.Cmd.Cluster.Sharding command palette](https://cmd.petabridge.com/articles/commands/cluster-sharding-commands.html), a deserialization error occurs in JSON.NET when deserializing the `ClusterShardingStats` response sent back by the coordinator:

```
ka.tcp://ShardFight@7061a2bcb4e7:5110: Error [Could not convert string 'akka.tcp://ShardFight@8fb41e2d2e27:5110' to dictionary key type 'Akka.Actor.Address'. Create a TypeConverter to convert from the string to the key type object. Path 'Regions['akka.tcp://ShardFight@8fb41e2d2e27:5110']', line 1, position 324.] [   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Akka.Serialization.NewtonSoftJsonSerializer.FromBinary(Byte[] bytes, Type type)
   at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
   at Akka.Remote.DefaultMessageDispatcher.Dispatch(IInternalActorRef recipient, Address recipientAddress, Payload message, IActorRef senderOption)
   at Akka.Remote.EndpointReader.<Reading>b__11_1(InboundPayload inbound)
   at lambda_method(Closure , Object , Action`1 , Action`1 , Action`1 )
   at Akka.Actor.ReceiveActor.ExecutePartialMessageHandler(Object message, PartialAction`1 partialAction)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)]
Cause: Unknown
```

The issue here is that we're using JSON.NET at all for this - this should be in a protobuf message.

**Comment by Aaronontheweb** [comment]
Looks like we're missing a protobuf message definition for this inside the JVM project:

https://github.com/akka/akka/blob/4e52432706f0460c477142ce185ec8b2c4b5dec8/akka-cluster-sharding/src/main/protobuf/ClusterShardingMessages.proto#L56-L63

I had figured as much - I'll go and add this.

**Comment by Aaronontheweb** [comment]
Looks like the issue is actually `ClusterShardingStats` causing this serialization error - although we don't properly serialize `ShardRegionStats` either using protobuf. I'll add a proto definition for `ClusterShardingStats` too.

**Comment by Aaronontheweb** [comment]
https://github.com/akkadotnet/akka.net/blob/dbc25dba6ee48ee44e005b806624c6655b53a002/src/contrib/cluster/Akka.Cluster.Sharding/ShardingMessages.cs#L144-L180 - barfs when we attempt to deserialize the `Address` using JSON.NET.
