### ISSUE TITLE
Custom supervisor strategy disables SelectError steps

### ISSUE THREAD

**Issue by Pzixel** [akkadotnet/akka.net#3908]
Assume following supervisor strategy that skips problematic elements:

```cs
static void Main(string[] args)
{
    var runnableGraph = Source.From(Enumerable.Range(0, 10).Select(x => x - 5))
        .Via(Flow.Create<int>().Select(x => x/x).SelectError(_ => new NullReferenceException("Completely different exception")))
        .ToMaterialized(Sink.ForEach<int>(Console.WriteLine), Keep.Right);

    using (var sys = ActorSystem.Create("Backup-Test"))
    using (var mat = ActorMaterializer.Create(sys, ActorMaterializerSettings.Create(sys).WithSupervisionStrategy(
        cause =>
        {
            Console.WriteLine($"Error happened: {cause.GetType().Name}");
            return Directive.Resume;
        })))
    {
        runnableGraph.Run(mat).Wait();
    }
}
```

which output is:

```
1
1
1
1
1
Error happened: DivideByZeroException
1
1
1
1
```

It works fine except we will see `DivideByZeroException`. If instead we remove custom supervisor strategy:

```
static void Main(string[] args)
{
    var runnableGraph = Source.From(Enumerable.Range(0, 10).Select(x => x - 5))
        .Via(Flow.Create<int>().Select(x => x/x).SelectError(_ => new NullReferenceException("Completely different exception")))
        .ToMaterialized(Sink.ForEach<int>(Console.WriteLine), Keep.Right);

    using (var sys = ActorSystem.Create("Backup-Test"))
    using (var mat = ActorMaterializer.Create(sys, ActorMaterializerSettings.Create(sys)))
    {
        runnableGraph.Run(mat).Wait();
    }
}
```

We'l see following:

```
1
1
1
1
1

Unhandled Exception: System.AggregateException: One or more errors occurred. (Completely different exception) ---> System.NullReferenceException: Completely different exception
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
```

And for some reason it doesn't match the strategy that returns `Drop` on messsages:

```
static void Main(string[] args)
{
    var runnableGraph = Source.From(Enumerable.Range(0, 10).Select(x => x - 5))
        .Via(Flow.Create<int>().Select(x => x/x).SelectError(_ => new NullReferenceException("Completely different exception")))
        .ToMaterialized(Sink.ForEach<int>(Console.WriteLine), Keep.Right);

    using (var sys = ActorSystem.Create("Backup-Test"))
    using (var mat = ActorMaterializer.Create(sys, ActorMaterializerSettings.Create(sys).WithSupervisionStrategy(
        cause =>
        {
            Console.WriteLine($"Error happened: {cause.GetType().Name}");
            return cause is DivideByZeroException ? Directive.Stop : Directive.Resume;
        })))
    {
        runnableGraph.Run(mat).Wait();
    }
}
```

Which produces:

```
1
1
1
1
1
Error happened: DivideByZeroException

Unhandled Exception: System.AggregateException: One or more errors occurred. (Completely different exception) ---> System.NullReferenceException: Completely different exception
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at ConsoleApp9.Program.Main(String[] args) in C:\Users\pzixe\Source\Repos\ConsoleApp9\ConsoleApp9\Program.cs:line 30
```

---

The desired output is:

```
1
1
1
1
1
Error happened: NullReferenceException
1
1
1
1
```

It's not actually a question but rather an assumption that API is broken in some way since current behavior is not intuitive in any sense.

**Comment by Horusiath** [comment]
@Pzixel have your read [the first note](https://getakka.net/articles/streams/error-handling.html#supervision-strategies) in the documentation related to streams supervision strategies? Could that be the case?

I agree that this behavior may be not intuitive - unfortunately select errors have been ported some time ago. Before trying to solve this issue by ourselves it first needs to be checked if canonical scala implementation haven't changed its own behavior since then - I think this indeed may have changed since then. Since Akka.NET is port library it must comply to reference implementation.

**Comment by Pzixel** [comment]
Hey. Yeas, I read that, but my whole point was it's documented this way but it's not convenient nor intuitive. Docs says that stage may behave differently when it's documented so, so I think it should be possible.
