### ISSUE TITLE
java.lang.RuntimeException: simulated failure at akka.testkit.TestProbeSpec$FailingActor$1$$anonfun$receive$1.applyOrElse(TestProbeSpec.scala:67) at akka.actor.Actor.aroundReceive(Actor.scala:532)

### ISSUE THREAD

**Issue by spshuklaji** [akkadotnet/akka.net#3972]
Trying to run the command sbt 
`sbt -no-colors -Dakka.scaladoc.diagrams=false -Dakka.parallelExecution=false test`

Akka Source code: 
`git clone --branch v2.6.0-M8 https://github.com/akka/akka.git`

Ran it in on `ubuntu:latest` container with `scala-2.12.10` and `sbt` installed.

Error Message 1:
```
Picked up JAVA_TOOL_OPTIONS:  -Dfile.encoding=UTF-8
Picked up _JAVA_OPTIONS: -Xmx10g
[info] TestProbeSpec:
Coroner Thread Count starts at 13 in akka.testkit.TestProbeSpec
[info] A TestProbe
[info] - must reply to futures (45 milliseconds)
[info] - must reply to messages (31 milliseconds) 
[info] - must properly send and reply to messages (24 milliseconds)
[info] - must create a child when invoking actorOf (26 milliseconds)
[ERROR] [10/09/2019 16:41:06.230] [TestProbeSpec-akka.actor.default-dispatcher-5] [akka://TestProbeSpec/system/testProbe-8/$a] simulated failure
java.lang.RuntimeException: simulated failure
        at akka.testkit.TestProbeSpec$FailingActor$1$$anonfun$receive$1.applyOrElse(TestProbeSpec.scala:67)
        at akka.actor.Actor.aroundReceive(Actor.scala:532)
        at akka.actor.Actor.aroundReceive$(Actor.scala:530)
        at akka.testkit.TestProbeSpec$FailingActor$1.aroundReceive(TestProbeSpec.scala:62)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:573)
        at akka.actor.ActorCell.invoke(ActorCell.scala:543)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:269)
        at akka.dispatch.Mailbox.run(Mailbox.scala:230)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```
Error Message 2:
```
Coroner Thread Count starts at 16 in akka.actor.PropsCreationSpec
[info] Props
[info] - must work with creator (57 milliseconds)
[info] - must work with classOf (1 millisecond)
[info] - must work with classOf + 1 `null` param (0 milliseconds)
[info] - must work with classOf + 2 `null` params (1 millisecond)
[info] Props Java API
[info] - must work with create(creator) (3 milliseconds)
[info] - must work with create(class, param) (0 milliseconds)
[ERROR] [10/09/2019 16:46:21.391] [PropsCreationSpec-akka.actor.internal-dispatcher-6] [akka://PropsCreationSpec/user/$f] null
akka.actor.ActorInitializationException: akka://PropsCreationSpec/user/$f: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:195)
        at akka.actor.ActorCell.create(ActorCell.scala:657)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:509)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:531)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:294)
        at akka.dispatch.Mailbox.run(Mailbox.scala:229)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
        at akka.actor.CreatorConsumer.produce(IndirectActorProducer.scala:81)
        at akka.actor.Props.newActor(Props.scala:212)
        at akka.actor.ActorCell.newActor(ActorCell.scala:609)
        at akka.actor.ActorCell.create(ActorCell.scala:635)
        ... 9 more
```

Finally at the end test status was:
```
[error] (akka-actor-tests / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 6437 s, completed Oct 9, 2019 6:23:17 PM
```

**Comment by Aaronontheweb** [comment]
This is the Akka.NET project - you're looking for https://github.com/akka/akka
