### ISSUE TITLE
During Akka.IO benchmark run, got exception in the output

### ISSUE THREAD

**Issue by IgorFedchenko** [akkadotnet/akka.net#4020]
When getting benchmark table for #4019, in one iteration of total 4800 runs I got the following exception in the console:
```csharp
[ERROR][04.11.2019 8:59:11][Thread 0012][akka://system/system/$a] Collection was modified; enumeration operation may not execute.
Cause: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.SortedSet`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Akka.IO.SimpleDnsCache.Cache.Cleanup() in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\IO\SimpleDnsCache.cs:line 125
   at Akka.IO.SimpleDnsCache.CleanUp() in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\IO\SimpleDnsCache.cs:line 84
   at Akka.IO.SimpleDnsManager.Receive(Object message) in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\IO\SimpleDnsManager.cs:line 63
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message) in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\Actor\ActorBase.cs:line 158
   at Akka.Actor.ActorCell.ReceiveMessage(Object message) in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\Actor\ActorCell.DefaultMessages.cs:line 177
   at Akka.Actor.ActorCell.Invoke(Envelope envelope) in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\Actor\ActorCell.DefaultMessages.cs:line 83
[ERROR][04.11.2019 8:59:11][Thread 0012][akka://system/system/$c] Object reference not set to an instance of an object.
Cause: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.SortedSet`1.DoRemove(T item)
   at Akka.IO.SimpleDnsCache.Cache.Cleanup() in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\IO\SimpleDnsCache.cs:line 129
   at Akka.IO.SimpleDnsCache.CleanUp() in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\IO\SimpleDnsCache.cs:line 84
   at Akka.IO.SimpleDnsManager.Receive(Object message) in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\IO\SimpleDnsManager.cs:line 62
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message) in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\Actor\ActorBase.cs:line 158
   at Akka.Actor.ActorCell.ReceiveMessage(Object message) in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\Actor\ActorCell.DefaultMessages.cs:line 177
   at Akka.Actor.ActorCell.Invoke(Envelope envelope) in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\Actor\ActorCell.DefaultMessages.cs:line 81
[ERROR][04.11.2019 8:59:11][Thread 0012][akka://system/system/$b] Object reference not set to an instance of an object.
Cause: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.SortedSet`1.Node.RotateRightLeft()
   at System.Collections.Generic.SortedSet`1.Node.Rotate(TreeRotation rotation)
   at System.Collections.Generic.SortedSet`1.DoRemove(T item)
   at Akka.IO.SimpleDnsCache.Cache.Cleanup() in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\IO\SimpleDnsCache.cs:line 129
   at Akka.IO.SimpleDnsCache.CleanUp() in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\IO\SimpleDnsCache.cs:line 84
   at Akka.IO.SimpleDnsManager.Receive(Object message) in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\IO\SimpleDnsManager.cs:line 62
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message) in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\Actor\ActorBase.cs:line 158
   at Akka.Actor.ActorCell.ReceiveMessage(Object message) in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\Actor\ActorCell.DefaultMessages.cs:line 177
   at Akka.Actor.ActorCell.Invoke(Envelope envelope) in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\Actor\ActorCell.DefaultMessages.cs:line 81
```

It was during one of the runs with 10 000 message count, 10 bytes per message and 3 concurrent clients.

This seems to be some very rare case, but still need to look at this later.

**Comment by IgorFedchenko** [comment]
Interesting, but got the same two of three exceptions (without `Collection was modified` one) on another interation with 100 bytes message size. And with exactly same number of clients, while was also running with 5, 7, 10, 20, 30, 40 of them without this error.

**Comment by Aaronontheweb** [comment]
@IgorFedchenko this seems like a bug, no?

**Comment by IgorFedchenko** [comment]
Sure, I will work on this.

**Comment by IgorFedchenko** [comment]
@Aaronontheweb So what is going on here.

When running with multiple clients (as in this case) there are multiple `SimpleDnsManager` actors running (one per each client), and each on them sometimes (set by `cache-cleanup-interval` HOCON setting, defaults to `120s`) calls `Cleanup` method on shared `IPeriodicCacheCleanup` object.

In that object, this is what is executed:
```csharp
public void CleanUp()
{
	var c = _cache.Value;
	if (!_cache.CompareAndSet(c, c.Cleanup()))
		CleanUp();
}
```

`c.Cleanup()` is modifying internal `queue` object and is not thread-safe. But it is called in multiple threads, and sometimes it throws exception (actually almost each run on my benchmark).

I have submitted PR, which adds thread safety to `Cleanup` method, and do not get exception anymore.
