### ISSUE TITLE
MNTR: TRX reporter fails with NRE

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#4035]
Version: 1.4.0-beta3

```
Cause: System.NullReferenceException: Object reference not set to an instance of an object.
   at Akka.MultiNodeTestRunner.Shared.AzureDevOps.TrxSinkActor.ReportFailure(SpecSession session, Dictionary`2 nodeResults)
   at Akka.MultiNodeTestRunner.Shared.AzureDevOps.TrxSinkActor.ReportSpec(SpecSession session, TestRun testRun, String computerName)
   at Akka.MultiNodeTestRunner.Shared.AzureDevOps.TrxSinkActor.HandleEndSpec(EndSpec endSpec)
   at lambda_method(Closure , Object , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 )
   at Akka.Tools.MatchHandler.PartialHandlerArgumentsCapture`11.Handle(T value)
   at Akka.Actor.ReceiveActor.ExecutePartialMessageHandler(Object message, PartialAction`1 partialAction)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
```

Failed during https://dev.azure.com/dotnet/Akka.NET/_build/results?buildId=24678&view=logs&j=dc4e9172-2a93-56ab-8572-2079bd522eec&t=7d446c1b-f726-5de4-2784-d7d7d79a78d2

**Comment by Aaronontheweb** [comment]
Full log file: 
[mntr_nre_fail_log.txt](https://github.com/akkadotnet/akka.net/files/3847538/mntr_nre_fail_log.txt)
