### ISSUE TITLE
PNCounterDictionary can't merge correctly with itself on DeltaPropagation

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#4198]
Found an explicit bug with this test. _Might_ be similar to #4184 but it also might be an issue with the way this test is written. Going to rule out the latter first before filing a new issue.

```
[ERROR][2/10/2020 12:42:05 AM][Thread 0016][akka://ReplicatorPruningSpec/user/replicator] Unable to cast object of type 'Akka.DistributedData.PNCounterDictionary`1[System.String]' to type 'Akka.DistributedData.ORDictionary`2[System.String,Akka.DistributedData.PNCounter]'.
Cause: System.InvalidCastException: Unable to cast object of type 'Akka.DistributedData.PNCounterDictionary`1[System.String]' to type 'Akka.DistributedData.ORDictionary`2[System.String,Akka.DistributedData.PNCounter]'.
   at Akka.DistributedData.ORDictionary`2.Merge(IReplicatedData other) in D:\a\1\s\src\contrib\cluster\Akka.DistributedData\ORDictionary.cs:line 279
   at Akka.DistributedData.Internal.DataEnvelope.Merge(IReplicatedData otherData) in D:\a\1\s\src\contrib\cluster\Akka.DistributedData\Internal\Internal.cs:line 494
   at Akka.DistributedData.Internal.DataEnvelope.Merge(DataEnvelope other) in D:\a\1\s\src\contrib\cluster\Akka.DistributedData\Internal\Internal.cs:line 473
   at Akka.DistributedData.Replicator.Write(String key, DataEnvelope writeEnvelope) in D:\a\1\s\src\contrib\cluster\Akka.DistributedData\Replicator.cs:line 726
   at Akka.DistributedData.Replicator.WriteAndStore(String key, DataEnvelope writeEnvelope, Boolean reply) in D:\a\1\s\src\contrib\cluster\Akka.DistributedData\Replicator.cs:line 679
   at Akka.DistributedData.Replicator.ReceiveGossip(IImmutableDictionary`2 updatedData, Boolean sendBack) in D:\a\1\s\src\contrib\cluster\Akka.DistributedData\Replicator.cs:line 1105
   at lambda_method(Closure , Object , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Object[] )
   at Akka.Tools.MatchHandler.PartialHandlerArgumentsCapture`16.Handle(T value) in D:\a\1\s\src\core\Akka\Util\MatchHandler\PartialHandlerArgumentsCapture.cs:line 761
   at Akka.Actor.ReceiveActor.ExecutePartialMessageHandler(Object message, PartialAction`1 partialAction) in D:\a\1\s\src\core\Akka\Actor\ReceiveActor.cs:line 78
   at Akka.Actor.UntypedActor.Receive(Object message) in D:\a\1\s\src\core\Akka\Actor\UntypedActor.cs:line 27
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message) in D:\a\1\s\src\core\Akka\Actor\ActorBase.cs:line 158
   at Akka.Actor.ActorCell.ReceiveMessage(Object message) in D:\a\1\s\src\core\Akka\Actor\ActorCell.DefaultMessages.cs:line 177
   at Akka.Actor.ActorCell.Invoke(Envelope envelope) in D:\a\1\s\src\core\Akka\Actor\ActorCell.DefaultMessages.cs:line 83
```

_Originally posted by @Aaronontheweb in https://github.com/akkadotnet/akka.net/pull/4196#issuecomment-584203506_

**Comment by Aaronontheweb** [comment]
Looks like this is a bug either with:

1. The way Hyperion is casting the PNCounterDictionary type on deserialization or
2. A bug with the PNCounterDictionary merge function in the first place.

**Comment by Aaronontheweb** [comment]
Strong change that Hyperion isn't the culprit - otherwise this spec should fail:

https://github.com/akkadotnet/akka.net/blob/48ffec286d80a45427ac72ea721fdf4a373d51fb/src/contrib/cluster/Akka.DistributedData.Tests/Serialization/ReplicatedDataSerializerSpec.cs#L183-L192

**Comment by Aaronontheweb** [comment]
```
[Node2:second][FAIL] Akka.DistributedData.Tests.MultiNode.ReplicatorPruningSpec.Pruning_of_CRDT_should_move_data_from_removed_node
[Node2:second][FAIL-EXCEPTION] Type: Xunit.Sdk.TrueException
--> [Node2:second][FAIL-EXCEPTION] Message: Failed: Expected a message of type Akka.DistributedData.UpdateSuccess, but received {ModifyFailure(C, System.InvalidCastException: Unable to cast object of type 'Akka.DistributedData.ORDictionary`2[System.String,Akka.DistributedData.PNCounter]' to type 'Akka.DistributedData.PNCounterDictionary`1[System.String]'.
   at Akka.DistributedData.Dsl.<>c__DisplayClass10_0`1.<Update>b__0(IReplicatedData data) in D:\olympus\akka.net\src\contrib\cluster\Akka.DistributedData\Dsl.cs:line 101
   at Akka.DistributedData.Replicator.ReceiveUpdate(IKey key, Func`2 modify, IWriteConsistency consistency, Object request) in D:\olympus\akka.net\src\contrib\cluster\Akka.DistributedData\Replicator.cs:line 576)} (type Akka.DistributedData.ModifyFailure) instead  from [akka://ReplicatorPruningSpec/user/replicator#2100921841]
```

Ouch - it even fails on an update.

**Comment by Aaronontheweb** [comment]
Figured this one out I think - problem is that all of the delta operations used by the `PNCounterDictionary` are all actually `ORMap<string, PNCounter>` delta operations - therefore we end up in a situation following DeltaPropagation where the object stored is the result of an `ORMap<string, PNCounter>.IDelta` and that's what is stored inside the local data set.

This only happens when a `PNCounterDictionary` is transmitted via a DeltaPropagation before the local node has received a copy of the same object, so the behavior is no consistent.

That `ORMap<string, PNCounter>` object is now the stored object. The ways to fix this are:

1. Ensure that the underlying object stored is always a PNCounterDictionary or
2. Ensure that the PNCounter object can always be safely converted into its underlying type.

Approach number 2 seems like it would be rife with problems, so the approach I'm going to try is having the `PNCounterDictionary` subclass all of the ORDictionary.IDeltaOperation types so we can handle this problem at the type level.

**Comment by Aaronontheweb** [comment]
Fixed the issue - subclassing the `ORDictionary<TKey, PNCounter>.IDeltaOperation` type did the trick.
