### ISSUE TITLE
DData: merging DataEnvelopes during pruning duplicates CRDT values (GCounter)

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#4200]
```
Node2:second][FAIL] Akka.DistributedData.Tests.MultiNode.ReplicatorPruningSpec.Pruning_of_CRDT_should_move_data_from_removed_node
[Node2:second][FAIL-EXCEPTION] Type: Xunit.Sdk.EqualException
--> [Node2:second][FAIL-EXCEPTION] Message: Assert.Equal() Failure
Expected: 9
Actual:   42
--> [Node2:second][FAIL-EXCEPTION] StackTrace:    at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer)
   at Akka.TestKit.AkkaSpecExtensions.ShouldBe[T](T self, T expected, String message)
   at Akka.DistributedData.Tests.MultiNode.ReplicatorPruningSpec.<>c__DisplayClass12_0.<Pruning_of_CRDT_should_move_data_from_removed_node>b__18()
   at Akka.TestKit.TestKitBase.AwaitAssert(Action assertion, Nullable`1 duration, Nullable`1 interval)
   at Akka.DistributedData.Tests.MultiNode.ReplicatorPruningSpec.<>c__DisplayClass12_0.<Pruning_of_CRDT_should_move_data_from_removed_node>b__15()
   at Akka.TestKit.TestKitBase.<>c__DisplayClass155_0.<Within>b__0()
   at Akka.TestKit.TestKitBase.Within[T](TimeSpan min, TimeSpan max, Func`1 function, String hint, Nullable`1 epsilonValue)
   at Akka.TestKit.TestKitBase.Within(TimeSpan min, TimeSpan max, Action action, String hint, Nullable`1 epsilonValue)
   at Akka.TestKit.TestKitBase.Within(TimeSpan max, Action action, Nullable`1 epsilonValue)
   at Akka.DistributedData.Tests.MultiNode.ReplicatorPruningSpec.<>c__DisplayClass12_0.<Pruning_of_CRDT_should_move_data_from_removed_node>b__7()
   at Akka.Remote.TestKit.MultiNodeSpec.RunOn(Action thunk, RoleName[] nodes)
   at Akka.DistributedData.Tests.MultiNode.ReplicatorPruningSpec.Pruning_of_CRDT_should_move_data_from_removed_node()
```

So this issue may have been introduced by #4185 - looks like when the `DataEnvelope` notices that the pruning values are different, we merge them _and update the underlying CRDT_ - instead of just updating the prune value.

_Originally posted by @Aaronontheweb in https://github.com/akkadotnet/akka.net/pull/4196#issuecomment-584457187_

**Comment by Aaronontheweb** [comment]
So what happens here, according to the gossip on one of the nodes that reproduces this failure (two of them produce the same results)

```
[DEBUG][2/11/2020 3:12:19 AM][Thread 0032][akka.tcp://ReplicatorPruningSpec@localhost:61210/user/replicator] Received gossip status from [akka.tcp://ReplicatorPruningSpec@localhost:61209], chunk 1/1 containing [A, C, B]
[DEBUG][2/11/2020 3:12:19 AM][Thread 0033][akka.tcp://ReplicatorPruningSpec@localhost:61210/user/replicator] Received gossip from [akka.tcp://ReplicatorPruningSpec@localhost:61209], containing [A, C, B]
[DEBUG][2/11/2020 3:12:19 AM][Thread 0033][akka.tcp://ReplicatorPruningSpec@localhost:61210/user/replicator] Checking data for [A:DataEnvelope(data=GCounter(9), prunning={UniqueAddress: (akka.tcp://ReplicatorPruningSpec@localhost:61208, 931003603)->Akka.DistributedData.PruningInitialized,})]
[DEBUG][2/11/2020 3:12:19 AM][Thread 0033][akka.tcp://ReplicatorPruningSpec@localhost:61210/user/replicator] Determined local data DataEnvelope(data=GCounter(9), prunning={}) and remote data DataEnvelope(data=GCounter(9), prunning={UniqueAddress: (akka.tcp://ReplicatorPruningSpec@localhost:61208, 931003603)->Akka.DistributedData.PruningInitialized,}) were different.
[DEBUG][2/11/2020 3:12:19 AM][Thread 0033][akka.tcp://ReplicatorPruningSpec@localhost:61210/user/replicator] Merged into DataEnvelope(data=GCounter(9), prunning={UniqueAddress: (akka.tcp://ReplicatorPruningSpec@localhost:61208, 931003603)->Akka.DistributedData.PruningInitialized,})
```

Received `PruningInitialized` for the GCounter from the leader. So far so good. Next round of gossip:

```
[DEBUG][2/11/2020 3:12:20 AM][Thread 0033][akka.tcp://ReplicatorPruningSpec@localhost:61210/user/replicator] Checking data for [A:DataEnvelope(data=GCounter(9), prunning={})]
[DEBUG][2/11/2020 3:12:20 AM][Thread 0033][akka.tcp://ReplicatorPruningSpec@localhost:61210/user/replicator] Determined local data DataEnvelope(data=GCounter(9), prunning={UniqueAddress: (akka.tcp://ReplicatorPruningSpec@localhost:61208, 931003603)->Akka.DistributedData.PruningInitialized,}) and remote data DataEnvelope(data=GCounter(9), prunning={}) were different.
[DEBUG][2/11/2020 3:12:20 AM][Thread 0033][akka.tcp://ReplicatorPruningSpec@localhost:61210/user/replicator] Merged into DataEnvelope(data=GCounter(12), prunning={UniqueAddress: (akka.tcp://ReplicatorPruningSpec@localhost:61208, 931003603)->Akka.DistributedData.PruningInitialized,})
```

Leader node has completed its pruning - we have not, probably because on non-leader nodes `Replicator.PerformRemovedNodePruning()` and `ReplicatorDeleteObsoletePruningPerformed()` both get called first on non-leader nodes before receiving the results of `Replicator.InitRemovedNodePruning()` from the leader. 

The problem appears to be one or both of the following:

1. Don't keep a tombstone of pruning once it's been fully performed, therefore any record of it happening doesn't get shared correctly with the other nodes and / or
2. The merge function is sensitive to ordering on the pruning information, when it shouldn't be given that these events will occur asynchronously with each other.

Going to try to tackle item 1 on this list first.

**Comment by Aaronontheweb** [comment]
Looking at the Replicator.PerformRemovedNodePruning() and ReplicatorDeleteObsoletePruningPerformed() code - looks to me like it does the right thing. Problem must be item 1 - that the tombstones get removed right away. Might be a date calculation problem with the "obsolete" timestamp being wrong.
