### ISSUE TITLE
Remote Association Error [Failed to write message to the transport] (Collection was modified; enumeration operation may not execute)

### ISSUE THREAD

**Issue by blackclavus** [akkadotnet/akka.net#4218]
(Sorry If I can't write a better title for this issue, but here is the explanation)

Sometimes, the system failed to send a message through Remote Actor and then failed to restore the connection. I don't know yet how to reproduce it, but it does happen sometimes.

Here is the log & stack trace:

```
[ERROR][02/14/2020 08:04:08][Thread 0009][[akka://fss-meta/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FFssFrontActorSystem%400.0.0.0%3A44907-1/endpointWriter#1740789249]] AssociationError [akka.tcp://fss-meta@fss.meta:38700] <- akka.tcp://FssFrontActorSystem@0.0.0.0:44907: Error [Failed to write message to the transport] []
Cause: Unknown
[WARNING][02/14/2020 08:04:08][Thread 0009][[akka://fss-meta/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FFssFrontActorSystem%400.0.0.0%3A44907-1#1483600799]] Association with remote system akka.tcp://FssFrontActorSystem@0.0.0.0:44907 has failed; address is now gated for 5000 ms. Reason is: [Akka.Remote.EndpointException: Failed to write message to the transport ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Hyperion.SerializerFactories.EnumerableSerializerFactory.<>c__DisplayClass10_0.<BuildSerializer>b__3(Stream stream, Object o, SerializerSession session)
   at Hyperion.Extensions.StreamEx.WriteObject(Stream stream, Object value, Type valueType, ValueSerializer valueSerializer, Boolean preserveObjectReferences, SerializerSession session)
   at lambda_method(Closure , Stream , Object , SerializerSession )
   at Hyperion.Extensions.StreamEx.WriteObject(Stream stream, Object value, Type valueType, ValueSerializer valueSerializer, Boolean preserveObjectReferences, SerializerSession session)
   at Akka.Serialization.HyperionSerializer.ToBinary(Object obj)
   at Akka.Remote.MessageSerializer.Serialize(ExtendedActorSystem system, Address address, Object message)
   at Akka.Remote.EndpointWriter.WriteSend(Send send)
   --- End of inner exception stack trace ---
   at Akka.Remote.EndpointWriter.PublishAndThrow(Exception reason, LogLevel level, Boolean needToThrow)
   at Akka.Remote.EndpointWriter.WriteSend(Send send)
   at Akka.Remote.EndpointWriter.<Writing>b__27_0(Send s)
   at lambda_method(Closure , Object , Action`1 , Action`1 , Action`1 )
   at Akka.Actor.ReceiveActor.ExecutePartialMessageHandler(Object message, PartialAction`1 partialAction)
   at Akka.Actor.ActorCell.<>c__DisplayClass106_0.<Akka.Actor.IUntypedActorContext.Become>b__0(Object m)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)]
[ERROR][02/14/2020 08:04:08][Thread 0009][akka://fss-meta/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FFssFrontActorSystem%400.0.0.0%3A44907-1/endpointWriter] Failed to write message to the transport
Cause: Akka.Remote.EndpointException: Failed to write message to the transport ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Hyperion.SerializerFactories.EnumerableSerializerFactory.<>c__DisplayClass10_0.<BuildSerializer>b__3(Stream stream, Object o, SerializerSession session)
   at Hyperion.Extensions.StreamEx.WriteObject(Stream stream, Object value, Type valueType, ValueSerializer valueSerializer, Boolean preserveObjectReferences, SerializerSession session)
   at lambda_method(Closure , Stream , Object , SerializerSession )
   at Hyperion.Extensions.StreamEx.WriteObject(Stream stream, Object value, Type valueType, ValueSerializer valueSerializer, Boolean preserveObjectReferences, SerializerSession session)
   at Akka.Serialization.HyperionSerializer.ToBinary(Object obj)
   at Akka.Remote.MessageSerializer.Serialize(ExtendedActorSystem system, Address address, Object message)
   at Akka.Remote.EndpointWriter.WriteSend(Send send)
   --- End of inner exception stack trace ---
   at Akka.Remote.EndpointWriter.PublishAndThrow(Exception reason, LogLevel level, Boolean needToThrow)
   at Akka.Remote.EndpointWriter.WriteSend(Send send)
   at Akka.Remote.EndpointWriter.<Writing>b__27_0(Send s)
   at lambda_method(Closure , Object , Action`1 , Action`1 , Action`1 )
   at Akka.Actor.ReceiveActor.ExecutePartialMessageHandler(Object message, PartialAction`1 partialAction)
   at Akka.Actor.ActorCell.<>c__DisplayClass106_0.<Akka.Actor.IUntypedActorContext.Become>b__0(Object m)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
```

Before it happens, usually there are hundreds messages like this
```
[DEBUG][02/14/2020 08:04:05][Thread 0007][[akka://fss-meta/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FFssFrontActorSystem%400.0.0.0%3A44907-1/endpointWriter#1740789249]] Drained buffer with maxWriteCount: 50, fullBackoffCount: 4,smallBackoffCount: 1, noBackoffCount: 1,adaptiveBackoff: 2000
[DEBUG][02/14/2020 08:04:05][Thread 0008][[akka://fss-meta/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FFssFrontActorSystem%400.0.0.0%3A44907-1/endpointWriter#1740789249]] Drained buffer with maxWriteCount: 50, fullBackoffCount: 2,smallBackoffCount: 1, noBackoffCount: 0,adaptiveBackoff: 2000
[DEBUG][02/14/2020 08:04:05][Thread 0006][[akka://fss-meta/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FFssFrontActorSystem%400.0.0.0%3A44907-1/endpointWriter#1740789249]] Drained buffer with maxWriteCount: 50, fullBackoffCount: 3,smallBackoffCount: 1, noBackoffCount: 0,adaptiveBackoff: 2000
[DEBUG][02/14/2020 08:04:06][Thread 0008][[akka://fss-meta/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FFssFrontActorSystem%400.0.0.0%3A44907-1/endpointWriter#1740789249]] Drained buffer with maxWriteCount: 50, fullBackoffCount: 12,smallBackoffCount: 1, noBackoffCount: 2,adaptiveBackoff: 2000
```

**Version Info**
Akka: 1.3.17
Akka.Remote: 1.3.17
Akka.Serialization.Hyperion: 1.3.7-beta64

Please tell me if there's a lack of information, so maybe I could add more, and if there's a suggestion what I should do / try in my code.

PS. I'm aware about this bug #2345 but I'm not sure if it related to this issue

Thanks

**Comment by Aaronontheweb** [comment]
Hi @blackclavus - this looks like a Hyperion bug. I'm going to create an issue there that cross-references this one.

**Comment by Aaronontheweb** [comment]
Just because this will be helpful later when debugging:

- Have you seen this issue when you've upgraded to a more recent version of Akka.Serialization.Hyperion? i.e. https://www.nuget.org/packages/Akka.Serialization.Hyperion/1.3.17-beta
- What does the data structure you're serializing look like? That'll help us find the issue in Hyperion.

**Comment by blackclavus** [comment]
Thank you @Aaronontheweb, sorry for the late reply. 
- I haven't tried to upgrade to recent version of Akka.Serialization.Hyperion, but I'll try as soon as I'm at office. 
- The data structure kinda look like this

```csharp
public class Inventory
{
    public List<IInventoryItemBase> Items { get; set; }
}
```

Now you mention it's Hyperion's bug; if there's a collection modification while class is being serialized, will it trigger this exception? I think I'll investigate the code for this possibility, and will report it here.

**Comment by Aaronontheweb** [comment]
Did you get a chance to try this with the updated version of Hyperion @blackclavus ?

**Comment by blackclavus** [comment]
Sorry for the late reply.

I got a problem while upgrading Hyperion.
```
Install-Package : NU1605: Detected package downgrade: System.Runtime from 4.3.1 to 4.3.0. Reference the package directly from the project to select a different version. 
```

**Comment by Aaronontheweb** [comment]
Weird, must be an issue with another package you have installed - Hyperion uses the latest:

https://github.com/akkadotnet/Hyperion/blob/3a08ddee7fded5bd15f29a1ba7bba6823d92273c/src/Hyperion/Hyperion.csproj#L16-L18

Also, we've concluded that this isn't a Hyperion bug - the problem is that the collection you're including your message is, itself, mutable - and thus can be modified while it's being serialized. Please be sure to copy your `List` into a new collection before sending it so this type of side-effect can't happen. Does that make sense?
