### ISSUE TITLE
Akka.Cluster.Metrics.Collector Exception: Hocon NullReferenceException

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#4241]
Version: Akka.NET v1.4.0-RC1

Ran into this error a number of times while running the MNTR on this PR and some others https://github.com/akkadotnet/akka.net/pull/4212

```
[Node #4(node-4)]Cause: [akka://ClusterMetricsEnabledSpec/system/cluster-metrics/collector-1#1982669716]: Akka.Actor.ActorInitializationException: Exception during creation ---> System.TypeLoadException: Error while creating actor instance of type Akka.Cluster.Metrics.ClusterMetricsCollector with 0 args: () ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
[Node #4(node-4)]   at Hocon.Config.GetConfig(HoconPath path)
[Node #4(node-4)]   at Akka.Cluster.Metrics.Configuration.ClusterMetricsSettings..ctor(Config config)
[Node #4(node-4)]   at Akka.Cluster.Metrics.MetricsCollectorBuilder.Build(ActorSystem system)
[Node #4(node-4)]   at Akka.Cluster.Metrics.ClusterMetricsCollector..ctor()
[Node #4(node-4)]   --- End of inner exception stack trace ---
[Node #4(node-4)]   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
[Node #4(node-4)]   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
[Node #4(node-4)]   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
[Node #4(node-4)]   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
[Node #4(node-4)]   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
[Node #4(node-4)]   at System.Activator.CreateInstance(Type type, Object[] args)
[Node #4(node-4)]   at Akka.Actor.Props.ActivatorProducer.Produce()
[Node #4(node-4)]   at Akka.Actor.Props.NewActor()
[Node #4(node-4)]   --- End of inner exception stack trace ---
[Node #4(node-4)]   at Akka.Actor.Props.NewActor()
[Node #4(node-4)]   at Akka.Actor.ActorCell.CreateNewActorInstance()
[Node #4(node-4)]   at Akka.Actor.ActorCell.<>c__DisplayClass117_0.<NewActor>b__0()
[Node #4(node-4)]   at Akka.Actor.ActorCell.UseThreadContext(Action action)
[Node #4(node-4)]   at Akka.Actor.ActorCell.NewActor()
[Node #4(node-4)]   at Akka.Actor.ActorCell.Create(Exception failure)
[Node #4(node-4)]   --- End of inner exception stack trace ---
[Node #4(node-4)]   at Akka.Actor.ActorCell.Create(Exception failure)
[Node #4(node-4)]   at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState)
```

I think we just need to update the `GetConfig` method to be a `TryGet` call instead, perhaps. Or this issue might be related to some of the other "racy" issues we've detected with `Config` such as https://github.com/akkadotnet/HOCON/issues/233 and https://github.com/akkadotnet/HOCON/issues/234

**Comment by Aaronontheweb** [comment]
Resolved via https://github.com/akkadotnet/akka.net/pull/4248
