### ISSUE TITLE
ORMultiValueDictionary - DistributedData Serialization InvalidCastException Unable to cast object of type 'DeltaGroup[System.String]' to type 'Akka.DistributedData.ORSet1[System.String]'

### ISSUE THREAD

**Issue by huzaifak** [akkadotnet/akka.net#4367]
- Which Akka.Net version you are using
1.4.4

- On which platform you are using Akka.Net
net 4.7

We are using Distributed registry and have a ORMultiValueDictionary collection. And often we see the below error logged in the akka logs. 

[System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Unable to cast object of type 'DeltaGroup[System.String]' to type 'Akka.DistributedData.ORSet1[System.String]'. at Akka.DistributedData.Serialization.ReplicatedDataSerializer.<>c__DisplayClass95_02.<GenericORDictionaryDeltaGroupFromProto>gMapEntryFromProto|0(MapEntry entry)
at System.Linq.Enumerable.<>cDisplayClass7_03.<CombineSelectors>b__0(TSource x) at System.Linq.Enumerable.WhereSelectEnumerableIterator2.MoveNext()
at System.Collections.Immutable.ImmutableDictionary2.AddRange(IEnumerable1 items, MutationInput origin, KeyCollisionBehavior collisionBehavior)
at System.Collections.Immutable.ImmutableDictionary2.AddRange(IEnumerable1 pairs, Boolean avoidToHashMap)
at System.Collections.Immutable.ImmutableDictionary.ToImmutableDictionaryTSource,TKey,TValue
at Akka.DistributedData.Serialization.ReplicatedDataSerializer.GenericORDictionaryDeltaGroupFromProtoTKey,TValue
--- End of inner exception stack trace ---
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at Akka.DistributedData.Serialization.ReplicatedDataSerializer.ORDictionaryDeltaGroupFromProto(ORMapDeltaGroup deltaGroup)
at Akka.DistributedData.Serialization.ReplicatedDataSerializer.ORMultiDictionaryDeltaFromBinary(Byte[] bytes)
at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
at Akka.DistributedData.Serialization.ReplicatorMessageSerializer.DataEnvelopeFromProto(DataEnvelope proto)
at Akka.DistributedData.Serialization.ReplicatorMessageSerializer.DeltaPropagationFromBinary(Byte[] bytes)
at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
at Akka.Remote.Serialization.MessageContainerSerializer.FromBinary(Byte[] bytes, Type type)
at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
at Akka.Remote.DefaultMessageDispatcher.Dispatch(IInternalActorRef recipient, Address recipientAddress, Payload message, IActorRef senderOption)
at Akka.Remote.EndpointReader.<Reading>b__11_0(InboundPayload inbound)
at lambda_method(Closure , Object , Action1 , Action1 , Action1 ) at Akka.Tools.MatchHandler.PartialHandlerArgumentsCapture4.Handle(T value)
at Akka.Actor.ReceiveActor.ExecutePartialMessageHandler(Object message, PartialAction`1 partialAction)
at Akka.Actor.UntypedActor.Receive(Object message)
at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
at Akka.Actor.ActorCell.ReceiveMessage(Object message)
at Akka.Actor.ActorCell.Invoke(Envelope envelope)

**Comment by Arkatufus** [comment]
@huzaifak I'm having trouble reproducing this bug, can you give us more information? Maybe a snippet of your configuration and codes on how you manipulate the ORMultiValueDisctionary instance?

**Comment by huzaifak** [comment]
we have a simple ORMultiValueDictionary<string, string> below is a snip it of the set function we use when setting the values in the registry. Please note we use a cluster with singleton performing most set operations and other nodes in the cluster are enabled for delta replication. however the error above is seen/logged on the singleton.

TKey and TVal are defined as string for this instance.

public async Task<bool> SetEntryCoreAsync(TKey key, IImmutableSet<TVal> vals, IWriteConsistency consistency, ActorSystem actorSystem)
{
	var registryKey = new ORMultiValueDictionaryKey<TKey, TVal>("someregistry");
	var c = Cluster.Get(actorSystem);
	var r = DistributedData.Get(actorSystem);
	var m = await r.Replicator.Ask<IUpdateResponse>(
		Dsl.Update(
			registryKey,
			ORMultiValueDictionary<TKey, TVal>.EmptyWithValueDeltas,
			consistency,
			s => s.SetItems(c.SelfUniqueAddress, key, vals)));

	return m.IsSuccessful;
}

We also create a separate actor that registers with the replicator for all changes.
ORMultiValueDictionaryKey<string, string> DefaultRegistryKey = new ORMultiValueDictionaryKey<string, string>("someregistry");

var r = DistributedData.Get(ActorSystem);
r.Replicator.Tell(Dsl.Subscribe(DefaultRegistryKey, Self));

Receive<Changed>(c =>{ 
c.Get(DefaultRegistryKey);
});
and in the same actor we register for the changed message where we pull the changes for our internal cache update. above is a simplified code version.

HOCON configuration.
akka {
	loggers = ["Akka.Logger.NLog.NLogLogger, Akka.Logger.NLog"]
	loglevel = DEBUG
		stdout - loglevel = DEBUG
		extensions = ["Akka.Cluster.Tools.PublishSubscribe.DistributedPubSubExtensionProvider, Akka.Cluster.Tools", "Akka.DistributedData.DistributedDataProvider, Akka.DistributedData"]
		cluster - dispatcher {
		type = ForkJoinDispatcher
			dedicated - thread - pool {
			thread - count = 8
				threadtype = background
		}
	}
	ddata - dispatcher {
		type = ForkJoinDispatcher
			dedicated - thread - pool {
			thread - count = 8
				threadtype = background
		}
	}
	actor {
		provider = "Akka.Cluster.ClusterActorRefProvider, Akka.Cluster"
			serializers {
			hyperion = "Akka.Serialization.HyperionSerializer, Akka.Serialization.Hyperion"
		}
		serialization - bindings {
			"System.Object" = hyperion
		}
		deployment {
			/jobeventstore-reader-router-pool {
			router = round-robin-pool
			resizer {
			enabled = on
			lower-bound = 1
			upper-bound = 4
			}
			}
			/jobeventstore - updater - router - pool {
				router = round - robin - pool
					resizer {
					enabled = on
						lower - bound = 1
						upper - bound = 4
				}
			}
			/notification-sender-router-pool {
			router = round-robin-pool
			nr-of-instances = 4
			cluster {
			enabled = on
			allow-local-routees = on
			max-nr-of-instances-per-node = 2
			}
			}
			}
			debug {
			receive = on
			autoreceive = on
			lifecycle = on
			event-stream = on
			unhandled = on
			}
			}
			remote {
			enabled-transports = ["akka.remote.dot-netty.tcp"]
			log-remote-lifecycle-events = DEBUG
			dot-netty.tcp {
			transport-protocol = tcp
			enable-pooling = false
			tcp-reuse-addr = on
			enforce-ip-family = true
			public-hostname = "2ua7252rnd.somedomain.com"
			hostname = "0.0.0.0"
			port = 9901
			ssl {
			suppress-validation = true
			certificate {
			path = "jobdispatcher.cer"
			}
			}
			maximum-frame-size = 1048576b
			}
			}
			cluster {
			debug {
			verbose-heartbeat-logging = on
			}
			use-dispatcher = akka.cluster-dispatcher
			seed-nodes = ["akka.tcp://JobDispatcherSystem@LAXQAX-MTIR1001.somedomain.com:9901","akka.tcp://JobtestSystem@laxmtir1002.somedomain.com:9901","akka.tcp://JobtestSystem@laxmtir1003.somedomain.com:9901","akka.tcp://JobtestSystem@2UA7252RND.somedomain.com:9901"]
			gossip-interval = 1s
			allow-weakly-up-members = on
			downing-provider-class = "Akka.Cluster.SplitBrainResolver, Akka.Cluster"
			down-removal-margin = 12s
			split-brain-resolver {
			active-strategy = static-quorum
			stable-after = 12s
			static-quorum {
			quorum-size = 3
			}
			}
			failure-detector {
			heartbeat-interval = 1s
			acceptable-heartbeat-pause = 30s
			}
			singleton {
			singleton-name = "CoreSingletonManager"
			hand-over-retry-interval = 1s
			min-number-of-hand-over-retries = 8
			}
			singleton-proxy {
			singleton-name = "CoreSingletonManager"
			singleton-identification-interval = 1s
			buffer-size = 1024
			}
			pub-sub {
			gossip-interval = 1s
			removed-time-to-live = 30s
			max-delta-elements = 128
			}
			distributed-data {
			use-dispatcher = akka.ddata-dispatcher
			gossip-interval = 15s
			serializer-cache-time-to-live = 120s
			delta-crdt {
				enabled = on
				max-delta-elements = 512
			}

				}
			}
			}

**Comment by huzaifak** [comment]
@Arkatufus i will also try and setup a standlone repro setup also too see if it can help.

**Comment by Arkatufus** [comment]
@huzaifak thank you for the info :)

**Comment by Arkatufus** [comment]
@huzaifak 
Can you change `ORMultiValueDictionary<string, string>.EmptyWithValueDeltas` to `ORMultiValueDictionary<string, string>.Empty` when you call `Dsl.Update()` and see if the problem presists?

**Comment by huzaifak** [comment]
@Arkatufus thanks for the suggestion i will give it a try, the issue is not very easily reproducible in our environment as well so will put the new code out and let you know how it goes.

**Comment by huzaifak** [comment]
@Arkatufus i did try the suggested change and still saw the below error logged. 
Please note the error was logged on laxqax-4002 which is a standby node in the cluster and laxqax-4001 was the singleton at the time. no error was logged on the singleton server.

2020-04-22 07:35:08.6375 Akka.Remote.ReliableDeliverySupervisor Association with remote system akka.tcp://JobDispatcherSystem@laxqax-4001.somedomain.com:9901 has failed; address is now gated for 5000 ms. Reason is: [System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Unable to cast object of type 'DeltaGroup[System.String]' to type 'Akka.DistributedData.ORSet`1[System.String]'.
   at Akka.DistributedData.Serialization.ReplicatedDataSerializer.<>c__DisplayClass95_0`2.<GenericORDictionaryDeltaGroupFromProto>g__MapEntryFromProto|0(MapEntry entry)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 items, MutationInput origin, KeyCollisionBehavior collisionBehavior)
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 pairs, Boolean avoidToHashMap)
   at System.Collections.Immutable.ImmutableDictionary.ToImmutableDictionary[TSource,TKey,TValue](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Akka.DistributedData.Serialization.ReplicatedDataSerializer.GenericORDictionaryDeltaGroupFromProto[TKey,TValue](ORMapDeltaGroup deltaGroup)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Akka.DistributedData.Serialization.ReplicatedDataSerializer.ORDictionaryDeltaGroupFromProto(ORMapDeltaGroup deltaGroup)
   at Akka.DistributedData.Serialization.ReplicatedDataSerializer.ORMultiDictionaryDeltaFromBinary(Byte[] bytes)
   at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
   at Akka.DistributedData.Serialization.ReplicatorMessageSerializer.DataEnvelopeFromProto(DataEnvelope proto)
   at Akka.DistributedData.Serialization.ReplicatorMessageSerializer.DeltaPropagationFromBinary(Byte[] bytes)
   at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
   at Akka.Remote.Serialization.MessageContainerSerializer.FromBinary(Byte[] bytes, Type type)
   at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
   at Akka.Remote.DefaultMessageDispatcher.Dispatch(IInternalActorRef recipient, Address recipientAddress, Payload message, IActorRef senderOption)
   at Akka.Remote.EndpointReader.<Reading>b__11_0(InboundPayload inbound)
   at lambda_method(Closure , Object , Action`1 , Action`1 , Action`1 )
   at Akka.Tools.MatchHandler.PartialHandlerArgumentsCapture`4.Handle(T value)
   at Akka.Actor.ReceiveActor.ExecutePartialMessageHandler(Object message, PartialAction`1 partialAction)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Akka.Actor.ActorCell.HandleFailed(Failed f)
   at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState)]

**Comment by Arkatufus** [comment]
Ok, I'll look into it more, thank you

**Comment by huzaifak** [comment]
Here is another method we use to add an entry in the collection for a key that already exists.

public async Task<bool> SetEntryAddCoreAsync(string key, string val, IWriteConsistency consistency, ActorSystem actorSystem)
        {
			var registryKey = new ORMultiValueDictionaryKey<string, string>("someregistry");
            var c = Cluster.Get(actorSystem);
            var r = DistributedData.Get(actorSystem);
            var m = await r.Replicator.Ask<IUpdateResponse>(
                Dsl.Update(
                    registryKey,
                    ORMultiValueDictionary<string, string>.EmptyWithValueDeltas,
                    consistency,
                    s => s.AddItem(c, key, val)));

            return m.IsSuccessful;
        }

Note as per the suggestion i have tried using ORMultiValueDictionary<string, string>.Empty, and still got the error.

**Comment by Arkatufus** [comment]
Sorry for the long delay, I've managed to reproduce the bug, and it turns out it's quite complicated to fix.

**Comment by huzaifak** [comment]
@Arkatufus, at least glad to hear its reproducible. hope it can be fixed.

**Comment by Arkatufus** [comment]
We're working on it, sorry for the long delay.

**Comment by Aaronontheweb** [comment]
Going to release Akka.NET v1.4.5 tonight, which includes this fix.
