### ISSUE TITLE
Sink probe does not receive data

### ISSUE THREAD

**Issue by nomailme** [akkadotnet/akka.net#4583]
Akka.Streams 1.4.10
Akka.Streams.TestKit 1.4.10
Platform: Windows

Getting weird results running this test. A code is bellow

```
        [Fact]
        public async Task Test1()
        {
            var mat = Sys.Materializer();
            var graph = GraphDsl.Create(builder =>
            {
                var merge = builder.Add(new Merge<string>(2,true));
                var partition = builder.Add(new Partition<string>(2, item => item.Length > 2 ? 0 : 1));
                var flow0 = Flow.Create<string>().Async().Select(x => string.Join(",", x, x));
                var flow1 = Flow.Create<string>().Async().Select(x => x);

                builder.From(partition.Out(0)).Via(flow0).To(merge);
                builder.From(partition.Out(1)).Via(flow1).To(merge);

                return new FlowShape<string, string>(partition.In, merge.Out);
            });

            var source = this.SourceProbe<string>();
            var tuple = source
                .Via(graph)
                .RunWith(this.SinkProbe<string>(), mat);
                
                tuple.RequestNext("x")
                .ExpectNextOrError("x",null);
                
        }
```

I get exception

```
Xunit.Sdk.TrueException
Failed: Timeout 00:00:03 while waiting for a message of type Akka.Streams.TestKit.TestSubscriber+OnNext`1[System.String] 
Expected: True
Actual:   False
   at Akka.TestKit.Xunit.XunitAssertions.Fail(String format, Object[] args)
   at Akka.TestKit.TestKitBase.InternalExpectMsgEnvelope[T](Nullable`1 timeout, Action`2 assert, String hint, Boolean shouldLog)
   at Akka.TestKit.TestKitBase.InternalExpectMsgEnvelope[T](Nullable`1 timeout, Action`1 msgAssert, Action`1 senderAssert, String hint)
   at Akka.TestKit.TestKitBase.InternalExpectMsg[T](Nullable`1 timeout, Action`1 msgAssert, String hint)
   at Akka.TestKit.TestKitBase.ExpectMsg[T](Action`1 assert, Nullable`1 timeout, String hint)
   at Akka.Streams.TestKit.TestSubscriber.ManualProbe`1.ExpectNext(T element, Nullable`1 timeout)
   at Akka.Streams.TestKit.TestSubscriber.Probe`1.RequestNext(T element)
   at StreamsPlayground.PartionFlow.Test1() in C:\work\AkkaStreamsAspNetCore\src\StreamsPlayground\PartionFlow.cs:line 40
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
--- End of stack trace from previous location where exception was thrown ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90

```

It works well if I use Sink.First<>()

**Comment by Arkatufus** [comment]
@nomailme 
I think you can re-arrange your code like this, and it should work:
```C#
        [Fact]
        public void Test1()
        {
            var mat = Sys.Materializer();
            var graph = GraphDsl.Create(builder =>
            {
                var merge = builder.Add(new Merge<string>(2, true));
                var partition = builder.Add(new Partition<string>(2, item => item.Length > 2 ? 0 : 1));
                var flow0 = Flow.Create<string>().Async().Select(x => string.Join(",", x, x));
                var flow1 = Flow.Create<string>().Async().Select(x => x);

                builder.From(partition.Out(0)).Via(flow0).To(merge);
                builder.From(partition.Out(1)).Via(flow1).To(merge);

                return new FlowShape<string, string>(partition.In, merge.Out);
            });

            var flow = Flow.FromGraph(graph);
            var (source, sink) = this.SourceProbe<string>()
                .Via(flow)
                .ToMaterialized(this.SinkProbe<string>(), Keep.Both)
                .Run(mat);

            sink.Request(99);
            source.SendNext("x");
            sink.ExpectNext("x");
            source.SendNext("xxx");
            sink.ExpectNext("xxx,xxx");
        }
```

**Comment by Arkatufus** [comment]
@nomailme I'm going to close this issue, you can re-open it if you're still having problem.
