### ISSUE TITLE
KeyNotFoundException thrown periodically.

### ISSUE THREAD

**Issue by tesgu** [akkadotnet/akka.net#4639]
Hi team, we are using Akka.net distributed data to implement a distributed cache. 

It is running in a cluster of three machines, implemented as a worker service in an asp.net core 3.1 application.

The version of the components we are using:
Akka -> 1.4.11
Akka.Remote -> 1.4.11
Akka.Cluster -> 1.4.11
Akka.DistributedData -> 1.4.11

It eventually starts periodically to throw a KeyNotFoundException. At this moment the distributed cache is deployed in production without any clients, so it seems something of the background maintenance (prunning maybe?).
For us is quite difficult to reproduce the issue as it is happening only in production and without any intervention from our side. 

If it helps, this is the exception is throwing. This occurs every 1 minute and a half, we haven't modified the default Distributed Data configuration.

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Akka.DistributedData.Internal.DataEnvelope.Equals(DataEnvelope other)
   at System.ValueTuple`2.Equals(ValueTuple`2 other)
   at System.Collections.Immutable.ImmutableDictionary`2.Comparers.Equals(HashBucket x, HashBucket y)
   at System.Collections.Immutable.SortedInt32KeyNode`1.SetOrAdd(Int32 key, TValue value, IEqualityComparer`1 valueComparer, Boolean overwriteExistingValue, Boolean& replacedExistingValue, Boolean& mutated)
   at System.Collections.Immutable.SortedInt32KeyNode`1.SetItem(Int32 key, TValue value, IEqualityComparer`1 valueComparer, Boolean& replacedExistingValue, Boolean& mutated)
   at System.Collections.Immutable.ImmutableDictionary`2.UpdateRoot(SortedInt32KeyNode`1 root, Int32 hashCode, HashBucket newBucket, IEqualityComparer`1 hashBucketComparer)
   at System.Collections.Immutable.ImmutableDictionary`2.Add(TKey key, TValue value, KeyCollisionBehavior behavior, MutationInput origin)
   at System.Collections.Immutable.ImmutableDictionary`2.SetItem(TKey key, TValue value)
   at Akka.DistributedData.Replicator.SetData(String key, DataEnvelope envelope)
   at Akka.DistributedData.Replicator.InitRemovedNodePruning()
   at Akka.DistributedData.Replicator.ReceiveRemovedNodePruningTick()
   at lambda_method(Closure , Object , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Object[] )
   at Akka.Tools.MatchHandler.PartialHandlerArgumentsCapture`16.Handle(T value)
   at Akka.Actor.ReceiveActor.ExecutePartialMessageHandler(Object message, PartialAction`1 partialAction)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)

**Comment by Aaronontheweb** [comment]
@tesgu I think we had someone raise this on another issue where we fixed one of these before - I'll file it as a bug and we'll try to get it fixed in the next point release. Should be straightforward to find.

**Comment by tesgu** [comment]
Thanks @Aaronontheweb
