### ISSUE TITLE
Akka 1.4.12 and 1.4.13 System.NullReferenceException System.OutOfMemoryException 

### ISSUE THREAD

**Issue by ArturChe** [akkadotnet/akka.net#4682]
Hi all.

We have a project based on Akka 1.4.11.
When updating it to 1.4.12 or 1.4.13 we observing that some unit-test failing with error and some are just don't want to stop (running infinitely).

Here is the stack trace from some of the failed tests:
```
System.AggregateException : One or more errors occurred.
  ----> System.AggregateException : One or more errors occurred.
  ----> System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> System.InvalidOperationException : failed to create a child event loop.
  ----> System.Threading.Tasks.TaskSchedulerException : An exception was thrown by a TaskScheduler.
  ----> System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Akka.Remote.Remoting.Start()
   at Akka.Remote.RemoteActorRefProvider.Init(ActorSystemImpl system)
   at Akka.Cluster.ClusterActorRefProvider.Init(ActorSystemImpl system)
   at Akka.Actor.Internal.ActorSystemImpl.Start()
   at Akka.Actor.ActorSystem.CreateAndStartSystem(String name, Config withFallback, ActorSystemSetup setup)
   at Akka.Actor.ActorSystem.Create(String name, ActorSystemSetup setup)
   at Akka.TestKit.TestKitBase.InitializeTest(ActorSystem system, ActorSystemSetup config, String actorSystemName, String testActorName)
   at Akka.TestKit.TestKitBase.InitializeTest(ActorSystem system, Config config, String actorSystemName, String testActorName)
   at Akka.TestKit.NUnit3.TestKit.InitializeActorSystemOnSetUp()
--AggregateException

--TargetInvocationException
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Akka.Remote.EndpointManager.get_Listens()
--- End of stack trace from previous location where exception was thrown ---
   at Akka.Remote.EndpointManager.<>c__DisplayClass47_0.<get_Listens>b__4()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--InvalidOperationException
   at DotNetty.Transport.Channels.MultithreadEventLoopGroup..ctor(Func`2 eventLoopFactory, Int32 eventLoopCount)
   at Akka.Remote.Transport.DotNetty.DotNettyTransport..ctor(ActorSystem system, Config config)
   at Akka.Remote.Transport.DotNetty.TcpTransport..ctor(ActorSystem system, Config config)
--TaskSchedulerException
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
   at System.Threading.Tasks.Task.InternalStartNew(Task creatingTask, Delegate action, Object state, CancellationToken cancellationToken, TaskScheduler scheduler, TaskCreationOptions options, InternalTaskOptions internalOptions, StackCrawlMark& stackMark)
   at System.Threading.Tasks.TaskFactory.StartNew(Action action, CancellationToken cancellationToken, TaskCreationOptions creationOptions, TaskScheduler scheduler)
   at DotNetty.Common.Concurrency.XThread.CreateLongRunningTask(XParameterizedThreadStart threadStartFunc)
   at DotNetty.Common.Concurrency.XThread..ctor(Action action)
   at DotNetty.Common.Concurrency.SingleThreadEventExecutor..ctor(IEventExecutorGroup parent, String threadName, TimeSpan breakoutInterval, IQueue`1 taskQueue)
   at DotNetty.Transport.Channels.SingleThreadEventLoop..ctor(IEventLoopGroup parent)
   at DotNetty.Transport.Channels.MultithreadEventLoopGroup.<>c.<.cctor>b__21_0(IEventLoopGroup group)
   at DotNetty.Transport.Channels.MultithreadEventLoopGroup..ctor(Func`2 eventLoopFactory, Int32 eventLoopCount)
--OutOfMemoryException
   at System.Threading.Thread.StartInternal(IPrincipal principal, StackCrawlMark& stackMark)
   at System.Threading.Thread.Start(StackCrawlMark& stackMark)
   at System.Threading.Thread.Start(Object parameter)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.QueueTask(Task task)
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
--TearDown
   at Akka.TestKit.TestKitBase.Dilated(TimeSpan duration)
   at Akka.TestKit.TestKitBase.Shutdown(ActorSystem system, Nullable`1 duration, Boolean verifySystemShutdown)
   at Akka.TestKit.TestKitBase.Shutdown(Nullable`1 duration, Boolean verifySystemShutdown)
   at Akka.TestKit.NUnit3.TestKit.AfterAll()
   at Akka.TestKit.NUnit3.TestKit.ShutDownActorSystemOnTearDown()

System.AggregateException : One or more errors occurred.
  ----> System.AggregateException : One or more errors occurred.
  ----> System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> System.InvalidOperationException : failed to create a child event loop.
  ----> System.Threading.Tasks.TaskSchedulerException : An exception was thrown by a TaskScheduler.
  ----> System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Akka.Remote.Remoting.Start()
   at Akka.Remote.RemoteActorRefProvider.Init(ActorSystemImpl system)
   at Akka.Cluster.ClusterActorRefProvider.Init(ActorSystemImpl system)
   at Akka.Actor.Internal.ActorSystemImpl.Start()
   at Akka.Actor.ActorSystem.CreateAndStartSystem(String name, Config withFallback, ActorSystemSetup setup)
   at Akka.Actor.ActorSystem.Create(String name, ActorSystemSetup setup)
   at Akka.TestKit.TestKitBase.InitializeTest(ActorSystem system, ActorSystemSetup config, String actorSystemName, String testActorName)
   at Akka.TestKit.TestKitBase..ctor(ITestKitAssertions assertions, ActorSystem system, ActorSystemSetup config, String actorSystemName, String testActorName)
   at Akka.TestKit.NUnit3.TestKit..ctor(Config config, String actorSystemName)
--AggregateException

--TargetInvocationException
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Akka.Remote.EndpointManager.get_Listens()
--- End of stack trace from previous location where exception was thrown ---
   at Akka.Remote.EndpointManager.<>c__DisplayClass47_0.<get_Listens>b__4()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--InvalidOperationException
   at DotNetty.Transport.Channels.MultithreadEventLoopGroup..ctor(Func`2 eventLoopFactory, Int32 eventLoopCount)
   at Akka.Remote.Transport.DotNetty.DotNettyTransport..ctor(ActorSystem system, Config config)
   at Akka.Remote.Transport.DotNetty.TcpTransport..ctor(ActorSystem system, Config config)
--TaskSchedulerException
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
   at System.Threading.Tasks.Task.InternalStartNew(Task creatingTask, Delegate action, Object state, CancellationToken cancellationToken, TaskScheduler scheduler, TaskCreationOptions options, InternalTaskOptions internalOptions, StackCrawlMark& stackMark)
   at System.Threading.Tasks.TaskFactory.StartNew(Action action, CancellationToken cancellationToken, TaskCreationOptions creationOptions, TaskScheduler scheduler)
   at DotNetty.Common.Concurrency.XThread.CreateLongRunningTask(XParameterizedThreadStart threadStartFunc)
   at DotNetty.Common.Concurrency.XThread..ctor(Action action)
   at DotNetty.Common.Concurrency.SingleThreadEventExecutor..ctor(IEventExecutorGroup parent, String threadName, TimeSpan breakoutInterval, IQueue`1 taskQueue)
   at DotNetty.Transport.Channels.SingleThreadEventLoop..ctor(IEventLoopGroup parent)
   at DotNetty.Transport.Channels.MultithreadEventLoopGroup.<>c.<.cctor>b__21_0(IEventLoopGroup group)
   at DotNetty.Transport.Channels.MultithreadEventLoopGroup..ctor(Func`2 eventLoopFactory, Int32 eventLoopCount)
--OutOfMemoryException
   at System.Threading.Thread.StartInternal(IPrincipal principal, StackCrawlMark& stackMark)
   at System.Threading.Thread.Start(StackCrawlMark& stackMark)
   at System.Threading.Thread.Start(Object parameter)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.QueueTask(Task task)
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
```

**Comment by Aaronontheweb** [comment]
@ArturChe do you have an example of what one of these unit tests look like? I wonder if it's a disposal issue with how the NUnit3 testkit is implemented.

**Comment by Aaronontheweb** [comment]
@ArturChe any updates on this?

**Comment by ArturChe** [comment]
@Aaronontheweb Hi, sorry. Do not have too much time for investigation of it. But the weird thing that we have found, for now, that on v 1.4.14 there is no problem with running unit tests on our Teamcity machine or locally on debug mode. The out-of-memory exception also gone, but some tests still hanging. Need to spend more time to find some pattern and check expectation messages timing.
