### ISSUE TITLE
Can not run Akka.MultiNodeTestRunner in vs or command line 

### ISSUE THREAD

**Issue by mushroom-cn** [akkadotnet/akka.net#4709]
I am woking on Akka.MultiNodeTestRunner 1.4.11. But I always get the following errors, while runing the test cases.
My test case is very esay. Just created a new actor.

My Project config is :
![image](https://user-images.githubusercontent.com/17469437/103602802-ea78f500-4f47-11eb-89c6-86d659465afc.png)
And I tried add `<PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest>`, but it does not work well.

Error: 
`Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process exited with error: Error:
  An assembly specified in the application dependencies manifest (ServiceMonitor.Test.deps.json) has already been found but with a different file extension:
    package: 'Akka.MultiNodeTestRunner', version: '1.4.11'
    path: 'lib/netcoreapp3.1/Akka.MultiNodeTestRunner.exe'
    previously found assembly: 'bin\Debug\netcoreapp3.1\Akka.MultiNodeTestRunner.dll'
. Please check the diagnostic logs for more information.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.ThrowOnTestHostExited(Boolean testHostExited)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
System.ArgumentException: The specified argument cannot be empty. (Parameter 'tests')
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.ValidateArg.NotNullOrEmpty[T](IEnumerable`1 arg, String parameterName)
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.TestRunCriteria..ctor(IEnumerable`1 tests, Int64 frequencyOfRunStatsChangeEvent, Boolean keepAlive, String testSettings, TimeSpan runStatsChangeEventTimeout, ITestHostLauncher testHostLauncher)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.TestPlatformHelpers.TestRequestManager.RunTests(TestRunRequestPayload testRunRequestPayload, ITestHostLauncher testHostLauncher, ITestRunEventsRegistrar testRunEventsRegistrar, ProtocolConfig protocolConfig)
   at Microsoft.VisualStudio.TestPlatform.Client.DesignMode.DesignModeClient.<>c__DisplayClass23_0.<StartTestRun>b__0()`

**Comment by Aaronontheweb** [comment]
We probably need to refactor the MNTR as a `dotnet tool` - but running it via Visual Studio's test runner is definitely not supported right now. Did you try this? https://getakka.net/articles/testing/multi-node-testing.html

**Comment by mushroom-cn** [comment]
@Aaronontheweb  Thanks for your help. I tried https://getakka.net/articles/testing/multi-node-testing.html and it works well. 
Looking forward to the MNTR Running in VS.

**Comment by Aaronontheweb** [comment]
Thanks! Let us know if there's anything else we can do to help.
