### ISSUE TITLE
Approval specs do not report failure properly

### ISSUE THREAD

**Issue by IgorFedchenko** [akkadotnet/akka.net#4765]
When we have public API modified, approval specs are failing. But instead of proper failure report we get NRE:
```
System.NullReferenceException
Object reference not set to an instance of an object.
   at ApprovalTests.Reporters.MultiReporter.Report(String approved, String received)
   at ApprovalTests.Approvers.FileApprover.ReportFailure(IApprovalFailureReporter reporter)
   at ApprovalTests.Core.Approver.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter)
   at ApprovalTests.Approvals.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter)
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer, IApprovalNamer namer, IApprovalFailureReporter reporter)
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer)
   at ApprovalTests.Approvals.Verify(String text, Func`2 scrubber)
   at Akka.API.Tests.CoreAPISpec.ApproveCore()
```

Contributor is able to check the reason locally, but still getting NRE in approval specs is frustrating.

**Comment by IgorFedchenko** [comment]
So far debugging shows be that when reporting failure, `ApprovalTests.Reporters.ApprovalReporter` class is used, and is trying to resolve `Type.GetType("Xunit.Assert, xunit")`, and fails.

And this is happening because `XUnitReporter` is used instead of `XUnit2Reporter` internally during approval report generation.
The following line returns `false` in `XUnit2Reporter`:
```csharp
AppDomain.CurrentDomain.GetAssemblies().Any<Assembly>(a => a.FullName.Contains("xunit.assert"))
```

`xunit.assert` is not included in the currently loaded assemblies.

**Comment by IgorFedchenko** [comment]
Seems like the problem is due to the fact that this assembly is lazily loaded into the context. Not sure if/how ApprovalTests library should fix that, but I will push PR to fix this for our CI.
