### ISSUE TITLE
Akka.IO.Tcp: Need to mark TCP actors with purely local deployment scopes to avoid errors when akka.actor.serialize-creators = on

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#4860]
Version: Akka.NET v1.4.17

Right now, when running with the following HOCON enabled:

```
akka.actor.serialize-creators = on
```

I get the following exception when attempting to open some inbound Akka.IO.Tcp sockets for accepting inbound connections:

```
[ERROR][3/18/2021 2:16:28 AM][Thread 0039][akka://test/system/IO-TCP] Unable to find a constructor to use for type Akka.IO.Buffers.DisabledBufferPool. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'BufferPool', line 1, position 225.
Cause: Newtonsoft.Json.JsonSerializationException: Unable to find a constructor to use for type Akka.IO.Buffers.DisabledBufferPool. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'BufferPool', line 1, position 225.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Akka.Serialization.NewtonSoftJsonSerializer.FromBinary(Byte[] bytes, Type type)
   at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
   at Akka.Actor.ActorCell.MakeChild(Props props, String name, Boolean async, Boolean systemService)
   at Akka.Actor.ActorCell.ActorOf(Props props, String name)
   at Akka.IO.TcpManager.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[DEBUG][3/18/2021 2:16:28 AM][Thread 0008][ActorSystem(test)] System shutdown initiated
```

This is because, I believe, the `TcpManager`'s `ActorOf` calls pass non-serializable arguments to its children:

https://github.com/akkadotnet/akka.net/blob/d2b88753ac8fa0ed7c479712ef38182a02e706bc/src/core/Akka/IO/TcpManager.cs#L75-L87

The fix for this, is to explicitly apply a `new Deploy(Scope.Local)` (or whatever the correct syntax is) to all of the `Props` used for creating these actors.

This is a relatively minor issue I only noticed because it affects the [Petabridge.Cmd](https://cmd.petabridge.com/) test suite - marking it as something a new contributor can explore.

**Comment by wesselkranenborg** [comment]
@Aaronontheweb: I tested the following nightly version of 1.4.19

```
<PackageReference Include="Akka" Version="1.4.19-beta637539553808642405" />
<PackageReference Include="Akka.Cluster" Version="1.4.19-beta637539553808642405" />
<PackageReference Include="Akka.Cluster.Sharding" Version="1.4.19-beta637539553808642405" />
<PackageReference Include="Akka.Cluster.Tools" Version="1.4.19-beta637539553808642405" />
<PackageReference Include="Akka.DependencyInjection" Version="1.4.19-beta637539553808642405" />
<PackageReference Include="Akka.Persistence.Query.Sql" Version="1.4.19-beta637539553808642405" />
<PackageReference Include="Akka.Persistence.SqlServer" Version="1.4.16" />
<PackageReference Include="Akka.Serialization.Hyperion" Version="1.4.19-beta637539553808642405" />
```

But am still getting this error on shutdown of my ActorSystem. You mentioned that it was related to this issue but is it related to this? Or do I need to open a new issue for this?

```
[ERROR][04/14/2021 19:38:05][Thread 0082][[akka://blueprint-service/system/IO-TCP#1876155147]] Swallowing exception during message send
Cause: Hyperion.ValueSerializers.UnsupportedTypeException: No coercion operator is defined between types 'Interop+Sys+SocketEvent*' and 'System.Object'.
   at Hyperion.ValueSerializers.UnsupportedTypeSerializer.WriteManifest(Stream stream, SerializerSession session)
   at Hyperion.Extensions.StreamEx.WriteObject(Stream stream, Object value, Type valueType, ValueSerializer valueSerializer, Boolean preserveObjectReferences, SerializerSession session)
   at Hyperion.Extensions.StreamEx.WriteObject(Stream stream, Object value, Type valueType, ValueSerializer valueSerializer, Boolean preserveObjectReferences, SerializerSession session)
   at lambda_method(Closure , Stream , Object , SerializerSession )
   at Hyperion.Extensions.StreamEx.WriteObject(Stream stream, Object value, Type valueType, ValueSerializer valueSerializer, Boolean preserveObjectReferences, SerializerSession session)
   at lambda_method(Closure , Stream , Object , SerializerSession )
   at Hyperion.Extensions.StreamEx.WriteObject(Stream stream, Object value, Type valueType, ValueSerializer valueSerializer, Boolean preserveObjectReferences, SerializerSession session)
   at lambda_method(Closure , Stream , Object , SerializerSession )
   at Hyperion.Extensions.StreamEx.WriteObject(Stream stream, Object value, Type valueType, ValueSerializer valueSerializer, Boolean preserveObjectReferences, SerializerSession session)
   at lambda_method(Closure , Stream , Object , SerializerSession )
   at Hyperion.ValueSerializers.ObjectSerializer.<.ctor>b__9_1(Stream stream, Object o, SerializerSession session)
   at Akka.Serialization.HyperionSerializer.ToBinary(Object obj)
   at Akka.Actor.ActorCell.SerializeAndDeserializePayload(Object obj)
   at Akka.Actor.ActorCell.SerializeAndDeserialize(Envelope envelope)
   at Akka.Actor.ActorCell.SendMessage(Envelope message)
```

**Comment by Arkatufus** [comment]
`System.Runtime.InteropServices.Interop.Sys.SocketEvent` is a struct and could not be coerced into an object. 
The real question is, why is it being serialized inside an envelope?

**Comment by wesselkranenborg** [comment]
We have also enabled `akka.actor.serialize-creators = on`. But we only see this error during shutdown of our actorsystem. It throws a number of times and then it shuts down.

**Comment by Arkatufus** [comment]
I'll try and give it a look, can you open a new issue?

**Comment by wesselkranenborg** [comment]
I just opened a new issue for it.
