### ISSUE TITLE
MNTR: can't accept CLI arguments from PowerShell

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#4904]
Version: Akka.NET v1.4.18

This issue occurs only on the PowerShell CLI - I don't have this trouble at all in `cmd`.

```
PS> .\bin\Release\netcoreapp3.1\Akka.Cluster.Tests.MultiNode.dll -Dmultinode.output-directory="D:\Repositories\olympus\akka.net\TestResults\multinode" -Dmultinode.failed-specs-directory="D:\Repositories\olympus\akka.net\TestResults\multinode" -Dmultinode.enable-filesink=on -Dmultinode.clear-output=1 -Dmultinode.spec="*StressSpec*"
```

Causes the MNTR to explode with the following error:

```
Unhandled exception. Akka.Configuration.ConfigurationException: Command line parameter '-Dmultinode' should follow the pattern [-Dmultinode.<key>=<value>].
   at Akka.Remote.TestKit.CommandLine.<>c.<.cctor>b__6_0() in D:\Repositories\olympus\akka.net\src\core\Akka.Remote.TestKit\CommandLine.cs:line 44
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Akka.Remote.TestKit.CommandLine.GetPropertyOrDefault(String key, String defaultStr) in D:\Repositories\olympus\akka.net\src\core\Akka.Remote.TestKit\CommandLine.cs:line 57
   at Akka.MultiNodeTestRunner.Program.Main(String[] args)

```

The same command on `cmd` works fine without issue - my guess is that this is a tokenization / whitespace error in the command line parser for the MNTR.

**Comment by Arkatufus** [comment]
You have to re-arrange things for it to work in powershell:
```
D:\git\akkadotnet\akka.net\src\core\Akka.MultiNodeTestRunner\bin\Release\netcoreapp3.1\Akka.MultiNodeTestRunner.exe `
  "D:\git\akkadotnet\akka.net\src\contrib\cluster\Akka.DistributedData.Tests.MultiNode\bin\Release\netcoreapp3.1\Akka.DistributedData.Tests.MultiNode.dll" `
  "-Dmultinode.reporter=trx" `
  "-Dmultinode.enable-filesink=on" `
  "-Dmultinode.output-directory=D:\git\akkadotnet\akka.net\TestResults\multinode" `
  "-Dmultinode.failed-specs-directory=D:\git\akkadotnet\akka.net\TestResults\multinode\FAILED_SPECS_LOGS" `
  "-Dmultinode.platform=netcore" `
  "-Dmultinode.spec=Akka.DistributedData.Tests.MultiNode.DurableDataPocoSpec"
```
Note the quotes differences

**Comment by Aaronontheweb** [comment]
Barf

**Comment by Aaronontheweb** [comment]
Not cool, Powershell
