### ISSUE TITLE
Persistence of object w/ IActorRef failing

### ISSUE THREAD

**Issue by mchandschuh** [akkadotnet/akka.net#4915]
- Which Akka.Net version you are using: 1.4.18
- On which platform you are using Akka.Net: Windows and Ubuntu
- A list of steps to reproduce the issue. Or an gist or github repo which can be easily used to reproduce your case.

- Persistent actor and call `Persist(message, x => { });` on a `message` with an `IActorRef` property.

I also have overriden serialization for `System.Object` to a custom serializer. Is there an akka provided `JsonConverter` for handling akka types? I can see in the stack that its going through my serializer. I had also tried providing my own `ActorRefJsonConverter` that serialized it to a string with value of the actor's path and then on deserialization would attempt to resolve the path via actor selection, but it didn't even get that far, it complained about the manifest saying it was an `IActorRef`. That deserialization part seemed to _not_ be going through my serializer though, so I was kind of confused.

I'm obviously doing something wrong here, so any advice is appreciated :)

Here's what I put together as my own `ActorRefJsonConverter` which basically delegates to whatever is registered in the actor system to handle actor refs. Here's some [background](https://stackoverflow.com/questions/16948626/serialize-complex-type-as-simple-type-json) on `TypeChangeJsonConverter` and for the full implementation I'm using, unfold below:

<details>

``` csharp
/// <summary>
/// Defines an implementation of <see cref="Newtonsoft.Json.JsonConverter"/> that can serialize a type into a completely different type
/// </summary>
/// <remarks>
/// Source: https://stackoverflow.com/questions/16948626/serialize-complex-type-as-simple-type-json/16956496#16956496
/// </remarks>
/// <typeparam name="TExternal">The external type, serialized by the application</typeparam>
/// <typeparam name="TInternal">The internal type, used to serialize the external type</typeparam>
public abstract class TypeChangeJsonConverter<TExternal, TInternal> : JsonConverter
{
    protected virtual bool MatchTypeUsingAssignableFrom { get; set; } = false;

    /// <summary>
    /// Reads the JSON representation of the object.
    /// </summary>
    /// <param name="reader">The <see cref="T:Newtonsoft.Json.JsonReader"/> to read from.</param>
    /// <param name="objectType">Type of the object.</param>
    /// <param name="existingValue">The existing value of object being read.</param>
    /// <param name="serializer">The calling serializer.</param>
    /// <returns>
    /// The object value.
    /// </returns>
    public override object ReadJson(
        JsonReader reader,
        Type objectType,
        object existingValue,
        Newtonsoft.Json.JsonSerializer serializer
        )
    {
        try
        {
            var externalType = serializer.Deserialize<TInternal>(reader);
            return Convert(externalType);
        }
        catch (Exception error)
        {
            throw new TypeChangeJsonConverterException(typeof(TExternal), typeof(TInternal),
                $"ReadJson: objectType: {objectType?.FullName} existingValue: {TrySerialize(existingValue)}: {error.Message}", error
            );
        }
    }

    /// <summary>
    /// Writes the JSON representation of the object.
    /// </summary>
    /// <param name="writer">The <see cref="T:Newtonsoft.Json.JsonWriter"/> to write to.</param>
    /// <param name="value">The value.</param>
    /// <param name="serializer">The calling serializer.</param>
    public override void WriteJson(JsonWriter writer, object value, Newtonsoft.Json.JsonSerializer serializer)
    {
        try
        {
            var internalType = Convert((TExternal)value);
            serializer.Serialize(writer, internalType, typeof(TInternal));
        }
        catch (Exception error)
        {
            throw new TypeChangeJsonConverterException(typeof(TExternal), typeof(TInternal),
                $"WriteJson: value: {TrySerialize(value)}: {error.Message}", error
            );
        }
    }

    /// <summary>
    /// Determines whether this instance can convert the specified object type.
    /// </summary>
    /// <param name="objectType">Type of the object.</param>
    /// <returns>
    /// <c>true</c> if this instance can convert the specified object type; otherwise, <c>false</c>.
    /// </returns>
    public override bool CanConvert(Type objectType)
    {
        if (MatchTypeUsingAssignableFrom)
        {
            return typeof(TExternal).IsAssignableFrom(objectType);
        }

        return typeof(TExternal) == objectType;
    }

    /// <summary>
    /// Convert the input value to a value to be serialized
    /// </summary>
    /// <param name="value">The input value to be converted before serialization</param>
    /// <returns>A new instance of <see cref="TInternal"/> that is to be serialized</returns>
    protected abstract TInternal Convert(TExternal value);

    /// <summary>
    /// Converts the input value to be deserialized
    /// </summary>
    /// <param name="value">The deserialized value that needs to be converted to <typeparamref name="TExternal"/></param>
    /// <returns>The converted value</returns>
    protected abstract TExternal Convert(TInternal value);

    private static string TrySerialize(object value)
    {
        try
        {
            return JToken.FromObject(value).ToString(Formatting.Indented);
        }
        catch
        {
            try
            {
                return value?.ToString();
            }
            catch
            {
                return value?.GetType().FullName;
            }
        }
    }
}

```

</details>

So the idea was to serialize using akka's serialization mechanism for `IActorRef` and inject that as a string value into the json being written, and when deserializing, pass that string (as bytes) to akka's serialization.

``` csharp
public class ActorRefJsonConverter : TypeChangeJsonConverter<IActorRef, string>
{
    protected override bool MatchTypeUsingAssignableFrom { get; set; } = true;

    private readonly Serializer serializer;

    public ActorRefJsonConverter(ActorSystem system)
    {
        serializer = system.Serialization.FindSerializerForType(typeof(IActorRef));
    }

    protected override string Convert(IActorRef value)
    {
        return Encoding.UTF8.GetString(serializer.ToBinary(value));
    }

    protected override IActorRef Convert(string value)
    {
        return serializer.FromBinary<IActorRef>(Encoding.UTF8.GetBytes(value));
    }
}
```

This serializer produces output in the following format:
``` json
{
    "$id": "1",
    "$type": "Akka.Actor.ActorRefBase+Surrogate, Akka",
    "Path": "akka://test/user/echo#1984621575"
}
```

Expand for Full Exception from logs:
<details>
```
[ERROR][4/7/2021 7:42:56 AM][Thread 0059][akka.tcp://fisc-demo@localhost:7501/user/service/orders/dN2Pf_0J41SuZjRufL4lUw/LNPtg8CTpUugfBBcO3A7Pw] Failed to persist event type [fisc.orders.OrderProtocol+SubmitTwapOrder] with sequence number [1] for persistenceId [users/dN2Pf_0J41SuZjRufL4lUw/orders/twap/LNPtg8CTpUugfBBcO3A7Pw].
Cause: Newtonsoft.Json.JsonSerializationException: Error getting value from 'RouterDispatcher' on 'Akka.Routing.NoRouter'.
 ---> System.NotSupportedException: NoRouter has no dispatcher
   at Akka.Routing.NoRouter.get_RouterDispatcher()
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at heman.serialization.json.JsonSerializer.Serialize(Object obj, Type type)
   at heman.serialization.SerializerExtensions.ToBinary(ISerializer serializer, Object obj, Type type)
   at heman.akka.SerializationAdapter.ToBinary(Object obj)
   at heman.akka.persistence.JournalEntry.ForPersistentMessage(IPersistentRepresentation message, Serialization serialization)
   at heman.akka.persistence.ObjectStoreJournal.WriteMessagesAsync(IEnumerable`1 messages)
   at Akka.Persistence.Journal.AsyncWriteJournal.<>c__DisplayClass21_0.<HandleWriteMessages>b__1()
   at Akka.Util.Internal.AtomicState.CallThrough[T](Func`1 task)
   at Akka.Util.Internal.AtomicState.CallThrough[T](Func`1 task)
   ```
</details>

Change History:
2021-04-07T07:13:00-04:00: Added info about my `ActorRefJsonConverter`
2021-04-07T07:18:00-04:00: Add example serialization output from unit test

**Comment by mchandschuh** [comment]
I found the `SurrogateConverter` and associated code. Despite it being internal, it looks like I should be able to hook into these classes and configure my serializer with them. Another obvious option is to ditch my serializer and configure the built into akka newtonsoft serializer w/ my custom converters. The latter is probably the easier approach here.

**Comment by mchandschuh** [comment]
Here's a serialized value, strangely enough with a `\n` in front of it:
```

oakka.tcp://fisc-demo@localhost:7501/user/service/orders/dN2Pf_0J41SuZjRufL4lUw/cgx_EKHCbUawPHG_zZv4ag#756844081
````
and I get this message:
```
System.Runtime.Serialization.SerializationException: 'Unimplemented deserialization of message with manifest [Akka.Actor.IActorRef, Akka] in [MiscMessageSerializer]'
```

This makes me think that `Akka.,Persistence` isn't using my serializer, which makes sense, considering the reference to `MiscMessageSerializer` -- further, the property it's deserializing _is_ of type `IActorRef` and it's part of a larger object, so it must by assuming the manifest of `IActorRef`, and reasonably so, despite the value being a string.

It seems what I need to happen is for `Akka.Persistence` to allow my serializer to handle this completely. Now, I do have a custom persistence implementation and this is making me think I'm not properly setting up the `IPersistentMessage` metadata outside of the `Payload` property.

Here's the raw json written to disk by my custom persistence implementation:
``` json
{
  "id": "venues/fake/orders/cgx_EKHCbUawPHG_zZv4ag",
  "sequence": 1,
  "manifest": "fisc.venues.FakeTwapOrder+OrderState, fisc, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
  "payload": "ew0KICAib3JkZXIiOiB7DQogICAgInVzZXJJZCI6ICJkTjJQZl8wSjQxU3VaalJ1Zkw0bFV3IiwNCiAgICAib3JkZXJJZCI6ICJjZ3hfRUtIQ2JVYXdQSEdfelp2NGFnIiwNCiAgICAidmVudWVOYW1lIjogImZha2UiLA0KICAgICJzb3VyY2UiOiAiMTAwMDAwIEdCUCIsDQogICAgImRlc3RpbmF0aW9uIjogIlVTRCIsDQogICAgInN0YXJ0IjogIjIwMjEtMDQtMDdUMTE6Mzk6MDAuMDAwMDAwMFoiLA0KICAgICJlbmQiOiAiMjAyMS0wNC0wN1QxMTo1OTozMC4wMDAwMDAwWiIsDQogICAgInN1Ym1pdHRlciI6ICJcbm9ha2thLnRjcDovL2Zpc2MtZGVtb0Bsb2NhbGhvc3Q6NzUwMS91c2VyL3NlcnZpY2Uvb3JkZXJzL2ROMlBmXzBKNDFTdVpqUnVmTDRsVXcvY2d4X0VLSENiVWF3UEhHX3padjRhZyM3NTY4NDQwODEiDQogIH0sDQogICJzdGFydEF0IjogIjIwMjEtMDQtMDdUMTE6Mzk6MDAuMDAwMDAwMFoiLA0KICAiZXhlY3V0aW9uSW50ZXJ2YWwiOiAiMDA6MDA6MzAiLA0KICAiZGVzdGluYXRpb24iOiAiMCBVU0QiLA0KICAic291cmNlRXhlY3V0ZWQiOiAiMCBHQlAiDQp9",
  "serializer": 395,
  "persistedAt": 1617795493648531
}
```

And for your convenience, here's the payload base64 decoded:

``` json
{
  "order": {
    "userId": "dN2Pf_0J41SuZjRufL4lUw",
    "orderId": "cgx_EKHCbUawPHG_zZv4ag",
    "venueName": "fake",
    "source": "100000 GBP",
    "destination": "USD",
    "start": "2021-04-07T11:39:00.0000000Z",
    "end": "2021-04-07T11:59:30.0000000Z",
    "submitter": "\noakka.tcp://fisc-demo@localhost:7501/user/service/orders/dN2Pf_0J41SuZjRufL4lUw/cgx_EKHCbUawPHG_zZv4ag#756844081"
  },
  "startAt": "2021-04-07T11:39:00.0000000Z",
  "executionInterval": "00:00:30",
  "destination": "0 USD",
  "sourceExecuted": "0 GBP"
}
```

I do find it interesting that there's a `\n` in front of my actor ref string _and_ that it's _completely_ different than what is produced in my unit test, making me think my serializer isn't being invoked at all here.

**Comment by mchandschuh** [comment]
Hmm... I was thinking I could _force_ the serializer type by using a specific ID, but there doesn't appear to be an easy way to fetch an akka serializer by it's serializer ID. You can deserialize by specifying an ID but serialization appears to force you to use the current configuration, which is reasonable, but the lack of symmetry here could be improved. I was thinking that I could force resolution to the newtonsoft (ID=1) and then serialize/deserialize using that same serializer, ignoring current configurations completely. Now, that might be a really bad idea in the face of akka.remote and akka.cluster, but what do I know :)

**Comment by mchandschuh** [comment]
OK -- So I did get something working but it raised the obvious issue of race conditions. When an application is just starting up there's a race between persistent actors, will the actor that has a serialized actor ref parse that message _before_ the referenced actor has been started? How does akka deal with this internally? I'm assuming `Akka.Persistence` fully supports serializing `IActorRef` via `Persist` calls that can later be rehydrated via `OnRecover`. What I ended up with is a shim to delay resolution of the parsed `IActorRef` until it's actually required. This allows the entire system to initialize.

Here's the new and improved `ActorRefJsonConverter` in all its glory:

``` csharp
public class ActorRefJsonConverter : TypeChangeJsonConverter<IActorRef, string>
{
    protected override bool MatchTypeUsingAssignableFrom { get; set; } = true;

    private readonly ActorSystem system;

    public ActorRefJsonConverter(ActorSystem system)
    {
        this.system = system;
    }

    protected override string Convert(IActorRef value)
    {
        return value.Path.ToStringWithAddress(value.Path.Address);
    }

    protected override IActorRef Convert(string value)
    {
        var path = ActorPath.Parse(value);
        return new DelayedResolvedActorRef(system, path);
    }

    private sealed class DelayedResolvedActorRef : IActorRef
    {
        public ActorPath Path => actorRef.Value.Path;

        private readonly Lazy<IActorRef> actorRef;

        public DelayedResolvedActorRef(ActorSystem system, ActorPath path)
        {
            actorRef = new Lazy<IActorRef>(() => ResolveActor(system, path));
        }

        private static IActorRef ResolveActor(ActorSystem system, ActorPath path)
        {
            return system.ActorSelection(path).ResolveOne(TimeSpan.FromSeconds(1)).WaitForValue();
        }

        public void Tell(object message, IActorRef sender)
        {
            actorRef.Value.Tell(message, sender);
        }

        public bool Equals(IActorRef other)
        {
            return actorRef.Value.Equals(other);
        }

        public int CompareTo(IActorRef other)
        {
            return actorRef.Value.CompareTo(other);
        }

        public ISurrogate ToSurrogate(ActorSystem system)
        {
            return actorRef.Value.ToSurrogate(system);
        }

        public int CompareTo(object obj)
        {
            return actorRef.Value.CompareTo(obj);
        }
    }
}

```

The objective is pretty obvious, delay resolving the actor path until absolutely necessary to allow for actors to spin up. The 1 second should likely be changed to something like 5 seconds, especially if your system has lots of persistent actors that are spinning up on start. I'm dying to know how akka handles these kinds of issues, I tried perusing the code (briefly) but didn't really see this concern addressed, but would love to be pointed towards it.

Something became apparent to me while working through this, and that's the simple fact that actor ref serialization is fragile at best, particularly in light of restarts. Consider this same situation but with remoting. These kinds of issues add motivation to use some sort of decentralized pubsub instead of direct remoting connections. The decoupling between running actor instances, particularly when in different processes, is absolutely necessary if robustness is of concern.

**Comment by Arkatufus** [comment]
May I ask what is it that you're trying to accomplish? Maybe there is a better way of achieving it compared to what you're doing right now.
Akka does add its own surrogate converter into the Json serializer, it added it [here](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Serialization/NewtonSoftJsonSerializer.cs#L172), and the class itself is [here](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Serialization/NewtonSoftJsonSerializer.cs#L292)

**Comment by mchandschuh** [comment]
The goal was the make order processing robust in the face of unexpected restarts. To do this, I used persistent actors. The actual worker actor is a persistent FSM. The work publishes his results to an `IActorRef` provided in the message that kicks off the work. In this case, both of these actors are running in the same process. I have all of this behaving the way I need it to for now. It's actually a demo app we had to throw together for an investor.

In the full production system we're building, we explicitly avoid persistence of `IActorRef` instances. For cross-service comms we use persistent topics. For intra-service comms, we event stream and distributed pub/sub to notify other actors within the service that we're up and running, allowing them to subscribe if they so choose.

This whole experience raised some questions and got me wondering what the guidance from your team would be. Specifically, is it **not** a good idea to persist `IActorRef` in persistent actors (thinking of 'reply-to' properties on messages)? Particularly in the case where the actor ref might be in a different application/actor system via remoting, during recovery there's a chance that the remote system isn't up. Won't that persistent actor fail to recover? Is there a recommended pattern for sending a 'reply-to' `IActorRef` to a persistent actor?

Thanks!

**Comment by ismaelhamed** [comment]
@mchandschuh so the key idea here is to store the `ActorPath`, not the `IActorRef`, and later get back the current incarnation for that actor using `ActorSelection`. But like @Arkatufus said, this should be taken care of by most Akka.NET serializers.

[What is the Difference Between Actor Reference and Path?](https://getakka.net/articles/concepts/addressing.html#what-is-the-difference-between-actor-reference-and-path)

**Comment by mchandschuh** [comment]
Thank you for the link, but I don't think this is a case of my misunderstanding the semantic differences between refs and paths, and I think I'm really just trying to highlight the inherent danger in serializing actor refs in persistent actors due to the risk of recovery failure because you still have a race condition no matter what you do. If the persistent actor recovers before the target actor does then the resolve operation will fail. This is what led me to implement the delayed resolve. There's still a race condition, there's no avoiding it, but by delaying actor resolution we at least make the race more favorable.

In my opinion, serializing actor refs that are later recovered by persistent actors must be done w/ great care and should likely just not be done, and instead provide a different mechanism for explicitly resolving the actor ref. Consider the ref pointing to a different application instance. In this case, you may want your persistent actor to loop, attempting to connect to the remote system periodically until its available, or maybe his work is high value enough and the status reporting is low value enough that he should continue without the resolution succeeding, perhaps persisting missed status messages to be delivered when the remote actor ref is finally available.

Anyway, I think it might be valuable to add some details about these nuances to the persistent actor documentation. I appreciate your time and responses.
