### ISSUE TITLE
Akka.DistributedData: port `VectorClock` performance optimizations to `VersionVector` and similar types

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#4956]
Version: v1.4.18

The performance optimizations we applied to https://github.com/akkadotnet/akka.net/pull/4952 for `VectorClock` could also be applied to the `VersionVector` type in the Akka.DistributedData library and many of the CRDT types contained within. That way, we could improve overall CRDT in-memory performance - especially comparison to other versions of the same object and eventually merging of like-kinded objects together.

**Comment by andyfurnival** [comment]
@Aaronontheweb could this explain why I get high memory usage when using DData?  When I start a 7 node cluster up, and I have a 5mb ddata file, no other activities happening in the cluster except internal gossip, I quickly run out of memory (512mb container limit) with lots of exceptions like this below.  

`Akka.DistributedData.Durable.LoadFailedException: failed to load durable distributed-data
 ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Akka.Actor.Address.CreateLazyToString()
   at Akka.DistributedData.Serialization.SerializationSupport.AddressFromProto(Address address)
   at Akka.DistributedData.Serialization.SerializationSupport.UniqueAddressFromProto(UniqueAddress address)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Akka.DistributedData.Serialization.SerializationSupport.VersionVectorFromProto(VersionVector versionVector)
   at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
   at System.Linq.Enumerable.ZipIterator[TFirst,TSecond,TResult](IEnumerable`1 first, IEnumerable`1 second, Func`3 resultSelector)+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 items, MutationInput origin, KeyCollisionBehavior collisionBehavior)
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 pairs, Boolean avoidToHashMap)
   at Akka.DistributedData.Serialization.ReplicatedDataSerializer.FromProto(ORSet orset)
   at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
   at Akka.DistributedData.Serialization.SerializationSupport.OtherMessageFromProto(OtherMessage other)
   at Akka.DistributedData.Serialization.ReplicatorMessageSerializer.DurableDataEnvelopeFromBinary(Byte[] bytes)
   at Akka.DistributedData.LightningDB.LmdbDurableStore.<Init>b__20_1(ValueTuple`2 x, Int32 i)
   at System.Linq.Enumerable.SelectIterator[TSource,TResult](IEnumerable`1 source, Func`3 selector)+MoveNext()
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 items, MutationInput origin, KeyCollisionBehavior collisionBehavior)
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 pairs, Boolean avoidToHashMap)
   at Akka.DistributedData.LightningDB.LmdbDurableStore.<Init>b__20_0(LoadAll loadAll)
   --- End of inner exception stack trace ---
   at Akka.DistributedData.LightningDB.LmdbDurableStore.<Init>b__20_0(LoadAll loadAll)
   at lambda_method(Closure , Object , Action`1 )
   at Akka.Actor.ReceiveActor.ExecutePartialMessageHandler(Object message, PartialAction`1 partialAction)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Phobos.Actor.PhobosActorCell.ProcessMsgWithTrace(Object underlyingMsg, ISpanContext context, IScope scope, Boolean followFromActiveSpan)
   at Phobos.Actor.PhobosActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope) `

**Comment by Aaronontheweb** [comment]
@andyfurnival yep, absolutely - we're planning on doing a v1.4.19 release today but we can tack on a v1.4.20 release shortly thereafter with this fixed. Most of the memory overhead actually comes from the `KeyValuePair<TKey,TValue>.Equals` implementation, amazingly.

**Comment by Aaronontheweb** [comment]
Began work on this https://github.com/akkadotnet/akka.net/pull/4990

**Comment by Aaronontheweb** [comment]
This is completed.
