### ISSUE TITLE
Akka.Cluster.Router Bug: throws exception when CHR is deployed via C# and HOCON

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#5038]
Version: Akka.NET v1.4.20

With the following HOCON:

```hocon
/tradesRouter {
  router = consistent-hashing-group
  routees.paths = ["/user/orderbooks"]
  cluster {
	  enabled = on
	  use-role = trade-processor
  }
}      
```

And the following C# deployment:

```csharp
var tradeRouter = _actorSystem.ActorOf(
                Props.Empty.WithRouter(new ClusterRouterGroup(
                    new ConsistentHashingGroup(new[] { "/user/orderbooks" },
                        TradeEventConsistentHashMapping.TradeEventMapping),
                    new ClusterRouterGroupSettings(10000, new[] { "/user/orderbooks" }, true, useRole: "trade-processor"))), "tradesRouter");
```

I get the following exception:

```
nhandled exception. System.ArgumentException: Expected ConsistentHashingGroup, got Akka.Cluster.Routing.ClusterRouterGroup (Parameter 'routerConfig')
   at Akka.Routing.ConsistentHashingGroup.WithFallback(RouterConfig routerConfig)
   at Akka.Actor.Deploy.WithFallback(Deploy other)
   at Phobos.Actor.Remote.PhobosRemoteActorRefProvider.<>c.<ActorOf>b__12_3(Deploy deploy1, Deploy deploy2)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at Phobos.Actor.Remote.PhobosRemoteActorRefProvider.ActorOf(ActorSystemImpl system, Props props, IInternalActorRef supervisor, ActorPath path, Boolean systemService, Deploy deploy, Boolean lookupDeploy, Boolean async)
   at Akka.Actor.ActorCell.MakeChild(Props props, String name, Boolean async, Boolean systemService)
   at Akka.Actor.ActorCell.AttachChild(Props props, Boolean isSystemService, String name)
   at Akka.Actor.Internal.ActorSystemImpl.ActorOf(Props props, String name)
   at Akka.CQRS.TradePlacers.Service.AkkaService.StartAsync(CancellationToken cancellationToken) in D:\Repositories\Petabridge\akkadotnet-cluster-workshop\src\Akka.CQRS.TradePlacers.Service\AkkaService.cs:line 52
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Akka.CQRS.TradePlacers.Service.Program.Main(String[] args) in D:\Repositories\Petabridge\akkadotnet-cluster-workshop\src\Akka.CQRS.TradePlacers.Service\Program.cs:line 30
   at Akka.CQRS.TradePlacers.Service.Program.<Main>(String[] args)
```

These two deployments are compatible with each other - they should go through. I believe this might also be regression - I didn't have these issues in v1.3*.

**Comment by Aaronontheweb** [comment]
Nevermind - that was my fault. Created a router while clustering wasn't running. Derp.
