### ISSUE TITLE
Akka.IO.Tcp: connecting to an unreachable DnsEndpoint never times out

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#5154]
**Version Information**
Version of Akka.NET? v1.4.21
Which Akka.NET Modules? Akka

**Describe the bug**
When attempting to connect to an unreachable `DnsEndpoint` via Akka.IO.Tcp:

```csharp
var invalidEnpdoint = new DnsEndPoint("fake", 1000);
  var pbmClient = PetabridgeCmdClient.Get(Sys);
  var cts = new CancellationTokenSource(TimeSpan.FromMilliseconds(10));
  var client = await pbmClient.StartRemoteClient(invalidEnpdoint, cts.Token); 
```

Which makes the following internal call:

```csharp
 _clientActor = actorRefFactory.ActorOf(Props.Create(() => new RemoteActorClient(_isDisposed, connected))
                    .WithDeploy(Deploy.Local),
                "remoteClient" + _counter.GetAndIncrement());
            
// kick off the TCP connection process
// the RemoteActorClient will handle all of the appropriate success / fail  signaling upstream
tcpActor.Tell(new Tcp.Connect(_remoteEndpoint, timeout: TimeSpan.FromSeconds(5)), _clientActor);
```

The `Tcp.Connect` call never fails - we simply get an endless printout of the following:

```
ERROR][7/25/2021 11:25:35 PM][Thread 0018][akka://akkacmd/system/$a/$a] One or more errors occurred.
Cause: System.AggregateException: One or more errors occurred. ---> System.Net.Sockets.SocketException: No such host is known
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Akka.IO.InetAddressDnsResolver.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
---> (Inner Exception #0) System.Net.Sockets.SocketException (0x80004005): No such host is known
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)<---

[ERROR][7/25/2021 11:25:35 PM][Thread 0016][akka://akkacmd/system/$b/$a] One or more errors occurred.
Cause: System.AggregateException: One or more errors occurred. ---> System.Net.Sockets.SocketException: No such host is known
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Akka.IO.InetAddressDnsResolver.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
---> (Inner Exception #0) System.Net.Sockets.SocketException (0x80004005): No such host is known
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)<---

[INFO][7/25/2021 11:25:37 PM][Thread 0039][akka://akkacmd/system/IO-TCP/$c] Message [ReceiveTimeout] from [akka://akkacmd/system/IO-TCP/$c#429187716] to [akka://akkacmd/system/IO-TCP/$c#429187716] was unhandled. [3] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO][7/25/2021 11:25:37 PM][Thread 0039][akka://akkacmd/system/IO-TCP/$b] Message [ReceiveTimeout] from [akka://akkacmd/system/IO-TCP/$b#1946559680] to [akka://akkacmd/system/IO-TCP/$b#1946559680] was unhandled. [4] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO][7/25/2021 11:25:42 PM][Thread 0037][akka://akkacmd/system/IO-TCP/$b] Message [ReceiveTimeout] from [akka://akkacmd/system/IO-TCP/$b#1946559680] to [akka://akkacmd/system/IO-TCP/$b#1946559680] was unhandled. [5] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

**Expected behavior**
The `Tcp.Connect` operation should yield a corresponding `Tcp.CommandFailed` event after the elapsed timeout.

**Actual behavior**
We never received a `Tcp.CommandFailed` event at all - just an endless loop of deadletters from `ReceiveTimeout`.

**Environment**
.NET Core 3.1

**Additional context**

If I change the `EndPoint` to an invalid `IpEndPoint` instead of a `DnsEndpoint`, then the `Tcp.Connect` operation returns the expected `Tcp.CommandFailed` event.

**Comment by Arkatufus** [comment]
The actual issue is here:
https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/IO/InetAddressDnsResolver.cs#L55
Task.Result will always return AggregatedException, so the exception will never get caught by this line:
https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/IO/InetAddressDnsResolver.cs#L60

**Comment by Arkatufus** [comment]
One fix would be to ditch GetHostEntryAsync async call and use GetHostEntry instead. No behaviour change will happen since the async call is blocking with the Result call.
Another fix would be to use ContinueWith and PipeTo and use AggregateException.Flatten() to fish for the appropriate exception type on failure.
