### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by blinker001** [akkadotnet/akka.net#5160]
Hi, I'm trying to run two services with different roles using Lighthouse as a seed node on AWS ECS.
Services are running inside of docker containers. 
For both services `public-ports` are exposed in Dockerfile.

Here are configs:
Coupon Service:

```
akka {
    actor{
        provider = cluster
    }
    remote {
        dot-netty.tcp {
            port = 0
            public-port = 20001
            hostname = localhost
            public-hostname = "coupon-api.example.com.local"
        }
    }
    cluster {
        seed-nodes = ["akka.tcp://Bonus@lighthouse.example.com.local:4053"]
        roles = ["coupon"] # roles this member is in
        role.["coupon"].min-nr-of-members = 1 # crawler role minimum node count
    }
    loglevel = "DEBUG"
    stdout-loglevel = "DEBUG"
    io.tcp.trace-logging = on
}

```

Transaction Service:
```
akka {
    actor{
        provider = cluster
    }
    remote {
        dot-netty.tcp {
            port = 0
            public-port = 20002
            hostname = localhost
            public-hostname = "ta-api.example.com.local"
        }
    }
    cluster {
        seed-nodes = ["akka.tcp://Bonus@lighthouse.example.com.local:4053"]
        roles = ["transaction"] # roles this member is in
        role.["transaction"].min-nr-of-members = 1 # crawler role minimum node count
    }
    loglevel = "DEBUG"
    stdout-loglevel = "DEBUG"
    io.tcp.trace-logging = on
}

```

One node joins cluster. But once second node joins they were not able to reach each other.
Both services joins cluster successfully. But after they were being marked us unreachable as I can see in logs.

Here are logs:

Lighthouse Logs:

```
timestamp,message		
[Docker-Bootstrap] IP=lighthouse.bonus-system.dev.intech.fun.local		
[Docker-Bootstrap] PORT=4053		
[Docker-Bootstrap] SEEDS=[""akka.tcp://Bonus@lighthouse.example.com.local:4053""]"		
[Lighthouse] ActorSystem: Bonus	 IP: lighthouse.example.com.local	 PORT: 4053
[Lighthouse] Performing pre-boot sanity check. Should be able to parse address [akka.tcp://Bonus@lighthouse.example.com.local:4053]		
[Lighthouse] Parse successful.		
[INFO][07/29/2021 21:58:11][Thread 0001][remoting (akka://Bonus)] Starting remoting		
[INFO][07/29/2021 21:58:12][Thread 0001][remoting (akka://Bonus)] Remoting started	 listening on addresses : [akka.tcp://Bonus@lighthouse.example.com.local:4053]	
[INFO][07/29/2021 21:58:12][Thread 0001][remoting (akka://Bonus)] Remoting now listens on addresses: [akka.tcp://Bonus@lighthouse.example.com.local:4053]		
[INFO][07/29/2021 21:58:12][Thread 0001][Cluster (akka://Bonus)] Cluster Node [akka.tcp://Bonus@lighthouse.example.com.local:4053] - Starting up...		
[INFO][07/29/2021 21:58:12][Thread 0001][Cluster (akka://Bonus)] Cluster Node [akka.tcp://Bonus@lighthouse.example.com.local:4053] - Started up successfully		
[INFO][07/29/2021 21:58:13][Thread 0005][akka.tcp://Bonus@lighthouse.example.com.local:4053/user/petabridge.cmd] petabridge.cmd host bound to [0.0.0.0:9110]		
[INFO][07/29/2021 21:58:13][Thread 0010][Cluster (akka://Bonus)] Cluster Node [1.5.5] - Node [akka.tcp://Bonus@lighthouse.example.com.local:4053] is JOINING itself (with roles [lighthouse], version [1.5.5]) and forming a new cluster"		
[INFO][07/29/2021 21:58:13][Thread 0010][Cluster (akka://Bonus)] Cluster Node [akka.tcp://Bonus@lighthouse.example.com.local:4053] - is the new leader among reachable nodes (more leaders may exist)		
[INFO][07/29/2021 21:58:13][Thread 0010][Cluster (akka://Bonus)] Cluster Node [akka.tcp://Bonus@lighthouse.example.com.local:4053] - Leader is moving node [akka.tcp://Bonus@lighthouse.example.com.local:4053] to [Up]		
[INFO][07/29/2021 21:58:25][Thread 0012][akka.tcp://Bonus@lighthouse.example.com.local:4053/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FBonus%40coupon-api.example.com.local%3A20001-1] Removing receive buffers for [akka.tcp://Bonus@lighthouse.example.com.local:4053]->[akka.tcp://Bonus@coupon-api.example.com.local:20001]		
[INFO][07/29/2021 21:58:25][Thread 0020][akka://Bonus/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FBonus%40coupon-api.example.com.local%3A20001-1/endpointWriter] Message [AckIdleCheckTimer] from [akka://Bonus/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FBonus%40coupon-api.example.com.local%3A20001-1/endpointWriter#1103816642] to [akka://Bonus/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FBonus%40coupon-api.example.com.local%3A20001-1/endpointWriter#1103816642] was not delivered. [1] dead letters encountered. If this is not an expected behavior then [akka://Bonus/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FBonus%40coupon-api.example.com.local%3A20001-1/endpointWriter#1103816642] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.		
[INFO][07/29/2021 21:58:26][Thread 0011][akka.tcp://Bonus@lighthouse.example.com.local:4053/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FBonus%40ta-api.example.com.local%3A20002-3] Removing receive buffers for [akka.tcp://Bonus@lighthouse.example.com.local:4053]->[akka.tcp://Bonus@ta-api.example.com.local:20002]		
[INFO][07/29/2021 22:03:34][Thread 0011][remoting (akka://Bonus)] Quarantined address [akka.tcp://Bonus@coupon-api.example.com.local:20001] is still unreachable or has not been restarted. Keeping it quarantined.		
[INFO][07/29/2021 22:03:34][Thread 0012][akka.tcp://Bonus@lighthouse.example.com.local:4053/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FBonus%40coupon-api.example.com.local%3A20001-2] Removing receive buffers for [akka.tcp://Bonus@lighthouse.example.com.local:4053]->[akka.tcp://Bonus@coupon-api.example.com.local:20001]		
[INFO][07/29/2021 22:03:44][Thread 0020][Cluster (akka://Bonus)] Cluster Node [akka.tcp://Bonus@lighthouse.example.com.local:4053] - Received InitJoin message from [[akka.tcp://Bonus@coupon-api.example.com.local:20001/system/cluster/core/daemon/joinSeedNodeProcess-1#1842426625]] to [akka.tcp://Bonus@lighthouse.example.com.local:4053]		
[INFO][07/29/2021 22:03:44][Thread 0020][Cluster (akka://Bonus)] Cluster Node [akka.tcp://Bonus@lighthouse.example.com.local:4053] - Sending InitJoinNack message from node [akka.tcp://Bonus@lighthouse.example.com.local:4053] to [[akka.tcp://Bonus@coupon-api.example.com.local:20001/system/cluster/core/daemon/joinSeedNodeProcess-1#1842426625]]		
[INFO][07/29/2021 22:03:44][Thread 0005][Cluster (akka://Bonus)] Cluster Node [1.0.0] - Node [akka.tcp://Bonus@coupon-api.example.com.local:20001] is JOINING, roles [coupon], version [1.0.0]"		
[INFO][07/29/2021 22:03:45][Thread 0020][Cluster (akka://Bonus)] Cluster Node [akka.tcp://Bonus@lighthouse.example.com.local:4053] - Leader is moving node [akka.tcp://Bonus@coupon-api.example.com.local:20001] to [Up]		
[INFO][07/29/2021 22:03:46][Thread 0005][Cluster (akka://Bonus)] Cluster Node [akka.tcp://Bonus@lighthouse.example.com.local:4053] - is no longer leader		
[INFO][07/29/2021 22:05:21][Thread 0011][remoting (akka://Bonus)] Quarantined address [akka.tcp://Bonus@ta-api.example.com.local:20002] is still unreachable or has not been restarted. Keeping it quarantined.		
[INFO][07/29/2021 22:05:21][Thread 0011][akka.tcp://Bonus@lighthouse.example.com.local:4053/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FBonus%40ta-api.example.com.local%3A20002-4] Removing receive buffers for [akka.tcp://Bonus@lighthouse.example.com.local:4053]->[akka.tcp://Bonus@ta-api.example.com.local:20002]		
[INFO][07/29/2021 22:05:34][Thread 0019][Cluster (akka://Bonus)] Cluster Node [akka.tcp://Bonus@lighthouse.example.com.local:4053] - Received InitJoin message from [[akka.tcp://Bonus@ta-api.example.com.local:20002/system/cluster/core/daemon/joinSeedNodeProcess-1#1891453320]] to [akka.tcp://Bonus@lighthouse.example.com.local:4053]		
[INFO][07/29/2021 22:05:34][Thread 0019][Cluster (akka://Bonus)] Cluster Node [akka.tcp://Bonus@lighthouse.example.com.local:4053] - Sending InitJoinNack message from node [akka.tcp://Bonus@lighthouse.example.com.local:4053] to [[akka.tcp://Bonus@ta-api.example.com.local:20002/system/cluster/core/daemon/joinSeedNodeProcess-1#1891453320]]		
[INFO][07/29/2021 22:05:35][Thread 0023][Cluster (akka://Bonus)] Cluster Node [1.0.0] - Node [akka.tcp://Bonus@ta-api.example.com.local:20002] is JOINING, roles [transaction], version [1.0.0]"		
[INFO][07/29/2021 22:05:45][Thread 0024][Cluster (akka://Bonus)] Cluster Node [akka.tcp://Bonus@lighthouse.example.com.local:4053] - is the new leader among reachable nodes (more leaders may exist)		
[INFO][07/29/2021 22:06:04][Thread 0019][Cluster (akka://Bonus)] Cluster Node [akka.tcp://Bonus@lighthouse.example.com.local:4053] - Leader can currently not perform its duties, reachability status: [Reachability([akka.tcp://Bonus@ta-api.example.com.local:20002 -> UniqueAddress: (akka.tcp://Bonus@coupon-api.example.com.local:20001, 1072090692): Unreachable [Unreachable] (1)][akka.tcp://Bonus@coupon-api.example.com.local:20001 -> UniqueAddress: (akka.tcp://Bonus@ta-api.example.com.local:20002, 1028455196): Unreachable [Unreachable] (1)])], member status: [$akka.tcp://Bonus@coupon-api.example.com.local:20001 $Up seen=$True, $akka.tcp://Bonus@lighthouse.example.com.local:4053 $Up seen=$True, $akka.tcp://Bonus@ta-api.example.com.local:20002 $Up seen=$True]"		
[INFO][07/29/2021 22:06:04][Thread 0019][akka.tcp://Bonus@lighthouse.example.com.local:4053/system/cluster/core/daemon/downingProvider] A network partition detected - unreachable nodes: [akka.tcp://Bonus@coupon-api.example.com.local:20001, akka.tcp://Bonus@ta-api.example.com.local:20002], remaining: [akka.tcp://Bonus@lighthouse.example.com.local:4053]"		
[INFO][07/29/2021 22:06:04][Thread 0019][akka.tcp://Bonus@lighthouse.example.com.local:4053/system/cluster/core/daemon/downingProvider] A network partition has been detected. KeepMajority(role: '') decided to down following nodes: [Member(address = akka.tcp://Bonus@lighthouse.example.com.local:4053, Uid=1995010842 status = Up, role=[lighthouse], upNumber=1, version=1.5.5)]"		
[INFO][07/29/2021 22:06:04][Thread 0019][Cluster (akka://Bonus)] Cluster Node [akka.tcp://Bonus@lighthouse.example.com.local:4053] - Marking node [akka.tcp://Bonus@lighthouse.example.com.local:4053] as [Down]		
[INFO][07/29/2021 22:06:05][Thread 0004][Cluster (akka://Bonus)] Cluster Node [akka.tcp://Bonus@lighthouse.example.com.local:4053] - Shutting down myself		
[INFO][07/29/2021 22:06:05][Thread 0004][Cluster (akka://Bonus)] Cluster Node [akka.tcp://Bonus@lighthouse.example.com.local:4053] - Shutting down...		
[INFO][07/29/2021 22:06:05][Thread 0004][Cluster (akka://Bonus)] Cluster Node [akka.tcp://Bonus@lighthouse.example.com.local:4053] - Successfully shut down		
[INFO][07/29/2021 22:06:05][Thread 0004][akka.tcp://Bonus@lighthouse.example.com.local:4053/user/petabridge.cmd] Shutting down petabridge.cmd host...		
[INFO][07/29/2021 22:06:05][Thread 0011][remoting-terminator] Shutting down remote daemon.		
[INFO][07/29/2021 22:06:05][Thread 0011][remoting-terminator] Remote daemon shut down	 proceeding with flushing remote transports.	
[INFO][07/29/2021 22:06:05][Thread 0011][akka.tcp://Bonus@lighthouse.example.com.local:4053/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FBonus%40coupon-api.example.com.local%3A20001-5] Removing receive buffers for [akka.tcp://Bonus@lighthouse.example.com.local:4053]->[akka.tcp://Bonus@coupon-api.example.com.local:20001]		
[INFO][07/29/2021 22:06:05][Thread 0011][akka.tcp://Bonus@lighthouse.example.com.local:4053/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FBonus%40ta-api.example.com.local%3A20002-6] Removing receive buffers for [akka.tcp://Bonus@lighthouse.example.com.local:4053]->[akka.tcp://Bonus@ta-api.example.com.local:20002]		
[INFO][07/29/2021 22:06:05][Thread 0030][remoting (akka://Bonus)] Remoting shut down		
[INFO][07/29/2021 22:06:05][Thread 0011][remoting-terminator] Remoting shut down.		
```

Coupon Service logs:
```
[40m[1m[33mwarn[39m[22m[49m: Microsoft.EntityFrameworkCore.Model.Validation[10620]
      The property 'AvailableCoupons.Deposit' is a collection or enumeration type with a value converter but with no value comparer. Set a value comparer to ensure the collection/enumeration elements are compared correctly.
[40m[1m[33mwarn[39m[22m[49m: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
[DEBUG][07/29/2021 22:03:41][Thread 0008][EventStream] StandardOutLogger started
[DEBUG][07/29/2021 22:03:41][Thread 0008][EventStream(Bonus)] Logger log1-DefaultLogger [DefaultLogger] started
[DEBUG][07/29/2021 22:03:41][Thread 0008][EventStream(Bonus)] StandardOutLogger being removed
[DEBUG][07/29/2021 22:03:41][Thread 0008][EventStream(Bonus)] Logger log1-DefaultLogger [DefaultLogger] started
[DEBUG][07/29/2021 22:03:41][Thread 0008][EventStream(Bonus)] StandardOutLogger being removed
[DEBUG][07/29/2021 22:03:41][Thread 0008][EventStream(Bonus)] Default Loggers started
[INFO][07/29/2021 22:03:41][Thread 0008][remoting (akka://Bonus)] Starting remoting
[DEBUG][07/29/2021 22:03:41][Thread 0019][remoting (akka://Bonus)] Starting prune timer for endpoint manager...
[INFO][07/29/2021 22:03:42][Thread 0008][remoting (akka://Bonus)] Remoting started; listening on addresses : [akka.tcp://Bonus@coupon-api.example.com.local:20001]
[INFO][07/29/2021 22:03:42][Thread 0008][remoting (akka://Bonus)] Remoting now listens on addresses: [akka.tcp://Bonus@coupon-api.example.com.local:20001]
[INFO][07/29/2021 22:03:42][Thread 0008][Cluster (akka://Bonus)] Cluster Node [akka.tcp://Bonus@coupon-api.example.com.local:20001] - Starting up...
[INFO][07/29/2021 22:03:42][Thread 0008][Cluster (akka://Bonus)] Cluster Node [akka.tcp://Bonus@coupon-api.example.com.local:20001] - Started up successfully
[40m[1m[33mwarn[39m[22m[49m: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {51925278-0450-432a-8be9-0559345271fd} may be persisted to storage in unencrypted form.
[DEBUG][07/29/2021 22:03:44][Thread 0019][akka.tcp://Bonus@coupon-api.example.com.local:20001/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FBonus%40lighthouse.example.com.local%3A4053-1/endpointWriter] Associated [akka.tcp://Bonus@coupon-api.example.com.local:20001] -> akka.tcp://Bonus@lighthouse.example.com.local:4053
[40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://[::]:80
[DEBUG][07/29/2021 22:03:44][Thread 0019][akka.tcp://Bonus@coupon-api.example.com.local:20001/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FBonus%40lighthouse.example.com.local%3A4053-1/endpointWriter] Drained buffer with maxWriteCount: 50, fullBackoffCount: 1,smallBackoffCount: 0, noBackoffCount: 0,adaptiveBackoff: 1000"
[40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
[40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
[40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
[INFO][07/29/2021 22:03:45][Thread 0008][Cluster (akka://Bonus)] Cluster Node [akka.tcp://Bonus@coupon-api.example.com.local:20001] - Welcome from [akka.tcp://Bonus@lighthouse.example.com.local:4053]
[DEBUG][07/29/2021 22:03:45][Thread 0027][akka.tcp://Bonus@coupon-api.example.com.local:20001/system/cluster/core/daemon] Cluster Node [akka.tcp://Bonus@coupon-api.example.com.local:20001] - Receiving gossip from [UniqueAddress: (akka.tcp://Bonus@lighthouse.example.com.local:4053, 1995010842)]"
[DEBUG][07/29/2021 22:03:45][Thread 0004][akka.tcp://Bonus@coupon-api.example.com.local:20001/system/cluster/core/daemon] Cluster Node [akka.tcp://Bonus@coupon-api.example.com.local:20001] - Receiving gossip from [UniqueAddress: (akka.tcp://Bonus@lighthouse.example.com.local:4053, 1995010842)]"
[DEBUG][07/29/2021 22:03:45][Thread 0004][akka.tcp://Bonus@coupon-api.example.com.local:20001/system/cluster/core/daemon] Cluster Node [akka.tcp://Bonus@coupon-api.example.com.local:20001] - Receiving gossip from [UniqueAddress: (akka.tcp://Bonus@lighthouse.example.com.local:4053, 1995010842)]"
[INFO][07/29/2021 22:03:45][Thread 0016][Cluster (akka://Bonus)] Cluster Node [akka.tcp://Bonus@coupon-api.example.com.local:20001] - is the new leader among reachable nodes (more leaders may exist)
[40m[1m[33mwarn[39m[22m[49m: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
[DEBUG][07/29/2021 22:05:35][Thread 0008][akka.tcp://Bonus@coupon-api.example.com.local:20001/system/cluster/core/daemon] Cluster Node [akka.tcp://Bonus@coupon-api.example.com.local:20001] - Receiving gossip from [UniqueAddress: (akka.tcp://Bonus@lighthouse.example.com.local:4053, 1995010842)]"
[WARNING][07/29/2021 22:05:35][Thread 0020][akka.tcp://Bonus@coupon-api.example.com.local:20001/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FBonus%40ta-api.example.com.local%3A20002-2/endpointWriter] AssociationError [akka.tcp://Bonus@coupon-api.example.com.local:20001] -> akka.tcp://Bonus@ta-api.example.com.local:20002: Error [Association failed with akka.tcp://Bonus@ta-api.example.com.local:20002] []
[WARNING][07/29/2021 22:05:35][Thread 0019][remoting (akka://Bonus)] Tried to associate with unreachable remote address [akka.tcp://Bonus@ta-api.example.com.local:20002]. Address is now gated for 5000 ms, all messages to this address will be delivered to dead letters. Reason: [Association failed with akka.tcp://Bonus@ta-api.example.com.local:20002] Caused by: [System.AggregateException: One or more errors occurred. (Connection refused tcp://Bonus@ta-api.example.com.local:20002)"
 ---> Akka.Remote.Transport.InvalidAssociationException: Connection refused tcp://Bonus@ta-api.example.com.local:20002
   at Akka.Remote.Transport.DotNetty.TcpTransport.AssociateInternal(Address remoteAddress)
   at Akka.Remote.Transport.DotNetty.DotNettyTransport.Associate(Address remoteAddress)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Akka.Remote.Transport.ProtocolStateActor.<>c.<InitializeFSM>b__12_18(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)"
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)]"
```

Transaction Service Logs:
```
[DEBUG][07/29/2021 22:05:31][Thread 0008][EventStream] StandardOutLogger started
[DEBUG][07/29/2021 22:05:32][Thread 0008][EventStream(Bonus)] Logger log1-DefaultLogger [DefaultLogger] started
[DEBUG][07/29/2021 22:05:32][Thread 0008][EventStream(Bonus)] StandardOutLogger being removed
[DEBUG][07/29/2021 22:05:32][Thread 0008][EventStream(Bonus)] Logger log1-DefaultLogger [DefaultLogger] started
[DEBUG][07/29/2021 22:05:32][Thread 0008][EventStream(Bonus)] StandardOutLogger being removed
[DEBUG][07/29/2021 22:05:32][Thread 0008][EventStream(Bonus)] Default Loggers started
[INFO][07/29/2021 22:05:32][Thread 0008][remoting (akka://Bonus)] Starting remoting
[DEBUG][07/29/2021 22:05:32][Thread 0019][remoting (akka://Bonus)] Starting prune timer for endpoint manager...
[INFO][07/29/2021 22:05:33][Thread 0008][remoting (akka://Bonus)] Remoting started; listening on addresses : [akka.tcp://Bonus@ta-api.example.com.local:20002]
[INFO][07/29/2021 22:05:33][Thread 0008][remoting (akka://Bonus)] Remoting now listens on addresses: [akka.tcp://Bonus@ta-api.example.com.local:20002]
[INFO][07/29/2021 22:05:33][Thread 0008][Cluster (akka://Bonus)] Cluster Node [akka.tcp://Bonus@ta-api.example.com.local:20002] - Starting up...
[INFO][07/29/2021 22:05:33][Thread 0008][Cluster (akka://Bonus)] Cluster Node [akka.tcp://Bonus@ta-api.example.com.local:20002] - Started up successfully
[DEBUG][07/29/2021 22:05:34][Thread 0019][akka.tcp://Bonus@ta-api.example.com.local:20002/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FBonus%40lighthouse.example.com.local%3A4053-1/endpointWriter] Associated [akka.tcp://Bonus@ta-api.example.com.local:20002] -> akka.tcp://Bonus@lighthouse.example.com.local:4053
[DEBUG][07/29/2021 22:05:34][Thread 0019][akka.tcp://Bonus@ta-api.example.com.local:20002/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FBonus%40lighthouse.example.com.local%3A4053-1/endpointWriter] Drained buffer with maxWriteCount: 50, fullBackoffCount: 1,smallBackoffCount: 0, noBackoffCount: 0,adaptiveBackoff: 1000"
[40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://[::]:80
[40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
[40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
[40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
[INFO][07/29/2021 22:05:35][Thread 0008][Cluster (akka://Bonus)] Cluster Node [akka.tcp://Bonus@ta-api.example.com.local:20002] - Welcome from [akka.tcp://Bonus@lighthouse.example.com.local:4053]
[WARNING][07/29/2021 22:05:35][Thread 0020][akka.tcp://Bonus@ta-api.example.com.local:20002/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FBonus%40coupon-api.example.com.local%3A20001-2/endpointWriter] AssociationError [akka.tcp://Bonus@ta-api.example.com.local:20002] -> akka.tcp://Bonus@coupon-api.example.com.local:20001: Error [Association failed with akka.tcp://Bonus@coupon-api.example.com.local:20001] []
[WARNING][07/29/2021 22:05:35][Thread 0020][remoting (akka://Bonus)] Tried to associate with unreachable remote address [akka.tcp://Bonus@coupon-api.example.com.local:20001]. Address is now gated for 5000 ms, all messages to this address will be delivered to dead letters. Reason: [Association failed with akka.tcp://Bonus@coupon-api.example.com.local:20001] Caused by: [System.AggregateException: One or more errors occurred. (Connection refused tcp://Bonus@coupon-api.example.com.local:20001)"
 ---> Akka.Remote.Transport.InvalidAssociationException: Connection refused tcp://Bonus@coupon-api.example.com.local:20001
   at Akka.Remote.Transport.DotNetty.TcpTransport.AssociateInternal(Address remoteAddress)
   at Akka.Remote.Transport.DotNetty.DotNettyTransport.Associate(Address remoteAddress)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Akka.Remote.Transport.ProtocolStateActor.<>c.<InitializeFSM>b__12_18(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)"
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)"
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)]"
```

What can be a problem?

Thanks.

**Comment by blinker001** [comment]
Interesting thing is that why I'm trying to telnet on port 20001 or 20002 connection also refused. 
Means like there is no listener on that port.

**Comment by blinker001** [comment]
dummy mistake. Port was not open on aws security group.
