### ISSUE TITLE
RestartFlow Akka Streams not working as expected

### ISSUE THREAD

**Issue by Danthar** [akkadotnet/akka.net#5165]
**Version Information**
Version of Akka.NET? 1.4.18
Which Akka.NET Modules? Akka Streams

**Describe the bug**
RestartFlow does not restart.

**To Reproduce**

```
        [Fact]
        public void RetryTestCases()
        {
            var flow = RestartFlow.OnFailuresWithBackoff(() =>
                {
                    return Flow.Create<int>() 
                        .Select(i =>
                        {
                            if(i == 6)
                                throw new ArgumentException($"BOOM");
                            return i;
                        }).Log("LOG ON ERROR", i => i, Sys.Log).WithAttributes(Attributes.CreateLogLevels(Attributes.LogLevels.Off, Attributes.LogLevels.Off, LogLevel.ErrorLevel));
                }, TimeSpan.FromMilliseconds(100), TimeSpan.FromSeconds(5), 0.3, 10);
            
            Source.From(new int[] { 1,2,3,4,5,6 })
                .Via(flow)
                .To(Sink.ForEach<int>(i =>
                {
                    Log.Info($"Received: {i}");
                })).Run(Sys.Materializer());
        }

```

**Expected behavior**
I expected the exception to occur 10 times. 

**Actual behavior**

```
[DEBUG][4-8-2021 10:12:10][Thread 0010][EventStream] subscribing [akka://testsystem/system/log-test#1666761903] to channel Akka.Event.LogEvent
[DEBUG][4-8-2021 10:12:11][Thread 0027][akka://testsystem/user] now supervising akka://testsystem/user/StreamSupervisor-0
[DEBUG][4-8-2021 10:12:11][Thread 0031][akka://testsystem/user/StreamSupervisor-0] Started (Akka.Streams.Implementation.StreamSupervisor)
[DEBUG][4-8-2021 10:12:11][Thread 0010][akka://testsystem/user/StreamSupervisor-0] now supervising akka://testsystem/user/StreamSupervisor-0/Flow-0-0-unknown-operation
[DEBUG][4-8-2021 10:12:11][Thread 0015][CoordinatedShutdown (akka://testsystem)] Performing phase [before-service-unbind] with [0] tasks.
[DEBUG][4-8-2021 10:12:11][Thread 0033][CoordinatedShutdown (akka://testsystem)] Performing phase [service-unbind] with [0] tasks.
[DEBUG][4-8-2021 10:12:11][Thread 0033][CoordinatedShutdown (akka://testsystem)] Performing phase [service-requests-done] with [0] tasks.
[DEBUG][4-8-2021 10:12:11][Thread 0033][CoordinatedShutdown (akka://testsystem)] Performing phase [service-stop] with [0] tasks.
[DEBUG][4-8-2021 10:12:11][Thread 0033][CoordinatedShutdown (akka://testsystem)] Performing phase [before-cluster-shutdown] with [0] tasks.
[DEBUG][4-8-2021 10:12:11][Thread 0033][CoordinatedShutdown (akka://testsystem)] Performing phase [cluster-sharding-shutdown-region] with [0] tasks.
[DEBUG][4-8-2021 10:12:11][Thread 0033][CoordinatedShutdown (akka://testsystem)] Performing phase [cluster-leave] with [0] tasks.
[DEBUG][4-8-2021 10:12:11][Thread 0033][CoordinatedShutdown (akka://testsystem)] Performing phase [cluster-exiting] with [0] tasks.
[DEBUG][4-8-2021 10:12:11][Thread 0033][CoordinatedShutdown (akka://testsystem)] Performing phase [cluster-exiting-done] with [0] tasks.
[DEBUG][4-8-2021 10:12:11][Thread 0033][CoordinatedShutdown (akka://testsystem)] Performing phase [cluster-shutdown] with [0] tasks.
[DEBUG][4-8-2021 10:12:11][Thread 0033][CoordinatedShutdown (akka://testsystem)] Performing phase [before-actor-system-terminate] with [0] tasks.
[DEBUG][4-8-2021 10:12:11][Thread 0033][CoordinatedShutdown (akka://testsystem)] Performing phase [actor-system-terminate] with [1] tasks: [terminate-system]
[DEBUG][4-8-2021 10:12:11][Thread 0033][ActorSystem(testsystem)] System shutdown initiated
[INFO][4-8-2021 10:12:11][Thread 0032][RestartFlowTestCase (akka://testsystem)] Received: 1
[INFO][4-8-2021 10:12:11][Thread 0032][RestartFlowTestCase (akka://testsystem)] Received: 2
[INFO][4-8-2021 10:12:11][Thread 0032][RestartFlowTestCase (akka://testsystem)] Received: 3
[INFO][4-8-2021 10:12:11][Thread 0032][RestartFlowTestCase (akka://testsystem)] Received: 4
[INFO][4-8-2021 10:12:11][Thread 0032][RestartFlowTestCase (akka://testsystem)] Received: 5
[DEBUG][4-8-2021 10:12:11][Thread 0024][akka://testsystem/user] Stopping
[DEBUG][4-8-2021 10:12:11][Thread 0033][akka://testsystem/user/StreamSupervisor-0] Stopping
[ERROR][4-8-2021 10:12:11][Thread 0032][ActorSystem(testsystem)] [LOG ON ERROR] Upstream failed.
Cause: System.ArgumentException: BOOM
   at AkkaStreamsTest.RestartFlowTestCase.<>c.<RetryTestCases>b__4_2(Int32 i) in C:\Dev\AkkaStreamsTest\RestartFlowTestCase.cs:line 156
   at Akka.Streams.Implementation.Fusing.Select`2.Logic.OnPush()

```

I have looked at the RestartFlow Test Spec in the project. But i could not find anything which indicated that im doing something wierd, or that im missing something.
Also i found this issue on the JVM repo which seems eerily familiar with what im seeing. https://github.com/akka/akka/issues/24726

Note: I also tried the normal `WithRestart` but that does not work either.

**Comment by Aaronontheweb** [comment]
Added this to the v1.4.23 milestone since we're getting ready to release 1.4.22 today.

cc @ismaelhamed - have you run into this trouble with `RestartFlow` before? Asking because I thought you'd patched it within the past year or so.

**Comment by Danthar** [comment]
Increased the source to 1...10. No change. Would have been strange anyway. Even if it is the last element in the stream, that particular stage is wrapped in a RestartFlow, so regardless, it should restart according to its settings right ?

**Comment by ismaelhamed** [comment]
Ok, I had some spare time at work and took a deeper look into this. And, we're having the same problem that [#24726](https://github.com/akka/akka/issues/24726)

I changed the code slightly to have an infinite stream. This is using `1.4.21`, BTW:

```csharp
var flow = RestartFlow.WithBackoff(() =>
{
    return Flow.Create<int>()
        .Select(i =>
        {
            if (i % 2 == 0) throw new ArgumentException("BOOM");
            return i;
        })
        .Log("InFlow");
}, TimeSpan.FromMilliseconds(100), TimeSpan.FromSeconds(5), 0.3, 10);

var values = (IEnumerable<int>)new int[] { 1, 2, 3, 4, 5, 6 };
Source.Cycle(() => values.GetEnumerator())
    .Via(flow)
    .Log("After Flow")
    .RunWith(Sink.Ignore<int>(), Sys.Materializer());
```

`WithBackoff` is behaving like it should, see the output below:

```
[12:41:25 DBG] [InFlow] Element: 1
[12:41:25 DBG] [After Flow] Element: 1
[12:41:25 ERR] [InFlow] Upstream failed. System.ArgumentException: BOOM
[12:41:25 DBG] Graph in finished
[12:41:25 DBG] Restarting graph in 00:00:00.1189943
[12:41:25 DBG] [InFlow] Element: 3
[12:41:25 DBG] [After Flow] Element: 3
[12:41:25 ERR] [InFlow] Upstream failed. System.ArgumentException: BOOM
[12:41:25 DBG] Graph in finished
[12:41:25 DBG] Restarting graph in 00:00:00.2093341
[12:41:25 DBG] [InFlow] Element: 5
[12:41:25 DBG] [After Flow] Element: 5
[12:41:25 ERR] [InFlow] Upstream failed. System.ArgumentException: BOOM
[12:41:25 DBG] Graph in finished
[12:41:25 DBG] Restarting graph in 00:00:00.5105864
[12:41:26 DBG] [InFlow] Element: 1
[12:41:26 DBG] [After Flow] Element: 1
[12:41:26 ERR] [InFlow] Upstream failed. System.ArgumentException: BOOM
[12:41:26 DBG] Graph in finished
[12:41:26 DBG] Restarting graph in 00:00:00.9627185
...
```

But on the other hand, look at the output of `OnFailuresWithBackoff`:

```
[12:29:42 DBG] [InFlow] Element: 1
[12:29:42 ERR] [InFlow] Upstream failed. System.ArgumentException: BOOM
[12:29:42 WRN] Restarting graph due to failure.System.ArgumentException: BOOM
[12:29:42 DBG] Restarting graph in 00:00:00.1126392
[12:29:42 ERR] [After Flow] Upstream failed. System.ArgumentException: Cannot pull a closed port
```

Notice the last exception ("Cannot pull a closed port"), that's the bug.

**Comment by Danthar** [comment]
AH. thats the same error as mentioned in that bug report from the JVM repo. 
So thats good news i suppose.

**Comment by ismaelhamed** [comment]
@Danthar are you up to grab this?

**Comment by Danthar** [comment]
Sure ill take a stab at it. I took a look at how they fixed it in that issue. Not a fan of the delay mechanic. But unsure if we can do better. Maybe they made more changes later on.
