### ISSUE TITLE
Can't start up Akka.Cluster when using custom task inlining dispatcher

### ISSUE THREAD

**Issue by Zetanova** [akkadotnet/akka.net#5184]
**Version Information**
akka 1.4.22
akka, cluster

**Describe the bug**
After update to akka 1.4.22 from 1.4.21 cluster startup fails

Error: ValueFactory attempted to access the Value property of this instance.
System.InvalidOperationException: ValueFactory attempted to access the Value property of this instance.

```
...
[07:28:04 INF] Starting remoting
[07:28:04 DBG] Starting prune timer for endpoint manager...
Loaded '/app/bin/Debug/net5.0/DotNetty.Buffers.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/app/bin/Debug/net5.0/DotNetty.Transport.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/app/bin/Debug/net5.0/DotNetty.Common.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/5.0.8/System.Reflection.TypeExtensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/5.0.8/System.Reflection.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/5.0.8/System.Reflection.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
[07:28:04 INF] Remoting started; listening on addresses : [akka.tcp://pnet@pnetcore-01.cluster:2552]
[07:28:04 INF] Remoting now listens on addresses: [akka.tcp://pnet@pnetcore-01.cluster:2552]
[07:28:04 INF] Cluster Node [akka.tcp://pnet@pnetcore-01.cluster:2552] - Starting up...
[07:28:05 ERR] ValueFactory attempted to access the Value property of this instance.
System.InvalidOperationException: ValueFactory attempted to access the Value property of this instance.
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Akka.Actor.Internal.ActorSystemImpl.TryGetExtension[T](T& extension)
   at Akka.Actor.Internal.ActorSystemImpl.GetExtension[T]()
   at Akka.Actor.ActorSystemWithExtensions.WithExtension[T,TI](ActorSystem system)
   at Akka.Cluster.Cluster.Get(ActorSystem system)
   at Akka.Cluster.ClusterCoreSupervisor.<SupervisorStrategy>b__4_0(Exception e)
   at Akka.Actor.LocalOnlyDecider.Decide(Exception cause)
   at Akka.Actor.OneForOneStrategy.Handle(IActorRef child, Exception exception)
   at Akka.Actor.SupervisorStrategy.HandleFailure(ActorCell actorCell, IActorRef child, Exception cause, ChildRestartStats stats, IReadOnlyCollection`1 children)
   at Akka.Actor.ActorCell.HandleFailed(Failed f)
   at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState)
[07:28:05 ERR] ValueFactory attempted to access the Value property of this instance.
[akka://pnet/system/cluster/core#653436502]: Akka.Actor.PreRestartException: Exception pre restart (System.InvalidOperationException)
 ---> System.InvalidOperationException: ValueFactory attempted to access the Value property of this instance.
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Akka.Actor.Internal.ActorSystemImpl.TryGetExtension[T](T& extension)
   at Akka.Actor.Internal.ActorSystemImpl.GetExtension[T]()
   at Akka.Actor.ActorSystemWithExtensions.WithExtension[T,TI](ActorSystem system)
   at Akka.Cluster.Cluster.Get(ActorSystem system)
   at Akka.Cluster.ClusterCoreSupervisor.PostStop()
   at Akka.Actor.ActorBase.PreRestart(Exception reason, Object message)
   at Akka.Actor.ActorBase.AroundPreRestart(Exception cause, Object message)
   at Akka.Actor.ActorCell.FaultRecreate(Exception cause)
   --- End of inner exception stack trace ---
Loaded '/app/bin/Debug/net5.0/DotNetty.Handlers.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/app/bin/Debug/net5.0/DotNetty.Codecs.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/5.0.8/System.Runtime.Intrinsics.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
[07:28:18 DBG] Associated [akka.tcp://pnet@pnetcore-01.cluster:2552] <- akka.tcp://pnet@pnetdata-01.cluster:2552
Loaded '/app/bin/Debug/net5.0/Akka.Persistence.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
...
[07:28:25 ERR] Failed to startup Cluster. You can try to increase 'akka.actor.creation-timeout'.
Akka.Actor.AskTimeoutException: Timeout after 00:00:20 seconds
   at Akka.Cluster.Cluster.GetClusterCoreRef()
[07:28:25 INF] Cluster Node [akka.tcp://pnet@pnetcore-01.cluster:2552] - Shutting down...
[07:28:25 INF] Cluster Node [akka.tcp://pnet@pnetcore-01.cluster:2552] - Successfully shut down
[07:28:25 INF] Cluster Node [akka.tcp://pnet@pnetcore-01.cluster:2552] - Started up successfully
...

```

**Comment by Zetanova** [comment]
From the exception stack trace, its not visible how/what is calling the extension inside its factory method.

**Comment by Zetanova** [comment]
Its only happening with my ChannelDispatcher 
It produces an other task execution order and inlining.

What I discovered is that akka + akka.cluster needs min. 4 active thread to start up.
3 are locked and 1 makes the bootstrap. Less then 4 it will dead lock

**Comment by Zetanova** [comment]
I found the issue:

The `ClusterActorRefProvider` is creating the Cluster instance with `Cluster.Get(system)`

The `Akka.Cluster.Cluster` constructor is locking with 
```
// force the underlying system to start
_clusterCore = GetClusterCoreRef().Result;
```
what has already a bad smell

The `ClusterCoreSupervisor` is creating two childs `ClusterDomainEventPublisher` and `ClusterCoreDaemon` 
on `GetClusterCoreRef` and returning the coreDaemon Ref to the sender.
The sender is the `Cluster` constructor itself (over ask).

Because the Cluster constructor is waiting on the clusterCoreRef and is initialized over Lazy
`Cluster.Get(system)` cannot be used until the Cluster constructor leaves. 

Both child actors `ClusterDomainEventPublisher` and `ClusterCoreDaemon`  are using `Cluster.Get(system)` instantly.
If the ActorCell of the child actors gets activated before the  `_clusterDaemons.Ask<IActorRef>(InternalClusterAction.GetClusterCoreRef.Instance, timeout)` of the Cluster constructor then cluster startup will crash.

**Comment by Zetanova** [comment]
PR: https://github.com/akkadotnet/akka.net/pull/5185

**Comment by Aaronontheweb** [comment]
> Its only happening with my ChannelDispatcher
> It produces an other task execution order and inlining.

So this is likely not a regression then, but it is a long-standing issue inside `Cluster` startup that is indeed smelly. I'll take a look at your PR!
