### ISSUE TITLE
Running Tests with MSTestAdapter fails with Akka 1.4.25

### ISSUE THREAD

**Issue by DSanchen** [akkadotnet/akka.net#5276]
**Version Information**
1.4.25 
Which Akka.NET Modules?
Akka.NET

**Describe the bug**
Without changes to my test code, tests will no longer work, when updating to 1.4.25. With <= 1.4.24 it worked.

An exception occurred while invoking executor 'executor://mstestadapter/v1': Method not found: 'Akka.Actor.IActorRef Akka.Actor.IInternalActorRef.GetChild(System.Collections.Generic.IEnumerable`1<System.String>)

The full Exception info is:
[13.09.2021 11:23:26.289 ] An exception occurred while invoking executor 'executor://mstestadapter/v1': Method not found: 'Akka.Actor.IActorRef Akka.Actor.IInternalActorRef.GetChild(System.Collections.Generic.IEnumerable`1<System.String>)'.
Stack trace:
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
   at System.Reflection.RuntimeMethodInfo.GetParameters()
   at Microsoft.VisualStudio.TestPlatform.MSTestFramework.ReflectHelper.HasCorrectTestInitializeCleanupSignature(MethodInfo method)
   at Microsoft.VisualStudio.TestPlatform.MSTestFramework.TypeCache.UpdateInfoIfTestInitializeOrCleanupMethod(TestClassInfo classInfo, MethodInfo methodInfo, Boolean isBase, Dictionary`2 instanceMethods, Type testInitializeAttributeType, Type testCleanupAttributeType)
   at Microsoft.VisualStudio.TestPlatform.MSTestFramework.TypeCache.CreateClassInfo(Type classType, TestMethod testMethod)
   at Microsoft.VisualStudio.TestPlatform.MSTestFramework.TypeCache.GetClassInfo(TestMethod testMethod)
   at Microsoft.VisualStudio.TestPlatform.MSTestFramework.TypeCache.GetTestMethodInfo(TestMethod testMethod, Boolean isDataSource, TestContextImplementation testContext, Int32 globalTestTimeout)
   at Microsoft.VisualStudio.TestPlatform.MSTestFramework.UnitTestRunner.RunInternal(TestMethod testMethod, Boolean isDataDriven, Dictionary`2 runParameters)
   at Microsoft.VisualStudio.TestPlatform.MSTestFramework.UnitTestRunner.RunSingleTest(String name, String fullClassName, Boolean isAsync, Dictionary`2 runParameters)
   at Microsoft.VisualStudio.TestPlatform.MSTestFramework.UnitTestRunner.RunSingleTest(String name, String fullClassName, Boolean isAsync, Dictionary`2 runParameters)
   at Microsoft.VisualStudio.TestPlatform.Extensions.VSTestIntegration.MixedModeExecutor.ExecuteTestViaMsTestV1Runner(TestCase testCase, ITestExecutionRecorder testExecutionRecorder, UnitTestRunner testRunner, DateTimeOffset& startTime, DateTimeOffset& endTime)
   at Microsoft.VisualStudio.TestPlatform.Extensions.VSTestIntegration.MixedModeExecutor.ExecuteTests(IEnumerable`1 tests, IRunContext runContext, ITestExecutionRecorder testExecutionRecorder, UnitTestRunner testRunner, TmiTestRun tmiTestRun)
   at Microsoft.VisualStudio.TestPlatform.Extensions.VSTestIntegration.MixedModeExecutor.ExecuteDurontoTestsInternal(IEnumerable`1 tests, IRunContext runContext, ITestExecutionRecorder testExecutionRecorder, String source, TestRunDirectories runDirectories, TmiTestRun tmiTestRun, Int32 globalTestTimeout)
   at Microsoft.VisualStudio.TestPlatform.Extensions.VSTestIntegration.MixedModeExecutor.ExecuteDurontoTests(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle, String source, TestRunDirectories runDirectories, TmiTestRun tmiTestRun, Int32 globalTestTimeout)
   at Microsoft.VisualStudio.TestPlatform.Extensions.VSTestIntegration.MixedModeExecutor.ExecuteTests(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle, TestRunDirectories runDirectories, Boolean isDeploymentDone, String source, Int32 globalTestimeout)
   at Microsoft.VisualStudio.TestPlatform.Extensions.VSTestIntegration.MixedModeExecutor.ExecuteTests(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle, TestRunDirectories runDirectories, Boolean isDeploymentDone, Int32 globalTestTimeout)
   at Microsoft.VisualStudio.TestPlatform.Extensions.VSTestIntegration.MixedModeExecutor.RunTests(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle, TestRunCancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.Extensions.VSTestIntegration.MSTestExecutor.RunTests(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.RunTestsWithTests.InvokeExecutor(LazyExtension`2 executor, Tuple`2 executorUri, RunContext runContext, IFrameworkHandle frameworkHandle)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.<>c__DisplayClass48_0.<RunTestInternalWithExecutors>b__0()
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformThread.<>c__DisplayClass0_0.<Run>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformThread.Run(Action action, PlatformApartmentState apartmentState, Boolean waitForCompletion)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.TryToRunInSTAThread(Action action, Boolean waitForCompletion)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTestInternalWithExecutors(IEnumerable`1 executorUriExtensionMap, Int64 totalTests)

**Environment**
Windows Visual Studio 2019

**Comment by Aaronontheweb** [comment]
@DSanchen so we broke this API in the last release, as this method wasn't used much outside of our own code:

```
An exception occurred while invoking executor 'executor://mstestadapter/v1': Method not found: 'Akka.Actor.IActorRef Akka.Actor.IInternalActorRef.GetChild(System.Collections.Generic.IEnumerable`1<System.String>)
```

So the issue in this case is that there's a DLL that isn't referencing v1.4.25 and this API is being accessed by the TestKit, by the sound of it. Can you let us know what the versions are for all of your Akka.NET-related PRs are? 

Looks like this change wasn't as safe was I thought it was - sorry about that. We made it because it _significantly_ improved performance for a lot of things, namely Akka.Remote, but we work really hard to avoid making changes like this for exactly this reason.

**Comment by Aaronontheweb** [comment]
Whoops, had to update my last comment - wanted to know about the version of all of the Akka.NET DLLs you're using, not PRs :p

**Comment by DSanchen** [comment]
🙈 
It's not what DLL's I'm using, but rather the one I was missing...
I am using Akka.TestKit.VsTest in its latest Version (1.3.2) and was not using Akka.TestKit directly... When I added a NuGet refernece to Akka.TestKit, Visual Studio told me, that it was updating Akka.TestKit.1.3.1 to 1.4.25 -- So I guess that caused the trouble...
Now when using Akka.TestKit directly, all my tests work as previously.
Thanks for your Time, and the ongoing work on the Akka framework ! I really appreciate that 👍

**Comment by Aaronontheweb** [comment]
Ah - I'll see if we can update the VSTest testkit. It's been a while.
