### ISSUE TITLE
Non-documented breaking change of channel-executor configuration

### ISSUE THREAD

**Issue by mralexes** [akkadotnet/akka.net#5541]
**Version Information**
Version of Akka.NET? 1.4.32
Which Akka.NET Modules? Akka

**Describe the bug**
After update from 1.4.20 to 1.4.32 channel-executor configuration (see [doc](https://getakka.net/articles/actors/dispatchers.html#channelexecutor)) is not valid anymore

**To Reproduce**
1. Create a console app with Akka 1.4.29+
2. Execute:
```
using Akka.Actor;

namespace ChannelExecutorIssue
{
    internal class Program
    {
        static void Main(string[] args)
        {
            // Following: https://getakka.net/articles/actors/dispatchers.html#channelexecutor
            var config = @"
                          akka.actor.default-dispatcher = { 
                                 executor = channel-executor
                          }";
            
            // Throws NRE in 1.4.29+
            var actorSystem = ActorSystem.Create("test", config);
        }
    }
}
```
3. Observe

**Expected behavior**
ActorSystem created successfully

**Actual behavior**
NRE is thrown:
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Akka.Dispatch.ChannelExecutorConfigurator..ctor(Config config, IDispatcherPrerequisites prerequisites)
   at Akka.Dispatch.MessageDispatcherConfigurator.ConfigureExecutor()
   at Akka.Dispatch.DispatcherConfigurator..ctor(Config config, IDispatcherPrerequisites prerequisites)
   at Akka.Dispatch.Dispatchers.ConfiguratorFrom(Config cfg)
   at Akka.Dispatch.Dispatchers.LookupConfigurator(String id)
   at Akka.Dispatch.Dispatchers.Lookup(String dispatcherName)
   at Akka.Dispatch.Dispatchers..ctor(ActorSystem system, IDispatcherPrerequisites prerequisites, ILoggingAdapter logger)
   at Akka.Actor.Internal.ActorSystemImpl.ConfigureDispatchers()
   at Akka.Actor.Internal.ActorSystemImpl..ctor(String name, Config config, ActorSystemSetup setup, Nullable`1 guardianProps)
   at Akka.Actor.ActorSystem.CreateAndStartSystem(String name, Config withFallback, ActorSystemSetup setup)
   at Akka.Actor.ActorSystem.Create(String name, Config config)
   at ChannelExecutorIssue.Program.Main(String[] args)
```
   

The issue is in the default config for `default-dispatcher` that has no `channel-executor.priority` set. Introduced in #5403    

Sidenote: default `channel-scheduler` configuration is expected to be at: `akka.channel-scheduler` https://github.com/akkadotnet/akka.net/blob/ccb467076f061239aecc976983c6990c372811dd/src/core/Akka/Dispatch/ChannelSchedulerExtension.cs#L63
But it is actually located under `akka.actor.channel-scheduler`     
Current workaround:
```
using Akka.Actor;

namespace ChannelExecutorIssue
{
    internal class Program
    {
        static void Main(string[] args)
        {
            //Copy akka.actor.channel-scheduler from Akka/Configuration/Pigeon.conf
            var config = @"
                          akka.channel-scheduler {
                              parallelism-min = 4    #same as for ForkJoinDispatcher
                              parallelism-factor = 1 #same as for ForkJoinDispatcher
                              parallelism-max = 64   #same as for ForkJoinDispatcher
                              work-max = 10          #max executed work items in sequence until priority loop
                              work-interval = 500    #time target of executed work items in ms
                              work-step = 2          #target work item count in interval / burst
                          }
                          akka.actor.default-dispatcher = { 
                              executor = channel-executor
                              channel-executor.priority = normal
                          }";
            
            var actorSystem = ActorSystem.Create("test", config);
        }
    }
}
```

**Comment by Aaronontheweb** [comment]
@eaba can you take this one?

**Comment by Aaronontheweb** [comment]
@mralexes thanks for reporting this - I totally missed that during the review.

**Comment by mralexes** [comment]
Might be related to #5498

**Comment by eaba** [comment]
> @eaba can you take this one?

Ok @Aaronontheweb

**Comment by eaba** [comment]
> The issue is in the default config for default-dispatcher that has no channel-executor.priority set

The default `channel-executor.priority`  is `normal` if not set by the user:
https://github.com/akkadotnet/akka.net/blob/405dfc585e633e3bf9222ed28348c325e8d1204e/src/core/Akka/Dispatch/AbstractDispatcher.cs#L124

**Comment by mralexes** [comment]
@eaba yes, but only if `cfg` variable is not `null`, which is `null` in this case)
