### ISSUE TITLE
FishForMessage should allow an allMessages optional parameter that can return all the messages until isMessage returns true

### ISSUE THREAD

**Issue by brah-mcdude** [akkadotnet/akka.net#5551]
Is your feature request related to a problem? Please describe: 
I need this feature in my tests. 

Describe the solution you'd like:
1. add a param: List<object> allMessages = null
2. add this line in the loop: allMessages?.Add(msg);

Describe alternatives you've considered: 
Write a separate method.

**Comment by brah-mcdude** [comment]
Test method: 

```c#
        [Fact]
        public async Task FishForMessage_should_fill_the_all_messages_param_if_not_null()
        {
            await Task.Run(delegate
            {
                var probe = base.CreateTestProbe("probe");
                probe.Tell("hello");
                probe.Tell("world");
                var allMessages = new List<object>();
                probe.FishForMessage<string>(isMessage: s => s == "world", allMessages: allMessages);
                allMessages.Should().BeEquivalentTo(new List<object> { "hello" });
            });
        }

```

**Comment by brah-mcdude** [comment]
Here is the modification to the current method: 

```c#
        public T FishForMessage<T>(Predicate<T> isMessage, TimeSpan? max = null, string hint = "", List<object> allMessages = null)
        {

```

**Comment by brah-mcdude** [comment]
TDD red state - test fails with: 

```c#
Xunit.Sdk.XunitException
  HResult=0x80131500
  Message=Expected allMessages to be a collection with 1 item(s), but found an empty collection.

With configuration:
- Use declared types and members
- Compare enums by value
- Include all non-private properties
- Include all non-private fields
- Match member by name (or throw)
- Without automatic conversion.
- Without automatic conversion.
- Be strict about the order of items in byte arrays

  Source=FluentAssertions
  StackTrace:
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.CollectingAssertionStrategy.ThrowIfAny(IDictionary`2 context)
   at FluentAssertions.Execution.AssertionScope.Dispose()
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEquality(EquivalencyValidationContext context)
   at FluentAssertions.Collections.CollectionAssertions`2.BeEquivalentTo[TExpectation](IEnumerable`1 expectation, Func`2 config, String because, Object[] becauseArgs)
   at FluentAssertions.Collections.CollectionAssertions`2.BeEquivalentTo[TExpectation](IEnumerable`1 expectation, String because, Object[] becauseArgs)
   at Akka.Testkit.Tests.TestKitBaseTests.ReceiveTests.<FishForMessage_should_fill_the_all_messages_param_if_not_null>b__6_0() in C:\Users\brahm\source\repos\akka.net\src\core\Akka.TestKit.Tests\TestKitBaseTests\ReceiveTests.cs:line 81
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

```

**Comment by brah-mcdude** [comment]
Here is the modification needed to get TDD green: 

```c#
                if (msg is T msg1 && isMessage(msg1))
                {
                    return msg1;
                }
                allMessages?.Add(msg);

```

**Comment by brah-mcdude** [comment]
I ran all other FishForMessage test methods. 
They all passed.

**Comment by brah-mcdude** [comment]
PR: Added one more message to the test #5552
