### ISSUE TITLE
XUnit explodes during some failure conditions inside NodeTestRunner

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#601]
Working on writing up the ClusterDeathWatchSpecs and I ran into this issue, which hard-crashes the `NodeTestRunner` - even after I added exception handling :\ 

Can't tell if this is a bug with XUnit or an issue with how we're using it inside the individual `NodeRunner` processes. CC @smalldave 

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.

Server stack trace:
   at Xunit.Xunit1ExceptionUtility.ConvertToFailureInformation(XmlNode failureNode)
   at Xunit.TestClassCallbackHandler.OnTest(XmlNode xml)
   at Xunit.TestClassCallbackHandler.OnXmlNode(XmlNode xml)
   at Xunit.XmlNodeCallbackHandler.System.Web.UI.ICallbackEventHandler.RaiseCallbackEvent(String eventArgument)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server,
 Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at System.Web.UI.ICallbackEventHandler.RaiseCallbackEvent(String eventArgument)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters
, CultureInfo culture)
   at Xunit.Sdk.ExecutorCallback.CallbackEventHandlerCallback.Notify(String value)
   at Xunit.Sdk.Executor.OnTestResult(ITestResult result, ExecutorCallback callback)
   at Xunit.Sdk.Executor.RunTests.<>c__DisplayClass12.<.ctor>b__11(ITestResult result)
   at Xunit.Sdk.TestClassCommandRunner.Execute(ITestClassCommand testClassCommand, List`1 methods, Predicate`1 startCall
back, Predicate`1 resultCallback)
   at Xunit.Sdk.Executor.RunTests.<>c__DisplayClass12.<.ctor>b__f()
   at Xunit.Sdk.Executor.ThreadRunner(Object threadStart)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object
state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, B
oolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocati
on. ---> System.NullReferenceException: Object reference not set to an instance of an object.

Server stack trace:
   at Xunit.Xunit1ExceptionUtility.ConvertToFailureInformation(XmlNode failureNode)
   at Xunit.TestClassCallbackHandler.OnTest(XmlNode xml)
   at Xunit.TestClassCallbackHandler.OnXmlNode(XmlNode xml)
   at Xunit.XmlNodeCallbackHandler.System.Web.UI.ICallbackEventHandler.RaiseCallbackEvent(String eventArgument)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server,
 Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at System.Web.UI.ICallbackEventHandler.RaiseCallbackEvent(String eventArgument)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters
, CultureInfo culture)
   at Xunit.Sdk.ExecutorCallback.CallbackEventHandlerCallback.Notify(String value)
   at Xunit.Sdk.Executor.OnTestResult(ITestResult result, ExecutorCallback callback)
   at Xunit.Sdk.Executor.RunTests.<>c__DisplayClass12.<.ctor>b__11(ITestResult result)
   at Xunit.Sdk.TestClassCommandRunner.Execute(ITestClassCommand testClassCommand, List`1 methods, Predicate`1 startCall
back, Predicate`1 resultCallback)
   at Xunit.Sdk.Executor.RunTests.<>c__DisplayClass12.<.ctor>b__f()
   at Xunit.Sdk.Executor.ThreadRunner(Object threadStart)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object
state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, B
oolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocati
on. ---> System.NullReferenceException: Object reference not set to an instance of an object.

Server stack trace:
   at Xunit.Xunit1ExceptionUtility.ConvertToFailureInformation(XmlNode failureNode)
   at Xunit.TestClassCallbackHandler.OnTest(XmlNode xml)
   at Xunit.TestClassCallbackHandler.OnXmlNode(XmlNode xml)
   at Xunit.XmlNodeCallbackHandler.System.Web.UI.ICallbackEventHandler.RaiseCallbackEvent(String eventArgument)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server,
 Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at System.Web.UI.ICallbackEventHandler.RaiseCallbackEvent(String eventArgument)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters
, CultureInfo culture)
   at Xunit.Sdk.ExecutorCallback.CallbackEventHandlerCallback.Notify(String value)
   at Xunit.Sdk.Executor.OnTestResult(ITestResult result, ExecutorCallback callback)
   at Xunit.Sdk.Executor.RunTests.<>c__DisplayClass12.<.ctor>b__11(ITestResult result)
   at Xunit.Sdk.TestClassCommandRunner.Execute(ITestClassCommand testClassCommand, List`1 methods, Predicate`1 startCall
back, Predicate`1 resultCallback)
   at Xunit.Sdk.Executor.RunTests.<>c__DisplayClass12.<.ctor>b__f()
   at Xunit.Sdk.Executor.ThreadRunner(Object threadStart)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object
state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, B
oolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

**Comment by smalldave** [comment]
Get anywhere with this? Will try and take a look at this tomorrow.

**Comment by Aaronontheweb** [comment]
@smalldave on my latest pr #606 I added a couple of bugfixes that I *thought* might be responsible for this, namely some issues with Helios and the `Conductor`. The problem comes up much less frequently now but it still does come up every now and then.

Big thing I'm noticing now is that when XUnit tanks it's usually preceded by a `NullReferenceException`. But here's the weird part: it's not isolated to one `NodeTestRunner`. It's not all of them either, but usually 2-3 of them are affected.

**Comment by smalldave** [comment]
Is this still an issue?

**Comment by Aaronontheweb** [comment]
@smalldave nah, I don't think so anymore - we'll need to upgrade to XUnit 2 at some point now that it's RTMed, but this is no longer a critical issue.
