### ISSUE TITLE
NuGet contains wrong dependency to Microsoft.Extensions.ObjectPool (5.0.5 instead of 5.0.0)

### ISSUE THREAD

**Issue by Lumoryel** [akkadotnet/akka.net#6083]
When I disassemble Akka.dll, it references Microsoft.Extensions.ObjectPool Version 5.0.0, but the NuGet Package defines a Reference to 5.0.5.

Without using assembly binding redirects, this leads to a runtime exception.

Am I wrong or is this just a wrong NuGet dependency?

**Comment by Aaronontheweb** [comment]
What could be wrong with this reference? 

https://github.com/akkadotnet/akka.net/blob/a55cb9e66c4dab89fcb94ed703db35296c80fd3d/src/core/Akka/Akka.csproj#L18

**Comment by Lumoryel** [comment]
Then I don't get it - if ObjectPool NuGet 5.0.5 delivers an ObjectPool.dll with Version 5.0.5, how can Akka.dll reference the ObjectPool.dll 5.0.0 ?

That's my runtime exception, when I disable automatic binding redirects:

```
Exception has been thrown by the target of an invocation. ---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.ObjectPool, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Akka.Serialization.NewtonSoftJsonSerializer..ctor(ExtendedActorSystem system, NewtonSoftJsonSerializerSettings settings)
   at Akka.Serialization.NewtonSoftJsonSerializer..ctor(ExtendedActorSystem system, Config config)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Akka.Serialization.Serialization..ctor(ExtendedActorSystem system)
   at Akka.Actor.Internal.ActorSystemImpl..ctor(String name, Config config, ActorSystemSetup setup, Nullable`1 guardianProps)
   at Akka.Actor.ActorSystem.CreateAndStartSystem(String name, Config withFallback, ActorSystemSetup setup)
   at Akka.Actor.ActorSystem.Create(String name, Config config)
[...]
```

**Comment by Aaronontheweb** [comment]
Are you referencing a newer version elsewhere in your solution?

**Comment by Lumoryel** [comment]
I'm not aware of any other dlls that need ObjectPool. Also checked that with the "Reference Conflicts Analyser" VS Extension.

![grafik](https://user-images.githubusercontent.com/51440746/187624544-33952db3-a757-40fb-b4eb-3a695e5ff582.png)

![grafik](https://user-images.githubusercontent.com/51440746/187624677-138c4375-f177-499c-ae26-fb6a24bd8ae2.png)

**Comment by Aaronontheweb** [comment]
Is this an ASP.NET Core project? Reason I ask is because this package is also referenced by its SDK: https://docs.microsoft.com/en-us/aspnet/core/performance/objectpool

Long story short though: I don't see anything that's wrong with our NuGet reference here.

**Comment by Lumoryel** [comment]
This is a .NET Framework 4.8 Project.

Why do we have problems?
The thing is, when we deploy via Visual Studio Setup Project, the App.config from the project is installed, instead of the automatically adjusted app.config where the binding redirects are added, so I had to change all our app.configs and include the binding redirect manually, just because of Akka.

Why does Akka.dll reference ObjectPool 5.0.0.0 although the PackageReference wants 5.0.5, AND the ObjectPool Nuget delivers a dll with version 5.0.5?
If we could find an answer I woudl be very happy...

**Comment by Lumoryel** [comment]
Aaah I found out that the ObjectPool Version displayed in ILDASM differs within the Nuget:
.NET 5 =  5.0.0.0
.netstandard2.0 = 5.0.0.0
.Net461 = 5.0.5.0

And our project gets the .Net461 = 5.0.5.0 copied, although Akka is targeting netstandard2.0 (and thus referencing the .netstandard version of ObjectPool?).
Is this correct?
Well I somehow agree with you that the Akka Nuget is correct, but there is still some discrepancy.
