### ISSUE TITLE
Updating to 1.5, got akka.logger.nlog error 

### ISSUE THREAD

**Issue by JTrotta** [akkadotnet/akka.net#6488]
**Version Information**
1.5
Akka.logger.nlog 1.4.10

**Describe the bug**
Exception message:
[ERROR]Method not found: 'Void Akka.Event.ILoggingAdapter.Info(System.String, System.Object[])'.
Cause: System.MissingMethodException: Method not found: 'Void Akka.Event.ILoggingAdapter.Info(System.String, System.Object[])'.
   at Akka.Logger.NLog.NLogLogger.<.ctor>b__2_4(InitializeLogger m)
   at lambda_method79(Closure, Object, Action`1, Action`1, Action`1, Action`1, Action`1)
   at Akka.Tools.MatchHandler.PartialHandlerArgumentsCapture`6.Handle(T value)
   at Akka.Actor.ReceiveActor.ExecutePartialMessageHandler(Object message, PartialAction`1 partialAction)
   at Akka.Actor.ReceiveActor.OnReceive(Object message)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)

**To Reproduce**
Update to 1.5

_Links to working reproductions on Github / Gitlab are very much appreciated_

**Expected behavior**
Working

**Actual behavior**
Error using nlog

**Environment**
Are you running on Linux? Windows? Docker? Linux/windows 
Which version of .NET? 7.0

**Comment by Aaronontheweb** [comment]
We need to upgrade the NLog plugin @JTrotta - it's affected by the breaking changes we introduced to the logging system in Akka.NET v1.5. We'll get on it.

**Comment by Aaronontheweb** [comment]
Now available on NuGet: https://github.com/akkadotnet/Akka.Logger.NLog/releases/tag/1.5.0 cc @JTrotta

**Comment by JTrotta** [comment]
> Now available on NuGet: https://github.com/akkadotnet/Akka.Logger.NLog/releases/tag/1.5.0 cc @JTrotta

It works. THANK YOU
