### ISSUE TITLE
Akka.Cluster.Sharding: `LeastShardAllocationStrategy` `ArgumentException` during rebalance

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#7365]
**Version Information**
Version of Akka.NET? not sure yet - waiting on reply in Discord
Which Akka.NET Modules? Akka.Cluster.Sharding

**Describe the bug**

```
System.ArgumentException: An element with the same key but a different value already exists. Key: 'akka.tcp://NuBreedSys@prod-nubreed-quote-process-managers-0.prod-nubreed-quote-process-managers-service:9233'
   at System.Collections.Immutable.ImmutableDictionary2.HashBucket.Add(TKey key, TValue value, IEqualityComparer1 keyOnlyComparer, IEqualityComparer1 valueComparer, KeyCollisionBehavior behavior, OperationResult& result)
   at System.Collections.Immutable.ImmutableDictionary2.AddRange(IEnumerable1 items, MutationInput origin, KeyCollisionBehavior collisionBehavior)
   at Akka.Cluster.Sharding.Internal.AbstractLeastShardAllocationStrategy.RegionEntriesFor(IImmutableDictionary2 currentShardAllocations)
   at Akka.Cluster.Sharding.LeastShardAllocationStrategy.Rebalance(IImmutableDictionary2 currentShardAllocations, IImmutableSet1 rebalanceInProgress)
   at Akka.Cluster.Sharding.ShardCoordinator.Active(Object message)
   at Akka.Cluster.Sharding.DDataShardCoordinator.<Activate>b__45_0(Object msg)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Phobos.Actor.PhobosActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)

```

**Expected behavior**

**Actual behavior**
What actually happened and how did it differ from your expectations?

**Screenshots**

**Environment**

Using `state-store-mode = ddata`

**Additional context**

Not sure yet, still working on getting thoughts organized here

**Comment by Aaronontheweb** [comment]
This is the line that throws:

https://github.com/akkadotnet/akka.net/blob/5e2bd0e2232efaab529c4be1c4db9e6328fb266b/src/contrib/cluster/Akka.Cluster.Sharding/ShardAllocationStrategy.cs#L169

When it's invoking this function:

https://github.com/akkadotnet/akka.net/blob/5e2bd0e2232efaab529c4be1c4db9e6328fb266b/src/contrib/cluster/Akka.Cluster.Sharding/Internal/AbstractLeastShardAllocationStrategy.cs#L127-L142

I'm guessing it's the `ToImmutableDictionary` call that is the problem here based on the stack trace provided by the user

**Comment by Aaronontheweb** [comment]
Also need to investigate why Akka.Cluster.Sharding never automatically healed from this issue either - that seems like a separate bug
