### ISSUE TITLE
NullReferenceException in ClusterDomainEventPublisher

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#742]
```xml
at Akka.Cluster.ClusterDomainEventPublisher.<SendCurrentClusterState>b__2(String r)
at System.Collections.Immutable.ImmutableDictionary.<>c__DisplayClass1`3.<ToImmutableDictionary>b__0(TSource element)
at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 items, MutationInput origin, KeyCollisionBehavior collisionBehavior)
at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 pairs, Boolean avoidToHashMap)
at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 pairs)
at System.Collections.Immutable.ImmutableDictionary.ToImmutableDictionary[TSource,TKey,TValue](IEnumer
able`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 keyComparer, IEqualityComparer`1 valueComparer)
   at System.Collections.Immutable.ImmutableDictionary.ToImmutableDictionary[TSource,TKey,TValue](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Akka.Cluster.ClusterDomainEventPublisher.SendCurrentClusterState(ActorRef receiver)
   at Akka.Cluster.ClusterDomainEventPublisher.Subscribe(ActorRef subscriber, SubscriptionInitialStateMode initMode, IEnumerable`1 to)
   at Akka.Cluster.ClusterDomainEventPublisher.OnReceive(Object message)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
```

Going to have to dig a bit deeper in this guy, but got this stacktrace from an actual app that runs Akka.Cluster. Never seen this issue show up in a test yet.

**Comment by smalldave** [comment]
My guess is that it's 

https://github.com/akkadotnet/akka.net/blob/e294506c762466befc1c2415cfe791ed16cdf976/src/core/Akka.Cluster/ClusterEvent.cs#L714

```csharp
_latestGossip.RoleLeader(r)
```

can return null

It's this in JVM Akka
```scala
def roleLeader(role: String): Option[UniqueAddress] = leaderOf(members.filter(_.hasRole(role)))
```

Needs to be changed so that if the RoleLeader is null then we add null to the dictionary. Looks like that is safe to do.

**Comment by Aaronontheweb** [comment]
@smalldave did you fix this in your most recent PR? I can't recall

**Comment by smalldave** [comment]
I didn't. See #772
