### ISSUE TITLE
Akka.TestKit: DelegatingSupervisorStrategy `KeyNotFoundException`

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#7437]
Looks like some of the changes we made to the TestKit might have introduced a problem here:

```
Cause: Akka.Actor.ActorKilledException: Kill
   at Akka.Actor.ActorCell.Kill()
   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.TestKit.Internal.InternalTestActorRef.TestActorCell.AutoReceiveMessage(Envelope envelope)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
Warning: [12/24/2024 11:23:57.091Z][Thread 0015][akka://test/deadLetters] DeadLetter from TestActor[akka://test/user/$$d] to [akka://test/deadLetters]: <Received dead letter from TestActor[akka://test/user/$$d]: workDone>
[INFO][12/24/2024 11:23:57.091Z][Thread 0021][akka://test/deadLetters] Message [String] from TestActor[akka://test/user/$$d] to [akka://test/deadLetters] was not delivered. [1] dead letters encountered. If this is not an expected behavior then [akka://test/deadLetters] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'. Message content: workDone
Error: [12/24/2024 11:23:57.590Z][Thread 0015][akka://test/system/testActor270] The given key '[akka://test/system/testActor270/$a#1593664040]' was not present in the dictionary.
Cause: System.Collections.Generic.KeyNotFoundException: The given key '[akka://test/system/testActor270/$a#1593664040]' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Akka.TestKit.DelegatingSupervisorStrategy.Handle(IActorRef child, Exception exception)
   at Akka.Actor.SupervisorStrategy.HandleFailure(ActorCell actorCell, IActorRef child, Exception cause, ChildRestartStats stats, IReadOnlyCollection`1 children)
   at Akka.Actor.ActorCell.HandleFailed(Failed f)
   at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState)
Error: [12/24/2024 11:23:57.590Z][Thread 0015][akka://test/system/testActor270] The given key '[akka://test/system/testActor270/actorName#616410545]' was not present in the dictionary.
Cause: System.Collections.Generic.KeyNotFoundException: The given key '[akka://test/system/testActor270/actorName#616410545]' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Akka.TestKit.DelegatingSupervisorStrategy.Handle(IActorRef child, Exception exception)
   at Akka.Actor.SupervisorStrategy.HandleFailure(ActorCell actorCell, IActorRef child, Exception cause, ChildRestartStats stats, IReadOnlyCollection`1 children)
   at Akka.Actor.ActorCell.HandleFailed(Failed f)
   at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState)
```

_Originally posted by @Aaronontheweb in https://github.com/akkadotnet/Akka.Hosting/issues/538#issuecomment-2561149187_

**Comment by Aaronontheweb** [comment]
This error was introduced in v1.5.33 due to https://github.com/akkadotnet/akka.net/pull/7221 - it's probably an easy fix.
