### ISSUE TITLE
Fix all racy unit tests

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#853]
We have a handful of evil unit tests inside Akka core that are either finding:

* legitimately bad behavior that we need to fix
* race conditions within specs
* race conditions within core actor code.

Time to hunt these bugs down and fix them so we can have full confidence in our test suite.

Here's the list thus far:

* [ ] DeathWatchSpec Bug209_any_user_messages_following_a_Terminate_message_should_be_forwarded_to_DeadLetterMailbox	
* [x]  ResizerSpec DefaultResizer_must_grow_as_needed_under_pressure	
* [x] ResizerSpec DefaultResizer_must_backoff	
* [x] InboxSpec Inbox_have_a_default_and_custom_timeouts	
* [x]  ConsistentHashingRouterSpec ConsistentHashingRouterMustAdjustNodeRingWhenRouteeDies	
* [ ] RoutingSpec Router_in_general_must_evict_terminated_routees	
* [x]   SupervisorHierarchySpec A_supervisor_hierarchy_must_handle_failure_in_creation_when_supervision_strategy_returns_Resume_and_Restart	
* [x] TailChoppingSpec Tail_chopping_router_must_throw_exception_if_no_result_will_arrive_within_the_given_time
* [ ] RemoteRouterSpec RemoteRouter_must_deploy_its_children_on_remote_host_driven_by_configuration

**Comment by annymsMthd** [comment]
I'll try to tackle some of these now. I noticed them in my PR on TC

**Comment by Aaronontheweb** [comment]
Here's a new one:

* []   SupervisorHierarchySpec A_supervisor_hierarchy_must_handle_failure_in_creation_when_supervision_strategy_returns_Resume_and_Restart

**Comment by Aaronontheweb** [comment]
Two more.... http://petabridge-ci.cloudapp.net/viewLog.html?buildId=670&tab=buildResultsDiv&buildTypeId=AkkaNet_AkkaNetPrBuild?guest=1

TailChoppingSpec.Tail_chopping_router_must_throw_exception_if_no_result_will_arrive_within_the_given_time	

```
Failed: Expected a message of type Akka.Actor.Status+Failure, but received {ack} (type System.String) instead  from [akka://all-systems/]
   at Akka.TestKit.TestKitBase.InternalExpectMsgEnvelope[T](Nullable`1 timeout, Action`2 assert, String hint, Boolean shouldLog) in d:\BuildAgent\work\49b164d63843fb4\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 203
   at Akka.TestKit.TestKitBase.InternalExpectMsgEnvelope[T](Nullable`1 timeout, Action`1 msgAssert, Action`1 senderAssert, String hint) in d:\BuildAgent\work\49b164d63843fb4\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 179
   at Akka.TestKit.TestKitBase.InternalExpectMsg[T](Nullable`1 timeout, Action`1 msgAssert, String hint) in d:\BuildAgent\work\49b164d63843fb4\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 154
   at Akka.Tests.Routing.TailChoppingSpec.Tail_chopping_router_must_throw_exception_if_no_result_will_arrive_within_the_given_time() in d:\BuildAgent\work\49b164d63843fb4\src\core\Akka.Tests\Routing\TailChoppingSpec.cs:line 172
------- Stdout: -------
[WARNING][4/16/2015 4:29:59 AM][Thread 0012][akka://RuntimeType-315/user] DeadLetter from [akka://RuntimeType-315/user] to [akka://RuntimeType-315/user]: <Received dead system message: <DeathWatchNotification>: [akka://RuntimeType-315/user/testActor334], ExistenceConfirmed=True, AddressTerminated=False>
[WARNING][4/16/2015 4:29:59 AM][Thread 0012][akka://RuntimeType-315/user] DeadLetter from [akka://RuntimeType-315/user] to [akka://RuntimeType-315/user]: <Received dead system message: <DeathWatchNotification>: [akka://RuntimeType-315/user/testActor335], ExistenceConfirmed=True, AddressTerminated=False>
[WARNING][4/16/2015 4:29:59 AM][Thread 0012][akka://RuntimeType-315/user] DeadLetter from [akka://RuntimeType-315/user] to [akka://RuntimeType-315/user]: <Received dead system message: <DeathWatchNotification>: [akka://RuntimeType-315/user/$b], ExistenceConfirmed=True, AddressTerminated=False>
[WARNING][4/16/2015 4:29:59 AM][Thread 0012][akka://RuntimeType-315/user] DeadLetter from [akka://RuntimeType-315/user] to [akka://RuntimeType-315/user]: <Received dead system message: <DeathWatchNotification>: [akka://RuntimeType-315/user/Actor5], ExistenceConfirmed=True, AddressTerminated=False>
```
 RemoteRouterSpec.RemoteRouter_must_deploy_its_children_on_remote_host_driven_by_configuration	

```
Failed: Timeout 00:00:06 while waiting for a message of type Akka.Actor.IActorRef 
   at Akka.TestKit.TestKitBase.InternalExpectMsgEnvelope[T](Nullable`1 timeout, Action`2 assert, String hint, Boolean shouldLog) in d:\BuildAgent\work\49b164d63843fb4\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 196
   at Akka.TestKit.TestKitBase.InternalExpectMsgEnvelope[T](Nullable`1 timeout, Action`1 msgAssert, Action`1 senderAssert, String hint) in d:\BuildAgent\work\49b164d63843fb4\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 179
   at Akka.TestKit.TestKitBase.InternalExpectMsg[T](Nullable`1 timeout, Action`1 msgAssert, String hint) in d:\BuildAgent\work\49b164d63843fb4\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 154
   at Akka.TestKit.TestKitBase.ExpectMsg[T](Nullable`1 duration, String hint) in d:\BuildAgent\work\49b164d63843fb4\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 29
   at Akka.Remote.Tests.RemoteRouterSpec.RemoteRouter_must_deploy_its_children_on_remote_host_driven_by_configuration() in d:\BuildAgent\work\49b164d63843fb4\src\core\Akka.Remote.Tests\RemoteRouterSpec.cs:line 121
```

**Comment by Aaronontheweb** [comment]
@annymsMthd looks like the TailChoppingSpec is still failing even after your PR:

TailChoppingSpec.Tail_chopping_router_must_throw_exception_if_no_result_will_arrive_within_the_given_time

**Comment by annymsMthd** [comment]
These failures are sneaky. I'll keep checking it out

**Comment by annymsMthd** [comment]
Do you know which build it failed on?

**Comment by Aaronontheweb** [comment]
@annymsMthd one of the dev builds immediately after I pulled in your PR: http://petabridge-ci.cloudapp.net/viewLog.html?buildId=703&tab=buildResultsDiv&buildTypeId=AkkaNet_AkkaNetUnstableLatest&guest=1

**Comment by annymsMthd** [comment]
That one looks like the build right before you merged #866. There was another tweak to TailChopping in there. I'm not sure if it really got it though. We should run the build on the agent a couple of times and I'll keep an eye out.

**Comment by Aaronontheweb** [comment]
good to know - I'll try it again then.

**Comment by Aaronontheweb** [comment]
Ran the builds 6 times each - looks good. Going mark off the tests that aren't failing as "fixed" for now (until we learn otherwise.)

**Comment by Aaronontheweb** [comment]
Reposting my comment from #868 

Aha! There we go - finally got a failure, but on a ResizerSpec test instead

http://petabridge-ci.cloudapp.net/viewLog.html?buildId=726&tab=buildResultsDiv&buildTypeId=AkkaNet_AkkaNetPrBuild&Guest=1

The frequency at which they're coming up is much less common now though, so I think you're making good progress.

**Comment by Aaronontheweb** [comment]
Friendly reminder - we still run into a lot of issues with the `RemoteRouterSpec` tests. Just failed my release build three times in a row. Would really appreciate it if someone could look into those!

**Comment by Horusiath** [comment]
What is the status of this issue?

**Comment by alexvaluyskiy** [comment]
This issue is not valid anymore
